-- RA-10: a companion rests with its character, by the character's rules.
BEGIN;
SET LOCAL search_path = extensions, public, pg_catalog;

INSERT INTO auth.users (id, email) VALUES
  ('e1110000-1111-4111-8111-111111111111', 'rest-owner@example.test'),
  ('e1220000-2222-4222-8222-222222222222', 'rest-stranger@example.test');
INSERT INTO public.characters (id, user_id, name, level) VALUES
  ('e2110000-1111-4111-8111-111111111111', 'e1110000-1111-4111-8111-111111111111', 'Rest owner', 5),
  ('e2220000-2222-4222-8222-222222222222', 'e1220000-2222-4222-8222-222222222222', 'Rest stranger', 3);

-- A level-scaled d10 Anomaly (5d10 = 50 HP at level 5) and a utility mount
-- that keeps its saved 13 HP.
INSERT INTO public.character_extras (id, character_id, name, extra_type, hp_current, hp_max, ac, speed, npc_data, is_active)
VALUES
  ('e3000000-0000-4000-8000-000000000001', 'e2110000-1111-4111-8111-111111111111',
   'Eternal Ancient Dragon', 'companion', 50, 50, 13, 30,
   '{"kind":"canonical-compendium","version":1,"provenance":{"canonicalId":"anomaly-0006","canonicalType":"anomaly","canonicalCollection":"anomalies","entryType":"Elemental","source":null,"sourceBook":null},"sourceFields":{"name":"Eternal Ancient Dragon","hpMax":12,"baseAc":13,"speed":30,"rank":"D"}}',
   false),
  ('e3000000-0000-4000-8000-000000000002', 'e2110000-1111-4111-8111-111111111111',
   'Bureau Riding Horse', 'mount', 13, 13, 10, 60,
   '{"kind":"canonical-compendium","version":1,"provenance":{"canonicalId":"mount-bureau-riding-horse","canonicalType":"vehicle","canonicalCollection":"vehicles","entryType":"mount","source":null,"sourceBook":"Rift Ascendant Canon"},"sourceFields":{"name":"Bureau Riding Horse","hpMax":13,"baseAc":10,"speed":60,"rank":"D"}}',
   false);

-- A combat-capable living mount on the vehicles sheet (5d10 = 50 HP).
INSERT INTO public.character_vehicles (id, character_id, vehicle_id, current_hp)
VALUES ('e4000000-0000-4000-8000-000000000001', 'e2110000-1111-4111-8111-111111111111',
  'mount-mountain-patrol-bear', 34);
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', 'e1110000-1111-4111-8111-111111111111', true);
SELECT public.register_character_vehicle_mount('e4000000-0000-4000-8000-000000000001', NULL);
RESET ROLE;

-- Instance ids are generated by the identity triggers; keep them readable
-- for every role in this transaction.
SELECT set_config('test.dragon', companion_instance_id::TEXT, true)
FROM public.character_extras WHERE id = 'e3000000-0000-4000-8000-000000000001';
SELECT set_config('test.horse', companion_instance_id::TEXT, true)
FROM public.character_extras WHERE id = 'e3000000-0000-4000-8000-000000000002';
SELECT set_config('test.bear', companion_instance_id::TEXT, true)
FROM public.character_vehicles WHERE id = 'e4000000-0000-4000-8000-000000000001';

-- Wounds, a downed mount, and conditions with every kind of rest policy.
UPDATE public.character_extras
SET hp_current = 7,
    conditions = '[
      "Poisoned",
      {"id":"c1","name":"Blessed","applied_at":"2026-09-29T00:00:00Z"},
      {"id":"c2","conditionId":"marked","conditionName":"Marked","isActive":true,"restPolicy":"persist"},
      {"id":"c3","conditionId":"warded","conditionName":"Warded","isActive":true,"restPolicy":"persist",
       "duration":{"unit":"rest","anchor":"long-rest","value":null,"remaining":null}},
      {"id":"c4","conditionId":"frightened","conditionName":"Frightened","isActive":true,"restPolicy":"remove-on-short-rest"},
      {"id":"c5","conditionId":"grappled","conditionName":"Grappled","isActive":false}
    ]'::jsonb
WHERE id = 'e3000000-0000-4000-8000-000000000001';
UPDATE public.character_extras SET hp_current = 2
WHERE id = 'e3000000-0000-4000-8000-000000000002';
UPDATE public.character_vehicles SET current_hp = 0
WHERE id = 'e4000000-0000-4000-8000-000000000001';

SELECT plan(27);

SELECT is(
  (SELECT array[app_private.companion_hit_dice_max(instance), app_private.companion_scaling_hit_die(instance)]
   FROM public.companion_instances AS instance WHERE instance.id = current_setting('test.dragon')::UUID),
  array[5, 10], 'a level-5 d10 companion has five d10 Hit Dice');
SELECT ok(
  (SELECT app_private.companion_hit_dice_max(instance) IS NULL
   FROM public.companion_instances AS instance WHERE instance.id = current_setting('test.horse')::UUID),
  'a companion that keeps its saved stats has no Hit Dice');
SELECT ok(
  (SELECT (combat_state->>'downed')::BOOLEAN FROM public.companion_instances
   WHERE id = current_setting('test.bear')::UUID),
  'the mount at 0 HP is downed');

-- ---------------------------------------------------------------------------
-- Short Rest: the owner spends Hit Dice
-- ---------------------------------------------------------------------------
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', 'e1110000-1111-4111-8111-111111111111', true);

SELECT is(public.rest_companions_for_character('e2110000-1111-4111-8111-111111111111', 'short'), 0,
  'a Short Rest changes nothing by itself');
SELECT is(public.spend_companion_hit_dice(current_setting('test.dragon')::UUID, 2, 13),
  '{"hp":20,"hpMax":50,"hitDie":10,"hitDiceMax":5,"hitDiceSpent":2}'::jsonb,
  'two Hit Dice heal the rolled 13 HP');
SELECT throws_ok(
  $$SELECT public.spend_companion_hit_dice(current_setting('test.dragon')::UUID, 1, 11)$$,
  '22023', 'INVALID_COMPANION_HIT_DICE_HEALING', 'one d10 cannot heal 11');
SELECT throws_ok(
  $$SELECT public.spend_companion_hit_dice(current_setting('test.dragon')::UUID, 4, 4)$$,
  '22023', 'COMPANION_HIT_DICE_UNAVAILABLE', 'only three Hit Dice remain');
SELECT throws_ok(
  $$SELECT public.spend_companion_hit_dice(current_setting('test.dragon')::UUID, 0, 0)$$,
  '22023', 'COMPANION_HIT_DICE_UNAVAILABLE', 'at least one die is spent');
SELECT throws_ok(
  $$SELECT public.spend_companion_hit_dice(current_setting('test.horse')::UUID, 1, 1)$$,
  '22023', 'COMPANION_HAS_NO_HIT_DICE', 'a saved-stat companion has no Hit Dice to spend');

SELECT set_config('request.jwt.claim.sub', 'e1220000-2222-4222-8222-222222222222', true);
SELECT throws_ok(
  $$SELECT public.spend_companion_hit_dice(current_setting('test.dragon')::UUID, 1, 5)$$,
  '42501', 'COMPANION_OWNER_REQUIRED', 'another player cannot spend the companion''s Hit Dice');
SELECT throws_ok(
  $$SELECT public.rest_companions_for_character('e2110000-1111-4111-8111-111111111111', 'long')$$,
  '42501', 'CHARACTER_OWNER_REQUIRED', 'another player cannot rest the character''s companions');
RESET ROLE;

SELECT is((SELECT hp_current FROM public.character_extras
  WHERE id = 'e3000000-0000-4000-8000-000000000001'), 20,
  'the companion sheet shows the healing');

-- Healing stops at the maximum; the spent dice still count. Each RPC runs in
-- its own transaction in the app; clearing the origin-sync guard it sets
-- lets the sheet edits below reach the living instance as they would there.
SELECT set_config('app.companion_c3_origin_sync', 'off', true);
UPDATE public.character_extras SET hp_current = 45
WHERE id = 'e3000000-0000-4000-8000-000000000001';
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', 'e1110000-1111-4111-8111-111111111111', true);
SELECT is(public.spend_companion_hit_dice(current_setting('test.dragon')::UUID, 3, 30)->'hp',
  '50'::jsonb, 'healing stops at the scaled maximum');
SELECT throws_ok(
  $$SELECT public.spend_companion_hit_dice(current_setting('test.dragon')::UUID, 1, 1)$$,
  '22023', 'COMPANION_HIT_DICE_UNAVAILABLE', 'all five Hit Dice are spent');
SELECT throws_ok(
  $$SELECT public.rest_companions_for_character('e2110000-1111-4111-8111-111111111111', 'nap')$$,
  '22023', 'INVALID_COMPANION_REST_KIND', 'only Short and Long Rests exist');
RESET ROLE;

-- ---------------------------------------------------------------------------
-- Long Rest
-- ---------------------------------------------------------------------------
SELECT set_config('app.companion_c3_origin_sync', 'off', true);
UPDATE public.character_extras SET hp_current = 5
WHERE id = 'e3000000-0000-4000-8000-000000000001';
SELECT is((SELECT (combat_state->>'hp')::INTEGER FROM public.companion_instances
  WHERE id = current_setting('test.dragon')::UUID), 5,
  'the wound reaches the living instance before the rest');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', 'e1110000-1111-4111-8111-111111111111', true);
SELECT is(public.rest_companions_for_character('e2110000-1111-4111-8111-111111111111', 'long'), 3,
  'a Long Rest rests every companion the character holds');
RESET ROLE;

SELECT is((SELECT array[hp_current, hp_max] FROM public.character_extras
  WHERE id = 'e3000000-0000-4000-8000-000000000001'), array[50, 50],
  'a Long Rest restores all HP');
SELECT is((SELECT hp_current FROM public.character_extras
  WHERE id = 'e3000000-0000-4000-8000-000000000002'), 13,
  'a saved-stat companion regains its saved maximum');
SELECT is((SELECT current_hp FROM public.character_vehicles
  WHERE id = 'e4000000-0000-4000-8000-000000000001'), 50,
  'a downed mount regains all HP');
SELECT ok((SELECT NOT (combat_state->>'downed')::BOOLEAN AND (combat_state->>'hp')::INTEGER = 50
  FROM public.companion_instances WHERE id = current_setting('test.bear')::UUID),
  'the mount is no longer downed');
SELECT is(
  (SELECT jsonb_agg(condition->>'conditionName')
   FROM public.character_extras, jsonb_array_elements(conditions) AS condition
   WHERE id = 'e3000000-0000-4000-8000-000000000001'),
  '["Marked", "Grappled"]'::jsonb,
  'conditions end as a character''s do; persistent and already-ended entries remain');
SELECT is((SELECT (combat_state->>'hitDiceSpent')::INTEGER FROM public.companion_instances
  WHERE id = current_setting('test.dragon')::UUID), 3,
  'it regains half its Hit Dice (two of five)');

SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', 'e1110000-1111-4111-8111-111111111111', true);
SELECT public.rest_companions_for_character('e2110000-1111-4111-8111-111111111111', 'long');
SELECT public.rest_companions_for_character('e2110000-1111-4111-8111-111111111111', 'long');
RESET ROLE;
SELECT is((SELECT (combat_state->>'hitDiceSpent')::INTEGER FROM public.companion_instances
  WHERE id = current_setting('test.dragon')::UUID), 0,
  'repeated Long Rests never recover more dice than were spent');

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
SELECT ok(
  has_function_privilege('authenticated', 'public.rest_companions_for_character(uuid,text)', 'EXECUTE')
  AND has_function_privilege('authenticated', 'public.spend_companion_hit_dice(uuid,integer,integer)', 'EXECUTE')
  AND NOT has_function_privilege('anon', 'public.rest_companions_for_character(uuid,text)', 'EXECUTE')
  AND NOT has_function_privilege('anon', 'public.spend_companion_hit_dice(uuid,integer,integer)', 'EXECUTE'),
  'only signed-in players can rest companions and spend their Hit Dice');
SELECT is((SELECT count(*) FROM pg_proc AS p
  JOIN pg_namespace AS n ON n.oid = p.pronamespace
  CROSS JOIN LATERAL aclexplode(COALESCE(p.proacl, acldefault('f', p.proowner))) AS acl
  WHERE n.nspname IN ('public', 'app_private')
    AND p.proname IN ('companion_hit_dice_max', 'companion_hit_dice_spent',
      'companion_conditions_after_long_rest', 'rest_companions_for_character',
      'spend_companion_hit_dice')
    AND acl.grantee = 0 AND acl.privilege_type = 'EXECUTE'), 0::bigint,
  'PUBLIC cannot execute the rest functions');
SELECT ok(NOT has_function_privilege('authenticated',
  'app_private.companion_hit_dice_spent(public.companion_instances)', 'EXECUTE'),
  'clients cannot call the Hit Dice helpers directly');

SELECT * FROM finish();
ROLLBACK;
