import { getMaxAbilityLevelForJobAtLevel } from "@/lib/abilityProgression";
import { normalizeJobAccessToken } from "@/lib/jobAbilityAccess";

export type PathAbilityKind = "spell" | "power" | "technique";
export type PathAbilityProgression = "third" | "base" | "full";

export interface PathAbilityGrant {
	jobName: string;
	pathName: string;
	level: number;
	kind: PathAbilityKind;
	sourceTokens: string[];
	schools?: string[];
	entryNames?: string[];
	progression?: PathAbilityProgression;
	maxLevel?: number;
	leveledSchoolsOnly?: boolean;
}

export const PATH_ABILITY_GRANTS: readonly PathAbilityGrant[] = [
	{
		jobName: "Destroyer",
		pathName: "Path of the Spell Breaker",
		level: 3,
		kind: "spell",
		sourceTokens: ["Mage"],
		schools: ["Abjuration", "Evocation"],
		progression: "third",
		leveledSchoolsOnly: true,
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Weave Infiltrator",
		level: 3,
		kind: "spell",
		sourceTokens: ["Mage"],
		schools: ["Enchantment", "Illusion"],
		progression: "third",
		leveledSchoolsOnly: true,
	},
	{
		jobName: "Striker",
		pathName: "Path of the Phantom Step",
		level: 3,
		kind: "spell",
		sourceTokens: [],
		entryNames: [
			"Fade to Shadow",
			"Phantom Step",
			"Echolocation Pulse",
			"Mana Lens",
			"Misty Blink",
		],
		maxLevel: 2,
	},
	{
		jobName: "Mage",
		pathName: "Path of the Phantasmist",
		level: 2,
		kind: "spell",
		sourceTokens: [],
		entryNames: ["Mana Lens"],
		maxLevel: 0,
	},
	{
		jobName: "Esper",
		pathName: "Path of the Psionic Breach",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [
			"Entropic Grasp",
			"Mind Spike",
			"Psychic Barrier",
			"Kinetic Burst",
			"Psionic Shockwave",
		],
		maxLevel: 5,
	},
	{
		jobName: "Mage",
		pathName: "Path of the Detonation Specialist",
		level: 2,
		kind: "power",
		sourceTokens: ["Mage"],
		entryNames: ["Runic Detonation"],
		progression: "full",
	},
	{
		jobName: "Esper",
		pathName: "Path of the Aetheric Cascade",
		level: 1,
		kind: "power",
		sourceTokens: ["Esper"],
		entryNames: ["Runic Detonation"],
		progression: "full",
	},
	{
		jobName: "Esper",
		pathName: "Path of the Psionic Breach",
		level: 1,
		kind: "power",
		sourceTokens: ["Esper"],
		entryNames: ["Parallel Processing", "Esper Ascension"],
		progression: "full",
	},
	{
		jobName: "Esper",
		pathName: "Path of the Psionic Breach",
		level: 1,
		kind: "technique",
		sourceTokens: ["Esper"],
		entryNames: ["Esper Singularity"],
	},
	{
		jobName: "Revenant",
		pathName: "Path of the Void Lord",
		level: 2,
		kind: "power",
		sourceTokens: ["Revenant"],
		entryNames: ["Final Entropy", "Entropic Avatar"],
		progression: "full",
	},
	{
		jobName: "Revenant",
		pathName: "Path of the Void Lord",
		level: 2,
		kind: "technique",
		sourceTokens: ["Revenant"],
		entryNames: ["Revenant's Final Entropy"],
	},
	{
		jobName: "Revenant",
		pathName: "Path of the Entropy Drinker",
		level: 2,
		kind: "power",
		sourceTokens: ["Revenant"],
		entryNames: ["Death's Momentum", "Entropy Harvest"],
		progression: "full",
	},
	{
		jobName: "Revenant",
		pathName: "Path of the Entropy Drinker",
		level: 2,
		kind: "technique",
		sourceTokens: ["Revenant"],
		entryNames: ["Entropy Surge", "Shadow Harvest"],
	},
	{
		jobName: "Revenant",
		pathName: "Path of the Wither Guard",
		level: 2,
		kind: "power",
		sourceTokens: ["Revenant"],
		entryNames: ["Withering Touch", "Entropic Feedback"],
		progression: "full",
	},
	{
		jobName: "Revenant",
		pathName: "Path of the Wither Guard",
		level: 2,
		kind: "technique",
		sourceTokens: ["Revenant"],
		entryNames: ["Withering Blade", "Entropic Rend"],
	},
	{
		jobName: "Revenant",
		pathName: "Path of the Entropy Blade",
		level: 2,
		kind: "power",
		sourceTokens: ["Revenant"],
		entryNames: ["Entropic Counter"],
		progression: "full",
	},
	{
		jobName: "Revenant",
		pathName: "Path of the Entropy Blade",
		level: 2,
		kind: "technique",
		sourceTokens: ["Revenant"],
		entryNames: ["Death's Reach", "Entropy Blade"],
	},
	{
		jobName: "Summoner",
		pathName: "Path of the Biome Architect",
		level: 2,
		kind: "power",
		sourceTokens: ["Summoner"],
		entryNames: ["Gate Reader"],
		progression: "full",
	},
	{
		jobName: "Summoner",
		pathName: "Path of the Apex Shifter",
		level: 2,
		kind: "power",
		sourceTokens: ["Summoner"],
		entryNames: ["Summoner's Leviathan"],
		progression: "full",
	},
	{
		jobName: "Summoner",
		pathName: "Path of the Pack Commander",
		level: 2,
		kind: "power",
		sourceTokens: ["Summoner"],
		entryNames: ["Summoner's Pack"],
		progression: "full",
	},
	{
		jobName: "Summoner",
		pathName: "Path of the Pack Commander",
		level: 2,
		kind: "technique",
		sourceTokens: ["Summoner"],
		entryNames: ["Summoner's Bond Strike", "Summoner's Convergence"],
	},
	{
		jobName: "Herald",
		pathName: "Path of the Combat Mandate",
		level: 1,
		kind: "power",
		sourceTokens: ["Herald"],
		entryNames: ["Guided Strike", "Commander's Presence", "Divine Mandate"],
		progression: "full",
	},
	{
		jobName: "Herald",
		pathName: "Path of the Combat Mandate",
		level: 1,
		kind: "technique",
		sourceTokens: ["Herald"],
		entryNames: ["Sacred Weapon", "Spiritual Hammer", "War God's Blessing"],
	},
	{
		jobName: "Herald",
		pathName: "Path of the Storm Mandate",
		level: 1,
		kind: "power",
		sourceTokens: ["Herald"],
		entryNames: ["Retributive Ward"],
		progression: "full",
	},
	{
		jobName: "Herald",
		pathName: "Path of the Triage Mandate",
		level: 1,
		kind: "power",
		sourceTokens: ["Herald"],
		entryNames: ["Herald's Intervention", "Circuit Defibrillator"],
		progression: "full",
	},
	{
		jobName: "Contractor",
		pathName: "Path of the Cursed Blade",
		level: 1,
		kind: "power",
		sourceTokens: ["Contractor"],
		entryNames: [
			"Cursed Blade Edge",
			"Pact Retaliation",
			"Tether of Binding",
			"Sacrifice Engine",
			"Blood Pact Escalation",
			"Patron's Embrace",
			"Patron Sacrifice",
			"Absolute Pact",
		],
		progression: "full",
	},
	{
		jobName: "Contractor",
		pathName: "Path of the Cursed Blade",
		level: 1,
		kind: "technique",
		sourceTokens: ["Contractor"],
		entryNames: [
			"Pact Blade",
			"Eldritch Riposte",
			"Pact Weapon Manifest",
			"Patron's Fury",
		],
	},
	{
		jobName: "Stalker",
		pathName: "Path of the Umbral Ascendant",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Shadow Strike"],
		maxLevel: 1,
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Blade Dancer",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Harmonic Counter"],
		maxLevel: 5,
	},
	{
		jobName: "Mage",
		pathName: "Path of the Shield Architect",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Mage",
		pathName: "Path of the Probability Mandate",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Mage",
		pathName: "Path of the Rift Caller",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Mage",
		pathName: "Path of the Matter Weaver",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Revenant",
		pathName: "Path of the Threshold Walker",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Stalker",
		pathName: "Path of the Apex Ascendant",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Stalker",
		pathName: "Path of the Pack Leader",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Stalker",
		pathName: "Path of the Rift Strider",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Holy Knight",
		pathName: "Path of the Verdant Mandate",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Technomancer",
		pathName: "Design: The Aether Chemist",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Technomancer",
		pathName: "Design: Swarm Conduit",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Technomancer",
		pathName: "Design: Aether Breacher",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Lore Resonance",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Hypnotic Resonance",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Shadow Resonance",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Genesis Resonance",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Dance Resonance",
		level: 1,
		kind: "spell",
		sourceTokens: [],
		entryNames: [],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Dance Resonance",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge", "Dissonant Strike"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Dance Resonance",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Strike", "Rhythmic Strike"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Hypnotic Resonance",
		level: 7,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Encore Performance"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Blade Resonance",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Resonance Slash"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Dance Resonance",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Arterial Cut"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Dance Resonance",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Dance Resonance",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Smite"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Dance Resonance",
		level: 9,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Slam"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Dance Resonance",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave", "Absolute Execution"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Dance Resonance",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension", "Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Apex Predator",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge", "Gate Reader"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Apex Predator",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Ascendant's Judgment", "Parallel Processing"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Apex Predator",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Killing Tempo", "Arcane Recovery"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Apex Predator",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Apex Strike", "Esper Ascension"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Apex Predator",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Apex Convergence"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Apex Predator",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Final Hunt"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Tactician",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Rampart Shell", "Withering Touch"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Tactician",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Death Mark", "Marked for Death"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Tactician",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Bulwark Resilience", "Commander's Presence"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Tactician",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Fortress Mode", "Summoner's Leviathan"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Tactician",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Pact", "Apex Convergence"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Bulwark",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Bulwark Stance", "Fault Line Stomp"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Bulwark",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Covenant Aegis"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Bulwark",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Devotion Guard"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Bulwark",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Sanctum", "Lattice-Stable Composite Shell"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Bulwark",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Fortress Mode", "Striker's Zenith"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Bulwark",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Holy Knight's Sacrifice"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Bulwark",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Skynet Protocol"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Last Stand",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Entropic Counter", "Iron Resolve"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Last Stand",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Crusader's Judgment"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Last Stand",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Kinetic Deflection Field"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Last Stand",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Lattice-Stable Composite Shell", "Arcane Charm"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Last Stand",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Last Stand", "Striker's Zenith"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Last Stand",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Last Stand",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Extinction Strike"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Aftershock",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Fault Line Stomp", "Nerve Gate Cascade"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Aftershock",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Divine Bastion"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Aftershock",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Earthquake Stomp"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Aftershock",
		level: 9,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Slam", "Demolition Wave"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Aftershock",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Mountain Crusher"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Aftershock",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Warhammer of the Absolute"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Aftershock",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Destroyer's Ruin"],
		progression: "base",
	},
	{
		jobName: "Destroyer",
		pathName: "Path of the Aftershock",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Final Strike"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Escalating Resonance",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge", "Fury Surge"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Escalating Resonance",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury", "Death Mark"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Escalating Resonance",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Cataclysm Overload", "Death's Shadow"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Escalating Resonance",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Patron Sacrifice"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Escalating Resonance",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Escalating Resonance",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension", "Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Gate Beast",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Reckless Cleave"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Gate Beast",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Gate Beast",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Savage Charge"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Gate Beast",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Titan's Rebuke"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Gate Beast",
		level: 9,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Carnage Wave"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Gate Beast",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Lycanthropy"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Gate Beast",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Entropic Avatar", "Fortress Mode"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Gate Beast",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Gate Beast",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Extinction Strike"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Rift Storm",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Crimson Howl", "Dissonant Strike"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Rift Storm",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["EMP Burst", "Idol's Duel"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Rift Storm",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Arsenal Deploy"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Rift Storm",
		level: 9,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Crescendo Finale"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Rift Storm",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Total Arsenal"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Rift Storm",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Rift Storm",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Resonance Apocalypse"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Rift Storm",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Skynet Protocol"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Absolute Zealot",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Strike"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Absolute Zealot",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Battle Cry"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Absolute Zealot",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Covenant Aegis", "Crusader's Judgment"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Absolute Zealot",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Sanctum", "Absolute Smite"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Absolute Zealot",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Absolute Zealot",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Eight Gates Release"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Absolute Zealot",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension", "Divine Mandate"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Mana Scars",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Mana Scars",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Counter Surge"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Mana Scars",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Death's Reach"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Mana Scars",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Lethal Precision"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Mana Scars",
		level: 9,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Circuit Breaker Slash", "Entropy Surge"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Mana Scars",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Patron Sacrifice"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Mana Scars",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Mana Scars",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension", "Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Aetheric Anomaly",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Mana Circuit Rush", "Mana-Laced Headbutt"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Aetheric Anomaly",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["EMP Burst"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Aetheric Anomaly",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Mana Forge"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Aetheric Anomaly",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Sanctum", "Arcane Charm"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Aetheric Anomaly",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["World Breaker"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Aetheric Anomaly",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave"],
		progression: "base",
	},
	{
		jobName: "Berserker",
		pathName: "Path of the Aetheric Anomaly",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension", "Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Terminus",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge", "Battle Cry"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Terminus",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Arterial Cut"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Terminus",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Terminus",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Smite", "Annihilation Rush"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Terminus",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave", "Absolute Execution"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Terminus",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Terminus",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Assassination Protocol"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Shadow Herald",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge", "Oath Purge"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Shadow Herald",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Gambit", "Phantom Blade Flurry"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Shadow Herald",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Arcane Recovery", "Cataclysm Overload"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Shadow Herald",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave", "Absolute Execution"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Shadow Herald",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension", "Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Vanguard Outrider",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Vanguard Outrider",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Strike"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Vanguard Outrider",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Arterial Cut"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Vanguard Outrider",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Vanguard Outrider",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Sanctum", "Absolute Smite"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Vanguard Outrider",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave", "Absolute Execution"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Vanguard Outrider",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension", "Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Gate Runner",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Gate Runner",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Strike"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Gate Runner",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Arterial Cut"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Gate Runner",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Gate Runner",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Sanctum", "Absolute Smite"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Gate Runner",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave", "Absolute Execution"],
		progression: "base",
	},
	{
		jobName: "Assassin",
		pathName: "Path of the Gate Runner",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension", "Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Kinetic Core",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Kinetic Core",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Strike"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Kinetic Core",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Arterial Cut"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Kinetic Core",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Kinetic Core",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Smite"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Kinetic Core",
		level: 9,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Slam"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Kinetic Core",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave", "Absolute Execution"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Kinetic Core",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Pact", "Apex Convergence"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Entropic Flow",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Battle Cry", "Cursed Blade Edge"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Entropic Flow",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury", "Blood Pact Escalation"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Entropic Flow",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Bulwark Resilience", "Cataclysm Overload"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Entropic Flow",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Execution"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Entropic Flow",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Last Stand"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Entropic Flow",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Pact"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Entropic Flow",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Assassination Protocol"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Blade Conductor",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Bulwark Stance", "Circuit Flare"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Blade Conductor",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Arterial Cut"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Blade Conductor",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Blade Conductor",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Smite", "Lattice-Stable Composite Shell"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Blade Conductor",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Execution", "Deathmark Strike"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Blade Conductor",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Blade Conductor",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Assassination Protocol"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Harmonic Surgeon",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge", "Battle Cry"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Harmonic Surgeon",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury", "Berserker's Gambit"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Harmonic Surgeon",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Lattice-Stable Composite Shell", "Annihilation Rush"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Harmonic Surgeon",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Last Stand", "Fortress Mode"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Harmonic Surgeon",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Extinction Strike"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Harmonic Surgeon",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Final Chorus"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Aetheric Channeler",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Bulwark Stance", "Circuit Flare"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Aetheric Channeler",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Crusader's Judgment"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Aetheric Channeler",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Death's Reach"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Aetheric Channeler",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Smite", "Arcane Charm"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Aetheric Channeler",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Mountain Crusher"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Aetheric Channeler",
		level: 13,
		kind: "power",
		sourceTokens: [],
		entryNames: ["World Breaker"],
		progression: "base",
	},
	{
		jobName: "Striker",
		pathName: "Path of the Aetheric Channeler",
		level: 17,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Destroyer's Ruin", "Extinction Strike"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Blade Resonance",
		level: 3,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Adrenaline Surge"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Blade Resonance",
		level: 3,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Strike"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Blade Resonance",
		level: 5,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Arterial Cut"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Blade Resonance",
		level: 5,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Berserker's Fury"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Blade Resonance",
		level: 9,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Smite"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Blade Resonance",
		level: 9,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Anchor Slam"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Blade Resonance",
		level: 13,
		kind: "technique",
		sourceTokens: [],
		entryNames: ["Absolute Cleave", "Absolute Execution"],
		progression: "base",
	},
	{
		jobName: "Idol",
		pathName: "Path of the Blade Resonance",
		level: 17,
		kind: "power",
		sourceTokens: [],
		entryNames: ["Absolute Ascension", "Absolute Pact"],
		progression: "base",
	},
];

function matchesName(
	a: string | null | undefined,
	b: string | null | undefined,
) {
	return normalizeJobAccessToken(a) === normalizeJobAccessToken(b);
}

function getThirdCasterMaxLevel(characterLevel: number): number {
	const level = Math.min(Math.max(characterLevel, 1), 20);
	if (level >= 19) return 4;
	if (level >= 13) return 3;
	if (level >= 7) return 2;
	if (level >= 3) return 1;
	return 0;
}

export function getPathGrantMaxAbilityLevel(
	grant: PathAbilityGrant,
	characterLevel: number,
): number {
	if (typeof grant.maxLevel === "number") return grant.maxLevel;
	if (grant.progression === "third")
		return getThirdCasterMaxLevel(characterLevel);
	if (grant.progression === "full") {
		return getMaxAbilityLevelForJobAtLevel("Mage", characterLevel, "spell");
	}
	const base = getMaxAbilityLevelForJobAtLevel(
		grant.jobName,
		characterLevel,
		grant.kind === "technique" ? "power" : grant.kind,
	);
	// When a path grant explicitly names entries (entryNames-based hybrid grant)
	// but the granted job can't naturally learn this ability kind (e.g., Idol on
	// Path of the Dance Resonance granting powers), the base progression returns
	// 0 and would block every entry. Fall back to the full-caster progression so
	// the named entries actually unlock at the right character level.
	if (base === 0 && grant.entryNames?.length) {
		return getMaxAbilityLevelForJobAtLevel("Mage", characterLevel, "spell");
	}
	return base;
}

export function getActivePathAbilityGrants(options: {
	jobName?: string | null;
	pathName?: string | null;
	characterLevel?: number | null;
	kind?: PathAbilityKind;
}): PathAbilityGrant[] {
	if (!options.jobName || !options.pathName) return [];
	const level = options.characterLevel ?? 0;
	return PATH_ABILITY_GRANTS.filter((grant) => {
		if (options.kind && grant.kind !== options.kind) return false;
		if (!matchesName(grant.jobName, options.jobName)) return false;
		if (!matchesName(grant.pathName, options.pathName)) return false;
		return level >= grant.level;
	});
}

export function pathGrantsAbilityKind(options: {
	jobName?: string | null;
	pathName?: string | null;
	characterLevel?: number | null;
	kind: PathAbilityKind;
}): boolean {
	return getActivePathAbilityGrants(options).length > 0;
}

export function getEffectiveMaxAbilityLevel(options: {
	jobName?: string | null;
	pathName?: string | null;
	characterLevel: number;
	kind: "spell" | "power";
}): number {
	const baseMax = getMaxAbilityLevelForJobAtLevel(
		options.jobName,
		options.characterLevel,
		options.kind,
	);
	const grantMax = getActivePathAbilityGrants({
		jobName: options.jobName,
		pathName: options.pathName,
		characterLevel: options.characterLevel,
		kind: options.kind,
	})
		.filter((grant) => !grant.entryNames?.length)
		.reduce(
			(max, grant) =>
				Math.max(
					max,
					getPathGrantMaxAbilityLevel(grant, options.characterLevel),
				),
			0,
		);
	return Math.max(baseMax, grantMax);
}

export function getPathAbilityGrantTokens(
	grants: readonly PathAbilityGrant[],
): string[] {
	const tokens = new Set<string>();
	for (const grant of grants) {
		for (const token of grant.sourceTokens)
			tokens.add(normalizeJobAccessToken(token));
		tokens.add(normalizeJobAccessToken(grant.pathName));
	}
	return Array.from(tokens).filter(Boolean);
}

export function normalizePathAbilityValue(
	value: string | null | undefined,
): string {
	return normalizeJobAccessToken(value);
}

/**
 * True iff the named entry is exclusively path-granted for the given job —
 * i.e., the entry's name appears in the `entryNames` list of at least one
 * PATH_ABILITY_GRANTS entry whose jobName matches. Such entries must NOT
 * be naturally learnable by the job; access is gated on selecting the path.
 *
 * Use this to exclude path-exclusive entries from the base eligibility
 * path in `isCanonicalSpellLearnable`/`isCanonicalPowerLearnable`/
 * `isCanonicalTechniqueLearnable` when no matching path is selected.
 */
export function isEntryPathExclusiveForJob(
	entryName: string | null | undefined,
	jobName: string | null | undefined,
	kind: PathAbilityKind,
): boolean {
	if (!entryName || !jobName) return false;
	const normalizedEntry = normalizePathAbilityValue(entryName);
	if (!normalizedEntry) return false;
	const normalizedJob = normalizeJobAccessToken(jobName);
	return PATH_ABILITY_GRANTS.some(
		(grant) =>
			grant.kind === kind &&
			normalizeJobAccessToken(grant.jobName) === normalizedJob &&
			grant.entryNames?.some(
				(name) => normalizePathAbilityValue(name) === normalizedEntry,
			),
	);
}
