project_id = "hqouinpnnmjjtvgjrnff"

[functions.signup]
verify_jwt = false

[storage.buckets]
[[storage.buckets.buckets]]
id = "compendium-images"
name = "compendium-images"
public = true
file_size_limit = 5242880
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/webp"]

[[storage.buckets.buckets]]
id = "custom-tokens"
name = "custom-tokens"
public = true
file_size_limit = 5242880
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/webp", "image/gif"]

[[storage.buckets.buckets]]
id = "character-portraits"
name = "character-portraits"
public = true
file_size_limit = 5242880
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/webp", "image/gif"]
