project_id = "rhqrtowjgocwkncqcerm"

[storage.buckets.compendium-images]
public = true
file_size_limit = 5242880
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/webp"]

[storage.buckets.custom-tokens]
public = true
file_size_limit = 5242880
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/webp", "image/gif"]

[storage.buckets.character-portraits]
public = true
file_size_limit = 5242880
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/webp", "image/gif"]
