import type { Container, Texture } from "pixi.js";
import { Graphics, Sprite } from "pixi.js";
import {
	WEATHER_PRESETS,
	type WeatherType,
} from "@/lib/vtt/terrainWeatherEngine";

/**
 * Native Pixi v8 weather renderer (GPU primary; the DOM/CSS overlay in
 * VTTEnhanced/AscendantMapView is the fallback when Pixi can't initialize).
 *
 * It is data-driven from `WEATHER_PRESETS` — only the *visual* fields are read
 * (`particleCount`, `particleVelocity`, `particleColor`). The weather
 * *mechanics* (visibility/difficult-terrain/ranged-disadvantage) live in
 * terrainWeatherEngine and are never touched here. Two render modes:
 *   • particle (count > 0): a wrapped pooled-sprite field driven by the preset
 *     velocity + colour, scaled by the active performance budget.
 *   • atmospheric (count === 0, fog/dense_fog): a gently-pulsing tint layer.
 * Other zero-particle types (clear, wind) render nothing.
 *
 * Purely visual — no bearing on any rule, mechanic, or canonical data.
 */

export type { WeatherType };

export type WeatherEmitter = {
	/** Advance the simulation. `deltaMs` is elapsed milliseconds (Ticker.deltaMS). */
	update: (deltaMs: number) => void;
	/** Remove all display objects from the layer and release references. */
	destroy: () => void;
};

type CreateWeatherEmitterOptions = {
	type: WeatherType;
	/** World bounds in pixels (scene width/height × grid × zoom). */
	width: number;
	height: number;
	/** Shared particle texture (a small white circle generated by the renderer). */
	texture: Texture;
	/** Performance budget from the active performance profile (fx.particleCount). */
	particleCount: number;
};

type WeatherParticle = {
	sprite: Sprite;
	x: number;
	y: number;
	vx: number;
	vy: number;
};

const clamp = (value: number, min: number, max: number) =>
	Math.min(max, Math.max(min, value));
const rand = (min: number, max: number) => min + Math.random() * (max - min);

/** Parse "rgba(r,g,b,a)" / "rgb(r,g,b)" / "transparent" into tint + alpha. */
const parseRgba = (input: string): { tint: number; alpha: number } => {
	const match = input.match(/rgba?\(([^)]+)\)/i);
	if (!match) return { tint: 0xffffff, alpha: 0 };
	const parts = match[1].split(",").map((p) => Number.parseFloat(p.trim()));
	const r = clamp(Math.round(parts[0] ?? 255), 0, 255);
	const g = clamp(Math.round(parts[1] ?? 255), 0, 255);
	const b = clamp(Math.round(parts[2] ?? 255), 0, 255);
	const a = Number.isFinite(parts[3]) ? clamp(parts[3], 0, 1) : 1;
	return { tint: (r << 16) | (g << 8) | b, alpha: a };
};

// Per-unit velocity → px/sec. Preset velocities are small per-frame deltas
// (rain dy=6, snow dy=1); this scales them to a readable on-screen speed.
const SPEED_SCALE = 42;
// Streaky (rain-like) weather draws elongated drops aligned to motion.
const STREAK_TYPES = new Set<WeatherType>([
	"rain",
	"heavy_rain",
	"thunderstorm",
]);

const isFogType = (type: WeatherType) => type === "fog" || type === "dense_fog";

/** A no-op emitter for clear/wind (no visible particles). */
const NOOP_EMITTER: WeatherEmitter = {
	update: () => {},
	destroy: () => {},
};

const createFogEmitter = (
	layer: Container,
	width: number,
	height: number,
	tint: number,
	baseAlpha: number,
): WeatherEmitter => {
	const fog = new Graphics();
	fog.rect(0, 0, Math.max(1, width), Math.max(1, height));
	fog.fill({ color: tint, alpha: baseAlpha });
	layer.addChild(fog);
	let destroyed = false;
	let elapsed = 0;
	return {
		update: (deltaMs) => {
			if (destroyed) return;
			elapsed += deltaMs / 1000;
			// Gentle ±15% alpha drift so the fog feels alive without distracting.
			fog.alpha = clamp(1 + 0.15 * Math.sin(elapsed * 0.6), 0.6, 1.15);
		},
		destroy: () => {
			if (destroyed) return;
			destroyed = true;
			fog.destroy();
		},
	};
};

/**
 * Create a weather renderer parented to `layer`. The caller drives it from the
 * Pixi ticker via `update(deltaMs)` and tears it down with `destroy()`.
 */
export function createWeatherEmitter(
	layer: Container,
	{ type, width, height, texture, particleCount }: CreateWeatherEmitterOptions,
): WeatherEmitter {
	const preset = WEATHER_PRESETS[type];
	if (!preset) return NOOP_EMITTER;
	const { tint, alpha } = parseRgba(preset.particleColor);

	if (isFogType(type)) {
		return createFogEmitter(layer, width, height, tint, alpha);
	}
	if (preset.particleCount <= 0) return NOOP_EMITTER;

	// Scale the designed particle count by the device's performance budget.
	const budget = Math.max(0, particleCount);
	const poolSize = clamp(
		Math.round((preset.particleCount * budget) / 40),
		6,
		400,
	);
	const vx = preset.particleVelocity.dx * SPEED_SCALE;
	const vy = preset.particleVelocity.dy * SPEED_SCALE;
	const streak = STREAK_TYPES.has(type);
	const rotation = streak ? Math.atan2(vy, vx) + Math.PI / 2 : 0;
	// Toroidal wrap margin so particles re-enter smoothly from the far edge.
	const margin = 40;
	const minX = -margin;
	const maxX = width + margin;
	const minY = -margin;
	const maxY = height + margin;
	const spanX = maxX - minX;
	const spanY = maxY - minY;

	const particles: WeatherParticle[] = [];
	for (let i = 0; i < poolSize; i++) {
		const sprite = new Sprite(texture);
		sprite.anchor.set(0.5);
		sprite.tint = tint;
		sprite.alpha = alpha;
		sprite.rotation = rotation;
		if (streak) {
			sprite.scale.set(0.12, rand(0.6, 0.95));
		} else {
			sprite.scale.set(rand(0.3, 0.55));
		}
		const x = rand(minX, maxX);
		const y = rand(minY, maxY);
		sprite.position.set(x, y);
		layer.addChild(sprite);
		particles.push({
			sprite,
			x,
			y,
			vx: vx + rand(-0.15, 0.15) * Math.abs(vx),
			vy: vy + rand(-0.15, 0.15) * Math.abs(vy),
		});
	}

	let destroyed = false;
	return {
		update: (deltaMs) => {
			if (destroyed) return;
			// Clamp dt so a long frame gap can't teleport the field across the map.
			const dt = clamp(deltaMs / 1000, 0, 0.05);
			if (dt <= 0) return;
			for (const p of particles) {
				p.x += p.vx * dt;
				p.y += p.vy * dt;
				// Toroidal wrap on both axes.
				if (p.x < minX) p.x += spanX;
				else if (p.x > maxX) p.x -= spanX;
				if (p.y < minY) p.y += spanY;
				else if (p.y > maxY) p.y -= spanY;
				p.sprite.position.set(p.x, p.y);
			}
		},
		destroy: () => {
			if (destroyed) return;
			destroyed = true;
			for (const p of particles) p.sprite.destroy();
			particles.length = 0;
		},
	};
}
