	{
		jobName: "Herald",
		pathName: "Path of the Restoration Mandate",
		level: 1,
		kind: "spell",
		sourceTokens: ["Herald"],
		entryNames: [
			"Aegis of the Absolute",
			"Fade to Shadow",
			"Corrosive Aura",
			"Entropic Wave",
			"Circuit Overclock",
			"Harmonic Barrage",
			"Death's Harvest",
			"Entropic Reaping",
			"Absolute Judgment",
			"Radiant Condemnation"
		],
		progression: "base",
	},	{
		jobName: "Herald",
		pathName: "Path of the Combat Mandate",
		level: 1,
		kind: "spell",
		sourceTokens: ["Herald","Mage"],
		entryNames: [
			"Aegis of the Absolute",
			"Bright Tomb",
			"Battlefield Harmony",
			"Crimson Cleave",
			"Harmonic Barrage",
			"Mana Overcharge",
			"Gate Ward",
			"Oath Aura",
			"Bureau Authority Override",
			"Pact Renegotiation"
		],
		progression: "base",
	},	{
		jobName: "Herald",
		pathName: "Path of the Triage Mandate",
		level: 1,
		kind: "spell",
		sourceTokens: ["Revenant"],
		entryNames: [
			"Hex Contract",
			"Necrotic Shroud",
			"Blood Tear",
			"Corrosive Aura",
			"Mana Siphon Strike",
			"Revenant's Embrace",
			"Death's Harvest",
			"Dimensional Anchor",
			"Raise Gate Dead"
		],
		progression: "base",
	},	{
		jobName: "Summoner",
		pathName: "Path of the Dream Weaver",
		level: 1,
		kind: "spell",
		sourceTokens: ["Idol","Esper"],
		entryNames: [
			"Fade to Shadow",
			"Phantom Step",
			"Entropic Wave",
			"Hymn of Courage",
			"Idol's Crescendo",
			"Anomaly Mimicry",
			"Enthralling Performance",
			"Pact Dominion",
			"Psionic Bastion"
		],
		progression: "base",
	},	{
		jobName: "Summoner",
		pathName: "Path of the Pack Commander",
		level: 1,
		kind: "spell",
		sourceTokens: ["Summoner"],
		entryNames: [
			"Bright Tomb",
			"Commanding Hymn",
			"Battlefield Harmony",
			"Blood Tear",
			"Absolute Beacon",
			"Circuit Overclock",
			"Anomaly Cage",
			"Anomaly Mimicry",
			"Absolute Judgment",
			"Gate Fissure"
		],
		progression: "base",
	},	{
		jobName: "Summoner",
		pathName: "Path of the Symbiotic Host",
		level: 1,
		kind: "spell",
		sourceTokens: ["Revenant","Mage"],
		entryNames: [
			"Healing Resonance",
			"Thorn Salvo",
			"Entropic Wave",
			"Mana Thorn Barrier",
			"Restoration Chorus"
		],
		progression: "base",
	},	{
		jobName: "Summoner",
		pathName: "Path of the Cosmic Conduit",
		level: 1,
		kind: "spell",
		sourceTokens: ["Herald","Mage"],
		entryNames: [
			"Bright Tomb",
			"Ember Trail",
			"Blood Tear",
			"Corrosive Aura",
			"Absolute Beacon",
			"Binding Oath",
			"Anomaly Cage",
			"Anomaly Leash",
			"Absolute Judgment",
			"Bureau Authority Override"
		],
		progression: "base",
	},	{
		jobName: "Contractor",
		pathName: "Path of the Cursed Blade",
		level: 1,
		kind: "spell",
		sourceTokens: ["Mage","Destroyer"],
		entryNames: [
			"Aegis of the Absolute",
			"Bright Tomb",
			"Arctic Lance",
			"Awakening Surge",
			"Absolute Beacon",
			"Binding Oath",
			"Anomaly Cage",
			"Anomaly Leash",
			"Absolute Judgment",
			"Bureau Authority Override"
		],
		progression: "base",
	},	{
		jobName: "Contractor",
		pathName: "Path of the Deep Dweller",
		level: 1,
		kind: "spell",
		sourceTokens: ["Mage"],
		entryNames: [
			"Bright Tomb",
			"Commanding Hymn",
			"Arctic Lance",
			"Awakening Surge",
			"Gate Anchor",
			"Mana Overcharge",
			"Anomaly Mimicry",
			"Dimensional Pocket",
			"Bureau Authority Override",
			"Restoration Chorus"
		],
		progression: "base",
	},	{
		jobName: "Esper",
		pathName: "Path of the Aetheric Dragon",
		level: 1,
		kind: "spell",
		sourceTokens: ["Mage"],
		entryNames: [
			"Aegis of the Absolute",
			"Bright Tomb",
			"Arctic Lance",
			"Awakening Surge",
			"Absolute Beacon",
			"Binding Oath",
			"Anomaly Cage",
			"Anomaly Leash",
			"Absolute Judgment",
			"Bureau Authority Override"
		],
		progression: "base",
	},	{
		jobName: "Esper",
		pathName: "Path of the Void Resonance",
		level: 1,
		kind: "spell",
		sourceTokens: ["Mage","Revenant"],
		entryNames: [
			"Aegis of the Absolute",
			"Commanding Hymn",
			"Blood Tear",
			"Entropy Siphon",
			"Absolute Beacon",
			"Binding Oath",
			"Anomaly Leash",
			"Death's Harvest",
			"Absolute Judgment",
			"Gate Fissure"
		],
		progression: "base",
	},	{
		jobName: "Esper",
		pathName: "Path of the Tempest Core",
		level: 1,
		kind: "spell",
		sourceTokens: ["Mage"],
		entryNames: [
			"Healing Resonance",
			"Tempest Binding",
			"Blood Tear",
			"Circuit Overload",
			"Harmonic Barrage",
			"Idol's Crescendo",
			"Resonance Cascade",
			"Thorn Fortress",
			"Bureau Authority Override",
			"Mana Storm"
		],
		progression: "base",
	},	{
		jobName: "Esper",
		pathName: "Path of the Psionic Breach",
		level: 1,
		kind: "spell",
		sourceTokens: ["Esper"],
		entryNames: [
			"Hex Contract",
			"Psychic Lance",
			"Entropic Wave",
			"Hymn of Courage",
			"Idol's Crescendo",
			"Pact Brand",
			"Enthralling Performance",
			"Phantom Swarm",
			"Pact Dominion",
			"Psionic Bastion"
		],
		progression: "base",
	},	{
		jobName: "Revenant",
		pathName: "Path of the Void Lord",
		level: 1,
		kind: "spell",
		sourceTokens: ["Contractor","Mage"],
		entryNames: [
			"Commanding Hymn",
			"Resonance Pulse",
			"Hallowed Ground",
			"Hymn of Courage",
			"Absolute Beacon",
			"Binding Oath",
			"Dimensional Anchor",
			"Oath Aura",
			"Absolute Judgment",
			"Pact Dominion"
		],
		progression: "base",
	},	{
		jobName: "Revenant",
		pathName: "Path of the Entropy Drinker",
		level: 1,
		kind: "spell",
		sourceTokens: ["Revenant"],
		entryNames: [
			"Resonance Pulse",
			"Soul Siphon",
			"Blood Tear",
			"Crimson Cleave",
			"Mana Siphon Strike"
		],
		progression: "base",
	},	{
		jobName: "Revenant",
		pathName: "Path of the Wither Guard",
		level: 1,
		kind: "spell",
		sourceTokens: ["Revenant"],
		entryNames: [
			"Aegis of the Absolute",
			"Healing Resonance",
			"Blood Tear",
			"Corrosive Aura",
			"Absolute Beacon",
			"Mana Siphon Strike",
			"Death's Harvest",
			"Entropic Reaping"
		],
		progression: "base",
	},	{
		jobName: "Revenant",
		pathName: "Path of the Plague Weaver",
		level: 1,
		kind: "spell",
		sourceTokens: ["Revenant","Summoner"],
		entryNames: [
			"Healing Resonance",
			"Thorn Salvo",
			"Mana Thorn Barrier",
			"Restoration Chorus"
		],
		progression: "base",
	},	{
		jobName: "Holy Knight",
		pathName: "Path of the Dominance Mandate",
		level: 1,
		kind: "spell",
		sourceTokens: ["Contractor","Esper"],
		entryNames: [
			"Bright Tomb",
			"Commanding Hymn",
			"Crimson Cleave",
			"Hymn of Courage",
			"Gravity Well",
			"Mana Detonation Charge",
			"Anomaly Leash",
			"Bureau Authority Override",
			"Pact Dominion"
		],
		progression: "base",
	},	{
		jobName: "Holy Knight",
		pathName: "Path of the Atonement Mandate",
		level: 1,
		kind: "spell",
		sourceTokens: ["Herald"],
		entryNames: [
			"Aegis of the Absolute",
			"Bright Tomb",
			"Hallowed Ground",
			"Oath Tether",
			"Absolute Beacon",
			"Mana Overcharge",
			"Gate Ward",
			"Oath Aura",
			"Bureau Authority Override",
			"Pact Renegotiation"
		],
		progression: "base",
	},	{
		jobName: "Holy Knight",
		pathName: "Path of the Exaltation Mandate",
		level: 1,
		kind: "spell",
		sourceTokens: ["Herald","Idol"],
		entryNames: [
			"Frost Lattice",
			"Crimson Cleave",
			"Deploy Drone",
			"Circuit Overclock",
			"Gravity Well",
			"Mass Circuit Boost"
		],
		progression: "base",
	},	{
		jobName: "Stalker",
		pathName: "Path of the Umbral Hunter",
		level: 1,
		kind: "spell",
		sourceTokens: ["Mage"],
		entryNames: [
			"Fade to Shadow",
			"Mana Thread Snare",
			"Hallowed Ground",
			"Hymn of Courage",
			"Circuit Overclock",
			"Pact Hunger",
			"Mass Circuit Boost",
			"Predator's Web"
		],
		progression: "base",
	},	{
		jobName: "Stalker",
		pathName: "Path of the Apex Slayer",
		level: 1,
		kind: "spell",
		sourceTokens: ["Herald","Mage"],
		entryNames: [
			"Aegis of the Absolute",
			"Bright Tomb",
			"Blood Tear",
			"Crimson Cleave",
			"Absolute Beacon",
			"Gravity Well",
			"Oath Aura",
			"Resonance Cascade",
			"Mana Storm"
		],
		progression: "base",
	},	{
		jobName: "Stalker",
		pathName: "Path of the Hive Synchronist",
		level: 1,
		kind: "spell",
		sourceTokens: ["Summoner","Mage"],
		entryNames: [
			"Crimson Cleave",
			"Deploy Drone",
			"Gravity Well",
			"Oath Aura",
			"Phantom Swarm",
			"Absolute Judgment",
			"Predator's Web"
		],
		progression: "base",
	},	{
		jobName: "Technomancer",
		pathName: "Design: The Aether Vessel",
		level: 1,
		kind: "spell",
		sourceTokens: ["Mage"],
		entryNames: [
			"Fade to Shadow",
			"Healing Resonance",
			"Circuit Overload",
			"Crimson Cleave",
			"Harmonic Barrage",
			"Idol's Crescendo",
			"Anomaly Cage",
			"Resonance Cascade",
			"Sonic Annihilation"
		],
		progression: "base",
	},	{
		jobName: "Technomancer",
		pathName: "Design: Resonance Siege",
		level: 1,
		kind: "spell",
		sourceTokens: ["Mage"],
		entryNames: [
			"Bright Tomb",
			"Ember Trail",
			"Awakening Surge",
			"Crimson Cleave",
			"Gravity Well",
			"Harmonic Barrage",
			"Dimensional Anchor",
			"Mana Cannon",
			"Gate Fissure",
			"Mana Cascade Failure"
		],
		progression: "base",
	},	{
		jobName: "Technomancer",
		pathName: "Design: Synchronist Binary",
		level: 1,
		kind: "spell",
		sourceTokens: ["Herald"],
		entryNames: [
			"Aegis of the Absolute",
			"Bright Tomb",
			"Circuit Overload",
			"Corrosive Aura",
			"Absolute Beacon",
			"Harmonic Barrage",
			"Anomaly Cage",
			"Death's Harvest",
			"Absolute Judgment",
			"Bureau Authority Override"
		],
		progression: "base",
	},