// Unified Sovereign application payload.
//
// When a Sovereign is locked in — whether generated by the embedded AI or
// imported from an outside AI — we persist a single `gemini_state` payload so
// the fusion is applied identically in every consumer:
//   • characters.active_sovereign_id  → SovereignOverlayPanel (display)        [set in useSaveSovereign]
//   • characters.gemini_state.overlay → characterEngine.aggregateGeminiFeatures (full class overlay)
//   • characters.gemini_state runtime → geminiResolver (theme / stability / power / modifiers)
//
// The overlay block is shape-compatible with `CharacterJob.gemini`, so the
// engine bridge can hand it straight to `aggregateGeminiFeatures`.

import type { GeneratedSovereign } from "@/lib/geminiProtocol";

/** Overlay block consumed by characterEngine.aggregateGeminiFeatures (== CharacterJob["gemini"]). */
export interface SovereignOverlayPayload {
	id: string;
	sovereignId: string;
	regent1Id: string | null;
	regent2Id: string | null;
	features: Array<{ name: string; description: string; type?: string }>;
	traits: Array<{ name: string; description: string; type?: string }>;
	statBonuses: Record<string, number>;
}

/** Full gemini_state written to the character on lock-in. */
export interface SovereignGeminiState extends SovereignOverlayPayload {
	sovereignName: string;
	isActive: boolean;
	fusionTheme: string | null;
	fusionStability: string | null;
	powerMultiplier: string | null;
	/** Runtime stat modifiers (Sovereigns grant abilities, not stat bonuses → usually empty). */
	modifiers: unknown[];
}

/**
 * Build the gemini_state for a locked-in Sovereign. `sovereignId` is the row id
 * returned from inserting into `saved_sovereigns`.
 */
export function buildSovereignGeminiState(
	sovereign: GeneratedSovereign,
	sovereignId: string,
): SovereignGeminiState {
	const features = sovereign.abilities.map((ability) => ({
		name: ability.name,
		description: ability.description,
		type: ability.action_type ?? "passive",
	}));

	return {
		id: sovereignId,
		sovereignId,
		sovereignName: sovereign.name,
		isActive: true,
		fusionTheme: sovereign.fusion_theme ?? null,
		fusionStability: sovereign.fusion_stability ?? null,
		powerMultiplier: sovereign.power_multiplier ?? null,
		regent1Id: sovereign.regentA?.id ?? null,
		regent2Id: sovereign.regentB?.id ?? null,
		features,
		traits: [],
		statBonuses: {},
		modifiers: [],
	};
}

/**
 * Extract the engine overlay block from a persisted `gemini_state`, for the
 * character-engine bridge. Returns undefined when no Sovereign is locked in or
 * the payload lacks fusion features.
 */
export function geminiOverlayFromState(
	geminiState: unknown,
): SovereignOverlayPayload | undefined {
	if (
		!geminiState ||
		typeof geminiState !== "object" ||
		Array.isArray(geminiState)
	) {
		return undefined;
	}
	const state = geminiState as Record<string, unknown>;
	const sovereignId =
		typeof state.sovereignId === "string" ? state.sovereignId : null;
	const features = Array.isArray(state.features) ? state.features : [];
	if (!sovereignId || features.length === 0) return undefined;

	return {
		id: sovereignId,
		sovereignId,
		regent1Id: typeof state.regent1Id === "string" ? state.regent1Id : null,
		regent2Id: typeof state.regent2Id === "string" ? state.regent2Id : null,
		features: features as SovereignOverlayPayload["features"],
		traits: Array.isArray(state.traits)
			? (state.traits as SovereignOverlayPayload["traits"])
			: [],
		statBonuses:
			state.statBonuses && typeof state.statBonuses === "object"
				? (state.statBonuses as Record<string, number>)
				: {},
	};
}

/** All `character_features.source` values for a Sovereign start with this. */
export const SOVEREIGN_FEATURE_SOURCE_PREFIX = "Sovereign:";

/** A character_features insert row (sans character_id) for one fusion ability. */
export interface SovereignFeatureRow {
	name: string;
	source: string;
	level_acquired: number;
	description: string;
	action_type: string;
	recharge: string | null;
	is_active: boolean;
	modifiers: null;
	homebrew_id: null;
}

/**
 * Map a Sovereign's 8 fusion abilities into real `character_features` rows so
 * they appear natively in the sheet's Features tab (grouped under "Sovereign")
 * and — for the active ones — in the Actions tab. Identical for embedded and
 * imported Sovereigns. Sovereigns grant abilities, not stat bonuses, so
 * `modifiers` is null.
 */
export function sovereignAbilitiesToFeatureRows(
	sovereign: GeneratedSovereign,
): SovereignFeatureRow[] {
	const source = `${SOVEREIGN_FEATURE_SOURCE_PREFIX} ${sovereign.name}`;
	return sovereign.abilities.map((ability) => ({
		name: ability.name,
		source,
		level_acquired: ability.level,
		description: ability.description,
		action_type: ability.action_type ?? "passive",
		recharge: ability.recharge,
		is_active: true,
		modifiers: null,
		homebrew_id: null,
	}));
}

/** True when a feature row was created by a Sovereign fusion. */
export function isSovereignFeatureSource(
	source: string | null | undefined,
): boolean {
	return (
		typeof source === "string" &&
		source.startsWith(SOVEREIGN_FEATURE_SOURCE_PREFIX)
	);
}

/** An active feature is a combat action when it costs an action/bonus/reaction. */
export function isActionableActionType(
	actionType: string | null | undefined,
): boolean {
	if (!actionType) return false;
	const a = actionType.toLowerCase();
	return a.includes("action") || a.includes("bonus") || a.includes("reaction");
}
