/**
 * Regenerate the server-owned companion source catalog after an authored
 * Anomaly/mount catalog revision. Review the resulting migration diff before
 * release; existing living-instance snapshots remain frozen separately.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { staticDataProvider } from "../src/data/compendium/providers";
import { allMounts } from "../src/data/compendium/vehicles";
import { createCanonicalCompanionSource } from "../src/lib/companions";

const REVISION = "canon.0741885f";
const OUTPUT = join(
	process.cwd(),
	"supabase/migrations/20260926071000_companion_source_catalog.sql",
);

const sqlString = (value: string): string => `'${value.replaceAll("'", "''")}'`;

interface CatalogRow {
	collection: "anomalies" | "vehicles";
	id: string;
	rank: string | null;
	hpMax: number;
	snapshot: ReturnType<typeof createCanonicalCompanionSource>;
}

function wholePositive(value: unknown, label: string): number {
	const number = Number(value);
	if (!Number.isSafeInteger(number) || number <= 0) {
		throw new Error(`Invalid ${label}: ${String(value)}`);
	}
	return number;
}

async function main(): Promise<void> {
	const anomalies = await staticDataProvider.getAnomalies();
	const rows: CatalogRow[] = anomalies.map((entry) => {
		const hpMax = wholePositive(entry.hit_points_average, `${entry.id} HP`);
		const baseAc = wholePositive(entry.armor_class, `${entry.id} AC`);
		const speed = Number(entry.speed_walk ?? 30) || 30;
		const rank = String(entry.gate_rank ?? entry.rank ?? "").trim() || null;
		return {
			collection: "anomalies",
			id: entry.id,
			rank,
			hpMax,
			snapshot: createCanonicalCompanionSource({
				canonicalId: entry.id,
				canonicalType: "anomaly",
				canonicalCollection: "anomalies",
				entryType: "anomaly",
				source: null,
				sourceBook: null,
				name: entry.name,
				hpMax,
				baseAc,
				speed,
				rank,
			}),
		};
	});

	for (const mount of allMounts.filter(
		(entry) => entry.vehicle_type === "mount",
	)) {
		const hpMax = wholePositive(mount.hit_points.max, `${mount.id} HP`);
		const baseAc = wholePositive(mount.armor_class, `${mount.id} AC`);
		const speed = Number(mount.speed?.land ?? 0);
		if (!Number.isSafeInteger(speed) || speed < 0) {
			throw new Error(`Invalid ${mount.id} speed`);
		}
		const rank = mount.rank ?? null;
		rows.push({
			collection: "vehicles",
			id: mount.id,
			rank,
			hpMax,
			snapshot: createCanonicalCompanionSource({
				canonicalId: mount.id,
				canonicalType: "vehicle",
				canonicalCollection: "vehicles",
				entryType: "mount",
				source:
					typeof (mount as { source?: unknown }).source === "string"
						? ((mount as { source?: string }).source ?? null)
						: null,
				sourceBook: mount.source_book ?? null,
				name: mount.name,
				hpMax,
				baseAc,
				speed,
				rank,
			}),
		});
	}

	const keys = rows.map((row) => `${row.collection}:${row.id}`);
	if (new Set(keys).size !== keys.length) {
		throw new Error("Duplicate canonical companion source ID");
	}
	rows.sort((a, b) =>
		a.collection === b.collection
			? a.id.localeCompare(b.id)
			: a.collection.localeCompare(b.collection),
	);

	const values = rows.map(
		(row) =>
			`  (${sqlString(row.collection)}, ${sqlString(row.id)}, ${row.rank === null ? "NULL" : sqlString(row.rank)}, ${row.hpMax}, ${sqlString(JSON.stringify(row.snapshot))}::jsonb, ${sqlString(REVISION)})`,
	);
	const sql = `-- Generated by scripts/generate-companion-source-catalog.ts.\n-- This is the server authority for source IDs and immutable acquisition stats.\nBEGIN;\n\nCREATE TABLE IF NOT EXISTS app_private.canonical_companion_sources (\n  source_collection TEXT NOT NULL CHECK (source_collection IN ('anomalies', 'vehicles')),\n  source_id TEXT NOT NULL,\n  rank TEXT,\n  hp_max INTEGER NOT NULL CHECK (hp_max > 0),\n  snapshot JSONB NOT NULL,\n  source_revision TEXT NOT NULL,\n  PRIMARY KEY (source_collection, source_id)\n);\n\nINSERT INTO app_private.canonical_companion_sources (\n  source_collection, source_id, rank, hp_max, snapshot, source_revision\n) VALUES\n${values.join(",\n")}\nON CONFLICT (source_collection, source_id) DO UPDATE SET\n  rank = EXCLUDED.rank,\n  hp_max = EXCLUDED.hp_max,\n  snapshot = EXCLUDED.snapshot,\n  source_revision = EXCLUDED.source_revision;\n\nREVOKE ALL ON app_private.canonical_companion_sources FROM PUBLIC, anon, authenticated;\n\nCOMMIT;\n`;
	writeFileSync(OUTPUT, sql, "utf8");
	console.log(`Wrote ${rows.length} canonical sources to ${OUTPUT}`);
}

void main();
