/** Regenerate the server's exact canonical Regent pick IDs and owed counts. */
import { writeFileSync } from "node:fs";
import { powers } from "../src/data/compendium/powers";
import { regents } from "../src/data/compendium/regents";
import { spells } from "../src/data/compendium/spells";
import { techniques } from "../src/data/compendium/techniques";
import { calculateTotalChoices } from "../src/lib/choiceCalculations";
import { regentToChoiceSource } from "../src/lib/regentProgression";

const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
const rows = new Map<
	string,
	{ kind: string; id: string; name: string; tier: number }
>();
for (const power of powers) {
	if (power.power_level >= 5)
		rows.set(`powers:${power.id}`, {
			kind: "powers",
			id: power.id,
			name: power.name,
			tier: power.power_level,
		});
}
for (const technique of techniques) {
	const tier = technique.level_requirement ?? 0;
	if (tier >= 5)
		rows.set(`techniques:${technique.id}`, {
			kind: "techniques",
			id: technique.id,
			name: technique.name,
			tier,
		});
}
for (const spell of spells) {
	const tier = spell.level ?? 0;
	const kind = tier === 0 ? "cantrips" : "spells";
	rows.set(`${kind}:${spell.id}`, {
		kind,
		id: spell.id,
		name: spell.name,
		tier,
	});
}

const catalogValues = [...rows.values()]
	.sort((a, b) => a.kind.localeCompare(b.kind) || a.id.localeCompare(b.id))
	.map(
		(row) =>
			`  (${quote(row.kind)}, ${quote(row.id)}, ${quote(row.name)}, ${row.tier})`,
	)
	.join(",\n");

const requirementValues = regents
	.flatMap((regent) =>
		Array.from({ length: 20 }, (_, index) => {
			const level = index + 1;
			const totals = calculateTotalChoices(
				null,
				null,
				[regentToChoiceSource(regent)],
				level,
			);
			const slots = regent.spellcasting?.spell_slots ?? {};
			const maxSpellTier = Object.entries(slots).reduce(
				(max, [ordinal, counts]) => {
					const tier = Number.parseInt(ordinal, 10);
					return Array.isArray(counts) && Number(counts[index]) > 0
						? Math.max(max, tier)
						: max;
				},
				0,
			);
			return `  (${quote(regent.id)}, ${quote(regent.name)}, ${level}, ${totals.powers ?? 0}, ${totals.techniques ?? 0}, ${totals.cantrips ?? 0}, ${totals.spells ?? 0}, ${maxSpellTier})`;
		}),
	)
	.join(",\n");

const output = `-- Generated by scripts/generate-regent-catchup-seed.ts. Do not edit by hand.
-- Power and technique options are canonical tier 5+; Regent identity/theme is curated by a Warden per unlock.
INSERT INTO app_private.regent_canonical_pick_options (kind, canonical_id, name, tier) VALUES
${catalogValues}
ON CONFLICT (kind, canonical_id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier;

INSERT INTO app_private.regent_catch_up_requirements (regent_id, regent_name, character_level, powers, techniques, cantrips, spells, max_spell_tier) VALUES
${requirementValues}
ON CONFLICT (regent_id, character_level) DO UPDATE SET
  regent_name = EXCLUDED.regent_name, powers = EXCLUDED.powers, techniques = EXCLUDED.techniques,
  cantrips = EXCLUDED.cantrips, spells = EXCLUDED.spells, max_spell_tier = EXCLUDED.max_spell_tier;
`;
writeFileSync(
	"supabase/migrations/20260926100100_regent_catchup_seed.sql",
	output,
);
