/**
 * Regenerate the canonical Sovereign source catalog after a Job, Path, or
 * Regent is added, renamed, or removed. It writes two files from the static
 * compendium the app reads:
 *
 *   api/_sovereignSources.ts  - read by /api/sovereign (always rewritten)
 *   supabase/migrations/<timestamp>_sovereign_source_catalog.sql
 *                             - replaces app_private.canonical_sovereign_sources
 *
 *   npx tsx scripts/generate-sovereign-source-catalog.ts [--timestamp=YYYYMMDDHHMMSS] [--force]
 *
 * Applied migrations are immutable, so each catalog change needs a NEW
 * migration; --force only overwrites a file with the same timestamp.
 * src/lib/__tests__/sovereignSourceCatalog.test.ts fails when either file
 * drifts from the static compendium.
 */
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { staticDataProvider } from "../src/data/compendium/providers";
import {
	buildSovereignSourceCatalog,
	type SovereignCanonicalSource,
} from "../src/lib/sovereign/sovereignSourceCatalog";

const sqlString = (value: string): string => `'${value.replaceAll("'", "''")}'`;

function utcTimestamp(date: Date): string {
	return date
		.toISOString()
		.replace(/[-:T]/g, "")
		.replace(/\.\d+Z$/, "");
}

function readOptions(argv: readonly string[]) {
	const timestamp =
		argv
			.find((arg) => arg.startsWith("--timestamp="))
			?.slice("--timestamp=".length) ?? utcTimestamp(new Date());
	if (!/^\d{14}$/.test(timestamp)) {
		throw new Error(`--timestamp must be YYYYMMDDHHMMSS, got ${timestamp}`);
	}
	return { timestamp, force: argv.includes("--force") };
}

function renderSovereignSourcesModule(
	sources: readonly SovereignCanonicalSource[],
): string {
	const body = sources
		.map((source) => `\t${JSON.stringify(source)},`)
		.join("\n");
	return `// Generated by scripts/generate-sovereign-source-catalog.ts. Do not edit.
//
// Canonical Job, Path, and Regent sources for /api/sovereign. Vercel runs api/
// files as plain Node modules, which cannot load the app's aliased compendium,
// so the function reads this generated copy. The parity test
// src/lib/__tests__/sovereignSourceCatalog.test.ts keeps it equal to the
// static compendium.

export type SovereignSourceKind = "job" | "path" | "regent";

export interface SovereignSourceRecord {
	kind: SovereignSourceKind;
	id: string;
	name: string;
	display_name?: string;
	title?: string;
	theme?: string;
	description?: string;
	hit_die?: number;
	primary_abilities?: string[];
	job_id?: string;
}

export const SOVEREIGN_SOURCES: readonly SovereignSourceRecord[] = [
${body}
];
`;
}

function renderSovereignSourceMigration(
	sources: readonly SovereignCanonicalSource[],
): string {
	const values = sources
		.map(
			(source) =>
				`  (${sqlString(source.kind)}, ${sqlString(source.id)}, ${sqlString(source.name)}, ${
					source.job_id ? sqlString(source.job_id) : "NULL"
				})`,
		)
		.join(",\n");
	return `-- Generated by scripts/generate-sovereign-source-catalog.ts from the static
-- compendium. Sovereign authority (definition validation, saved rows, and
-- attachment) uses these canonical ids, the same slugs characters store in
-- characters.job_id / path_id and the app sends to /api/sovereign.
BEGIN;

CREATE TABLE IF NOT EXISTS app_private.canonical_sovereign_sources (
  kind TEXT NOT NULL CHECK (kind IN ('job', 'path', 'regent')),
  canonical_id TEXT NOT NULL,
  name TEXT NOT NULL,
  job_id TEXT,
  PRIMARY KEY (kind, canonical_id),
  CHECK ((kind = 'path') = (job_id IS NOT NULL))
);
REVOKE ALL ON app_private.canonical_sovereign_sources FROM PUBLIC, anon, authenticated;

DELETE FROM app_private.canonical_sovereign_sources;
INSERT INTO app_private.canonical_sovereign_sources (kind, canonical_id, name, job_id)
VALUES
${values};

COMMIT;
`;
}

async function main(): Promise<void> {
	const { timestamp, force } = readOptions(process.argv.slice(2));
	const migration = join(
		process.cwd(),
		`supabase/migrations/${timestamp}_sovereign_source_catalog.sql`,
	);
	if (existsSync(migration) && !force) {
		throw new Error(`${migration} exists; pass --force to overwrite it.`);
	}

	const [jobs, paths, regents] = await Promise.all([
		staticDataProvider.getJobs(),
		staticDataProvider.getPaths(),
		staticDataProvider.getRegents(),
	]);
	const sources = buildSovereignSourceCatalog({ jobs, paths, regents });

	writeFileSync(
		join(process.cwd(), "api/_sovereignSources.ts"),
		renderSovereignSourcesModule(sources),
		"utf8",
	);
	writeFileSync(migration, renderSovereignSourceMigration(sources), "utf8");

	const count = (kind: string) =>
		sources.filter((source) => source.kind === kind).length;
	console.log(
		`Wrote ${sources.length} Sovereign sources (${count("job")} jobs, ${count("path")} paths, ${count("regent")} Regents) to api/_sovereignSources.ts and ${migration}`,
	);
}

main().catch((error: unknown) => {
	console.error(error);
	process.exit(1);
});
