/**
 * Count exactly how many entries are generated by the combinatorial code.
 */
const fs = require('fs');

// For each supplemental file, count prefixes * forms = generated entries
function countCombinations(filePath) {
  const raw = fs.readFileSync(filePath, 'utf-8');
  
  // Find all family blocks and count prefix/form combos
  const familyBlocks = raw.split(/\n\t\{/).filter(b => b.includes('prefixes:'));
  
  let total = 0;
  const details = [];
  
  for (const block of familyBlocks) {
    const prefixMatch = block.match(/prefixes:\s*\[([^\]]+)\]/s);
    const formMatch = block.match(/forms:\s*\[([^\]]+)\]/s);
    
    if (prefixMatch && formMatch) {
      const prefixes = prefixMatch[1].match(/"[^"]+"/g) || [];
      const forms = formMatch[1].match(/"[^"]+"/g) || [];
      const count = prefixes.length * forms.length;
      total += count;
      
      const classMatch = block.match(/classes:\s*\[([^\]]+)\]/);
      const classes = classMatch ? classMatch[1].replace(/"/g, '').trim() : '?';
      const modeMatch = block.match(/mode:\s*"([^"]+)"/);
      const mode = modeMatch ? modeMatch[1] : '?';
      
      details.push({
        classes,
        mode,
        prefixes: prefixes.length,
        forms: forms.length,
        generated: count,
        sampleNames: prefixes.slice(0,2).map(p => p.replace(/"/g,'')).flatMap(p => 
          forms.slice(0,2).map(f => `${p} ${f.replace(/"/g,'')}`)
        ),
      });
    }
  }
  
  return { total, details };
}

const files = {
  'Spells (rank-d.ts)': { type: 'manual', path: 'src/data/compendium/spells/rank-d.ts' },
  'Spells (supplemental)': { type: 'generated', path: 'src/data/compendium/spells/supplemental.ts' },
  'Powers (core)': { type: 'manual', path: 'src/data/compendium/powers-core.ts' },
  'Powers (supplemental)': { type: 'generated', path: 'src/data/compendium/powers-supplemental.ts' },
  'Techniques (core)': { type: 'manual', path: 'src/data/compendium/techniques-core.ts' },
  'Techniques (supplemental)': { type: 'generated', path: 'src/data/compendium/techniques-supplemental.ts' },
};

let grandTotal = 0;
const report = {};

for (const [label, info] of Object.entries(files)) {
  if (!fs.existsSync(info.path)) { console.log(label, ': NOT FOUND'); continue; }
  
  if (info.type === 'manual') {
    const raw = fs.readFileSync(info.path, 'utf-8');
    // Count object blocks with id: field
    const matches = raw.match(/\n\t\{[\s\S]*?id:\s*"/g) || [];
    const count = matches.length;
    report[label] = { count, type: 'manual' };
    grandTotal += count;
    console.log(`${label}: ${count} manual entries`);
  } else {
    const result = countCombinations(info.path);
    report[label] = { count: result.total, type: 'generated', families: result.details };
    grandTotal += result.total;
    console.log(`${label}: ${result.total} generated entries`);
    for (const d of result.details) {
      console.log(`  ${d.classes} [${d.mode}]: ${d.prefixes}p × ${d.forms}f = ${d.generated} (e.g., ${d.sampleNames.join(', ')})`);
    }
  }
}

console.log(`\n=== GRAND TOTAL: ${grandTotal} entries ===`);

// Now check for template diversity
console.log('\n=== TEMPLATE DIVERSITY AUDIT ===');

for (const filePath of [
  'src/data/compendium/spells/supplemental.ts',
  'src/data/compendium/powers-supplemental.ts',
  'src/data/compendium/techniques-supplemental.ts',
]) {
  const raw = fs.readFileSync(filePath, 'utf-8');
  
  // Count description templates per mode
  const templateBlocks = raw.match(/Templates\s*=\s*\[/g) || [];
  const templateSets = raw.match(/(?:const\s+\w+Templates|case\s+"[^"]+":\s*return\s+pick)/g) || [];
  
  // Count template variants  
  const templateArrays = [...raw.matchAll(/Templates\s*=\s*\[([\s\S]*?)\];/g)];
  const templateCounts = templateArrays.map(m => {
    const entries = m[1].match(/`[^`]+`/g) || [];
    return entries.length;
  });
  
  console.log(`\n${filePath}:`);
  console.log(`  Description template sets: ${templateArrays.length}`);
  console.log(`  Templates per set: ${templateCounts.join(', ')}`);
  
  // Count unique lore pool entries
  const lorePool = raw.match(/_LORE(?:_POOL)?\s*(?::\s*string\[\])?\s*=\s*\[([\s\S]*?)\];/);
  if (lorePool) {
    const loreEntries = lorePool[1].match(/"/g) || [];
    console.log(`  Unique lore entries: ${Math.floor(loreEntries.length / 2)}`);
  }
  
  const flavorPool = raw.match(/_FLAVOR(?:_POOL)?\s*(?::\s*string\[\])?\s*=\s*\[([\s\S]*?)\];/);
  if (flavorPool) {
    const flavorEntries = flavorPool[1].match(/"/g) || [];
    console.log(`  Unique flavor entries: ${Math.floor(flavorEntries.length / 2)}`);
  }
}

fs.writeFileSync('scratch/compendium_count_report.json', JSON.stringify(report, null, 2));
