// Extra Powers — 40 entries, 100% RA-original mechanics
module.exports = [
	// ═══ LEVEL 1-3 GAP FILLS ═══
	{
		name: "Fault Line Stomp",
		lv: 1,
		cls: ["Destroyer"],
		mode: "guard",
		sch: "Evocation",
		desc: "Slam the ground and send a shockwave along a 30-foot line. Each creature in the line: DC 13 STR save or knocked prone and take 2d6 force. The line becomes difficult terrain for 1 minute as the floor fractures.",
		flavor: "The floor disagreed with her foot. The floor lost.",
		eff: "Prone + 2d6 force in a line.",
		disc: "Bureau structural engineers hate this spell. Destroyers use it anyway.",
		dt: "force",
		save: "Strength",
		dc: 13,
	},
	{
		name: "Crimson Frenzy",
		lv: 1,
		cls: ["Berserker"],
		mode: "overload",
		sch: "Transmutation",
		desc: "Enter a mana-fueled frenzy for 1 minute. You gain +2 to melee damage rolls and advantage on Strength checks, but attacks against you have advantage. When the frenzy ends, gain 1 level of exhaustion.",
		flavor: "She stopped thinking. She started hitting. Better.",
		eff: "+2 melee damage, advantage on STR, attacks against you have advantage.",
		disc: "Bureau combat psychologists classify this as 'controlled decompensation.' Berserkers call it Tuesday.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Nerve Strike",
		lv: 1,
		cls: ["Assassin"],
		mode: "ambush",
		sch: "Necromancy",
		desc: "As part of a melee attack, target a nerve cluster. On hit, deal normal damage + 1d8 necrotic. Target must make DC 13 VIT save or have disadvantage on its next attack roll as pain disrupts its motor control.",
		flavor: "She didn't hit hard. She hit precisely. Worse.",
		eff: "Extra 1d8 necrotic + attack disadvantage on failed save.",
		disc: "Bureau hand-to-hand instructors teach the nerve map. Assassins memorize it.",
		dt: "necrotic",
		save: "Vitality",
		dc: 13,
	},
	{
		name: "Pressure Point Cascade",
		lv: 1,
		cls: ["Striker"],
		mode: "kinetic",
		sch: "Transmutation",
		desc: "After hitting with an unarmed strike, trigger a cascade of mana-pressure through the target's body. Deal normal damage + 1d6 force and push the target 10 feet. If it collides with a wall or creature, both take 1d6 bludgeoning.",
		flavor: "One touch. Three impacts. The wall counts.",
		eff: "Extra 1d6 force + push + collision damage.",
		disc: "The Bureau training dummy budget tripled after Strikers joined. They go through walls.",
		dt: "force",
		save: "",
		dc: 0,
	},
	{
		name: "Circuit Flare",
		lv: 2,
		cls: ["Holy Knight"],
		mode: "radiant",
		sch: "Evocation",
		desc: "As a bonus action, ignite your mana circuit's radiant output. For 1 minute, your melee attacks deal +1d6 radiant and shed bright light 10 feet. Undead and fiends that start their turn within 5 feet take 1d4 radiant.",
		flavor: "She glows. The things that shouldn't exist stop existing.",
		eff: "+1d6 radiant melee, light aura, passive undead damage.",
		disc: "The Absolute's radiance channeled through a weapon is described as 'warm.' Undead describe it as 'terminal.'",
		dt: "radiant",
		save: "",
		dc: 0,
	},
	{
		name: "Drone Overwatch",
		lv: 2,
		cls: ["Technomancer"],
		mode: "device",
		sch: "Conjuration",
		desc: "Deploy a hovering combat drone (AC 14, 10 HP, 30 ft fly) that occupies your bonus action. Each turn, the drone can fire: ranged attack +4, 1d8 lightning. If the drone is destroyed, it explodes: each creature within 5 feet takes 2d6 lightning.",
		flavor: "Airborne. Armed. Autonomous. Mostly.",
		eff: "Drone fires 1d8 lightning/turn; explodes for 2d6 on destruction.",
		disc: "Model designation MK-V Scout-Strike. Previous models are classified as 'learning opportunities.'",
		dt: "lightning",
		save: "",
		dc: 0,
	},
	{
		name: "Prey Sense",
		lv: 2,
		cls: ["Stalker"],
		mode: "tracking",
		sch: "Divination",
		desc: "Attune to a creature you've damaged within the last hour. For 10 minutes, you know its exact location within 1 mile, its remaining HP percentage, and whether it's moving. Your first attack against it each turn deals +1d6 damage.",
		flavor: "She tasted its blood once. That's enough.",
		eff: "Track + HP read + 1d6 bonus damage.",
		disc: "A Stalker tracked an A-Rank anomaly through 4 gate floors using Prey Sense alone. It took 6 hours. She was patient.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Harmonic Ward",
		lv: 2,
		cls: ["Idol"],
		mode: "resonance",
		sch: "Abjuration",
		desc: "Begin a defensive harmonic. For 1 minute, you and up to 3 allies within 15 feet gain +1 AC and resistance to thunder damage. As a reaction, you can end the harmonic early to grant one ally within range 2d8 temporary HP.",
		flavor: "The frequency protects. The silence follows.",
		eff: "+1 AC, thunder resistance, emergency temp HP burst.",
		disc: "During a gate-breach concert, an Idol maintained Harmonic Ward while performing. Ticket sales for the next show sold out in 3 minutes.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Tether of Binding",
		lv: 2,
		cls: ["Contractor"],
		mode: "pact",
		sch: "Conjuration",
		desc: "Launch a spectral chain from your patron that latches onto a creature within 30 feet. DC 14 PRS save or tethered for 1 minute: target can't move more than 30 feet from you, and if it tries to teleport, it takes 3d6 psychic damage and the teleport fails.",
		flavor: "Your patron wants you close. The chain insists.",
		eff: "Movement leash + teleport suppression.",
		disc: "Bureau containment teams request Contractors specifically for high-mobility targets. The tether has a 97% containment rate.",
		dt: "psychic",
		save: "Presence",
		dc: 14,
	},
	{
		name: "Death's Momentum",
		lv: 2,
		cls: ["Revenant"],
		mode: "entropy",
		sch: "Necromancy",
		desc: "When you reduce a creature to 0 HP, your mana circuit surges. You immediately gain 2d8 temporary HP and can move up to 15 feet without provoking opportunity attacks. Your next melee attack within 1 round deals +1d8 necrotic.",
		flavor: "Death feeds her. She's always hungry.",
		eff: "On-kill: temp HP + free move + bonus damage.",
		disc: "Bureau analysts note that Revenants fight harder, not weaker, as enemies fall. The momentum is literal.",
		dt: "necrotic",
		save: "",
		dc: 0,
	},

	// ═══ LEVEL 3-5 ═══
	{
		name: "Seismic Anchor",
		lv: 3,
		cls: ["Destroyer"],
		mode: "guard",
		sch: "Abjuration",
		desc: "Plant yourself as an immovable point. For 1 minute, you can't be moved against your will, knocked prone, or pushed. Your AC increases by +2. As a reaction, when an ally within 10 feet is targeted by an attack, you can force the attack to target you instead.",
		flavor: "She became the ground. The ground doesn't move.",
		eff: "Immovable stance + AC boost + ally protection.",
		disc: "A Destroyer held Seismic Anchor for 4 minutes while an S-Rank gate boss tried to push her off a bridge. The bridge broke. She didn't.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Berserker's Gambit",
		lv: 3,
		cls: ["Berserker"],
		mode: "overload",
		sch: "Transmutation",
		desc: "Sacrifice hit points to fuel devastation. Spend up to 20 HP (no reduction); your next melee attack within 1 round deals bonus damage equal to twice the HP spent. If you reduce the target to 0 HP, you regain half the HP spent.",
		flavor: "She paid in blood. The target paid more.",
		eff: "Trade HP for 2x bonus melee damage; kill refunds half.",
		disc: "Bureau combat medics keep Berserkers on a 'HP budget.' The Berserkers consistently overdraft.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Phantom Blade Flurry",
		lv: 3,
		cls: ["Assassin"],
		mode: "ambush",
		sch: "Illusion",
		desc: "Create 3 illusory copies of your weapon that strike simultaneously with your real attack. Make one melee attack; on a hit, deal normal damage + 3d6 force as the phantom blades strike. The target must make a DC 15 INT save or be unable to use reactions until the end of your next turn.",
		flavor: "Four blades. One is real. All of them hurt.",
		eff: "Extra 3d6 force + reaction denial.",
		disc: "Bureau security footage shows four simultaneous impacts from different angles. Image analysis confirms only one physical blade.",
		dt: "force",
		save: "Intelligence",
		dc: 15,
	},
	{
		name: "One-Inch Collapse",
		lv: 3,
		cls: ["Striker"],
		mode: "kinetic",
		sch: "Evocation",
		desc: "Concentrate your entire mana output into a single point-blank strike delivered at skin contact distance. Melee attack with advantage; on hit: 4d10 force damage. If the target is grappled or restrained, damage increases to 6d10.",
		flavor: "One inch. Full force. Everything behind it.",
		eff: "4d10 force (6d10 if target is restrained/grappled).",
		disc: "Bureau training dummies don't survive this technique. The Bureau stopped buying replacements and uses conjured targets instead.",
		dt: "force",
		save: "",
		dc: 0,
	},
	{
		name: "Covenant Aegis",
		lv: 3,
		cls: ["Holy Knight"],
		mode: "radiant",
		sch: "Abjuration",
		desc: "As a reaction when you or an ally within 30 feet takes damage, invoke the Absolute's covenant. The damage is halved, and the attacker must make a DC 15 PRS save or be marked: you have advantage on attacks against marked creatures for 1 minute.",
		flavor: "The Absolute remembers who struck first.",
		eff: "Halve damage + mark attacker (advantage on attacks vs them).",
		disc: "Holy Knights invoke this without hesitation. The covenant's protection has never failed when the oath was genuine.",
		dt: "radiant",
		save: "Presence",
		dc: 15,
	},
	{
		name: "Payload Deployment",
		lv: 3,
		cls: ["Technomancer"],
		mode: "device",
		sch: "Evocation",
		desc: "Launch a guided mana-payload that detonates at a point within 120 feet. Each creature in a 20-foot radius: DC 15 AGI save, 4d8 fire on failure, half on success. Constructs and gate-tech in the area take double damage.",
		flavor: "Guidance system locked. Payload away. Cover your ears.",
		eff: "4d8 fire in 20-foot radius; double vs constructs.",
		disc: "The payload guidance system is accurate to within 6 inches. Bureau munitions teams consider this 'adequate.'",
		dt: "fire",
		save: "Agility",
		dc: 15,
	},
	{
		name: "Quarry Pindown",
		lv: 3,
		cls: ["Stalker"],
		mode: "tracking",
		sch: "Conjuration",
		desc: "Fire a mana-tracking bolt at a creature within 90 feet. Ranged attack: 3d8 piercing on hit, and the target is pinned (speed becomes 0) until it uses an action to make a DC 15 STR check to pull the bolt free. While pinned, your attacks against it deal +1d6 damage.",
		flavor: "Pinned. Tracked. Finished when she's ready.",
		eff: "3d8 piercing + speed 0 + bonus damage while pinned.",
		disc: "The mana-bolt anchors itself to the nearest solid surface through the target. Extraction requires 'considerable effort.'",
		dt: "piercing",
		save: "",
		dc: 0,
	},
	{
		name: "Encore Performance",
		lv: 4,
		cls: ["Idol"],
		mode: "resonance",
		sch: "Enchantment",
		desc: "After casting a spell of 3rd level or lower, immediately cast it again as a bonus action without expending a slot. The encore version deals half damage or has half duration. You can only encore a spell once per long rest.",
		flavor: "They asked for an encore. She was already casting it.",
		eff: "Repeat a spell (3rd or lower) at half potency, no slot cost.",
		disc: "Bureau mana-efficiency analysts rate this as 'impossible.' Idols rate it as 'Tuesday night.'",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Blood Pact Escalation",
		lv: 4,
		cls: ["Contractor"],
		mode: "pact",
		sch: "Necromancy",
		desc: "Offer your own HP to your patron for increased power. Spend up to 30 HP (can't be reduced). For the next minute, all your pact spells deal +1d8 bonus damage per 10 HP spent, and your spell save DC increases by 1 per 10 HP spent.",
		flavor: "The patron accepts payment. In blood. In advance.",
		eff: "Trade HP for +damage and +DC on pact spells.",
		disc: "Bureau pact oversight flags this as 'high-risk self-modification.' Contractors consider it 'an investment.'",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Entropy Harvest",
		lv: 4,
		cls: ["Revenant"],
		mode: "entropy",
		sch: "Necromancy",
		desc: "For 1 minute, whenever a creature within 30 feet dies, you absorb its residual mana-circuit energy: regain 2d8 HP and gain +1 to attack rolls (stacking, max +3). At max stacks, your necrotic damage ignores resistance.",
		flavor: "She gets stronger as they fall. That's the design.",
		eff: "On-death within 30 ft: heal + stacking attack bonus.",
		disc: "Bureau after-action reports note Revenants become 'significantly more dangerous' as combat progresses. The data supports this.",
		dt: "",
		save: "",
		dc: 0,
	},

	// ═══ LEVEL 5-7 ═══
	{
		name: "Bulwark Singularity",
		lv: 5,
		cls: ["Destroyer"],
		mode: "guard",
		sch: "Abjuration",
		desc: "Become the absolute center of defense. For 1 minute: all damage dealt to allies within 15 feet is redirected to you, you gain resistance to all damage, and your AC increases by +3. You can't move or take the Attack action while maintaining.",
		flavor: "Every hit. Every ally. Through her. She holds.",
		eff: "Absorb all ally damage within 15 ft + resistance + AC boost.",
		disc: "A Destroyer maintained Bulwark Singularity for 2 minutes during the Osaka Crisis. She absorbed 847 points of damage. She survived.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Annihilation Rush",
		lv: 5,
		cls: ["Berserker"],
		mode: "overload",
		sch: "Transmutation",
		desc: "Your mana circuit overloads into a 30-second combat trance. For 5 rounds: your melee attacks deal +3d6 damage, you have advantage on all attack rolls, and you can make one additional melee attack per turn. You can't cast spells during the rush. When it ends: 2 levels of exhaustion.",
		flavor: "Thirty seconds. That's all she needs. That's all anyone needs.",
		eff: "+3d6 melee damage, advantage, extra attack, then 2 exhaustion.",
		disc: "Bureau medical teams prepare recovery stations before Berserkers engage in S-Rank operations. The trance duration is precisely 30 seconds.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Kill Protocol",
		lv: 5,
		cls: ["Assassin"],
		mode: "ambush",
		sch: "Illusion",
		desc: "Become invisible for 1 round. The first attack you make while invisible is a guaranteed critical hit if it hits. The attack deals an additional 5d6 damage of the weapon's type. After the attack, you can teleport 30 feet to a space in dim light.",
		flavor: "Invisible. One attack. Critical. Gone.",
		eff: "Guaranteed crit on first attack + 5d6 bonus + teleport.",
		disc: "Bureau surveillance can't track Kill Protocol. By the time the cameras adjust, the Assassin is 30 feet away in shadow.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Mana Reactor Core",
		lv: 5,
		cls: ["Technomancer"],
		mode: "device",
		sch: "Transmutation",
		desc: "Activate a mana reactor within your focus device. For 10 minutes: all your device spells deal +2d6 damage, your spell slots regenerate 1 level of slots per minute (max 3rd level), and your drone/construct allies gain +2 AC.",
		flavor: "Reactor online. All systems at 200%. Proceed.",
		eff: "+2d6 device damage + slot regen + construct AC boost.",
		disc: "Bureau engineering teams designed the reactor core with 47 safety interlocks. Technomancers disable at least 30 of them.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Absolute Smite",
		lv: 5,
		cls: ["Holy Knight"],
		mode: "radiant",
		sch: "Evocation",
		desc: "Channel the Absolute's full judgment through your weapon. Next melee hit deals +6d8 radiant damage (+8d8 vs undead/fiends). The target must make a DC 17 PRS save or be stunned for 1 round. If the target is killed, it cannot be raised by any means below 7th level.",
		flavor: "Judgment. Delivered. Final.",
		eff: "+6d8 radiant, stun on failed save, anti-resurrection rider.",
		disc: "Three confirmed kills using Absolute Smite have resulted in permanent termination of S-Rank undead anomalies. The Absolute doesn't allow encores.",
		dt: "radiant",
		save: "Presence",
		dc: 17,
	},
	{
		name: "Orbital Strike Array",
		lv: 6,
		cls: ["Technomancer"],
		mode: "device",
		sch: "Evocation",
		desc: "Deploy three guided mana-charges that detonate in sequence at points within 120 feet. Each creates a 15-foot radius explosion: DC 17 AGI save, 5d8 fire/force on failure, half on success. Creatures hit by multiple blasts save once but take damage from each.",
		flavor: "Three targets. Three impacts. One Technomancer.",
		eff: "Three 15-foot blasts: 5d8 fire/force each.",
		disc: "The Bureau's damage assessment team uses special software to calculate Orbital Strike Array collateral. The software crashes frequently.",
		dt: "fire",
		save: "Agility",
		dc: 17,
	},
	{
		name: "Idol's Magnum Opus",
		lv: 6,
		cls: ["Idol"],
		mode: "resonance",
		sch: "Enchantment",
		desc: "Perform a 1-round masterwork that reshapes the battlefield. All allies within 60 feet: regain 4d8 HP, gain +2 to all saves for 1 minute, and are cured of frightened, charmed, and stunned. All enemies: DC 17 PRS save or charmed for 1 round and can't take reactions.",
		flavor: "The perfect performance. Once per concert. Once per lifetime.",
		eff: "Mass heal + buff + cure allies; charm + reaction-deny enemies.",
		disc: "Bureau combat psych evaluators confirmed: an Idol's Magnum Opus shifted the morale of a 30-person raid from 'panicking' to 'invincible' in 6 seconds.",
		dt: "",
		save: "Presence",
		dc: 17,
	},
	{
		name: "Patron's Embrace",
		lv: 6,
		cls: ["Contractor"],
		mode: "pact",
		sch: "Necromancy",
		desc: "Your patron temporarily merges with your mana circuit. For 1 minute: you gain 50 temp HP, resistance to two damage types of your patron's choosing, and your pact spells ignore resistance. When the spell ends, you take 4d6 psychic damage as the patron withdraws.",
		flavor: "The patron is inside you now. It feels like drowning. In power.",
		eff: "50 temp HP, 2 resistances, ignore resistance on pact spells.",
		disc: "Bureau psych evaluators note that Contractors under Patron's Embrace exhibit 'personality bleed' — mannerisms and speech patterns shift to match their patron.",
		dt: "psychic",
		save: "",
		dc: 0,
	},
	{
		name: "Final Entropy",
		lv: 6,
		cls: ["Revenant"],
		mode: "entropy",
		sch: "Necromancy",
		desc: "Mark a creature for entropic collapse. For 1 minute, every time you deal necrotic damage to the marked target, its HP maximum is reduced by the damage dealt. If its HP max reaches 0, it disintegrates entirely and can't be revived.",
		flavor: "Everything ends. She decides when.",
		eff: "Necrotic damage reduces target's max HP; kill at 0 max HP = permanent death.",
		disc: "Bureau containment protocol classifies Final Entropy as 'irreversible termination.' Revenants consider it 'efficient.'",
		dt: "necrotic",
		save: "",
		dc: 0,
	},
	{
		name: "Quarry Annihilation",
		lv: 6,
		cls: ["Stalker"],
		mode: "tracking",
		sch: "Divination",
		desc: "Lock onto a creature you've tracked for at least 1 minute. For the next minute, all your attacks against it have advantage, you deal +3d6 bonus damage per hit, and it can't benefit from invisibility, cover, or teleportation against you.",
		flavor: "Tracked long enough. Time's up.",
		eff: "Advantage + 3d6 bonus + target can't hide or flee.",
		disc: "A Stalker used Quarry Annihilation on an S-Rank gate boss that had been fleeing for 40 minutes. The boss lasted 18 seconds.",
		dt: "",
		save: "",
		dc: 0,
	},

	// ═══ LEVEL 7-9 ═══
	{
		name: "Fortress Mode",
		lv: 7,
		cls: ["Destroyer"],
		mode: "guard",
		sch: "Abjuration",
		desc: "Transform into a living fortress. For 1 minute: your AC becomes 25, you gain immunity to forced movement and prone, all allies within 20 feet gain +3 AC, and any creature that hits you with melee takes 2d8 force retaliation. Speed becomes 0.",
		flavor: "She IS the fortification. The enemy attacks the building.",
		eff: "AC 25, ally AC aura, melee retaliation, immobile.",
		disc: "Bureau tactical AI classified a Destroyer in Fortress Mode as 'terrain feature, allied, impassable.' The AI wasn't wrong.",
		dt: "force",
		save: "",
		dc: 0,
	},
	{
		name: "Terminal Velocity",
		lv: 7,
		cls: ["Berserker"],
		mode: "overload",
		sch: "Transmutation",
		desc: "Push your mana circuit beyond terminal capacity. For 3 rounds: all melee damage is tripled, you can't be knocked unconscious (fight at 0 HP), and your movement speed triples. When the effect ends, if you're at 0 HP, you die.",
		flavor: "Three rounds. Everything tripled. Including the consequences.",
		eff: "Triple melee damage, death-immunity for 3 rounds, risk of death.",
		disc: "Bureau medical teams describe Terminal Velocity as 'borrowing from a future that may not exist.' Two confirmed survivals. One confirmed death.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Perfect Kill",
		lv: 7,
		cls: ["Assassin"],
		mode: "ambush",
		sch: "Illusion",
		desc: "Mark a target and spend 1 minute observing it (can be done while invisible). After observation, your next attack against the target within 1 hour: automatically hits, automatically crits, deals max damage on all dice, and the target must make DC 18 VIT save or be reduced to 0 HP.",
		flavor: "She watched. She waited. She decided.",
		eff: "Auto-hit, auto-crit, max damage, potential instant kill.",
		disc: "Bureau records contain two confirmed Perfect Kills against S-Rank targets. Both required exactly one strike.",
		dt: "",
		save: "Vitality",
		dc: 18,
	},
	{
		name: "Eight Gates Release",
		lv: 7,
		cls: ["Striker"],
		mode: "kinetic",
		sch: "Transmutation",
		desc: "Unlock all eight mana gates in your circuit simultaneously. For 1 minute: unarmed damage becomes 4d10, speed doubles, you gain an extra action each turn, and you can make opportunity attacks with advantage. When it ends: 3 levels of exhaustion.",
		flavor: "Eight gates. All open. Nothing held back.",
		eff: "4d10 unarmed, double speed, extra action, then 3 exhaustion.",
		disc: "Bureau martial arts researchers documented the eight-gate sequence. The seventh gate is described as 'inadvisable.' The eighth is 'theoretical.'",
		dt: "force",
		save: "",
		dc: 0,
	},
	{
		name: "S-Rank Smite",
		lv: 9,
		cls: ["Holy Knight"],
		mode: "radiant",
		sch: "Evocation",
		desc: "The ultimate expression of the Absolute's judgment. Next melee hit deals +12d8 radiant. The target's mana circuit is permanently scarred: it loses access to its highest-level ability permanently. Undead and fiends are instantly destroyed regardless of HP.",
		flavor: "One strike. S-Rank. The Absolute's final word.",
		eff: "+12d8 radiant + permanent ability loss + instant undead/fiend kill.",
		disc: "Bureau records: one confirmed S-Rank Smite. The Holy Knight collapsed after. The S-Rank gate boss was already dust.",
		dt: "radiant",
		save: "",
		dc: 0,
	},
	{
		name: "Singularity Engine",
		lv: 9,
		cls: ["Technomancer"],
		mode: "device",
		sch: "Transmutation",
		desc: "Activate the theoretical singularity engine in your focus device. For 1 minute: all device abilities deal triple damage, you can cast two spells per turn, all your constructs/drones gain +50 HP and triple damage. When it ends, your focus device is destroyed (requires 7 days to rebuild).",
		flavor:
			"Singularity engaged. All limiters removed. Device will not survive.",
		eff: "Triple damage on all device abilities, dual-cast, construct empowerment.",
		disc: "Bureau engineering division classified the singularity engine as 'theoretically possible.' One Technomancer proved them right. The device was scrap afterward.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Predator Supremacy",
		lv: 9,
		cls: ["Stalker"],
		mode: "tracking",
		sch: "Divination",
		desc: "Enter the ultimate tracking state. For 1 hour: you automatically know the location of every creature within 1 mile, can't be surprised, have advantage on all attacks, and your first hit each turn deals +4d8 damage. You can track a creature across dimensional boundaries.",
		flavor: "Everything within a mile is prey. Everything.",
		eff: "1-mile omniscience, advantage on all attacks, +4d8 first-hit bonus.",
		disc: "Bureau S-Rank operations deploy Stalkers in Predator Supremacy state as 'primary acquisition assets.' Nothing escapes.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Final Chorus",
		lv: 9,
		cls: ["Idol"],
		mode: "resonance",
		sch: "Enchantment",
		desc: "Perform the Final Chorus — a harmonic so perfect it reshapes reality within 120 feet. All allies: full HP restoration, all conditions removed, gain 50 temp HP. All enemies: DC 20 PRS save or charmed and incapacitated for 1 minute. You can't cast spells for 24 hours after.",
		flavor: "The last song. The perfect song. Everything stops to listen.",
		eff: "Full ally heal + mass charm/incapacitate enemies.",
		disc: "Bureau records list one Final Chorus. Every creature in a 120-foot radius stopped fighting. Allies. Enemies. The gate boss. For 47 seconds, there was only music.",
		dt: "",
		save: "Presence",
		dc: 20,
	},
	{
		name: "Absolute Pact",
		lv: 9,
		cls: ["Contractor"],
		mode: "pact",
		sch: "Conjuration",
		desc: "Invoke the ultimate clause of your patron contract. Your patron physically manifests (CR 20, acts independently, follows your commands) for 1 minute. You take 8d6 psychic damage at the end of each of your turns while the patron is manifested. If you die during the manifestation, your patron claims your soul.",
		flavor:
			"You called. The patron answered. In person. Permanently, if you're not careful.",
		eff: "Summon CR 20 patron; 8d6 psychic/turn to you; death = soul claimed.",
		disc: "Bureau classified. One confirmed Absolute Pact. The Contractor survived. The S-Rank gate did not. The patron 'seemed satisfied.'",
		dt: "psychic",
		save: "",
		dc: 0,
	},
];
