// Extra Powers B — 25 entries, 100% RA-original
module.exports = [
	{
		name: "Gravity Well Slam",
		lv: 2,
		cls: ["Destroyer"],
		mode: "guard",
		sch: "Transmutation",
		desc: "Create a 10-foot gravity well centered on your weapon strike. All creatures within 10 feet are pulled 5 feet toward you and must make DC 14 STR save or be knocked prone. You gain +1 AC per creature pulled until end of your next turn.",
		flavor: "Everything comes to her. That's the gravity of the situation.",
		eff: "Pull + prone + AC scaling.",
		disc: "Bureau physics division confirmed the gravity differential at 4G. Inside a 10-foot radius. The Destroyer shrugged.",
		dt: "force",
		save: "Strength",
		dc: 14,
	},
	{
		name: "Adrenaline Surge",
		lv: 1,
		cls: ["Berserker", "Striker"],
		mode: "overload",
		sch: "Transmutation",
		desc: "As a reaction when you take damage, surge your mana circuit's combat response. Gain temporary HP equal to 1d8 + your Constitution modifier. Your next melee attack deals +1d6 damage.",
		flavor: "She got hit. She got angry. She got stronger.",
		eff: "Reaction temp HP + bonus melee damage.",
		disc: "Bureau medical staff track 'adrenaline surge events.' Berserkers average 12 per gate operation.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Phantom Decoy",
		lv: 2,
		cls: ["Assassin", "Idol"],
		mode: "ambush",
		sch: "Illusion",
		desc: "Create a perfect mana-clone decoy at your position and turn invisible for 1 round. The decoy has 1 HP and mimics your last action. When the decoy is destroyed, it explodes for 2d6 psychic to all creatures within 5 feet.",
		flavor: "Which one is real? Wrong question. Both hurt.",
		eff: "Invisibility + decoy + psychic explosion on decoy death.",
		disc: "Bureau combat instructors use this in training exercises. Trainees learn to check for decoys. They still fall for them.",
		dt: "psychic",
		save: "",
		dc: 0,
	},
	{
		name: "Gate Reader",
		lv: 1,
		cls: ["Stalker", "Summoner"],
		mode: "tracking",
		sch: "Divination",
		desc: "Touch a gate surface and read its dimensional frequency. Learn the gate's rank, number of floors remaining, boss type category, and dominant element. Also learn if any other Awakened have entered in the last 24 hours.",
		flavor: "She listens to the gate. The gate talks.",
		eff: "Full gate intelligence scan.",
		disc: "Bureau recon protocols require Gate Reader before any entry. The intelligence it provides has a 98% accuracy rate.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Sacrifice Engine",
		lv: 3,
		cls: ["Contractor"],
		mode: "pact",
		sch: "Necromancy",
		desc: "Sacrifice a summoned creature, familiar, or willing ally's temporary HP to fuel a devastating patron attack. For every 10 HP sacrificed, deal 3d8 patron-element damage to one creature within 60 feet (no save, no attack roll).",
		flavor: "The patron demands a sacrifice. The patron provides the damage.",
		eff: "Convert HP to guaranteed damage (3d8 per 10 HP).",
		disc: "Bureau pact oversight classifies this as 'morally complex.' Contractors classify it as 'efficient.'",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Resonance Counter",
		lv: 2,
		cls: ["Idol"],
		mode: "resonance",
		sch: "Abjuration",
		desc: "As a reaction when an ally within 30 feet is hit by an attack, perform a counter-harmonic that reduces the damage by 2d8 + your Presence modifier. If the damage is reduced to 0, the attacker takes 1d8 thunder.",
		flavor: "She sang a note. The blow softened. The enemy flinched.",
		eff: "Reaction damage reduction + counter damage.",
		disc: "Idols who master this become permanent raid fixtures. Bureau assignment priority: 'immediate.'",
		dt: "thunder",
		save: "",
		dc: 0,
	},
	{
		name: "Mana Forge",
		lv: 4,
		cls: ["Technomancer"],
		mode: "device",
		sch: "Transmutation",
		desc: "Over 10 minutes, forge a temporary magical weapon or piece of armor from raw mana-crystal. The item lasts 8 hours, counts as +1, and can be attuned immediately. You can also modify an existing weapon: add +1d6 elemental damage for 8 hours.",
		flavor: "She built it from nothing. It works better than factory.",
		eff: "Create +1 weapon/armor or add 1d6 elemental to existing weapon.",
		disc: "Bureau quartermasters stopped requisitioning weapons for Technomancers. They just build their own. Often better.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Entropic Feedback",
		lv: 3,
		cls: ["Revenant"],
		mode: "entropy",
		sch: "Necromancy",
		desc: "When you take necrotic damage, your circuit converts it to power. For 1 minute, you are immune to necrotic damage. Instead, necrotic damage you would take heals you for half the amount. Your necrotic attacks deal +1d8 during this time.",
		flavor: "Feed her entropy. She grows.",
		eff: "Necrotic immunity + convert necrotic to healing + damage bonus.",
		disc: "Bureau combat analysts noted that attacking a Revenant with necrotic abilities during Entropic Feedback is 'catastrophically counterproductive.'",
		dt: "necrotic",
		save: "",
		dc: 0,
	},
	{
		name: "Herald's Intervention",
		lv: 3,
		cls: ["Herald"],
		mode: "radiant",
		sch: "Abjuration",
		desc: "As a reaction when an ally within 60 feet would be reduced to 0 HP, intervene with the Absolute's grace. The ally instead drops to 1 HP and gains 2d10 temporary HP. You take 2d6 radiant damage from the strain.",
		flavor: "Not on her watch. Not today.",
		eff: "Prevent ally death-blow + temp HP; self-damage cost.",
		disc: "Bureau Herald training prioritizes this power above all others. A Herald who can't intervene isn't a Herald.",
		dt: "radiant",
		save: "",
		dc: 0,
	},
	{
		name: "Parallel Processing",
		lv: 4,
		cls: ["Esper"],
		mode: "tracking",
		sch: "Divination",
		desc: "Split your consciousness into parallel threads. For 1 minute, you can concentrate on 2 spells simultaneously, and you have advantage on all Intelligence and Presence checks. When the effect ends, you gain 1 level of exhaustion.",
		flavor: "Two thoughts. Two spells. One mind. Barely.",
		eff: "Dual concentration + advantage on mental checks + exhaustion.",
		disc: "Bureau psionic researchers classify dual concentration as 'theoretically impossible.' Espers classify it as 'Tuesday.'",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "War Cry",
		lv: 4,
		cls: ["Berserker", "Destroyer"],
		mode: "overload",
		sch: "Enchantment",
		desc: "Release a mana-amplified war cry. All enemies within 30 feet: DC 16 PRS save or frightened for 1 minute. All allies within 30 feet: gain 2d8 temporary HP and advantage on their next attack roll.",
		flavor: "She screamed. The allies charged. The enemies ran.",
		eff: "Mass fear (enemies) + temp HP and advantage (allies).",
		disc: "Bureau audiological equipment registers a War Cry at 140 decibels. The mana component causes an additional 'existential dread.'",
		dt: "",
		save: "Presence",
		dc: 16,
	},
	{
		name: "Execute Protocol",
		lv: 5,
		cls: ["Stalker"],
		mode: "tracking",
		sch: "Divination",
		desc: "When you hit a creature that is below half its maximum HP, you can trigger Execute Protocol. The attack deals an additional 5d10 damage. If the target has 30 HP or fewer after the bonus damage, it dies instantly.",
		flavor: "Below half. Execution threshold. Protocol active.",
		eff: "5d10 bonus vs bloodied + instant kill at 30 HP.",
		disc: "Bureau Hunter rankings weight Execute Protocol proficiency heavily. The ability to finish targets is 'operationally critical.'",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Radiant Martyr",
		lv: 5,
		cls: ["Holy Knight"],
		mode: "radiant",
		sch: "Abjuration",
		desc: "When you would be reduced to 0 HP, you can instead drop to 1 HP and release a burst of the Absolute's radiance. All enemies within 30 feet: DC 17 PRS save, 6d8 radiant on failure, half on success. All allies regain 3d8 HP.",
		flavor: "She fell. Then the light fell. Then everything changed.",
		eff: "Defy death + radiant burst to enemies + mass heal allies.",
		disc: "Bureau combat chaplains call this 'the Absolute's last gift.' Holy Knights who use it typically require 48 hours of recovery.",
		dt: "radiant",
		save: "Presence",
		dc: 17,
	},
	{
		name: "Summoner's Pack",
		lv: 4,
		cls: ["Summoner"],
		mode: "tracking",
		sch: "Conjuration",
		desc: "Summon 3 Small gate-creature scouts (AC 13, 10 HP each, 40 ft speed). They act on your initiative, obey mental commands, and can perform the Help action. If one is destroyed, it explodes for 1d6 force to adjacent creatures.",
		flavor: "Three scouts. Three pairs of eyes. Three explosive surprises.",
		eff: "3 scout creatures + Help action + explosive death.",
		disc: "Bureau reconnaissance values quantity over quality at lower gate levels. Three scouts cover more ground than one big summon.",
		dt: "force",
		save: "",
		dc: 0,
	},
	{
		name: "Mana Recycler",
		lv: 3,
		cls: ["Technomancer", "Mage"],
		mode: "device",
		sch: "Transmutation",
		desc: "When you cast a spell of 3rd level or lower that deals no damage, immediately recover a spell slot of 1 level lower than the spell cast. This can only trigger once per short rest.",
		flavor: "Waste not. The mana goes somewhere useful.",
		eff: "Recover lower-level slot on non-damage spell cast.",
		disc: "Bureau mana-efficiency metrics improved 23% after Technomancers adopted Mana Recycler into standard loadouts.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Circuit Defibrillator",
		lv: 5,
		cls: ["Herald", "Technomancer"],
		mode: "device",
		sch: "Evocation",
		desc: "As an action, touch a creature at 0 HP and jumpstart its mana circuit. The creature immediately regains consciousness with HP equal to 3d10 + your spellcasting modifier and can take its turn normally this round.",
		flavor: "Clear. Pulse restored. Fight.",
		eff: "Instant revive at 3d10 HP + immediate action.",
		disc: "Bureau field medics carry this as mandatory kit. The difference between a failed raid and a successful one is often one Circuit Defibrillator.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Runic Detonation",
		lv: 6,
		cls: ["Mage", "Esper"],
		mode: "overload",
		sch: "Evocation",
		desc: "Inscribe a mana-rune on a surface. The rune detonates when triggered (proximity, timer, or command word). Detonation: DC 17 INT save in 30-foot radius, 8d8 force on failure, half on success. You can have up to 3 runes active simultaneously.",
		flavor: "Three runes. Three traps. Three regrets.",
		eff: "8d8 force in 30-foot radius; up to 3 active at once.",
		disc: "Bureau demolitions teams replaced physical explosives with Runic Detonation charges. The cleanup is simpler and the yield is higher.",
		dt: "force",
		save: "Intelligence",
		dc: 17,
	},
	{
		name: "Commander's Presence",
		lv: 6,
		cls: ["Herald", "Holy Knight"],
		mode: "radiant",
		sch: "Enchantment",
		desc: "Project an aura of absolute tactical authority. For 1 minute, all allies within 60 feet: can use your saving throw bonus instead of their own (their choice per save), and when you take the Help action, the ally gains +1d8 to the roll instead of advantage.",
		flavor: "She commands. They follow. They survive.",
		eff: "Share save bonus + enhanced Help action.",
		disc: "Bureau tactical command rates Heralds with Commander's Presence as 'force multiplier assets.' Assignment priority: S-Rank operations.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Entropic Avatar",
		lv: 8,
		cls: ["Revenant"],
		mode: "entropy",
		sch: "Necromancy",
		desc: "Transform into an avatar of entropy for 1 minute. Gain +50 temp HP, fly speed 60 feet, immunity to necrotic and poison, and all your attacks deal +3d8 necrotic. Creatures that touch you or hit you with melee take 2d8 necrotic. When the form ends: 3 levels of exhaustion.",
		flavor:
			"She stopped being human. For one minute. The minute was sufficient.",
		eff: "Transformation: massive buffs + contact damage + heavy exhaustion cost.",
		disc: "Bureau records classify Entropic Avatar as 'S-Rank threat equivalent.' Revenants in this form are not approached by allies or enemies.",
		dt: "necrotic",
		save: "",
		dc: 0,
	},
	{
		name: "Esper Ascension",
		lv: 8,
		cls: ["Esper"],
		mode: "tracking",
		sch: "Divination",
		desc: "Ascend to a state of total psionic awareness. For 1 minute: you levitate 30 feet (fly 30 ft hover), have blindsight 120 feet, can read thoughts of all creatures within 120 feet (no save), and your psychic spells deal +4d6 damage. When it ends: stunned for 1 round.",
		flavor:
			"She sees everything. Every thought. Every intention. Every weakness.",
		eff: "Flight + blindsight + thought reading + psychic damage boost.",
		disc: "Bureau psionic assessment rates Esper Ascension as 'perception beyond human parameters.' The one-round stun is considered 'a fair trade.'",
		dt: "psychic",
		save: "",
		dc: 0,
	},
	{
		name: "Patron Sacrifice",
		lv: 7,
		cls: ["Contractor"],
		mode: "pact",
		sch: "Necromancy",
		desc: "Offer a significant portion of your life force to your patron in exchange for a massive power surge. Permanently reduce your max HP by 10. In return: regain all expended spell slots, gain +3 to spell save DC for 1 minute, and your next patron spell deals double damage.",
		flavor: "The patron demands. You pay. The power is worth it. Usually.",
		eff: "Permanent HP loss for full slot recovery + DC boost + double damage.",
		disc: "Bureau pact oversight STRONGLY discourages this power. The HP reduction is permanent. Contractors who use it more than twice are flagged for intervention.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Striker's Zenith",
		lv: 8,
		cls: ["Striker"],
		mode: "kinetic",
		sch: "Transmutation",
		desc: "Enter a state of perfect kinetic harmony. For 1 minute: your unarmed attacks deal 3d10 + STR force, you can make 4 unarmed attacks per action, your movement doesn't provoke opportunity attacks, and you can run along walls and across water.",
		flavor: "Perfect balance. Perfect speed. Perfect violence.",
		eff: "3d10 unarmed, 4 attacks, free movement, wall/water run.",
		disc: "Bureau martial assessment: a Striker in Zenith state operates at 'beyond measurable human combat efficiency.' The one-minute limit is considered 'merciful.'",
		dt: "force",
		save: "",
		dc: 0,
	},
	{
		name: "Berserker's Last Stand",
		lv: 8,
		cls: ["Berserker"],
		mode: "overload",
		sch: "Transmutation",
		desc: "Activate when you are at or below 25% HP. For 1 minute: your melee damage is quadrupled, you can't be knocked unconscious, you regenerate 2d10 HP per round, and you are immune to frightened and charmed. When it ends: you drop to 0 HP (death saves).",
		flavor: "She's dying. She doesn't care. She fights harder.",
		eff: "Quadruple melee damage + death immunity + regen + crash at end.",
		disc: "Bureau medical teams describe this as 'borrowing against a future that may not arrive.' Berserkers with Vitality saves above 18 survive the crash 80% of the time.",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Summoner's Leviathan",
		lv: 8,
		cls: ["Summoner"],
		mode: "tracking",
		sch: "Conjuration",
		desc: "Summon a Huge gate-leviathan (AC 18, HP 200, multiattack: 3 at +10 for 3d10+7) that acts on its own initiative and obeys your mental commands. It has resistance to all damage and immunity to frightened. Lasts 1 minute or until destroyed.",
		flavor: "The gate opened. Something enormous answered.",
		eff: "Huge CR 12 summon: 200 HP, multiattack, resistance to all.",
		disc: "Bureau gate-response teams classify a summoned leviathan as 'allied strategic asset.' The leviathan classifies them as 'small.'",
		dt: "",
		save: "",
		dc: 0,
	},
	{
		name: "Divine Mandate",
		lv: 9,
		cls: ["Herald"],
		mode: "radiant",
		sch: "Enchantment",
		desc: "Speak with the Absolute's voice. All creatures within 120 feet that can hear you must make DC 20 PRS save. On failure: they must follow one complex command (up to 25 words) for 1 hour. On success: they are frightened of you for 1 minute. Allies are immune.",
		flavor: "The Absolute speaks. Through her. Everyone obeys.",
		eff: "Mass domination (120 ft) or fear on save.",
		disc: "Bureau Director classification: ABSOLUTE AUTHORITY. One confirmed use. The Director authorized it personally. The S-Rank gate-boss and its entire army knelt.",
		dt: "",
		save: "Presence",
		dc: 20,
	},
];
