// Powers Level 4-9 — 40 unique entries
module.exports = [
	// ═══ LEVEL 4 ═══
	{ name:"Fortress Pulse", lv:4, cls:["Destroyer"], mode:"guard", sch:"Abjuration", dt:"force", desc:"Release a defensive shockwave. As a reaction when you or an ally within 10 feet takes damage, reduce it by 3d10. All hostile creatures within 10 feet must make a DC 16 Strength save or be pushed 15 feet and knocked prone.", eff:"Massive damage reduction + AoE push/prone.", flavor:"The fortress fights back.", disc:"Bureau structural engineers classify a Destroyer using Fortress Pulse as 'load-bearing personnel.'", save:"Strength", dc:16 },
	{ name:"Berserker's Fury", lv:4, cls:["Berserker"], mode:"overload", sch:"Transmutation", dt:"fire", desc:"Enter a heightened Overload state. For 1 minute, your melee weapon attacks deal an extra 2d8 fire damage, you have advantage on Strength checks and saves, and you gain resistance to bludgeoning, piercing, and slashing damage. You can't cast spells while active.", eff:"Damage buff + advantage + resistance.", flavor:"Past the limit. Past the pain. Past everything.", disc:"Medical scans show a Berserker in heightened Overload operates at 300% normal mana throughput. Bureau doctors call it 'unsustainable.' Berserkers disagree.", save:"", dc:0 },
	{ name:"Death Mark", lv:4, cls:["Assassin"], mode:"ambush", sch:"Necromancy", dt:"necrotic", desc:"Mark a creature you can see (bonus action). For 1 minute, your attacks against the marked target deal an extra 2d8 necrotic damage, and the target can't regain hit points. If you reduce it to 0 HP while marked, you become invisible until the end of your next turn.", eff:"Sustained damage buff + anti-heal + kill stealth.", flavor:"The contract is signed. In your blood.", disc:"Assassin Guild contracts literally mark the target with a mana signature matching this power. The target never knows.", save:"", dc:0 },
	{ name:"Velocity Barrage", lv:4, cls:["Striker"], mode:"kinetic", sch:"Transmutation", dt:"bludgeoning", desc:"Execute a flurry of six rapid strikes against one or two targets within 5 feet. Make six unarmed attacks, each dealing 1d6 + AGI modifier bludgeoning damage. If four or more hit the same target, it must make a DC 16 Vitality save or be stunned for 1 round.", eff:"Six attacks + conditional stun.", flavor:"Six hits. Two seconds. One outcome.", disc:"Frame-by-frame analysis shows each strike targets a different nerve gate. The precision is 'beyond human.'", save:"Vitality", dc:16 },
	{ name:"Crusader's Judgment", lv:4, cls:["Holy Knight"], mode:"radiant", sch:"Evocation", dt:"radiant", desc:"Channel your oath into a devastating melee strike. On your next hit, deal weapon damage plus 5d8 radiant damage. If the target is undead or a fiend, the extra damage is 6d8 and it must make a DC 16 Presence save or be banished to its native plane for 1 minute.", eff:"Massive radiant smite + conditional banishment.", flavor:"By the Absolute's will. Begone.", disc:"Three confirmed banishments on record. All three targets returned after 1 minute. All three were immediately engaged again.", save:"Presence", dc:16 },
	{ name:"Siege Protocol", lv:4, cls:["Technomancer"], mode:"device", sch:"Evocation", dt:"lightning", desc:"Deploy a heavy weapons platform (AC 16, HP 30, immobile). On each of your turns, use a bonus action to fire: 5d8 lightning in a 60-foot line (DC 16 AGI save, half on success). Lasts 1 minute or until destroyed.", eff:"Sustained AoE line damage.", flavor:"Heavy ordnance deployed. Clear the firing lane.", disc:"The platform's power cell burns out after exactly 10 shots. The Technomancer who designed it called this 'planned obsolescence.'", save:"Agility", dc:16 },
	{ name:"Hunter's Judgment", lv:4, cls:["Stalker"], mode:"tracking", sch:"Divination", dt:"", desc:"After tracking a creature for at least 1 minute, declare judgment. For the next hour, you have advantage on all attack rolls against the target, can't be surprised by it, and your critical hit range against it expands to 19-20.", eff:"Extended advantage + crit expansion.", flavor:"I've studied you long enough. Time's up.", disc:"A Stalker's judgment has a 94% mission success rate. The other 6% were interrupted by gate-collapses, not target evasion.", save:"", dc:0 },

	// ═══ LEVEL 5 ═══
	{ name:"Adamantine Shell", lv:5, cls:["Destroyer"], mode:"guard", sch:"Abjuration", dt:"force", desc:"Encase yourself in ultra-dense mana for 1 minute. You gain resistance to all damage except psychic, immunity to critical hits, and any creature that hits you with a melee attack takes 3d6 force damage.", eff:"Near-total damage resistance + crit immunity + retaliation.", flavor:"Hit me. I dare you.", disc:"A Destroyer survived a direct hit from an S-Rank gate boss's breath weapon while in Adamantine Shell. She described it as 'warm.'", save:"", dc:0 },
	{ name:"Eruption", lv:5, cls:["Berserker"], mode:"overload", sch:"Evocation", dt:"fire", desc:"Detonate your stored Overload energy in a 20-foot radius explosion centered on you. Each creature in the area makes a DC 17 Vitality save: 8d8 fire damage on failure, half on success. You are immune to this damage. All creatures in the area are pushed 15 feet away.", eff:"Massive AoE fire + push. Self-immune.", flavor:"Everything within twenty feet dies or moves. Those are the only options.", disc:"The blast radius was measured at exactly 20 feet, 0 inches. Berserkers have more control than they let on.", save:"Vitality", dc:17 },
	{ name:"Phantom Army", lv:5, cls:["Assassin"], mode:"ambush", sch:"Illusion", dt:"necrotic", desc:"Create 4 shadow duplicates of yourself. Each has AC 14, 1 HP, and can make attacks using your stats for 1d8 necrotic damage. Attacks against you target a random duplicate (d4+1: 1-4 hits duplicate, 5 hits you). Lasts 1 minute.", eff:"4 combat duplicates + evasion.", flavor:"Five of her. One is real. Choose wisely.", disc:"Bureau combat simulations show that an Assassin with Phantom Army has an 87% survival rate against opponents two ranks higher.", save:"", dc:0 },
	{ name:"Thousand Fists", lv:5, cls:["Striker"], mode:"kinetic", sch:"Transmutation", dt:"bludgeoning", desc:"Enter a state of supreme martial focus for 1 round. You can make 10 unarmed attacks against creatures within reach. Each deals 1d8 + AGI modifier bludgeoning. If you hit the same creature 6+ times, it's stunned until the end of its next turn (no save).", eff:"10 attacks + guaranteed stun on 6+ hits.", flavor:"She doesn't stop. She doesn't slow down. She doesn't miss.", disc:"Bureau high-speed cameras captured a Striker executing Thousand Fists in 1.8 seconds. The footage is used in recruitment materials.", save:"", dc:0 },
	{ name:"Absolute Sanctum", lv:5, cls:["Holy Knight"], mode:"radiant", sch:"Abjuration", dt:"radiant", desc:"Create a 15-foot radius zone of absolute protection for 1 minute. Allies inside gain +3 AC, advantage on all saves, and resistance to all damage. Hostile creatures entering take 4d8 radiant and must make a DC 17 Presence save or be pushed out.", eff:"Fortress zone: AC + saves + resistance + entry damage.", flavor:"Within this circle, nothing fails. The Absolute ensures it.", disc:"A Holy Knight's Absolute Sanctum held against a Monarch-class anomaly's area attack. The anomaly adjusted its targeting.", save:"Presence", dc:17 },
	{ name:"Arsenal Deploy", lv:5, cls:["Technomancer"], mode:"device", sch:"Conjuration", dt:"lightning", desc:"Deploy three combat devices simultaneously: a turret (1d10 lightning per turn), a shield emitter (+2 AC to allies within 10 ft), and a scanner (advantage on attacks against scanned targets). Each has AC 15, 20 HP. All last 1 minute.", eff:"Triple device deployment: offense + defense + intel.", flavor:"Full loadout. All systems green.", disc:"The Arsenal Deploy kit weighs 2 pounds in its collapsed state. Technomancer engineering violates several laws of physics.", save:"", dc:0 },
	{ name:"Apex Predator", lv:5, cls:["Stalker"], mode:"tracking", sch:"Transmutation", dt:"", desc:"Enter a heightened predatory state for 1 minute. Your movement speed doubles, you have advantage on all attack rolls, you can't be surprised, and your first hit each turn deals an extra 3d6 damage. You must make a DC 15 Presence save at the end of the duration or gain 1 level of exhaustion.", eff:"Ultimate hunting mode with exhaustion risk.", flavor:"The apex predator doesn't announce itself. You just stop existing.", disc:"Bureau combat analysts rate a Stalker in Apex Predator state as 'equivalent to a B-Rank gate boss.' The comparison is conservative.", save:"", dc:0 },

	// ═══ LEVEL 6-7 ═══
	{ name:"Immovable Aegis", lv:6, cls:["Destroyer","Holy Knight"], mode:"guard", sch:"Abjuration", dt:"force", desc:"Become an immovable defensive bastion for 1 minute. You can't be moved against your will, have immunity to prone, and reduce all damage by your STR modifier + 10. As a reaction, redirect any attack targeting an ally within 15 feet to yourself.", eff:"Flat damage reduction + attack redirect.", flavor:"I don't move. Neither does anything behind me.", disc:"An A-Rank Destroyer absorbed 47 attacks in a single encounter while maintaining this power. Zero reached the team behind her.", save:"", dc:0 },
	{ name:"Cataclysm Overload", lv:6, cls:["Berserker"], mode:"overload", sch:"Evocation", dt:"fire", desc:"Detonate stored mana in a 30-foot radius: 10d10 fire damage (DC 17 VIT, half on success). You are immune. All surfaces in the area ignite. Creatures that fail the save are set ablaze (2d6 fire per turn, action to extinguish). Leaves a 30-foot crater.", eff:"Massive fire AoE + persistent burn + terrain destruction.", flavor:"She burned. Everything burned. She stood up.", disc:"The crater left by Cataclysm Overload has been measured at an average depth of 4 feet. Bureau fills them in.", save:"Vitality", dc:17 },
	{ name:"Death's Shadow", lv:6, cls:["Assassin"], mode:"ambush", sch:"Illusion", dt:"necrotic", desc:"Become one with shadow for 1 minute. While in dim light or darkness: invisible, can move through creatures, and your attacks deal an extra 4d8 necrotic. First attack each turn auto-crits if target hasn't acted yet this combat.", eff:"Supreme stealth + bonus damage + auto-crit on unaware.", flavor:"The shadow is alive. It has opinions about your continued existence.", disc:"Bureau after-action reports attribute 0 witness accounts to A-Rank Assassins using this power. By design.", save:"", dc:0 },
	{ name:"Infinite Barrage", lv:6, cls:["Striker"], mode:"kinetic", sch:"Transmutation", dt:"force", desc:"For 1 minute, your unarmed attacks deal an extra 2d6 force damage, you can make 4 attacks per Attack action instead of 2, and your movement speed increases by 20 feet. Each creature you hit has its speed reduced by 5 feet (cumulative).", eff:"Sustained speed + multi-attack + cumulative slow.", flavor:"She doesn't tire. Her targets do.", disc:"Bureau endurance tests show a Striker in Infinite Barrage processes mana 5x faster than baseline. The biological implications are 'being studied.'", save:"", dc:0 },
	{ name:"Warhammer of the Absolute", lv:7, cls:["Holy Knight"], mode:"radiant", sch:"Conjuration", dt:"radiant", desc:"Summon a Huge spectral hammer of radiant mana. Make a melee spell attack (Presence) against a creature: 10d10 radiant damage on a hit. Undead/fiends take max damage. The impact creates a 15-foot radius zone of consecrated ground for 1 minute (enemies have disadvantage on saves).", eff:"Massive single-target radiant + consecrated terrain.", flavor:"The Absolute brings the hammer. You just aim it.", disc:"The hammer manifests for exactly 0.3 seconds. The consecrated ground lasts considerably longer.", save:"", dc:0 },
	{ name:"Total Arsenal", lv:7, cls:["Technomancer"], mode:"device", sch:"Conjuration", dt:"lightning", desc:"Deploy your complete device arsenal: 2 turrets (2d10 each), a dome shield (+3 AC, 50 ft radius), a scanner (truesight 120 ft), and a repair drone (heals allies 2d8/turn). All devices have AC 17, 40 HP. Lasts 1 minute.", eff:"Full device deployment: offense + defense + utility + healing.", flavor:"Full kit. Maximum deployment. All frequencies hostile.", disc:"Total Arsenal has only been deployed 7 times in Bureau history. All 7 missions were rated 'impossible' beforehand. All 7 succeeded.", save:"", dc:0 },
	{ name:"Apex Strike", lv:7, cls:["Stalker"], mode:"tracking", sch:"Divination", dt:"", desc:"Study a target for 1 round, then deliver the perfect attack. Your next attack against the target auto-hits, auto-crits, and deals maximum damage. If the target has legendary resistance, it expends one use.", eff:"Guaranteed max-damage crit + legendary resistance burn.", flavor:"One shot. One kill. That's not a motto. That's a fact.", disc:"Bureau records show 3 confirmed Apex Strikes against S-Rank targets. All three were decisive.", save:"", dc:0 },

	// ═══ LEVEL 8-9 ═══
	{ name:"World Breaker", lv:8, cls:["Destroyer"], mode:"guard", sch:"Evocation", dt:"force", desc:"Channel all defensive energy into a single apocalyptic counter-strike. As a reaction when hit, negate all damage from the attack and respond with 12d12 force damage (no save). The impact creates a 30-foot crater and all creatures within are knocked prone.", eff:"Full negate + 12d12 force counter + AoE prone.", flavor:"You shouldn't have done that.", disc:"One confirmed use against a Monarch-class anomaly. The Monarch reconsidered its life choices.", save:"", dc:0 },
	{ name:"Nuclear Overload", lv:8, cls:["Berserker"], mode:"overload", sch:"Evocation", dt:"fire", desc:"Release all stored mana in a 60-foot radius nuclear-class detonation. 15d10 fire damage (DC 19 VIT, half on success). You are immune. Everything in the area is obliterated — structures, terrain, objects. Leaves a glassed crater.", eff:"15d10 fire in 60-foot radius. Total environmental destruction.", flavor:"She warned them. They didn't listen.", disc:"Bureau classifies Nuclear Overload as a 'weapon of mass destruction.' Usage requires written authorization from the Bureau Director.", save:"Vitality", dc:19 },
	{ name:"Reaper's Sentence", lv:8, cls:["Assassin"], mode:"ambush", sch:"Necromancy", dt:"necrotic", desc:"Touch a creature. It must make a DC 19 Vitality save. On failure: if it has 100 HP or fewer, it dies instantly. If more, it takes 12d10 necrotic damage. On success: 6d10 necrotic damage. Creatures killed by this power can't be resurrected for 1 year.", eff:"Conditional instant kill + massive necrotic.", flavor:"Sentence delivered.", disc:"The Assassin Guild considers this power sacred. It's only taught to those who have proven they won't misuse it. Three have.", save:"Vitality", dc:19 },
	{ name:"Final Strike", lv:9, cls:["Striker"], mode:"kinetic", sch:"Evocation", dt:"force", desc:"Channel every ounce of kinetic energy into a single punch. Make an unarmed attack with +10 to hit. On a hit: 20d10 force damage. If this reduces the target to 0 HP, the excess damage carries to the next creature within 10 feet. After using this, you can't use powers until after a long rest.", eff:"20d10 force + overflow damage. Exhausting.", flavor:"One punch. That's all she ever needed.", disc:"Bureau seismographs register Final Strike as a localized earthquake. The Richter reading has been as high as 3.2.", save:"", dc:0 },
	{ name:"Absolute Ascension", lv:9, cls:["Holy Knight"], mode:"radiant", sch:"Transmutation", dt:"radiant", desc:"Transcend mortal limits for 1 minute. You gain: fly speed 60 ft, immunity to all conditions, resistance to all damage, +5 to all saves, your weapon deals an extra 6d8 radiant on every hit, and you shed bright light 120 feet. After the effect ends, gain 3 levels of exhaustion.", eff:"Divine transformation: flight + immunity + damage + light.", flavor:"For one minute, she was the Absolute's sword.", disc:"There are two confirmed Ascensions in Bureau history. Both ended gate-breaks that were classified as 'unsurvivable.'", save:"", dc:0 },
	{ name:"Skynet Protocol", lv:9, cls:["Technomancer"], mode:"device", sch:"Conjuration", dt:"lightning", desc:"Deploy a self-directing combat AI network. 10 autonomous drones, each AC 18, 30 HP, dealing 2d10 lightning per attack. The network targets optimally, covering all flanks. It also provides truesight 300 ft, +5 to all ally attack rolls within range, and jams enemy communications. Lasts 1 minute.", eff:"10 drones + truesight + ally buff + comms jamming.", flavor:"All frequencies compromised. All targets acquired. All exits blocked.", disc:"The Bureau's AI ethics board reviewed this power for 6 months. They approved it with 'extreme reservations.'", save:"", dc:0 },
	{ name:"Apex Convergence", lv:9, cls:["Stalker"], mode:"tracking", sch:"Divination", dt:"", desc:"Mark every hostile creature within 300 feet simultaneously. For 1 minute, you and all allies have advantage on attacks against all marked targets, can't be surprised, have truesight 300 ft, and the first hit against each marked target each round deals an extra 4d6 damage.", eff:"Mass mark: advantage + truesight + bonus damage for entire party.", flavor:"Every target. Every angle. Every exit. All at once.", disc:"A Stalker used Apex Convergence during a double S-Rank gate-break. The tactical advantage was described as 'the closest thing to omniscience in combat.'", save:"", dc:0 },
];
