// Powers Level 1-3 — 40 unique entries
// 7 primary martial jobs + 4 path-hybrid casters
module.exports = [
	// ═══ DESTROYER (guard) ═══
	{
		name: "Rampart Shell",
		lv: 1,
		cls: ["Destroyer"],
		mode: "guard",
		sch: "Abjuration",
		dt: "force",
		desc: "Harden your mana field into a reactive shell. As a reaction when you or an adjacent ally takes damage, reduce it by 1d10 + STR modifier. If the attack was melee, the attacker takes force feedback equal to half the amount blocked.",
		eff: "Damage reduction + force retaliation.",
		flavor: "The wall hits back.",
		disc: "Bureau combat instructors demonstrate this with a sledgehammer. The hammer breaks.",
		save: "Vitality",
		dc: 13,
	},
	{
		name: "Bulwark Stance",
		lv: 2,
		cls: ["Destroyer"],
		mode: "guard",
		sch: "Abjuration",
		dt: "force",
		desc: "Plant yourself and channel defensive mana through your weapon. Until the start of your next turn, you have +2 AC and advantage on Strength saves. Creatures that hit you with melee attacks take 2d6 force damage.",
		eff: "+2 AC, advantage on STR saves, retaliation.",
		flavor: "Immovable. Unavoidable.",
		disc: "The stance was developed after a Destroyer tanked a gate boss's charge without moving. The boss moved.",
		save: "",
		dc: 0,
	},
	{
		name: "Titan's Rebuke",
		lv: 3,
		cls: ["Destroyer"],
		mode: "guard",
		sch: "Evocation",
		dt: "force",
		desc: "When a creature within 5 feet hits you, channel the impact into a devastating counterstrike. As a reaction, make a melee weapon attack with advantage. On a hit, deal weapon damage plus 3d8 force damage and push the target 10 feet.",
		eff: "Counterattack with bonus force damage + push.",
		flavor: "You hit me. My turn.",
		disc: "A Destroyer used this against a B-Rank gate boss's claw attack. The boss reconsidered its targeting priorities.",
		save: "",
		dc: 0,
	},

	// ═══ BERSERKER (overload) ═══
	{
		name: "Fury Surge",
		lv: 1,
		cls: ["Berserker"],
		mode: "overload",
		sch: "Transmutation",
		dt: "fire",
		desc: "Channel volatile combat energy into a single devastating blow. When you hit with a melee weapon attack, deal an additional 2d6 fire damage. If you are in Overload, the target must also make a DC 13 Vitality save or be set ablaze, taking 1d6 fire at the start of its next turn.",
		eff: "Bonus fire damage + ignite on Overload.",
		flavor: "The fire doesn't come from outside. It comes from you.",
		disc: "First documented when a Berserker's Overload discharge melted through a gate-crystal wall.",
		save: "Vitality",
		dc: 13,
	},
	{
		name: "Crimson Howl",
		lv: 2,
		cls: ["Berserker"],
		mode: "overload",
		sch: "Enchantment",
		dt: "thunder",
		desc: "Release a terrifying war cry charged with Overload energy. Each hostile creature within 15 feet must make a DC 14 Presence save or be frightened of you until the end of your next turn. Frightened creatures also take 2d6 thunder damage.",
		eff: "AoE frighten + thunder damage.",
		flavor: "The sound alone draws blood.",
		disc: "Bureau audiologists measured the howl at 140 decibels. The mana component adds a frequency humans can't hear but can definitely feel.",
		save: "Presence",
		dc: 14,
	},
	{
		name: "Rupture Break",
		lv: 3,
		cls: ["Berserker"],
		mode: "overload",
		sch: "Evocation",
		dt: "fire",
		desc: "Slam the ground with Overload-charged force, creating a 15-foot radius shockwave. Each creature in the area makes a DC 15 Strength save: 4d8 fire damage and knocked prone on failure, half damage on success. The area becomes difficult terrain.",
		eff: "AoE fire + prone + difficult terrain.",
		flavor: "The floor isn't your ally anymore.",
		disc: "Training facilities reinforced their floors specifically because of this technique. It didn't help.",
		save: "Strength",
		dc: 15,
	},

	// ═══ ASSASSIN (ambush) ═══
	{
		name: "Shadow Strike",
		lv: 1,
		cls: ["Assassin"],
		mode: "ambush",
		sch: "Illusion",
		dt: "necrotic",
		desc: "Cloak your weapon in shadow mana and strike from concealment. If you attack from hiding or with advantage, deal an additional 2d6 necrotic damage. The target's vision dims — it has disadvantage on its next attack roll.",
		eff: "Bonus necrotic damage + attack debuff.",
		flavor: "You saw the shadow. You didn't see the blade.",
		disc: "Assassin Guild trainees practice this 500 times before field certification. The target dummy is replaced 499 times.",
		save: "",
		dc: 0,
	},
	{
		name: "Phantom Lunge",
		lv: 2,
		cls: ["Assassin"],
		mode: "ambush",
		sch: "Conjuration",
		dt: "necrotic",
		desc: "Teleport up to 15 feet to an unoccupied space adjacent to a target and immediately make a melee weapon attack. If you were hidden, the attack deals an extra 3d6 necrotic damage and the target can't take reactions until the end of your next turn.",
		eff: "Teleport + ambush strike + reaction denial.",
		flavor: "Distance is a courtesy she doesn't extend.",
		disc: "Bureau security cameras show a 0.2 second gap between positions. The kill takes 0.1.",
		save: "",
		dc: 0,
	},
	{
		name: "Lethal Precision",
		lv: 3,
		cls: ["Assassin"],
		mode: "ambush",
		sch: "Divination",
		dt: "necrotic",
		desc: "Study a creature for one round (bonus action). On your next turn, your first attack against that creature automatically crits if it hits. The attack deals an additional 3d8 necrotic damage from targeting a vital mana-node.",
		eff: "Guaranteed crit setup + bonus necrotic.",
		flavor: "She doesn't aim for the body. She aims for the circuit.",
		disc: "Bureau combat analysts call this 'surgical.' Surgeons find the comparison insulting.",
		save: "",
		dc: 0,
	},

	// ═══ STRIKER (kinetic) ═══
	{
		name: "Kinetic Rush",
		lv: 1,
		cls: ["Striker"],
		mode: "kinetic",
		sch: "Transmutation",
		dt: "bludgeoning",
		desc: "Convert momentum into raw impact. After moving at least 10 feet, your next unarmed strike deals an additional 2d6 bludgeoning damage. You can then move 10 feet without provoking opportunity attacks.",
		eff: "Bonus damage after movement + free disengage move.",
		flavor: "She was there. She was here. You're on the floor.",
		disc: "Striker velocity was measured at 47 mph during a kinetic rush. The target's velocity was 0.",
		save: "",
		dc: 0,
	},
	{
		name: "Nerve Gate Cascade",
		lv: 2,
		cls: ["Striker"],
		mode: "kinetic",
		sch: "Transmutation",
		dt: "bludgeoning",
		desc: "Deliver a rapid sequence of three strikes targeting different nerve gates. Make three unarmed attacks, each dealing 1d8 + AGI modifier bludgeoning damage. If all three hit the same target, it must make a DC 14 Vitality save or be stunned until the end of its next turn.",
		eff: "Triple attack + conditional stun.",
		flavor: "Three hits. One second. Zero arguments.",
		disc: "The nerve gate sequence was mapped by a Striker who studied gate-anomaly anatomy for six months. She hit all the right spots.",
		save: "Vitality",
		dc: 14,
	},
	{
		name: "Shockwave Palm",
		lv: 3,
		cls: ["Striker"],
		mode: "kinetic",
		sch: "Evocation",
		dt: "force",
		desc: "Channel kinetic energy through your palm and release it on contact. Make an unarmed strike. On a hit, deal weapon damage plus 4d8 force damage and push the target 20 feet. If the target collides with a solid surface, it takes an additional 2d6 bludgeoning damage.",
		eff: "Palm strike + massive push + collision damage.",
		flavor: "One palm. Twenty feet. The wall at twenty-one.",
		disc: "The impact crater was 3 inches deep in reinforced concrete. The Striker's palm was unharmed.",
		save: "",
		dc: 0,
	},

	// ═══ HOLY KNIGHT (radiant) ═══
	{
		name: "Radiant Intercept",
		lv: 1,
		cls: ["Holy Knight"],
		mode: "radiant",
		sch: "Abjuration",
		dt: "radiant",
		desc: "As a reaction when an ally within 10 feet is attacked, interpose yourself and grant the ally +3 AC against the attack. If the attack still hits, you take the damage instead and deal 1d8 radiant damage to the attacker.",
		eff: "Ally protection + damage transfer + retaliation.",
		flavor: "I stand between you and everything else.",
		disc: "Holy Knights don't flinch during Radiant Intercept. Bureau psychologists believe it's not courage — it's certainty.",
		save: "",
		dc: 0,
	},
	{
		name: "Oath Purge",
		lv: 2,
		cls: ["Holy Knight"],
		mode: "radiant",
		sch: "Evocation",
		dt: "radiant",
		desc: "Channel your oath into a burst of purifying light. One creature within 30 feet must make a DC 14 Presence save: 3d8 radiant damage on failure, half on success. If the target is undead or fiend-type, it also has disadvantage on attack rolls until the end of its next turn.",
		eff: "Radiant damage + undead/fiend debuff.",
		flavor: "The light finds what hides in the dark.",
		disc: "An Oath Purge cast inside a shadow-filled gate instantly illuminated the entire chamber. Every shadow anomaly was visible.",
		save: "Presence",
		dc: 14,
	},
	{
		name: "Divine Bastion",
		lv: 3,
		cls: ["Holy Knight"],
		mode: "radiant",
		sch: "Abjuration",
		dt: "radiant",
		desc: "Create a 10-foot radius aura of radiant protection centered on you for 1 minute. Allies in the aura gain +2 to AC and saving throws. Hostile creatures entering the aura take 2d6 radiant damage. You can end the aura early to heal all allies in it for 3d8 HP.",
		eff: "Protective aura + entry damage + burst heal option.",
		flavor: "Within this light, nothing falls.",
		disc: "During a gate siege, a Holy Knight maintained Divine Bastion for the full minute while the raid team evacuated. She was the last one out.",
		save: "",
		dc: 0,
	},

	// ═══ TECHNOMANCER (device) ═══
	{
		name: "Shock Drone",
		lv: 1,
		cls: ["Technomancer"],
		mode: "device",
		sch: "Evocation",
		dt: "lightning",
		desc: "Deploy a small hovering drone that zaps the nearest hostile creature within 30 feet at the end of each of your turns for 1d8 lightning damage (ranged spell attack using INT). The drone has AC 12, 5 HP, and lasts 1 minute.",
		eff: "Persistent auto-damage drone.",
		flavor: "Set it and forget it. It doesn't forget.",
		disc: "The MK-I Shock Drone had a 30% friendly fire rate. The MK-III does not. We don't talk about MK-II.",
		save: "",
		dc: 0,
	},
	{
		name: "Mana Scan Array",
		lv: 2,
		cls: ["Technomancer"],
		mode: "device",
		sch: "Divination",
		dt: "",
		desc: "Deploy a scanning device that reveals all creatures within 60 feet, including invisible ones. For 1 minute, creatures in the scan area can't benefit from invisibility against you or your allies. You also learn each creature's current HP percentage.",
		eff: "Mass detect + anti-invisibility + HP scan.",
		flavor: "All contacts identified. None hidden.",
		disc: "The scan array processes 4,000 data points per second. Bureau intelligence analysts wish they had this kind of budget.",
		save: "",
		dc: 0,
	},
	{
		name: "Overcharge Payload",
		lv: 3,
		cls: ["Technomancer"],
		mode: "device",
		sch: "Evocation",
		dt: "lightning",
		desc: "Fire an overcharged projectile from your focus device. Ranged spell attack (INT): 4d10 lightning damage on a hit. If the target is wearing metal armor or is a construct, the attack has advantage and deals an extra 2d10 damage.",
		eff: "High single-target damage + bonus vs metal/constructs.",
		flavor: "All power to main cannon. Fire.",
		disc: "The payload's mana signature is visible on Bureau sensors from 3 miles away. Subtlety was never the goal.",
		save: "",
		dc: 0,
	},

	// ═══ STALKER (tracking) ═══
	{
		name: "Prey Lock",
		lv: 1,
		cls: ["Stalker"],
		mode: "tracking",
		sch: "Divination",
		dt: "",
		desc: "Mark a creature you can see within 90 feet. For 1 hour, you know the target's direction and distance while within 1 mile. Your first attack each turn against the marked target deals an extra 1d6 damage of your weapon's type.",
		eff: "Tracking + bonus damage on first hit.",
		flavor: "Marked. No amount of running changes that.",
		disc: "A Stalker's prey lock has never been successfully broken by a target. The record for evasion is 47 minutes.",
		save: "",
		dc: 0,
	},
	{
		name: "Terrain Ghost",
		lv: 2,
		cls: ["Stalker"],
		mode: "tracking",
		sch: "Transmutation",
		dt: "",
		desc: "Adapt to your environment. For 1 hour, you ignore difficult terrain, can't be tracked except by magical means, and have advantage on Stealth checks. If you are in natural terrain within a gate, you also gain +10 feet movement speed.",
		eff: "Terrain mastery + stealth advantage + speed.",
		flavor: "The forest doesn't slow her. It hides her.",
		disc: "Bureau field tests showed a Stalker using Terrain Ghost crossed a B-Rank gate's obstacle course in half the time of any other job.",
		save: "",
		dc: 0,
	},
	{
		name: "Resonance Snare",
		lv: 3,
		cls: ["Stalker"],
		mode: "tracking",
		sch: "Conjuration",
		dt: "force",
		desc: "Set an invisible mana-wire trap in a 10-foot square area. The first creature to enter triggers it: DC 15 Agility save or take 4d6 force damage and be restrained. The snare alerts you mentally when triggered. Lasts 8 hours or until triggered.",
		eff: "Invisible trap + restraint + mental alert.",
		flavor: "She set the trap an hour ago. She's been waiting.",
		disc: "A Stalker once rigged an entire gate floor with Resonance Snares. The anomalies cleared themselves.",
		save: "Agility",
		dc: 15,
	},

	// ═══ PATH-HYBRID: IDOL (resonance) ═══
	{
		name: "Dissonant Strike",
		lv: 1,
		cls: ["Idol"],
		mode: "resonance",
		sch: "Evocation",
		dt: "thunder",
		desc: "Infuse your weapon with sonic resonance. Your next melee attack deals an additional 1d8 thunder damage and the target must make a DC 13 Presence save or have disadvantage on its next attack roll as the dissonance disrupts its coordination.",
		eff: "Bonus thunder + attack debuff.",
		flavor: "The beat drops. So does the target.",
		disc: "Dance Resonance Idols incorporate this into their combat choreography. The audience can't tell where performance ends and violence begins.",
		save: "Presence",
		dc: 13,
	},
	{
		name: "Tempo Shift",
		lv: 2,
		cls: ["Idol"],
		mode: "resonance",
		sch: "Transmutation",
		dt: "",
		desc: "Alter your personal rhythm to move with supernatural speed. Until the end of your turn, your movement speed doubles, you don't provoke opportunity attacks, and your next melee attack has advantage.",
		eff: "Speed burst + free movement + advantage.",
		flavor: "Double-time. Try to keep up.",
		disc: "K-pop dance fighting styles emphasize tempo changes. This power is the combat expression of that principle.",
		save: "",
		dc: 0,
	},

	// ═══ PATH-HYBRID: HERALD (divine) ═══
	{
		name: "Guided Strike",
		lv: 1,
		cls: ["Herald"],
		mode: "divine",
		sch: "Divination",
		dt: "radiant",
		desc: "Channel the Absolute's guidance into your weapon. As a bonus action, gain +5 to your next attack roll made before the end of your turn. If the attack hits, it deals an additional 1d6 radiant damage.",
		eff: "+5 to hit + bonus radiant.",
		flavor: "The Absolute points. You swing.",
		disc: "Combat Mandate Heralds use this as their primary engagement tool. Miss rates drop to near zero.",
		save: "",
		dc: 0,
	},
	{
		name: "Retributive Ward",
		lv: 2,
		cls: ["Herald"],
		mode: "divine",
		sch: "Abjuration",
		dt: "radiant",
		desc: "Place a retributive ward on yourself or an ally within 30 feet. The next time the warded creature is hit by a melee attack, the attacker takes 3d6 radiant damage and is pushed 10 feet away.",
		eff: "Reactive radiant damage + push.",
		flavor: "Hit her. See what happens.",
		disc: "Storm Mandate Heralds prefer this power because the radiant discharge resembles a lightning bolt.",
		save: "",
		dc: 0,
	},

	// ═══ PATH-HYBRID: CONTRACTOR (pact) ═══
	{
		name: "Cursed Blade Edge",
		lv: 1,
		cls: ["Contractor"],
		mode: "pact",
		sch: "Necromancy",
		dt: "necrotic",
		desc: "Your patron infuses your weapon with pact energy. For 1 minute, your weapon attacks deal an extra 1d6 necrotic damage. If you reduce a creature to 0 HP while this is active, you gain temporary HP equal to your Presence modifier + your level.",
		eff: "Bonus necrotic + kill reward.",
		flavor: "The blade drinks. You don't ask what.",
		disc: "Cursed Blade path Contractors report their weapons sometimes vibrate when enemies are nearby. The patrons deny involvement.",
		save: "",
		dc: 0,
	},
	{
		name: "Pact Retaliation",
		lv: 2,
		cls: ["Contractor"],
		mode: "pact",
		sch: "Abjuration",
		dt: "force",
		desc: "As a reaction when you take damage, your patron retaliates. The attacker takes 2d8 force damage and must make a DC 14 Presence save or be frightened of you until the end of its next turn.",
		eff: "Reactive force damage + frighten.",
		flavor: "Your patron takes offense on your behalf.",
		disc: "Bureau analysts cannot identify the source of the retaliatory force. The pact entity is 'unavailable for comment.'",
		save: "Presence",
		dc: 14,
	},

	// ═══ PATH-HYBRID: REVENANT (entropy) ═══
	{
		name: "Withering Touch",
		lv: 1,
		cls: ["Revenant"],
		mode: "entropy",
		sch: "Necromancy",
		dt: "necrotic",
		desc: "Channel entropy through your weapon. Your next melee attack deals an additional 1d8 necrotic damage. The target must make a DC 13 Vitality save or have its speed reduced by 10 feet until the end of its next turn as its muscles decay momentarily.",
		eff: "Bonus necrotic + speed reduction.",
		flavor: "Everything she touches remembers it was temporary.",
		disc: "Wither Guard Revenants train this technique through meditation on impermanence. The combat applications emerged naturally.",
		save: "Vitality",
		dc: 13,
	},
	{
		name: "Entropic Counter",
		lv: 2,
		cls: ["Revenant"],
		mode: "entropy",
		sch: "Necromancy",
		dt: "necrotic",
		desc: "As a reaction when hit by a melee attack, release a burst of entropic energy. The attacker takes 2d8 necrotic damage and its weapon corrodes — the next attack it makes with that weapon has disadvantage.",
		eff: "Reactive necrotic + weapon debuff.",
		flavor: "The sword swings. The sword regrets.",
		disc: "Entropy Blade Revenants can corrode mana-forged weapons. Bureau artificers are 'concerned.'",
		save: "",
		dc: 0,
	},

	// ═══ CROSS-CLASS SHARED ═══
	{
		name: "Iron Resolve",
		lv: 1,
		cls: ["Destroyer", "Berserker", "Holy Knight", "Stalker"],
		mode: "guard",
		sch: "Abjuration",
		dt: "",
		desc: "Harden your will against mental assault. As a reaction when you fail a save against being charmed or frightened, reroll the save with advantage. You must use the new result.",
		eff: "Reroll mental save with advantage.",
		flavor: "No.",
		disc: "The simplest and most used power in the Bureau arsenal. One word. One effect. One result.",
		save: "",
		dc: 0,
	},
	{
		name: "Second Wind",
		lv: 1,
		cls: [
			"Destroyer",
			"Berserker",
			"Assassin",
			"Striker",
			"Holy Knight",
			"Technomancer",
			"Stalker",
		],
		mode: "guard",
		sch: "Transmutation",
		dt: "",
		desc: "Draw on your mana reserves for an emergency burst of healing. As a bonus action, regain 1d10 + your character level in hit points. Usable once per short rest.",
		eff: "Self-heal as bonus action.",
		flavor: "Not done yet.",
		disc: "Every martial Awakened learns this. Those who don't learn it don't survive to learn anything else.",
		save: "",
		dc: 0,
	},
	{
		name: "Combat Roll",
		lv: 2,
		cls: ["Assassin", "Striker", "Stalker", "Technomancer"],
		mode: "kinetic",
		sch: "Transmutation",
		dt: "",
		desc: "As a reaction when targeted by an attack you can see, roll up to 15 feet to an unoccupied space. The triggering attack has disadvantage. You don't provoke opportunity attacks during this movement.",
		eff: "Evasive reaction + repositioning.",
		flavor: "She wasn't there when the fist arrived.",
		disc: "Bureau mobility training emphasizes this technique above all others. Dodge first, counter second.",
		save: "",
		dc: 0,
	},
	{
		name: "Battle Cry",
		lv: 2,
		cls: ["Destroyer", "Berserker", "Holy Knight"],
		mode: "overload",
		sch: "Enchantment",
		dt: "",
		desc: "Release a war cry that bolsters your allies. As a bonus action, up to 3 allies within 30 feet gain advantage on their next attack roll and +2 to their next saving throw, both made before the end of your next turn.",
		eff: "Mass buff: advantage on attack + save bonus.",
		flavor: "When she yells, you fight harder. You can't explain why.",
		disc: "Bureau psychologists classify this as 'resonance-amplified combat motivation.' Soldiers call it 'the boost.'",
		save: "",
		dc: 0,
	},
	{
		name: "Marked for Death",
		lv: 3,
		cls: ["Assassin", "Stalker", "Destroyer"],
		mode: "ambush",
		sch: "Divination",
		dt: "",
		desc: "Mark a creature you can see within 60 feet. For 1 minute, all attacks against the marked target have +2 to hit, and critical hits against it deal an extra 2d6 damage of the weapon's type. Only one mark active at a time.",
		eff: "Party-wide hit bonus + crit bonus vs target.",
		flavor: "Everyone knows where to aim now.",
		disc: "Raid leaders coordinate with Assassins for mark placement. It's the most requested power in organized gate clears.",
		save: "",
		dc: 0,
	},
];
