// Level 5-6 Spells — 22 unique entries
module.exports = [
	// ═══ LEVEL 5 ═══
	{
		name: "Mana Storm",
		lv: 5,
		sch: "Evocation",
		cls: ["Mage", "Esper"],
		ct: "1 action",
		rng: "150 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "10d6",
		dt: "force",
		save: "Agility",
		dc: 17,
		ePri: "10d6 force damage in 40-foot radius.",
		eSec: "Destroys all nonmagical objects in the area.",
		desc: "Unleash a cataclysmic sphere of raw mana at a point within range. Each creature in a 40-foot radius must make a DC 17 Agility save: 10d6 force damage on failure, half on success. Nonmagical objects are destroyed. The blast leaves a temporary dead-mana zone for 1 round.",
		higher: "Damage increases by 2d6 per level above 5th.",
		flavor: "The point of no return. For everyone.",
		disc: "The first Mana Storm test leveled a Bureau training facility. The replacement was built further from the city.",
		tags: ["mage", "esper", "force", "devastation", "area"],
	},
	{
		name: "Raise Gate Dead",
		lv: 5,
		sch: "Necromancy",
		cls: ["Revenant"],
		ct: "1 minute",
		rng: "Touch",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Restore a dead creature to life with 1 HP.",
		eSec: "Target takes -4 penalty to all d20 rolls for 4 days.",
		desc: "Touch a creature that died within the last 10 days and restore it to life with 1 hit point. The soul must be willing and free to return. The target takes a -4 penalty to all attack rolls, saving throws, and ability checks, decreasing by 1 every 24 hours until eliminated.",
		higher: "At 7th level, the time limit extends to 100 days.",
		flavor: "Death filed a complaint. The Revenant overruled it.",
		disc: "Bureau ethics policy requires written consent before casting. Most Hunters pre-sign the form during orientation.",
		tags: ["revenant", "necromancy", "resurrection", "healing"],
	},
	{
		name: "Pact Dominion",
		lv: 5,
		sch: "Enchantment",
		cls: ["Contractor"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "psychic",
		save: "Presence",
		dc: 17,
		ePri: "Dominate a creature on failed save.",
		eSec: "Use action to command the target; it obeys.",
		desc: "Channel your patron's will directly into a creature's mind. The target makes a DC 17 Presence save. On failure, it is dominated for the duration: you use your action to issue commands and the target obeys to the best of its ability. It repeats the save each time it takes damage.",
		higher: "At 7th level, duration extends to 1 hour.",
		flavor: "Your patron has a suggestion. It's not optional.",
		disc: "Bureau interrogation protocols forbid this spell. Field operatives have broader discretion.",
		tags: ["contractor", "dominate", "control", "enchantment"],
	},
	{
		name: "Sonic Annihilation",
		lv: 5,
		sch: "Evocation",
		cls: ["Idol"],
		ct: "1 action",
		rng: "Self (60-foot cone)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "8d8",
		dt: "thunder",
		save: "Vitality",
		dc: 17,
		ePri: "8d8 thunder damage in 60-foot cone.",
		eSec: "Failed saves are deafened and stunned for 1 round.",
		desc: "Release a devastating wave of amplified harmonic destruction in a 60-foot cone. Each creature must make a DC 17 Vitality save: 8d8 thunder damage, deafened for 1 minute, and stunned until end of their next turn on failure. Half damage and deafened only on success.",
		higher: "Damage increases by 1d8 per level above 5th.",
		flavor: "The final encore. Nobody asked for an encore.",
		disc: "Structural damage reports cite this spell as the #1 cause of gate-adjacent building collapse. The Idol Guild pays the insurance.",
		tags: ["idol", "thunder", "devastation", "stun", "deaf"],
	},
	{
		name: "Absolute Judgment",
		lv: 5,
		sch: "Evocation",
		cls: ["Herald", "Holy Knight"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "8d8",
		dt: "radiant",
		save: "Vitality",
		dc: 17,
		ePri: "8d8 radiant damage, or 10d8 vs undead/fiends.",
		eSec: "Failed save blinds target for 1 round.",
		desc: "Call down a column of the Absolute's judgment on a creature within range. The target makes a DC 17 Vitality save: 8d8 radiant damage on failure (10d8 against undead and fiend-type anomalies), half on success. On failure, the target is also blinded until end of its next turn.",
		higher: "Damage increases by 1d8 per level above 5th.",
		flavor: "Judgment rendered. Appeal denied.",
		disc: "The column of light is visible from orbit. Bureau satellite tracking confirms three instances in the last fiscal year.",
		tags: ["herald", "holy-knight", "radiant", "judgment", "anti-undead"],
	},
	{
		name: "Predator's Web",
		lv: 5,
		sch: "Conjuration",
		cls: ["Stalker", "Assassin"],
		ct: "1 action",
		rng: "120 feet",
		dur: "Concentration, up to 1 hour",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "Agility",
		dc: 17,
		ePri: "Create a 40-foot cube of mana-wire that restrains creatures.",
		eSec: "Restrained creatures take 4d6 force at start of each turn.",
		desc: "Spread a 40-foot cube of near-invisible mana-wire at a point within range. Creatures entering the area must make a DC 17 Agility save or be restrained. Restrained creatures take 4d6 force damage at the start of each turn. They can repeat the save at the end of each turn to escape.",
		higher: "At 7th level, the web also suppresses teleportation.",
		flavor: "The trap is set. The prey has arrived. Welcome.",
		disc: "A Stalker once webbed an entire gate-floor exit. The raid team walked through freely. The anomalies did not.",
		tags: ["stalker", "assassin", "conjuration", "restraint", "trap"],
	},
	{
		name: "Mass Circuit Boost",
		lv: 5,
		sch: "Transmutation",
		cls: ["Technomancer"],
		ct: "1 action",
		rng: "30 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Up to 6 allies gain +2 AC, advantage on AGI saves, +10 speed.",
		eSec: "Spell ends for a creature if it falls unconscious.",
		desc: "Overclock up to 6 willing creatures' mana circuits simultaneously. For the duration, each target gains +2 AC, advantage on Agility saves, +10 feet movement speed, and can take one additional action on each turn (Attack [one attack only], Dash, Disengage, Hide, or Use Object).",
		higher: "At 7th level, targets also gain advantage on Strength saves.",
		flavor: "All units: performance mode activated. Execute.",
		disc: "The energy cost is immense. Technomancers who cast this on a full raid party typically sleep for 16 hours afterward.",
		tags: ["technomancer", "haste", "buff", "area", "transmutation"],
	},
	{
		name: "Gate Fissure",
		lv: 5,
		sch: "Conjuration",
		cls: ["Summoner", "Mage"],
		ct: "1 action",
		rng: "120 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "6d6",
		dt: "force",
		save: "Agility",
		dc: 17,
		ePri: "Create a 60-foot line, 10-foot wide fissure.",
		eSec: "Creatures crossing take 6d6 force. Area is impassable terrain.",
		desc: "Tear a rift in local space-time creating a 60-foot long, 10-foot wide, 20-foot deep fissure. Creatures in the area when it opens must make a DC 17 Agility save or fall in, taking 6d6 force damage. The fissure is impassable terrain. Creatures can climb out with a DC 15 Athletics check.",
		higher:
			"At 7th level, length extends to 100 feet and damage increases to 8d6.",
		flavor: "The floor is no longer an assumption.",
		disc: "Bureau seismologists initially classified these events as micro-earthquakes until they noticed the perfectly straight fault lines.",
		tags: ["summoner", "mage", "conjuration", "terrain", "devastating"],
	},
	{
		name: "Restoration Chorus",
		lv: 5,
		sch: "Evocation",
		cls: ["Herald", "Idol"],
		ct: "1 bonus action",
		rng: "60 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Up to 6 creatures regain 3d8 + casting mod HP.",
		eSec: "Also removes one condition: poisoned, blinded, or deafened.",
		desc: "Broadcast a restorative harmonic across the mana-lattice, targeting up to 6 creatures within range. Each regains 3d8 + your spellcasting modifier HP. You can also purge one condition from each target: poisoned, blinded, or deafened.",
		higher: "Healing increases by 1d8 per level above 5th.",
		flavor: "Six notes. Six circuits repaired. She doesn't waste frequencies.",
		disc: "During the Osaka Incident, a Herald's Restoration Chorus kept a 12-person raid team operational through a 4-hour siege.",
		tags: ["herald", "idol", "healing", "mass", "bonus-action"],
	},
	{
		name: "Psionic Shockwave",
		lv: 5,
		sch: "Enchantment",
		cls: ["Esper"],
		ct: "1 action",
		rng: "Self (60-foot radius)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "8d6",
		dt: "psychic",
		save: "Presence",
		dc: 17,
		ePri: "8d6 psychic in 60-foot radius.",
		eSec: "Failed saves are stunned for 1 round.",
		desc: "Release a devastating omnidirectional burst of psychic energy. Each creature within 60 feet must make a DC 17 Presence save: 8d6 psychic damage and stunned until end of its next turn on failure, half damage on success. Allies are not exempt unless you exclude them (up to 5).",
		higher:
			"Damage increases by 1d6 per level above 5th. At 7th level, you can exclude up to 10 creatures.",
		flavor: "Every mind in range hears the same thing: silence.",
		disc: "Bureau psionic containment protocol was written specifically because of this spell.",
		tags: ["esper", "psychic", "area", "stun", "devastating"],
	},

	// ═══ LEVEL 6 ═══
	{
		name: "Arc Cascade",
		lv: 6,
		sch: "Evocation",
		cls: ["Mage", "Technomancer", "Esper"],
		ct: "1 action",
		rng: "150 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "10d8",
		dt: "lightning",
		save: "Agility",
		dc: 17,
		ePri: "10d8 lightning to primary target, arcs to 3 more for 5d8.",
		eSec: "Each arc jumps to a different nearby creature.",
		desc: "Discharge a mana-charged bolt at a creature within range. DC 17 Agility save: 10d8 lightning on failure, half on success. The bolt then arcs through the mana-lattice to up to 3 additional creatures within 30 feet of the first; each saves for 5d8.",
		higher: "One additional arc per level above 6th.",
		flavor: "Lightning doesn't strike twice. This does.",
		disc: "Bureau power infrastructure was redesigned after a Technomancer's Arc Cascade fed back into the municipal grid.",
		tags: [
			"mage",
			"technomancer",
			"esper",
			"lightning",
			"cascade",
			"multi-target",
		],
	},
	{
		name: "Entropy Field",
		lv: 6,
		sch: "Necromancy",
		cls: ["Revenant", "Contractor"],
		ct: "1 action",
		rng: "Self (40-foot radius)",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "6d6",
		dt: "necrotic",
		save: "Vitality",
		dc: 17,
		ePri: "6d6 necrotic per turn in 40-foot radius.",
		eSec: "All healing in the area is halved.",
		desc: "Generate a persistent field of accelerated entropy. Each hostile creature that starts its turn in the 40-foot radius must make a DC 17 Vitality save: 6d6 necrotic on failure, half on success. All healing effects within the area are halved for the duration.",
		higher:
			"At 8th level, damage increases to 8d6 and healing is fully suppressed.",
		flavor: "Nothing grows here. Nothing will for a while.",
		disc: "The long-term environmental impact of Entropy Fields is classified. Bureau ecologists are 'monitoring the situation.'",
		tags: [
			"revenant",
			"contractor",
			"necrotic",
			"area",
			"anti-healing",
			"sustained",
		],
	},
	{
		name: "Resonance Symphony",
		lv: 6,
		sch: "Enchantment",
		cls: ["Idol"],
		ct: "1 action",
		rng: "Self (90-foot radius)",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "All allies gain +3 to attack rolls, saves, and AC.",
		eSec: "Allies are immune to fear and charm.",
		desc: "Perform an overwhelming symphonic broadcast that empowers every ally within 90 feet. For the duration, allies gain +3 to attack rolls, saving throws, and AC, and are immune to being frightened or charmed. Enemies that start their turn in the area have disadvantage on attack rolls.",
		higher: "At 8th level, allies also gain resistance to all damage.",
		flavor: "Every instrument. Every voice. Every heart. In perfect sync.",
		disc: "Bureau combat analysts classify a field-deployed Resonance Symphony as a 'force multiplier equivalent to an additional S-Rank Hunter.'",
		tags: ["idol", "enchantment", "mass-buff", "devastating", "performance"],
	},
	{
		name: "Absolute Barrier",
		lv: 6,
		sch: "Abjuration",
		cls: ["Herald", "Holy Knight"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "All allies in range have resistance to all damage.",
		eSec: "Caster can't attack or cast offensive spells while maintaining.",
		desc: "Channel the full protective mandate of the Absolute. For the duration, all friendly creatures within 30 feet gain resistance to all damage. However, while concentrating on this spell, you cannot make attacks or cast damaging spells.",
		higher: "At 8th level, allies also gain advantage on all saving throws.",
		flavor: "Nothing gets through. The Absolute has spoken.",
		disc: "A Holy Knight maintained Absolute Barrier for 47 minutes during the Seoul Raid while the strike team eliminated the gate boss.",
		tags: ["herald", "holy-knight", "abjuration", "protection", "resistance"],
	},
	{
		name: "Disintegration Beam",
		lv: 6,
		sch: "Transmutation",
		cls: ["Mage", "Technomancer"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "ranged",
		abl: "Intelligence",
		dmg: "10d6+40",
		dt: "force",
		save: "Agility",
		dc: 17,
		ePri: "10d6+40 force damage on hit.",
		eSec: "Target reduced to 0 HP is disintegrated entirely.",
		desc: "Fire a thin green ray of annihilation at a creature within range. Make a ranged spell attack. On a hit, the target takes 10d6+40 force damage. If this reduces the target to 0 HP, it is completely disintegrated along with nonmagical items it carries.",
		higher: "Damage increases by 3d6 per level above 6th.",
		flavor: "One beam. One equation. Zero remainder.",
		disc: "Bureau hazmat protocols classify the residual dust as 'biologically inert.' The dust was once a B-Rank gate boss.",
		tags: ["mage", "technomancer", "force", "single-target", "lethal"],
	},
	{
		name: "Nightmare Pact",
		lv: 6,
		sch: "Illusion",
		cls: ["Contractor", "Esper"],
		ct: "1 action",
		rng: "120 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "6d10",
		dt: "psychic",
		save: "Presence",
		dc: 17,
		ePri: "6d10 psychic per turn on failed save.",
		eSec: "Target is paralyzed while affected.",
		desc: "Trap a creature's consciousness in a waking nightmare constructed by your patron. The target must make a DC 17 Presence save at the start of each of its turns: 6d10 psychic damage and paralyzed on failure. On success, the nightmare breaks and the spell ends.",
		higher: "At 8th level, the target has disadvantage on the first save.",
		flavor: "Close your eyes. It's worse when they're open.",
		disc: "Bureau psych teams report that targets retain fragments of the nightmare for weeks. Counseling is recommended.",
		tags: [
			"contractor",
			"esper",
			"psychic",
			"paralysis",
			"nightmare",
			"devastating",
		],
	},
	{
		name: "Gate Behemoth",
		lv: 6,
		sch: "Conjuration",
		cls: ["Summoner"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 hour",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Summon a Large CR 8 gate-creature.",
		eSec: "Behemoth acts on own initiative, obeys mental commands.",
		desc: "Tear open a major rift and summon a Large gate behemoth (AC 17, HP 100, multiattack: 2 slams at +8 for 2d10+5 bludgeoning). The behemoth acts on its own initiative and obeys your mental commands. It vanishes at 0 HP or when the spell ends.",
		higher: "At 8th level, summon a Huge CR 10 behemoth.",
		flavor: "Something large answers. Something larger than you expected.",
		disc: "Bureau gate-response teams designate summoned behemoths as 'allied contacts' on their tactical displays. The behemoths don't seem to mind.",
		tags: ["summoner", "conjuration", "summon", "behemoth", "sustained"],
	},
	{
		name: "Umbral Assassination",
		lv: 6,
		sch: "Illusion",
		cls: ["Assassin"],
		ct: "1 bonus action",
		rng: "Self",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Become invisible. First attack deals extra 8d6 damage.",
		eSec: "After attacking, immediately teleport 30 feet to a shadow.",
		desc: "Vanish into the umbral layer of mana-space. You are invisible for the duration. The first attack you make deals an extra 8d6 damage (your choice of type). After attacking, you immediately teleport up to 30 feet to a space in dim light or darkness.",
		higher:
			"At 8th level, you remain invisible after attacking if you end in darkness.",
		flavor: "The shadow moves. Once. That's all it takes.",
		disc: "Bureau surveillance footage shows a 0.7 second window between visibility and the kill. Most targets don't register the transition.",
		tags: ["assassin", "stealth", "invisibility", "burst", "teleport"],
	},
];
