// Level 2 Spells — 20 unique entries
module.exports = [
	{
		name: "Mana Seal",
		lv: 2,
		sch: "Abjuration",
		cls: ["Mage", "Technomancer"],
		ct: "1 action",
		rng: "Touch",
		dur: "Until dispelled",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Seal a door, container, or gate-breach point with hardened mana.",
		eSec: "DC to break through increases by 10. Caster passes freely.",
		desc: "Touch a closed entry point — a door, container, or minor gate fissure — and fuse it shut with crystallized mana. The seal is invisible but tangible, raising the DC to breach by 10. You and designated allies pass through unimpeded. The seal can be suppressed by a successful Circuit Interrupt for 10 minutes.",
		higher:
			"At 4th level, the seal sends a mana-pulse alert to you when tampered with.",
		flavor: "Sealed. Not with metal. With will.",
		disc: "Bureau containment teams layer Mana Seals on compromised gate perimeters. The current stacking record is eleven.",
		tags: ["mage", "technomancer", "utility", "containment"],
	},
	{
		name: "Triple Ignition",
		lv: 2,
		sch: "Evocation",
		cls: ["Mage", "Esper", "Contractor"],
		ct: "1 action",
		rng: "120 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "ranged",
		abl: "Intelligence",
		dmg: "6d6",
		dt: "fire",
		save: "",
		dc: 0,
		ePri: "Three thermal bolts, each dealing 2d6 fire damage.",
		eSec: "Bolts can target different creatures.",
		desc: "Compress mana into three superheated projectiles and launch them at targets within range. Make a ranged spell attack for each bolt. On a hit, each deals 2d6 fire damage. You can concentrate all bolts on one target or split them across multiple.",
		higher: "One additional bolt per level above 2nd.",
		flavor: "Three ignition points. Three scorch marks. Zero excuses.",
		disc: "Bureau damage assessors identify this by the triangular thermal scarring it leaves on gate-crystal walls.",
		tags: ["mage", "esper", "contractor", "fire", "multi-target"],
	},
	{
		name: "Oath Tether",
		lv: 2,
		sch: "Abjuration",
		cls: ["Herald", "Holy Knight"],
		ct: "1 action",
		rng: "Touch",
		dur: "1 hour",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Target gains +1 AC and +1 to saves.",
		eSec: "Caster absorbs identical damage from tethered ally.",
		desc: "Create a mana-oath tether between yourself and a willing creature. For the duration, the target gains +1 to AC and saving throws and resistance to all damage. However, each time the tethered ally takes damage, the Absolute routes an equal amount to your mana circuit.",
		higher: "At 4th level, you gain resistance to the routed damage.",
		flavor: "Half the weight. All the oath.",
		disc: "Holy Knights cast this only on those they would die for. The Bureau logs every tether activation.",
		tags: ["herald", "holy-knight", "protection", "oath", "tether"],
	},
	{
		name: "Misty Blink",
		lv: 2,
		sch: "Conjuration",
		cls: ["Esper", "Stalker", "Assassin"],
		ct: "1 bonus action",
		rng: "Self",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Teleport up to 60 feet to a space you can see.",
		eSec: "After teleporting, next attack has advantage if made this turn.",
		desc: "Dissolve into mana-mist and reform at an unoccupied space you can see within 60 feet. If you make an attack immediately after teleporting on the same turn, you have advantage on the attack roll.",
		higher:
			"At 4th level, you can bring one willing creature you touch along with you.",
		flavor: "She was there. Now she's here. Don't blink.",
		disc: "Bureau analysts measure the transit time at 0.003 seconds. The subjective experience is described as 'uncomfortable folding.'",
		tags: ["esper", "stalker", "assassin", "teleport", "mobility"],
	},
	{
		name: "Entropic Wave",
		lv: 2,
		sch: "Necromancy",
		cls: ["Revenant"],
		ct: "1 action",
		rng: "Self (30-foot cone)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "3d8",
		dt: "necrotic",
		save: "Vitality",
		dc: 14,
		ePri: "3d8 necrotic damage in 30-foot cone.",
		eSec: "Caster regains HP equal to highest single damage roll.",
		desc: "Release a wave of accelerated decay in a 30-foot cone. Each creature in the area must make a DC 14 Vitality save, taking 3d8 necrotic damage on failure (half on success). You regain HP equal to the highest single damage die rolled.",
		higher: "Damage increases by 1d8 per level above 2nd.",
		flavor: "Everything ends. She just reminds them.",
		disc: "The wave leaves no residue. Bureau forensics cannot determine what was damaged — only that something was.",
		tags: ["revenant", "necrotic", "area", "self-heal"],
	},
	{
		name: "Resonance Amplifier",
		lv: 2,
		sch: "Transmutation",
		cls: ["Idol", "Technomancer"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "All allies within 30 feet add 1d4 to attack rolls and saves.",
		eSec: "The caster's voice/signal carries clearly through environmental noise.",
		desc: "Broadcast an amplified harmonic field in a 30-foot radius. For the duration, each friendly creature in the area (including you) can add 1d4 to every attack roll and saving throw. Your voice or signal transmission carries clearly through any environmental noise within range.",
		higher: "At 4th level, the bonus also applies to ability checks.",
		flavor: "She turns up the volume. Everyone performs better.",
		disc: "Concert venues near gates report spontaneous Resonance Amplifier activation during emotional performances. Bureau monitors these events.",
		tags: ["idol", "technomancer", "buff", "area", "concentration"],
	},
	{
		name: "Oath Smite",
		lv: 2,
		sch: "Evocation",
		cls: ["Holy Knight"],
		ct: "1 bonus action",
		rng: "Self",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "radiant",
		save: "",
		dc: 0,
		ePri: "Next melee hit deals extra 3d8 radiant damage.",
		eSec: "Target must make DC 14 Presence save or be frightened of you for 1 minute.",
		desc: "Charge your weapon with the full weight of your oath. The next melee hit during the spell's duration deals an extra 3d8 radiant damage. The target must also make a DC 14 Presence save or be frightened of you for 1 minute (save ends).",
		higher: "Extra damage increases by 1d8 per level above 2nd.",
		flavor: "The oath has teeth. You're about to see them.",
		disc: "Footage from the Seoul Raid shows a Holy Knight's Oath Smite cleaving through a gate-boss's mana shield like paper.",
		tags: ["holy-knight", "radiant", "smite", "fear"],
	},
	{
		name: "Predator's Mark",
		lv: 2,
		sch: "Divination",
		cls: ["Stalker", "Assassin"],
		ct: "1 bonus action",
		rng: "90 feet",
		dur: "Concentration, up to 1 hour",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Advantage on Perception and Survival checks to track target.",
		eSec: "Target can't benefit from invisibility or half cover against you.",
		desc: "Lock your senses onto a creature you can see. For the duration, you have advantage on Perception and Survival checks to find and track the target. The target cannot benefit from invisibility or half cover against your attacks.",
		higher:
			"At 4th level, you also learn the target's current HP as a percentage.",
		flavor: "Prey doesn't choose. The predator does.",
		disc: "A Stalker held Predator's Mark on a gate boss for 47 minutes across three floors of a dungeon. The boss never escaped.",
		tags: ["stalker", "assassin", "tracking", "concentration"],
	},
	{
		name: "Psychic Barrier",
		lv: 2,
		sch: "Abjuration",
		cls: ["Esper"],
		ct: "1 reaction",
		rng: "Self",
		dur: "1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Resistance to psychic damage.",
		eSec: "Advantage on saves against charmed, frightened, and stunned.",
		desc: "As a reaction to taking psychic damage or being targeted by a charm/fear effect, erect a psionic barrier around your consciousness. For the duration, you have resistance to psychic damage and advantage on saves against being charmed, frightened, or stunned.",
		higher:
			"At 4th level, you can extend the barrier to one ally within 30 feet.",
		flavor: "You knock. Nobody's home.",
		disc: "Espers describe the barrier as 'a quiet room inside a screaming building.' It's considered essential training.",
		tags: ["esper", "psionic", "defense", "mental"],
	},
	{
		name: "Gate Snare",
		lv: 2,
		sch: "Conjuration",
		cls: ["Summoner"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "2d6",
		dt: "force",
		save: "Strength",
		dc: 14,
		ePri: "Restrain target on failed save.",
		eSec: "Restrained target takes 2d6 force at start of each turn.",
		desc: "Open micro-rifts around a creature that snap shut like jaws. The target must make a DC 14 Strength save or be restrained by spatial distortion for the duration, taking 2d6 force damage at the start of each of its turns. It can repeat the save at the end of each turn.",
		higher:
			"At 4th level, affects a 10-foot radius. At 6th level, damage increases to 3d6.",
		flavor: "Space folds around you. Good luck unfolding it.",
		disc: "Bureau spatial analysts confirm the snare creates brief pocket dimensions around the target's limbs. The physics are 'concerning.'",
		tags: ["summoner", "conjuration", "restraint", "force"],
	},
	{
		name: "Pact Chains",
		lv: 2,
		sch: "Conjuration",
		cls: ["Contractor"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "2d6",
		dt: "necrotic",
		save: "Strength",
		dc: 14,
		ePri: "Restrain target on failed save.",
		eSec: "Restrained target has disadvantage on ability checks.",
		desc: "Summon spectral chains inscribed with pact sigils that bind a creature within range. The target must make a DC 14 Strength save or be restrained and suffer disadvantage on ability checks for the duration. It takes 2d6 necrotic damage at the start of each of its turns while restrained.",
		higher:
			"At 4th level, you can chain a second creature within 10 feet of the first.",
		flavor: "The contract has a binding clause. This is it.",
		disc: "Each Contractor's chains bear different sigils matching their patron. Bureau occultists catalogue every variation.",
		tags: ["contractor", "pact", "restraint", "necrotic"],
	},
	{
		name: "Battlefield Harmony",
		lv: 2,
		sch: "Enchantment",
		cls: ["Idol", "Herald"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Up to 3 allies can use your reaction to add 1d6 to a failed save.",
		eSec: "Allies also gain 5 temp HP when first affected.",
		desc: "Weave a sustaining harmonic that links up to 3 willing creatures within range. For the duration, when a linked creature fails a saving throw, you can use your reaction to let it add 1d6 to the result, potentially changing the outcome. Each creature also gains 5 temp HP when first linked.",
		higher:
			"At 4th level, affects up to 5 creatures and the bonus becomes 1d8.",
		flavor: "Together. Louder. Stronger.",
		disc: "Raid leaders request Idols specifically for this spell. It has saved more lives than any healing spell in the Bureau record.",
		tags: ["idol", "herald", "support", "buff", "concentration"],
	},
	{
		name: "Mana Turret",
		lv: 2,
		sch: "Evocation",
		cls: ["Technomancer"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "ranged",
		abl: "Intelligence",
		dmg: "1d8",
		dt: "force",
		save: "",
		dc: 0,
		ePri: "Deploy a turret that attacks each turn for 1d8+INT force.",
		eSec: "Turret has 10 HP, AC 15, and occupies a 5-foot space.",
		desc: "Deploy a compact mana-powered turret at an unoccupied point within range. It has AC 15, 10 HP, and occupies a 5-foot space. On each of your turns, you can use a bonus action to command it to make a ranged spell attack (+INT) dealing 1d8+INT modifier force damage at a target within 60 feet.",
		higher:
			"At 4th level, turret HP increases to 20 and it fires twice per command.",
		flavor: "Point. Click. Repeat.",
		disc: "The original prototype was the size of a car. Current models fit in a backpack. Technomancer engineering moves fast.",
		tags: ["technomancer", "device", "summon", "sustained-damage"],
	},
	{
		name: "Hallowed Ground",
		lv: 2,
		sch: "Abjuration",
		cls: ["Herald"],
		ct: "1 action",
		rng: "Self (15-foot radius)",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "radiant",
		save: "",
		dc: 0,
		ePri: "Allies in area gain +2 to AC against undead and fiends.",
		eSec: "Undead entering the area take 1d6 radiant damage.",
		desc: "Consecrate a 15-foot radius centered on you with the Absolute's protective radiance. Allies within the area gain +2 to AC against attacks from undead and fiend-type anomalies. Undead that enter the area or start their turn there take 1d6 radiant damage.",
		higher:
			"At 4th level, the area also grants advantage on saves against necrotic damage.",
		flavor: "This ground is sacred. Act accordingly.",
		disc: "During the Gwangju Crisis, a Herald maintained Hallowed Ground for six hours while the evacuation completed. She collapsed after.",
		tags: ["herald", "radiant", "protection", "area", "anti-undead"],
	},
	{
		name: "Shadow Transit",
		lv: 2,
		sch: "Illusion",
		cls: ["Assassin"],
		ct: "1 bonus action",
		rng: "Self",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Teleport between shadows up to 60 feet apart.",
		eSec: "Advantage on first melee attack after teleporting.",
		desc: "Step into a shadow within 5 feet of you and emerge from a different shadow within 60 feet. Both locations must be in dim light or darkness. After teleporting, you have advantage on the first melee attack you make before the end of the turn.",
		higher:
			"At 4th level, range increases to 120 feet and you can bring one willing creature.",
		flavor: "Shadow to shadow. The space between doesn't exist.",
		disc: "Bureau security protocols now require full lighting in all hallways after three separate Assassin infiltrations went undetected.",
		tags: ["assassin", "teleport", "stealth", "shadow"],
	},
	{
		name: "Corrosive Aura",
		lv: 2,
		sch: "Transmutation",
		cls: ["Revenant", "Contractor"],
		ct: "1 action",
		rng: "Self (10-foot radius)",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "2d4",
		dt: "necrotic",
		save: "Vitality",
		dc: 14,
		ePri: "Creatures entering or starting turn in aura take 2d4 necrotic.",
		eSec: "Nonmagical objects in the area slowly corrode.",
		desc: "Emanate an aura of accelerated entropy in a 10-foot radius. Each creature that enters the area for the first time on a turn or starts its turn there must make a DC 14 Vitality save or take 2d4 necrotic damage. Nonmagical objects in the area visibly corrode over the duration.",
		higher:
			"Damage increases by 1d4 per level above 2nd. At 4th level, radius extends to 15 feet.",
		flavor: "She walks through the room. The room remembers.",
		disc: "Crime scene investigators can identify a Corrosive Aura's footprint by the pattern of material degradation.",
		tags: ["revenant", "contractor", "necrotic", "aura", "area"],
	},
	{
		name: "Rift-Companion Link",
		lv: 2,
		sch: "Divination",
		cls: ["Summoner", "Stalker"],
		ct: "1 action",
		rng: "Touch",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Telepathic mana-link with a gate-creature companion.",
		eSec: "Companion has advantage on attacks vs targets within 5 feet of you.",
		desc: "Form a mana-circuit bridge with a willing gate-creature companion you touch. For the duration, you share thoughts telepathically and can switch sensory perception to the companion's perspective as a bonus action. The linked creature has advantage on attack rolls against anything within 5 feet of you.",
		higher:
			"At 4th level, the link extends to 1 mile and the companion gains temporary HP equal to your level.",
		flavor: "Two circuits. One signal. One hunt.",
		disc: "A Summoner's gate-creature reportedly refused to engage until the link was established. Bureau ethologists call this 'mutual consent.'",
		tags: ["summoner", "stalker", "gate-creature", "telepathy", "companion"],
	},
	{
		name: "Kinetic Burst",
		lv: 2,
		sch: "Evocation",
		cls: ["Mage", "Esper"],
		ct: "1 action",
		rng: "Self (20-foot radius)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "3d6",
		dt: "force",
		save: "Strength",
		dc: 14,
		ePri: "3d6 force damage in 20-foot radius.",
		eSec: "All failed saves are pushed 10 feet away from you.",
		desc: "Release a spherical shockwave of concentrated kinetic mana centered on yourself. Each creature within 20 feet must make a DC 14 Strength save, taking 3d6 force damage and being pushed 10 feet away on failure. Half damage and no push on success.",
		higher: "Damage increases by 1d6 per level above 2nd.",
		flavor: "Personal space. Enforced.",
		disc: "Bureau containment teams keep this spell in reserve for 'oh no' moments. It has a 100% deployment success rate.",
		tags: ["mage", "esper", "force", "area", "push"],
	},
	{
		name: "Deploy Drone",
		lv: 2,
		sch: "Conjuration",
		cls: ["Technomancer"],
		ct: "1 action",
		rng: "30 feet",
		dur: "Concentration, up to 1 hour",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Deploy a small reconnaissance drone with 30 ft fly speed.",
		eSec: "See and hear through the drone. Can deliver Touch spells through it.",
		desc: "Deploy a Small mana-powered drone at a point within range. The drone has AC 12, 5 HP, 30 ft fly speed, and can hover. You can see and hear through the drone (bonus action to switch). You can deliver Touch-range spells through the drone as if you were in its space.",
		higher: "At 4th level, drone HP increases to 15 and gains 60 ft fly speed.",
		flavor: "Eyes in the sky. Your sky.",
		disc: "The drone model is designated 'MK-IV Scout.' MK-I through III are classified as 'learning experiences.'",
		tags: ["technomancer", "drone", "utility", "reconnaissance", "conjuration"],
	},
	{
		name: "Hymn of Courage",
		lv: 2,
		sch: "Enchantment",
		cls: ["Idol"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Allies in range are immune to being frightened.",
		eSec: "Already frightened allies can repeat their save immediately.",
		desc: "Begin a stirring vocal performance that radiates courage. For the duration, all friendly creatures within 30 feet are immune to being frightened. Any frightened ally that enters the area or is in the area when you cast this can immediately repeat the save to end the effect.",
		higher: "At 4th level, the hymn also grants immunity to being charmed.",
		flavor: "Fear is a frequency. She broadcasts a different one.",
		disc: "During a gate-break in Busan, an Idol's Hymn of Courage kept 200 civilians calm during evacuation. She received a commendation.",
		tags: ["idol", "enchantment", "morale", "area", "fear-immunity"],
	},
];
