// Extra Spells B — 20 entries, 100% RA-original mechanics (no D&D reskins)
module.exports = [
	{
		name: "Quarantine Membrane",
		lv: 3,
		sch: "Abjuration",
		cls: ["Herald", "Technomancer", "Mage"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Create a 20-foot dome that blocks anomaly-type creatures.",
		eSec: "Gate-anomalies can't enter; Awakened pass freely.",
		desc: "Project a shimmering dome of purified mana in a 20-foot radius. Gate-anomaly creatures cannot enter or pass through the barrier. Awakened creatures and mundane beings pass freely. Spells can cross the barrier normally.",
		higher:
			"At 5th level, dome also blocks mana-projectiles fired by anomalies.",
		flavor: "Inside is safe. Outside is their problem.",
		disc: "Bureau evacuation protocols center on Quarantine Membranes. Civilians inside, anomalies outside. Simple.",
	},
	{
		name: "Mana Detonation Charge",
		lv: 3,
		sch: "Evocation",
		cls: ["Technomancer", "Assassin"],
		ct: "1 action",
		rng: "Touch",
		dur: "8 hours",
		conc: false,
		atk: "",
		abl: "",
		dmg: "6d6",
		dt: "force",
		save: "Agility",
		dc: 15,
		ePri: "Plant a mana charge that detonates on trigger: 6d6 force in 15-foot radius.",
		eSec: "You choose the trigger: proximity, timer, or command word.",
		desc: "Compress mana into a volatile charge and affix it to a surface. You set the trigger: proximity (creature within 5 feet), timer (1 round to 8 hours), or command word (you speak it within 120 feet). When triggered: 6d6 force in a 15-foot radius, DC 15 AGI save for half.",
		higher:
			"Damage increases by 2d6 per level above 3rd. At 5th level, plant 2 charges per cast.",
		flavor: "She left a present. Don't touch it.",
		disc: "Bureau demolitions teams replaced traditional explosives with these. The cleanup is simpler — no shrapnel.",
	},
	{
		name: "Sympathetic Circuit",
		lv: 3,
		sch: "Transmutation",
		cls: ["Herald", "Holy Knight"],
		ct: "1 action",
		rng: "30 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Link up to 3 allies' mana circuits: damage taken is split equally.",
		eSec: "When one linked ally uses a healing spell, all linked allies heal for half.",
		desc: "Create a sympathetic resonance between up to 3 willing creatures' mana circuits. For the duration, when any linked creature takes damage, the total is divided equally among all linked creatures. When any linked creature receives magical healing, all others regain HP equal to half that healing.",
		higher: "At 5th level, link up to 5 creatures.",
		flavor: "Together, the weight is lighter. That's the oath.",
		disc: "Bureau raid teams with a Herald running Sympathetic Circuit have a 94% survival rate. Without it: 71%.",
	},
	{
		name: "Anomaly Mimicry",
		lv: 4,
		sch: "Illusion",
		cls: ["Summoner", "Contractor", "Revenant"],
		ct: "1 action",
		rng: "Self",
		dur: "Concentration, up to 1 hour",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Your mana signature mimics a gate-anomaly of CR equal to your level.",
		eSec: "Gate-anomalies treat you as one of their own. Awakened may be fooled (INT save).",
		desc: "Overwrite your mana-circuit's broadcast signature to mimic a gate-anomaly. You appear to be an anomaly of CR equal to your character level. Gate-anomalies treat you as one of their own (unless you attack them). Awakened creatures who observe you can make a DC 16 Intelligence save to see through the disguise.",
		higher:
			"At 6th level, you also gain the movement modes of the mimicked creature type.",
		flavor: "She walks among them. They don't look twice.",
		disc: "Bureau infiltration specialists use this for gate reconnaissance. The longest recorded sustained mimicry was 47 minutes inside an A-Rank gate.",
	},
	{
		name: "Unstable Rift Tear",
		lv: 4,
		sch: "Conjuration",
		cls: ["Mage", "Summoner"],
		ct: "1 action",
		rng: "120 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "4d8",
		dt: "force",
		save: "Agility",
		dc: 16,
		ePri: "Open a 10-foot rift that pulls creatures toward it and shreds them.",
		eSec: "Creatures within 30 feet are pulled 15 feet toward the rift each round.",
		desc: "Tear a 10-foot unstable dimensional rift at a point within range. At the start of each creature's turn within 30 feet, it's pulled 15 feet toward the rift (DC 16 Strength save to resist). Creatures entering the rift or starting their turn inside: DC 16 AGI save, 4d8 force on failure, half on success.",
		higher: "At 6th level, pull distance increases to 25 feet.",
		flavor: "The hole in reality is hungry.",
		disc: "Bureau analysts classify rifts as 'uncontrolled gate events.' This spell is a controlled uncontrolled gate event. The terminology bothers them.",
	},
	{
		name: "Ghost Protocol",
		lv: 4,
		sch: "Illusion",
		cls: ["Assassin", "Stalker", "Technomancer"],
		ct: "1 action",
		rng: "Self",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Erase your mana signature from all detection methods.",
		eSec: "You're invisible to mana-sight, Anomaly Scan, and divination. Physical senses still work.",
		desc: "Completely suppress your mana-circuit's broadcast signature. For the duration, you are undetectable by any mana-based detection (divination spells, mana-sight, Anomaly Scan, gate-creature tremorsense). You remain visible to normal senses.",
		higher: "At 6th level, you can also suppress one ally's signature.",
		flavor: "On paper, she doesn't exist. On the lattice, she never did.",
		disc: "Bureau counterintelligence developed this for deep-cover operations. The irony of a mana-powered spell that hides mana is not lost on anyone.",
	},
	{
		name: "Pact Renegotiation",
		lv: 5,
		sch: "Enchantment",
		cls: ["Contractor"],
		ct: "1 action",
		rng: "Self",
		dur: "1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Temporarily upgrade your patron pact: all pact abilities deal +2d6 damage.",
		eSec: "Pact spells cost 1 fewer slot level (min 1). Patron demands a favour afterward.",
		desc: "Force-renegotiate the terms of your patron pact for 1 minute, drawing more power than originally agreed. All pact-granted abilities deal +2d6 damage of your pact's damage type, and pact spells cost 1 fewer slot level (minimum 1). After the spell ends, your patron extracts a favour (Warden determines the cost).",
		higher: "At 7th level, bonus damage increases to +3d8.",
		flavor:
			"The patron agrees to new terms. Temporarily. The interest rate is steep.",
		disc: "Bureau pact oversight warns against this spell. Every Contractor who uses it reports their patron 'seemed pleased.' That's never good.",
	},
	{
		name: "Mana Cascade Failure",
		lv: 5,
		sch: "Evocation",
		cls: ["Mage", "Technomancer", "Esper"],
		ct: "1 action",
		rng: "90 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "8d6",
		dt: "force",
		save: "Intelligence",
		dc: 17,
		ePri: "8d6 force damage; target loses its highest remaining spell slot.",
		eSec: "If target has no spell slots, it's stunned for 1 round instead.",
		desc: "Trigger a catastrophic feedback cascade in a creature's mana circuit. DC 17 Intelligence save: 8d6 force on failure and the target loses its highest remaining spell slot. If the target has no mana-casting ability, it's stunned until the end of its next turn instead.",
		higher: "Damage increases by 1d6 per level above 5th.",
		flavor: "Her circuit overloaded. Not accidentally.",
		disc: "Bureau anti-mage doctrine centers on this spell. Stripping enemy resources wins wars.",
	},
	{
		name: "Gate-Layer Overlap",
		lv: 6,
		sch: "Conjuration",
		cls: ["Summoner", "Mage"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Overlap the material plane with the gate-dimension in a 30-foot radius.",
		eSec: "Gate-anomaly traits activate for Summoners; terrain becomes difficult for non-Awakened.",
		desc: "Force the local gate-dimensional layer to overlap with the material plane. Within 30 feet: the terrain warps (difficult terrain for non-Awakened), gravity fluctuates (ranged attacks have disadvantage), and Summoner-class creatures gain +2 AC and advantage on saves. Gate-anomalies in the area become confused (50% chance of attacking nearest creature instead of intended target).",
		higher: "At 8th level, radius extends to 60 feet.",
		flavor: "Two dimensions. Same space. Same time. Different rules.",
		disc: "Bureau dimensional analysts rank this as a 'Category 4 dimensional event.' It's the only one that's intentional.",
	},
	{
		name: "Echo Split",
		lv: 6,
		sch: "Illusion",
		cls: ["Assassin", "Esper", "Idol"],
		ct: "1 action",
		rng: "Self",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Create a perfect mana-echo of yourself that acts independently.",
		eSec: "Echo has your stats but half HP. Both can attack. You choose which is 'real' each round.",
		desc: "Split your mana-circuit output into two bodies: yourself and a perfect echo. The echo has your stats but half your current HP. It acts on your initiative and can take all normal actions. At the start of each turn, you choose which body is 'you' — the other is the echo. If either body drops to 0 HP, it vanishes and the spell ends.",
		higher: "At 8th level, the echo has full HP.",
		flavor: "Two of her. Which one do you aim at?",
		disc: "Bureau tactical analysts confirmed that an Assassin with Echo Split active has a 200% engagement efficiency increase. The math is straightforward.",
	},
	{
		name: "Absolute Mandate",
		lv: 7,
		sch: "Enchantment",
		cls: ["Herald", "Holy Knight"],
		ct: "1 action",
		rng: "Self (60-foot radius)",
		dur: "1 round",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "Presence",
		dc: 18,
		ePri: "All hostile creatures in range must obey one simple command.",
		eSec: "Commands: drop weapons, kneel, flee, or freeze. One round only.",
		desc: "Channel the Absolute's authority through the mana-lattice as an irrefutable command. All hostile creatures within 60 feet: DC 18 Presence save. On failure, they must obey one simple command: drop weapons, kneel, flee, or freeze. The effect lasts 1 round.",
		higher: "At 9th level, the command lasts 2 rounds.",
		flavor: "The Absolute speaks through her. Everyone listens.",
		disc: "Bureau records show three Absolute Mandates issued during S-Rank gate-boss encounters. All three bosses knelt.",
	},
	{
		name: "Resonance Overwrite",
		lv: 7,
		sch: "Transmutation",
		cls: ["Technomancer", "Esper"],
		ct: "1 action",
		rng: "Touch",
		dur: "1 hour",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Permanently modify one of the target's mana-circuit properties.",
		eSec: "Grant resistance to one damage type, or change one saving throw proficiency.",
		desc: "Rewrite a willing creature's mana-circuit at the fundamental level. Choose one: grant resistance to a damage type, change one saving throw proficiency to a different ability score, or add proficiency in one skill. The change lasts for 1 hour.",
		higher: "At 9th level, duration extends to 24 hours.",
		flavor: "She rewrites what you are. Temporarily. But it feels permanent.",
		disc: "Bureau medical teams use this to prepare Hunters for specific gate environments. Tailored resistance saves lives.",
	},
	{
		name: "Circuit Annihilation Wave",
		lv: 8,
		sch: "Evocation",
		cls: ["Mage", "Esper"],
		ct: "1 action",
		rng: "Self (60-foot cone)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "12d8",
		dt: "force",
		save: "Vitality",
		dc: 19,
		ePri: "12d8 force in 60-foot cone. All active spells on targets are dispelled.",
		eSec: "Mana-items carried by affected creatures are suppressed for 1 minute.",
		desc: "Unleash a purging wave of raw mana that annihilates all magical activity in a 60-foot cone. DC 19 Vitality save: 12d8 force on failure, half on success. All active spell effects on creatures in the area are immediately dispelled. Magical items carried by affected creatures are suppressed for 1 minute.",
		higher: "",
		flavor: "Everything in that direction stops being magic.",
		disc: "Bureau anti-mage doctrine lists this as 'escalation tier 3.' It's the mana equivalent of a tactical strike.",
	},
	{
		name: "Dimensional Lockdown",
		lv: 8,
		sch: "Abjuration",
		cls: ["Herald", "Mage", "Technomancer"],
		ct: "1 action",
		rng: "Self (1-mile radius)",
		dur: "24 hours",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "No gates can open, no portals can form, no dimensional travel works within 1 mile.",
		eSec: "Existing gates are suppressed for the duration.",
		desc: "Anchor the dimensional fabric within a 1-mile radius with overwhelming stabilizing force. For 24 hours: no new gates can open, no portals can form, all dimensional travel fails, and existing gates are suppressed. This spell requires 10 minutes of preparation and a mana-crystal worth 1000 GP.",
		higher: "",
		flavor:
			"This mile of reality stays closed. For twenty-four hours. No exceptions.",
		disc: "Bureau gate-breach protocol: if a gate can't be entered, it can be locked. Four confirmed deployments. All successful.",
	},
	{
		name: "Mana Circuit Genesis",
		lv: 9,
		sch: "Transmutation",
		cls: ["Herald", "Mage"],
		ct: "8 hours",
		rng: "Touch",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Permanently awaken a mundane creature's latent mana circuit.",
		eSec: "Target becomes an Awakened with one level in any caster job.",
		desc: "The ultimate act of creation: force-awaken a latent mana circuit in a mundane creature. After 8 hours of sustained mana infusion, the target permanently becomes an Awakened with one level in a caster job of your choosing. The target retains all existing abilities and gains spellcasting. This spell can only be cast once per year.",
		higher: "",
		flavor: "She makes Hunters. From nothing. From anyone.",
		disc: "Bureau Director classification: ABSOLUTE SECRET. Two confirmed castings. Both recipients are currently S-Rank. The implications are 'world-changing.'",
	},
];
