// Extra Spells A — 20 entries, 100% RA-original mechanics (no D&D reskins)
module.exports = [
	{
		name: "Gate Resonance Spike",
		lv: 1,
		sch: "Evocation",
		cls: ["Mage", "Technomancer"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "ranged",
		abl: "Intelligence",
		dmg: "2d8",
		dt: "force",
		save: "",
		dc: 0,
		ePri: "2d8 force; extra 1d8 if target is a gate-anomaly.",
		eSec: "Leaves a traceable mana-signature on the target for 1 minute.",
		desc: "Fire a pulse calibrated to gate-frequency mana. On hit: 2d8 force damage (3d8 against gate-anomalies). The impact leaves a traceable mana-signature on the target for 1 minute, granting advantage on Stalker tracking checks against it.",
		higher: "Damage increases by 1d8 per level above 1st.",
		flavor: "The pulse knows what came through a Gate. It hits harder.",
		disc: "Bureau R&D designed this specifically for gate-breach first response. The tracking signature was an accident they kept.",
	},
	{
		name: "Lattice Feedback Loop",
		lv: 1,
		sch: "Abjuration",
		cls: ["Herald", "Technomancer"],
		ct: "1 reaction",
		rng: "Self",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "1d6",
		dt: "force",
		save: "",
		dc: 0,
		ePri: "When hit by a spell, reduce damage by 1d6+INT and reflect remainder as force.",
		eSec: "If reflected damage exceeds 10, caster must make VIT save or lose concentration.",
		desc: "When struck by a spell, route incoming mana through your circuit's feedback buffer. Reduce damage taken by 1d6+Intelligence modifier. If you reduce more than 10 damage, the original caster must make a DC 13 Vitality save or lose concentration.",
		higher: "Reduction increases by 1d6 per level above 1st.",
		flavor: "Her circuit doesn't just absorb. It argues back.",
		disc: "A Technomancer accidentally discovered this by miscalibrating a mana-dampener. The dampener broke. She didn't.",
	},
	{
		name: "Mana Thread Snare",
		lv: 1,
		sch: "Conjuration",
		cls: ["Stalker", "Assassin"],
		ct: "1 bonus action",
		rng: "30 feet",
		dur: "1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "Agility",
		dc: 13,
		ePri: "Invisible mana-thread connects you to the target.",
		eSec: "You always know target's location; it can't benefit from invisibility against you.",
		desc: "Launch an invisible mana-filament that bonds to a creature within range. DC 13 Agility save to avoid. While connected, you always know the target's exact position — it cannot benefit from invisibility, cover, or concealment against you. The thread breaks if the target moves more than 120 feet away.",
		higher:
			"At 3rd level, the thread also reveals the target's current HP percentage.",
		flavor: "Run. The thread follows.",
		disc: "Bureau pursuit teams deploy this before engaging fleeing anomalies. The thread has never been outrun.",
	},
	{
		name: "Awakening Surge",
		lv: 2,
		sch: "Transmutation",
		cls: ["Herald", "Idol", "Esper"],
		ct: "1 action",
		rng: "Touch",
		dur: "1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Target's mana circuit overclocks: +2 to one ability score.",
		eSec: "When the spell ends, target gains 1 level of exhaustion.",
		desc: "Touch a willing creature and force-awaken dormant capacity in their mana circuit. For the duration, one ability score of your choice increases by 2 (max 22). When the spell ends, the target gains 1 level of exhaustion as the circuit cools.",
		higher: "At 4th level, boost two ability scores simultaneously.",
		flavor: "More than you are. For sixty seconds. Then the bill comes due.",
		disc: "Bureau combat medics use this in emergencies only. The exhaustion trade-off limits casual deployment.",
	},
	{
		name: "Rift Echo",
		lv: 2,
		sch: "Divination",
		cls: ["Summoner", "Stalker", "Mage"],
		ct: "1 action",
		rng: "Self (60-foot radius)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Map all gate-anomalies, traps, and hidden passages within 60 feet.",
		eSec: "Also reveals the gate-floor's dimensional stability rating.",
		desc: "Emit a low-frequency mana pulse that bounces off gate-dimensional boundaries. You instantly learn the location of all anomalies, traps, concealed passages, and dimensional weak points within 60 feet. You also learn the local dimensional stability rating (stable, unstable, collapsing).",
		higher:
			"At 4th level, range extends to 120 feet and reveals anomaly types.",
		flavor: "She pings the rift. The rift pings back.",
		disc: "Every Bureau gate-team leader casts this upon entering a new floor. The stability rating has saved more lives than any combat spell.",
	},
	{
		name: "Circuit Overload",
		lv: 2,
		sch: "Evocation",
		cls: ["Technomancer", "Esper"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "3d8",
		dt: "lightning",
		save: "Intelligence",
		dc: 14,
		ePri: "3d8 lightning; target's next spell costs an additional slot level.",
		eSec: "Constructs and mana-devices take double damage.",
		desc: "Target a creature's mana circuit and inject a destabilizing charge. DC 14 Intelligence save: 3d8 lightning on failure and the target's next spell within 1 minute costs one additional slot level (a 3rd-level spell requires a 4th-level slot). Constructs and mana-devices take double damage.",
		higher: "Damage increases by 1d8 per level above 2nd.",
		flavor: "Your circuit just got expensive.",
		disc: "Bureau anti-mage countermeasures rely heavily on this. Making enemy spells more costly wins battles of attrition.",
	},
	{
		name: "Patron's Witness",
		lv: 2,
		sch: "Divination",
		cls: ["Contractor"],
		ct: "1 action",
		rng: "Self",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "See through your patron's senses in a 1-mile radius.",
		eSec: "Patron can communicate warnings: advantage on initiative and perception.",
		desc: "Open a two-way sensory channel with your patron entity. For the duration, you can perceive through your patron's awareness within a 1-mile radius, granting you advantage on Perception checks and initiative rolls. Your patron may offer cryptic tactical observations.",
		higher: "At 4th level, your patron grants you tremorsense 30 feet.",
		flavor: "Your patron watches everything. Now you watch through their eyes.",
		disc: "Bureau psych evaluations note that Contractors who use this frequently develop 'shared personality traits' with their patrons.",
	},
	{
		name: "Mana Siphon Strike",
		lv: 3,
		sch: "Necromancy",
		cls: ["Revenant", "Assassin"],
		ct: "1 action",
		rng: "Touch",
		dur: "Instantaneous",
		conc: false,
		atk: "melee",
		abl: "Intelligence",
		dmg: "5d8",
		dt: "necrotic",
		save: "",
		dc: 0,
		ePri: "5d8 necrotic on hit; you regain HP equal to half damage dealt.",
		eSec: "If target is a spellcaster, you also recover one expended spell slot (max 3rd level).",
		desc: "Channel entropic mana through a melee strike. On hit: 5d8 necrotic damage. You regain HP equal to half the damage dealt. If the target has mana-casting ability, you also recover one expended spell slot of 3rd level or lower.",
		higher:
			"Damage increases by 1d8 per level above 3rd. Max recovered slot increases by 1 per 2 levels.",
		flavor:
			"She takes what your circuit doesn't need anymore. And some of what it does.",
		disc: "The Bureau classifies this as 'field resupply.' Revenants classify it as 'lunch.'",
	},
	{
		name: "Gate Anchor",
		lv: 3,
		sch: "Abjuration",
		cls: ["Mage", "Herald", "Technomancer"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Prevent all teleportation, summoning, and dimensional travel within 30 feet.",
		eSec: "Gate-anomalies in the area can't phase or shift planes.",
		desc: "Anchor the local mana-lattice to prevent dimensional manipulation. Within a 30-foot radius: no creature can teleport, be summoned, or use dimensional travel. Gate-anomalies cannot phase between dimensional layers. Existing teleportation effects are suppressed.",
		higher: "At 5th level, radius extends to 60 feet.",
		flavor: "Nobody leaves. Nobody arrives. This space is locked.",
		disc: "Bureau containment teams cast this immediately upon gate-breach detection. It's the difference between a breach and a catastrophe.",
	},
	{
		name: "Idol's Crescendo",
		lv: 3,
		sch: "Enchantment",
		cls: ["Idol"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "4d8",
		dt: "thunder",
		save: "Presence",
		dc: 15,
		ePri: "4d8 thunder to enemies; allies gain temp HP equal to damage dealt to nearest enemy.",
		eSec: "Creatures that fail the save are charmed for 1 round.",
		desc: "Build mana-resonance to a peak and release in a devastating harmonic burst. Enemies within 30 feet: DC 15 Presence save, 4d8 thunder on failure (half on success), charmed for 1 round on failure. Each ally in the area gains temporary HP equal to the damage dealt to the nearest enemy.",
		higher: "Damage increases by 1d8 per level above 3rd.",
		flavor: "The chorus hits. The audience decides whose side they're on.",
		disc: "Bureau event coordinators banned Idol combat performances at guild celebrations after the third 'accidental crescendo.'",
	},
	{
		name: "Dimensional Pocket",
		lv: 4,
		sch: "Conjuration",
		cls: ["Mage", "Technomancer", "Summoner"],
		ct: "1 action",
		rng: "Self",
		dur: "1 hour",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Create a 64-cubic-foot extradimensional space accessible from your palm.",
		eSec: "Objects placed inside have no weight. Space collapses if you die.",
		desc: "Open a stable extradimensional pocket anchored to your mana circuit. The space is 4x4x4 feet and accessible through a shimmering portal in your palm. Objects placed inside have no weight to you. The pocket collapses harmlessly (ejecting contents) if you fall unconscious or die.",
		higher: "At 6th level, pocket expands to 8x8x8 feet and lasts 8 hours.",
		flavor:
			"She puts the gate boss's head in her pocket. The pocket is bigger than it looks.",
		disc: "Bureau logistics teams use these for field supply transport. The weight savings are 'operationally significant.'",
	},
	{
		name: "Mana Circuit Splice",
		lv: 4,
		sch: "Transmutation",
		cls: ["Technomancer", "Herald"],
		ct: "1 action",
		rng: "Touch",
		dur: "1 hour",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Temporarily grant a non-caster one spell slot (up to 3rd level).",
		eSec: "The recipient can cast any spell they've observed cast in the last 24 hours.",
		desc: "Splice a temporary mana pathway into a willing creature's circuit, granting it one spell slot of 3rd level or lower. The recipient can use this slot to cast any spell it has directly observed being cast within the last 24 hours, using your spellcasting modifier.",
		higher: "At 6th level, grants a slot up to 5th level.",
		flavor:
			"She gives mana to those who don't have it. Temporarily. Generously. Once.",
		disc: "Bureau training programs use this to let mundane soldiers experience casting. Most describe it as 'addictive.'",
	},
	{
		name: "Anomaly Cage",
		lv: 4,
		sch: "Abjuration",
		cls: ["Herald", "Stalker", "Summoner"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "2d8",
		dt: "radiant",
		save: "Presence",
		dc: 16,
		ePri: "Trap a gate-anomaly in a shrinking mana cage.",
		eSec: "Each round, cage shrinks and deals 2d8 radiant. Target must save each round to escape.",
		desc: "Construct a cage of interlocking mana-barriers around a gate-type creature. DC 16 Presence save each round or remain trapped; the cage shrinks each round, dealing 2d8 radiant that increases by 1d8 per round. On a successful save, the creature breaks free.",
		higher: "At 6th level, initial damage increases to 4d8.",
		flavor: "The cage gets smaller. The anomaly gets quieter.",
		disc: "Bureau containment protocol for live-capture missions. The escalating damage is 'motivational for cooperation.'",
	},
	{
		name: "Rift Walk",
		lv: 5,
		sch: "Conjuration",
		cls: ["Assassin", "Stalker", "Mage"],
		ct: "1 bonus action",
		rng: "Self",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Step between the material plane and the gate-layer as a bonus action.",
		eSec: "While in gate-layer: invisible and can move through objects. Can't attack from gate-layer.",
		desc: "Phase between the material plane and the adjacent gate-dimensional layer. As a bonus action each turn, you can shift layers. While in the gate-layer, you are invisible and incorporeal (can move through objects and creatures). You can't attack or cast offensive spells from the gate-layer. Shifting back ends the invisibility.",
		higher:
			"At 7th level, you can make one attack during the shift without fully materializing.",
		flavor: "She steps sideways. Into somewhere else. Then back.",
		disc: "Bureau dimensional analysts confirmed this spell operates on the same frequency as natural gate boundaries. It's walking through a wall that isn't there yet.",
	},
	{
		name: "Bureau Authority Override",
		lv: 5,
		sch: "Enchantment",
		cls: ["Herald", "Holy Knight", "Idol"],
		ct: "1 action",
		rng: "Self (60-foot radius)",
		dur: "1 round",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "Presence",
		dc: 17,
		ePri: "All hostile creatures in range must use their reaction to move toward you.",
		eSec: "Affected creatures have disadvantage on attacks against anyone other than you.",
		desc: "Project an overwhelming aura of Bureau-sanctioned command authority through the mana-lattice. All hostile creatures within 60 feet: DC 17 Presence save. On failure, they must use their reaction to move toward you and have disadvantage on attacks against anyone other than you until the start of your next turn.",
		higher:
			"At 7th level, also grants you resistance to all damage until your next turn.",
		flavor: "Eyes on me. All of you. That's an order.",
		disc: "The Bureau's official position is that this spell 'represents legitimate tactical authority.' Hunters call it 'aggro.'",
	},
	{
		name: "Mana Storm Nexus",
		lv: 6,
		sch: "Evocation",
		cls: ["Mage", "Esper"],
		ct: "1 action",
		rng: "120 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "4d10",
		dt: "force",
		save: "Agility",
		dc: 17,
		ePri: "Create a 20-foot nexus that deals 4d10 force/round to creatures inside.",
		eSec: "Nexus pulls creatures 10 feet toward center at start of their turn.",
		desc: "Detonate a mana-instability at a point within range, creating a swirling 20-foot radius nexus of raw mana-force. Creatures starting their turn in the area are pulled 10 feet toward the center and must make a DC 17 Agility save: 4d10 force on failure, half on success. You can move the nexus 30 feet as a bonus action.",
		higher: "At 8th level, radius increases to 30 feet and damage to 6d10.",
		flavor: "The nexus doesn't care about your plans. It has its own gravity.",
		disc: "Bureau combat analysts classify a deployed Mana Storm Nexus as an 'area denial weapon.' Everything inside disagrees with being inside.",
	},
	{
		name: "Lattice Severance",
		lv: 7,
		sch: "Abjuration",
		cls: ["Mage", "Technomancer"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "Intelligence",
		dc: 18,
		ePri: "Sever a creature's connection to the mana-lattice.",
		eSec: "Target can't cast spells, use mana abilities, or benefit from magic items.",
		desc: "Isolate a creature's mana circuit from the ambient lattice. DC 18 Intelligence save. On failure, the target is severed: it can't cast spells, use any mana-based ability, or benefit from magical items for the duration. It can repeat the save at the end of each turn.",
		higher:
			"At 9th level, the target also loses resistance to non-magical damage.",
		flavor: "Disconnected. Welcome to what mundane feels like.",
		disc: "Bureau anti-Hunter protocols include this as the primary tool against rogue Awakened. It's the mana equivalent of cutting the power.",
	},
	{
		name: "Gate Collapse",
		lv: 8,
		sch: "Conjuration",
		cls: ["Summoner", "Mage"],
		ct: "1 action",
		rng: "120 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "12d10",
		dt: "force",
		save: "Agility",
		dc: 19,
		ePri: "Collapse a 40-foot radius pocket of space-time: 12d10 force.",
		eSec: "All active gates, portals, and teleportation effects in the area are destroyed.",
		desc: "Trigger a controlled collapse of local space-time in a 40-foot radius. DC 19 Agility save: 12d10 force on failure, half on success. All active gates, portals, summoning effects, and dimensional anchors within the area are permanently destroyed. The collapsed zone is difficult terrain for 24 hours.",
		higher: "",
		flavor: "Space folds. Then it unfolds. Nothing in between survives.",
		disc: "Bureau records list four Gate Collapse castings. Each one sealed an active S-Rank gate-breach. The collateral damage reports are 'voluminous.'",
	},
	{
		name: "S-Rank Awakening",
		lv: 9,
		sch: "Transmutation",
		cls: ["Mage", "Esper", "Herald"],
		ct: "1 action",
		rng: "Self",
		dur: "1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "All ability scores become 25. Gain 100 temp HP. Immune to conditions.",
		eSec: "When spell ends, gain 5 levels of exhaustion.",
		desc: "Force your mana circuit past every safety limiter simultaneously. For 1 minute: all ability scores become 25, you gain 100 temporary HP, you're immune to all conditions, your speed doubles, and you gain an extra action each turn. When the spell ends, you gain 5 levels of exhaustion.",
		higher: "",
		flavor: "S-Rank. For sixty seconds. The price is everything after.",
		disc: "Bureau records contain one confirmed S-Rank Awakening. The Hunter survived. Barely. She didn't cast for six months.",
	},
	{
		name: "Absolute Severance",
		lv: 9,
		sch: "Necromancy",
		cls: ["Revenant", "Contractor"],
		ct: "1 action",
		rng: "Touch",
		dur: "Instantaneous",
		conc: false,
		atk: "melee",
		abl: "Intelligence",
		dmg: "14d8",
		dt: "necrotic",
		save: "Vitality",
		dc: 20,
		ePri: "14d8 necrotic on hit. Target's max HP is reduced by the damage dealt.",
		eSec: "If max HP reaches 0, target's mana circuit is permanently destroyed.",
		desc: "Channel the full entropy of your mana circuit into a single devastating touch. Melee spell attack: 14d8 necrotic. The target's HP maximum is reduced by the damage dealt (no save). If maximum HP reaches 0, the creature's mana circuit is permanently annihilated — it cannot be revived by any means short of an Absolute Edict.",
		higher: "",
		flavor: "She touches you once. Your mana circuit doesn't exist anymore.",
		disc: "Bureau classified. Three known instances. All targets were S-Rank gate-anomalies. All three are confirmed permanently terminated.",
	},
];
