// Level 3-4 Spells — 25 unique entries
module.exports = [
	// ═══ LEVEL 3 ═══
	{
		name: "Mana Barrage",
		lv: 3,
		sch: "Evocation",
		cls: ["Mage", "Technomancer"],
		ct: "1 action",
		rng: "150 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "8d6",
		dt: "fire",
		save: "Agility",
		dc: 15,
		ePri: "8d6 fire damage in 20-foot radius.",
		eSec: "Ignites flammable objects not worn or carried.",
		desc: "Saturate a 20-foot radius sphere centered on a point within range with concentrated thermal mana. Each creature in the area makes a DC 15 Agility save, taking 8d6 fire damage on failure (half on success). Flammable objects not being worn or carried ignite.",
		higher: "Damage increases by 1d6 per level above 3rd.",
		flavor: "The Bureau calls it 'area denial.' The targets call it nothing.",
		disc: "Standard Bureau clearance doctrine: Mana Barrage first, ask questions about the crater later.",
		tags: ["mage", "technomancer", "fire", "area", "devastation"],
	},
	{
		name: "Revenant's Embrace",
		lv: 3,
		sch: "Necromancy",
		cls: ["Revenant"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "5d6",
		dt: "necrotic",
		save: "Vitality",
		dc: 15,
		ePri: "5d6 necrotic damage, caster heals for half total dealt.",
		eSec: "Killed creatures can't be raised as undead for 24 hours.",
		desc: "Release a pulse of entropic hunger in a 30-foot radius. Each creature must make a DC 15 Vitality save: 5d6 necrotic on failure, half on success. You regain HP equal to half the total damage dealt across all targets. Creatures killed by this spell cannot be raised for 24 hours.",
		higher: "Damage increases by 1d6 per level above 3rd.",
		flavor: "She breathes in. Everything else breathes out.",
		disc: "Bureau necromantic containment teams carry anti-entropy wards specifically for this spell.",
		tags: ["revenant", "necrotic", "area", "self-heal", "anti-undead"],
	},
	{
		name: "Pact Hunger",
		lv: 3,
		sch: "Enchantment",
		cls: ["Contractor"],
		ct: "1 action",
		rng: "90 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "4d8",
		dt: "psychic",
		save: "Presence",
		dc: 15,
		ePri: "4d8 psychic + frightened on failed save.",
		eSec: "Frightened target must use its movement to flee.",
		desc: "Channel your patron's dread presence through your voice. A creature within range must make a DC 15 Presence save. On failure: 4d8 psychic damage and frightened for the duration. While frightened, the target must use its movement to move away from you. Save at end of each turn.",
		higher:
			"At 5th level, affects up to 3 creatures within 10 feet of each other.",
		flavor: "Your patron is hungry. It's looking at them.",
		disc: "Targets describe hearing a voice that isn't the Contractor's. Bureau psych evaluations are mandatory after exposure.",
		tags: ["contractor", "pact", "fear", "psychic", "control"],
	},
	{
		name: "Harmonic Barrage",
		lv: 3,
		sch: "Evocation",
		cls: ["Idol", "Esper"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "5d6",
		dt: "thunder",
		save: "Vitality",
		dc: 15,
		ePri: "5d6 thunder damage in a line.",
		eSec: "Failed saves are also deafened for 1 round.",
		desc: "Project a devastating sonic lance in a 60-foot line, 5 feet wide. Each creature in the line must make a DC 15 Vitality save: 5d6 thunder damage and deafened for 1 round on failure, half damage on success.",
		higher:
			"Damage increases by 1d6 per level above 3rd. At 5th level, line width increases to 10 feet.",
		flavor: "She hit a note that walls couldn't handle.",
		disc: "Structural engineers ban this spell within 50 feet of load-bearing columns. Idols rarely comply.",
		tags: ["idol", "esper", "thunder", "line", "area"],
	},
	{
		name: "Phase Strike",
		lv: 3,
		sch: "Conjuration",
		cls: ["Assassin", "Stalker"],
		ct: "1 bonus action",
		rng: "Self",
		dur: "1 round",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "force",
		save: "",
		dc: 0,
		ePri: "Next weapon attack teleports you adjacent to target first.",
		eSec: "Attack deals extra 3d8 force damage.",
		desc: "Phase through mana-space to deliver a devastating strike. As a bonus action, mark a creature within 60 feet. Before the end of your next turn, when you make a weapon attack against the marked creature, you teleport to an unoccupied space within 5 feet of it first. The attack deals an extra 3d8 force damage.",
		higher: "Extra damage increases by 1d8 per level above 3rd.",
		flavor: "Distance is a suggestion. You just declined.",
		disc: "The Assassin who perfected this technique reportedly said 'running is for people who haven't Awakened.'",
		tags: ["assassin", "stalker", "teleport", "strike", "force"],
	},
	{
		name: "Absolute Beacon",
		lv: 3,
		sch: "Evocation",
		cls: ["Herald", "Holy Knight"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "radiant",
		save: "",
		dc: 0,
		ePri: "Allies in range gain +2 to attack rolls and saves vs undead/fiends.",
		eSec: "Undead/fiends in range have disadvantage on attack rolls.",
		desc: "Radiate the Absolute's protective light. For the duration, allies within 30 feet gain +2 to attack rolls and saving throws against undead and fiend-type anomalies. Undead and fiends in the area have disadvantage on attack rolls.",
		higher:
			"At 5th level, the beacon also deals 2d6 radiant damage to undead entering the area.",
		flavor: "The light doesn't ask permission. It arrives.",
		disc: "During the Jeju Raid, a Herald's beacon held back a swarm of shade-class anomalies for twelve critical minutes.",
		tags: ["herald", "holy-knight", "radiant", "aura", "anti-undead"],
	},
	{
		name: "Mana Overcharge",
		lv: 3,
		sch: "Transmutation",
		cls: ["Mage", "Esper"],
		ct: "1 bonus action",
		rng: "Self",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Next spell deals max damage instead of rolling.",
		eSec: "After the empowered spell, take 1d6 force damage from backlash.",
		desc: "Overcharge your mana circuit for one devastating release. The next damaging spell you cast within the duration deals maximum damage instead of rolling damage dice. After that spell resolves, you take 1d6 force damage from circuit backlash.",
		higher: "At 5th level, backlash damage is reduced to 0.",
		flavor: "Full power. No safeties. One shot.",
		disc: "Bureau medical staff report a 12% hospitalization rate from overcharge backlash. Usage rates have not declined.",
		tags: ["mage", "esper", "buff", "metamagic", "risk-reward"],
	},
	{
		name: "Summon Gate Echo",
		lv: 3,
		sch: "Conjuration",
		cls: ["Summoner"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 hour",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Summon a CR 2 gate-creature that obeys your commands.",
		eSec: "Echo has its own turn and can attack, grapple, or guard.",
		desc: "Tear a brief rift and pull a semi-autonomous gate echo into an unoccupied space within range. The echo is a Medium creature (AC 14, HP 30, +5 to hit, 2d6+3 damage) that acts on its own initiative and obeys your mental commands (no action required). It vanishes at 0 HP.",
		higher:
			"At 5th level, summon a CR 4 echo (AC 16, HP 50, 2d8+4 damage). At 7th, CR 6.",
		flavor: "Something answers. It always answers.",
		disc: "Gate echoes recognize their summoner instantly. Bureau researchers believe the rift imprints loyalty during transit.",
		tags: ["summoner", "conjuration", "minion", "sustained"],
	},
	{
		name: "Circuit Overclock",
		lv: 3,
		sch: "Transmutation",
		cls: ["Technomancer"],
		ct: "1 action",
		rng: "Touch",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Target gains +2 to AC, advantage on Agility saves.",
		eSec: "Target's speed increases by 10 feet.",
		desc: "Overclock a willing creature's mana circuit, boosting physical performance. For the duration, the target gains +2 AC, advantage on Agility saving throws, and +10 feet movement speed. The spell ends early if the target falls unconscious.",
		higher:
			"At 5th level, also grants an additional action on each turn (attack, Dash, Disengage, Hide, or Use Object only).",
		flavor: "Performance mode: engaged. Do not exceed recommended parameters.",
		disc: "The recommended parameters have never not been exceeded. Technomancers consider warnings 'suggestions.'",
		tags: ["technomancer", "buff", "haste", "transmutation"],
	},
	{
		name: "Binding Oath",
		lv: 3,
		sch: "Enchantment",
		cls: ["Holy Knight"],
		ct: "1 action",
		rng: "30 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "radiant",
		save: "Presence",
		dc: 15,
		ePri: "Target can't willingly move away from you.",
		eSec: "If target attacks anyone other than you, it takes 2d8 radiant.",
		desc: "Invoke your oath to bind a creature to single combat. The target must make a DC 15 Presence save. On failure, it cannot willingly move further from you and takes 2d8 radiant damage each time it attacks a creature other than you. Save at end of each turn.",
		higher:
			"At 5th level, the target also has disadvantage on attacks against creatures other than you.",
		flavor: "This is between us. Your oath. My blade.",
		disc: "Holy Knight dueling traditions stem from this spell. Breaking the binding is considered a grave dishonor.",
		tags: ["holy-knight", "oath", "control", "single-combat", "radiant"],
	},
	{
		name: "Whisper Network",
		lv: 3,
		sch: "Divination",
		cls: ["Assassin", "Idol", "Contractor"],
		ct: "1 action",
		rng: "1 mile",
		dur: "10 minutes",
		conc: false,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Send a 25-word message to a creature you know.",
		eSec: "Recipient can reply with a 25-word response.",
		desc: "Transmit a whispered message of 25 words or fewer to a creature within 1 mile that you are familiar with. The creature hears the message in your voice and can reply with 25 words of its own. The spell can reach across gate boundaries.",
		higher:
			"At 5th level, range extends to 10 miles and message length to 50 words.",
		flavor: "The message arrives. Only the right ears hear it.",
		disc: "Bureau intelligence operatives use this spell exclusively for field communications. It cannot be intercepted by mundane means.",
		tags: ["assassin", "idol", "contractor", "communication", "utility"],
	},
	{
		name: "Gravity Well",
		lv: 3,
		sch: "Transmutation",
		cls: ["Esper", "Mage"],
		ct: "1 action",
		rng: "90 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "2d6",
		dt: "force",
		save: "Strength",
		dc: 15,
		ePri: "20-foot radius zone of intensified gravity.",
		eSec: "Creatures entering or starting turn take 2d6 force, speed halved.",
		desc: "Create a 20-foot radius zone of intensified gravity at a point within range. Each creature entering the zone or starting its turn there must make a DC 15 Strength save or take 2d6 force damage and have its speed halved until it leaves. Flying creatures fall.",
		higher: "Damage increases by 1d6 per level above 3rd.",
		flavor: "Down is a command. You just gave it.",
		disc: "An Esper once centered a Gravity Well on a flying gate boss. The crater is still visible.",
		tags: ["esper", "mage", "gravity", "area", "control"],
	},

	// ═══ LEVEL 4 ═══
	{
		name: "Resonance Cascade",
		lv: 4,
		sch: "Evocation",
		cls: ["Idol", "Esper"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "6d8",
		dt: "thunder",
		save: "Vitality",
		dc: 16,
		ePri: "6d8 thunder damage in 30-foot radius.",
		eSec: "Failed saves are stunned until end of their next turn.",
		desc: "Release a catastrophic sonic detonation centered on yourself. Each creature within 30 feet (except you) must make a DC 16 Vitality save: 6d8 thunder damage and stunned until end of its next turn on failure, half damage on success. All glass within range shatters.",
		higher: "Damage increases by 1d8 per level above 4th.",
		flavor: "The concert hall is now a blast zone.",
		disc: "Bureau structural engineers added 'resonance dampening' to gate-adjacent building codes after this spell was first documented.",
		tags: ["idol", "esper", "thunder", "area", "stun"],
	},
	{
		name: "Dimensional Anchor",
		lv: 4,
		sch: "Abjuration",
		cls: ["Mage", "Herald"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "ranged",
		abl: "Intelligence",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Target cannot teleport or use extradimensional travel.",
		eSec: "If target attempts to teleport, it takes 4d6 force damage.",
		desc: "Launch a mana anchor that pins a creature to its current plane. Make a ranged spell attack. On a hit, the target is barred from teleportation, plane shifting, gate travel, and all extradimensional movement for the duration. If it attempts any such effect, it takes 4d6 force damage.",
		higher: "At 6th level, affects all creatures in a 15-foot radius.",
		flavor: "You're staying right here. With us.",
		disc: "Standard protocol for gate-boss encounters after three bosses escaped via emergency teleportation.",
		tags: ["mage", "herald", "anti-teleport", "control", "abjuration"],
	},
	{
		name: "Death's Harvest",
		lv: 4,
		sch: "Necromancy",
		cls: ["Revenant"],
		ct: "1 action",
		rng: "Self (30-foot cone)",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "6d8",
		dt: "necrotic",
		save: "Vitality",
		dc: 16,
		ePri: "6d8 necrotic in 30-foot cone.",
		eSec: "For each creature reduced to 0 HP, regain 2d8 HP.",
		desc: "Exhale a torrent of concentrated entropy in a 30-foot cone. Each creature in the area makes a DC 16 Vitality save: 6d8 necrotic on failure, half on success. For each creature reduced to 0 HP by this spell, you regain 2d8 hit points.",
		higher: "Damage increases by 1d8 per level above 4th.",
		flavor: "She reaps. It's what Revenants do.",
		disc: "Bureau containment teams classify this as a 'population management' tool. The euphemism is intentional.",
		tags: ["revenant", "necrotic", "cone", "harvest", "self-heal"],
	},
	{
		name: "Oath Aura",
		lv: 4,
		sch: "Abjuration",
		cls: ["Holy Knight"],
		ct: "1 action",
		rng: "Self (30-foot radius)",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Allies in range add Presence modifier to all saves.",
		eSec: "Caster is immune to being frightened.",
		desc: "Radiate your oath's authority. For the duration, you and all friendly creatures within 30 feet add your Presence modifier (minimum +1) to all saving throws. You are also immune to being frightened while concentrating on this spell.",
		higher: "At 6th level, the aura also grants resistance to spell damage.",
		flavor: "Stand near me. I'll carry the rest.",
		disc: "A Holy Knight's Oath Aura reportedly held a raid team together through a Monarch-class fear pulse. Not one member fled.",
		tags: ["holy-knight", "oath", "aura", "saves", "protection"],
	},
	{
		name: "Phantom Swarm",
		lv: 4,
		sch: "Illusion",
		cls: ["Assassin", "Contractor"],
		ct: "1 action",
		rng: "Self",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "Presence",
		dc: 16,
		ePri: "Create 3 illusory duplicates that mirror your movement.",
		eSec: "Each duplicate can deliver attacks (1d8 psychic each).",
		desc: "Manifest three illusory copies of yourself that occupy your space and mirror your movements. Attacks against you randomly target you or a duplicate (d4: 1-3 hits duplicate, 4 hits you). Each duplicate has 1 HP, AC 14, and can deliver melee attacks dealing 1d8 psychic damage using your spell attack modifier.",
		higher: "At 6th level, create 5 duplicates.",
		flavor: "Which one is real? Wrong question.",
		disc: "Bureau combat evaluators cannot reliably identify the original. That's the point.",
		tags: ["assassin", "contractor", "illusion", "duplicates", "defense"],
	},
	{
		name: "Gate Ward",
		lv: 4,
		sch: "Abjuration",
		cls: ["Summoner", "Stalker", "Technomancer"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "",
		save: "",
		dc: 0,
		ePri: "Create a 20-foot dome that blocks summoning and teleportation.",
		eSec: "Creatures inside gain advantage on saves against conjuration spells.",
		desc: "Erect a translucent 20-foot radius dome at a point within range. For the duration, no creature can teleport into or out of the area, and summoning effects within the dome fail. Creatures inside gain advantage on saves against conjuration spells.",
		higher:
			"At 6th level, the dome also blocks divination attempts targeting creatures inside.",
		flavor: "Nothing gets in. Nothing gets out. That's the deal.",
		disc: "Standard containment protocol for unstable gate perimeters. Bureau gate-response teams deploy this before anything else.",
		tags: ["summoner", "stalker", "technomancer", "ward", "anti-teleport"],
	},
	{
		name: "Mana Cannon",
		lv: 4,
		sch: "Evocation",
		cls: ["Technomancer", "Mage"],
		ct: "1 action",
		rng: "120 feet",
		dur: "Instantaneous",
		conc: false,
		atk: "",
		abl: "",
		dmg: "6d10",
		dt: "force",
		save: "Agility",
		dc: 16,
		ePri: "6d10 force damage to a single target.",
		eSec: "On failed save by 5+, target is knocked prone and stunned until end of its next turn.",
		desc: "Channel maximum output through your focus device and fire a concentrated beam of force at one creature. The target makes a DC 16 Agility save: 6d10 force damage on failure, half on success. If the target fails by 5 or more, it's also knocked prone and stunned until end of its next turn.",
		higher: "Damage increases by 1d10 per level above 4th.",
		flavor: "All systems nominal. All safeties off. Fire.",
		disc: "The recoil shattered every window in the test facility. The Technomancer called it 'acceptable.'",
		tags: ["technomancer", "mage", "force", "single-target", "devastation"],
	},
	{
		name: "Enthralling Performance",
		lv: 4,
		sch: "Enchantment",
		cls: ["Idol"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "",
		dt: "psychic",
		save: "Presence",
		dc: 16,
		ePri: "Charm up to 5 creatures that can hear you.",
		eSec: "Charmed targets regard you as a trusted friend.",
		desc: "Begin a captivating performance that overwhelms the senses. Up to 5 creatures within 60 feet that can hear you must make a DC 16 Presence save or be charmed for the duration. Charmed creatures regard you as a trusted friend and won't attack you. They can repeat the save if harmed.",
		higher:
			"At 6th level, charmed creatures also follow simple non-harmful instructions.",
		flavor: "They're not fans. They're converts. There's a difference.",
		disc: "An Idol once charmed an entire gate-creature pack during a live broadcast. The ratings were unprecedented.",
		tags: ["idol", "enchantment", "charm", "mass", "performance"],
	},
	{
		name: "Pact Gate",
		lv: 4,
		sch: "Conjuration",
		cls: ["Contractor"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 1 minute",
		conc: true,
		atk: "",
		abl: "",
		dmg: "4d6",
		dt: "force",
		save: "Agility",
		dc: 16,
		ePri: "Create two linked 5-foot portals within range.",
		eSec: "Attacks and spells can pass through. Creatures take 4d6 force entering unwillingly.",
		desc: "Open two linked portals within range. Willing creatures can move between them freely. Attacks and spells can pass through as if the spaces were adjacent. Unwilling creatures forced through must make a DC 16 Agility save or take 4d6 force damage from spatial shearing.",
		higher: "At 6th level, range extends to 120 feet.",
		flavor: "Two doors. One path. Infinite applications.",
		disc: "Bureau tactical teams use Pact Gates for flanking maneuvers. The portals' aesthetic always matches the patron's domain.",
		tags: ["contractor", "conjuration", "portal", "tactical", "utility"],
	},
	{
		name: "Thorn Fortress",
		lv: 4,
		sch: "Conjuration",
		cls: ["Summoner", "Herald"],
		ct: "1 action",
		rng: "60 feet",
		dur: "Concentration, up to 10 minutes",
		conc: true,
		atk: "",
		abl: "",
		dmg: "3d6",
		dt: "piercing",
		save: "Agility",
		dc: 15,
		ePri: "Create a 20-foot radius zone of razor-sharp gate-flora.",
		eSec: "Creatures entering or starting turn take 3d6 piercing, area is difficult terrain.",
		desc: "Conjure a thicket of razor-sharp gate-flora in a 20-foot radius centered on a point within range. The area becomes difficult terrain. Each creature entering the area or starting its turn there must make a DC 15 Agility save: 3d6 piercing on failure, half on success.",
		higher:
			"At 6th level, damage increases to 4d6 and the thicket also provides three-quarters cover to creatures inside.",
		flavor: "The garden grows. It does not welcome visitors.",
		disc: "Gate-flora thorns dissolve after the spell ends but the scratches remain. Bureau medics stock extra bandages.",
		tags: ["summoner", "herald", "conjuration", "area", "terrain", "nature"],
	},
];
