// Extra Techniques — 40 entries, 100% RA-original mechanics
module.exports = [
	// ═══ LEVEL 1-2 GAP FILLS ═══
	{
		name: "Gate Breaker Chop",
		lv: 1,
		cls: ["Destroyer", "Berserker"],
		mode: "offensive",
		sch: "Evocation",
		desc: "A devastating overhead strike that channels mana through the weapon's edge. Melee attack: normal damage + 1d8 force. If the target is a construct or gate-structure, deals double bonus damage. Can be used to destroy gate-crystal locks.",
		flavor: "She doesn't pick locks. She picks axes.",
		eff: "Extra 1d8 force; double vs constructs/gate-structures.",
		disc: "Bureau gate-breach teams assign Destroyers to structural targets specifically. The chop is 'architecturally efficient.'",
		dt: "force",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Mana Circuit Rush",
		lv: 1,
		cls: ["Striker", "Berserker"],
		mode: "offensive",
		sch: "Transmutation",
		desc: "Flood your mana circuit into your legs and charge up to 30 feet in a straight line toward a target. If you reach it, make a melee attack with advantage. On hit, normal damage + 1d8 force and target must make DC 13 STR save or be knocked prone.",
		flavor: "She closed the distance before the anomaly flinched.",
		eff: "30-foot charge + advantage + 1d8 force + knockdown.",
		disc: "Bureau combat trainers call this 'closing the gap.' The gap is usually between the Hunter and the thing that should be running.",
		dt: "force",
		save: "Strength",
		dc: 13,
		wpn: "melee",
	},
	{
		name: "Precision Disarm",
		lv: 1,
		cls: ["Assassin", "Stalker"],
		mode: "offensive",
		sch: "Transmutation",
		desc: "Target the tendons and grip-muscles with a precise strike. On a hit, normal damage and the target must make DC 13 AGI save or drop one held item of your choice. The item lands at the target's feet.",
		flavor: "The sword is on the ground now. So is your confidence.",
		eff: "Forced item drop on failed save.",
		disc: "Bureau disarmament protocol for humanoid targets. Works on anomalies too — if they have hands.",
		dt: "",
		save: "Agility",
		dc: 13,
		wpn: "melee",
	},
	{
		name: "Riposte Lattice",
		lv: 1,
		cls: ["Holy Knight", "Destroyer"],
		mode: "defensive",
		sch: "Abjuration",
		desc: "As a reaction when a creature misses you with a melee attack, immediately make a melee attack against it. If you hit, deal normal damage + 1d6 radiant and regain 1d4 HP.",
		flavor: "You missed. She didn't.",
		eff: "Counter-attack + 1d6 radiant + self-heal.",
		disc: "Holy Knights train riposte reflexes from the first day. The Bureau measures their reaction time at 0.08 seconds.",
		dt: "radiant",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Sonic Throw",
		lv: 1,
		cls: ["Idol", "Technomancer"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Infuse a thrown weapon or projectile with sonic mana. Ranged attack: normal damage + 1d8 thunder. If the target is concentrating on a spell, it has disadvantage on the concentration save.",
		flavor: "The projectile screams. So does the target.",
		eff: "Extra 1d8 thunder + concentration disadvantage.",
		disc: "Idols sometimes use microphone stands as thrown weapons with this technique. It's surprisingly effective.",
		dt: "thunder",
		save: "",
		dc: 0,
		wpn: "ranged",
	},
	{
		name: "Anchor Strike",
		lv: 2,
		cls: ["Destroyer", "Holy Knight"],
		mode: "offensive",
		sch: "Abjuration",
		desc: "Strike a creature and anchor it to the local mana-lattice. On hit: normal damage + 2d6 force, and the target's speed becomes 0 until the end of its next turn. If it tries to teleport, it takes 2d8 force and the teleport fails.",
		flavor: "You're here. You're staying here.",
		eff: "2d6 force + speed 0 + teleport denial.",
		disc: "Gate-anomalies with phase-shift abilities fear this technique specifically. The anchor doesn't care about dimensions.",
		dt: "force",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Mana Overrun",
		lv: 2,
		cls: ["Berserker", "Striker"],
		mode: "offensive",
		sch: "Transmutation",
		desc: "Charge through up to 3 creatures in a 30-foot line. Make a separate melee attack against each. Each hit deals normal damage + 1d6 force. Creatures hit must make DC 14 STR save or be pushed 10 feet to the side.",
		flavor: "Through them. Not around them. Through.",
		eff: "Multi-target charge: 1d6 force + push per target.",
		disc: "Bureau hallway combat training includes Mana Overrun as the primary breach technique. The hallway is usually wider after.",
		dt: "force",
		save: "Strength",
		dc: 14,
		wpn: "melee",
	},
	{
		name: "Vital Point Strike",
		lv: 2,
		cls: ["Assassin", "Striker"],
		mode: "offensive",
		sch: "Necromancy",
		desc: "Target a creature's mana-circuit junction point with a surgical strike. On hit: normal damage + 2d6 necrotic. Target's mana recovery is suppressed: it can't regain HP from any source until the end of its next turn.",
		flavor: "She hit the exact point where healing stops working.",
		eff: "2d6 necrotic + heal suppression for 1 round.",
		disc: "Bureau anatomy charts mark 14 primary junction points. Assassins memorize all 14 in their first week.",
		dt: "necrotic",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Resonance Slash",
		lv: 2,
		cls: ["Idol"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Infuse a melee weapon with harmonic resonance and strike. On hit: normal damage + 2d6 thunder. The impact creates a 10-foot shockwave: each creature other than you within 10 feet of the target makes DC 14 VIT save or takes 1d6 thunder.",
		flavor: "The slash sings. Everything nearby listens.",
		eff: "2d6 thunder + 10-foot area splash 1d6 thunder.",
		disc: "Idol combat performances that include Resonance Slash are rated 'crowd-pleasers.' The crowd is usually the enemy.",
		dt: "thunder",
		save: "Vitality",
		dc: 14,
		wpn: "melee",
	},
	{
		name: "Thermal Coating",
		lv: 2,
		cls: ["Technomancer", "Mage"],
		mode: "utility",
		sch: "Transmutation",
		desc: "As a bonus action, coat your weapon with superheated mana. For 1 minute, your weapon attacks deal +1d6 fire damage and ignite flammable objects. You can dismiss the coating as a free action.",
		flavor: "The blade doesn't glow red. It glows white.",
		eff: "+1d6 fire on weapon attacks for 1 minute.",
		disc: "Technomancers can calibrate the thermal output precisely. Most set it to 'maximum' and call it done.",
		dt: "fire",
		save: "",
		dc: 0,
		wpn: "melee",
	},

	// ═══ LEVEL 3-4 ═══
	{
		name: "Gate Cutter",
		lv: 3,
		cls: ["Destroyer"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Swing your weapon in a massive arc that tears through the mana-lattice. All creatures in a 15-foot cone in front of you: DC 15 AGI save, 4d8 force on failure, half on success. Gate-structures and mana-barriers take double damage.",
		flavor: "The arc cuts through everything. Including the gate itself.",
		eff: "4d8 force in 15-foot cone; double vs gate-structures.",
		disc: "Bureau demolition teams use this instead of explosives inside active gates. It's faster and doesn't require paperwork.",
		dt: "force",
		save: "Agility",
		dc: 15,
		wpn: "melee",
	},
	{
		name: "Skull Splitter",
		lv: 3,
		cls: ["Berserker"],
		mode: "offensive",
		sch: "Evocation",
		desc: "A single devastating overhead strike that concentrates your full mana output. Melee attack: normal damage + 4d10 force. If the target is at or below half HP, you score a critical hit on a roll of 18-20.",
		flavor: "One swing. Maximum force. The skull was optional.",
		eff: "Extra 4d10 force + expanded crit range vs bloodied targets.",
		disc: "Bureau combat footage shows Skull Splitter impacts registering on seismographs. The nearest station is 2 miles away.",
		dt: "force",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Shadow Execution",
		lv: 3,
		cls: ["Assassin"],
		mode: "offensive",
		sch: "Illusion",
		desc: "If you are hidden from the target, your attack automatically crits. On hit: normal damage + 3d6 necrotic. Target must make DC 15 PRS save or be blinded until the end of its next turn as shadow-mana floods its visual cortex.",
		flavor: "From the shadow. Into the shadow. They never see.",
		eff: "Auto-crit from stealth + 3d6 necrotic + blind.",
		disc: "Bureau security footage from Shadow Execution incidents shows a single frame of distortion. By the next frame, the target is down.",
		dt: "necrotic",
		save: "Presence",
		dc: 15,
		wpn: "melee",
	},
	{
		name: "Iron Pillar Stance",
		lv: 3,
		cls: ["Destroyer", "Holy Knight"],
		mode: "defensive",
		sch: "Abjuration",
		desc: "Plant your feet and become an immovable defender. For 1 minute: you can't be moved, gain +3 AC, and as a reaction can make a melee attack against any creature that enters your reach. Movement speed becomes 0.",
		flavor: "The pillar doesn't move. The pillar doesn't need to.",
		eff: "+3 AC, can't be moved, reaction attacks on approach, speed 0.",
		disc: "A Holy Knight held Iron Pillar for 12 minutes at a gate chokepoint. 47 anomalies tried to pass. None did.",
		dt: "",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Cascade Combo",
		lv: 3,
		cls: ["Striker"],
		mode: "offensive",
		sch: "Transmutation",
		desc: "Execute a three-hit mana-accelerated combo. Make three unarmed attacks (each at -2). Each successive hit that connects deals escalating damage: 1d8, 2d8, 3d8 force. If all three connect, the target is stunned until end of its next turn.",
		flavor: "One. Two. Three. Stun.",
		eff: "Escalating 1d8/2d8/3d8 force combo; full combo = stun.",
		disc: "Bureau martial arts assessors clock the full combo at 0.4 seconds. The third hit arrives before the first impact registers.",
		dt: "force",
		save: "",
		dc: 0,
		wpn: "unarmed",
	},
	{
		name: "Quarry Brand",
		lv: 3,
		cls: ["Stalker"],
		mode: "offensive",
		sch: "Divination",
		desc: "When you hit a creature, mark it as prey. For 1 minute: you have advantage on attacks against it, you always know its location, and your first hit each turn deals +2d6 damage. If the target dies, you can transfer the mark as a free action.",
		flavor: "Branded. Hunted. Ended.",
		eff: "Advantage + tracking + 2d6 bonus; transferable on kill.",
		disc: "Stalkers brand their quarry silently. Bureau after-action reports note that branded targets die 70% faster.",
		dt: "",
		save: "",
		dc: 0,
		wpn: "any",
	},
	{
		name: "Devotion Guard",
		lv: 3,
		cls: ["Holy Knight"],
		mode: "defensive",
		sch: "Abjuration",
		desc: "As a reaction when an ally within 10 feet takes damage, interpose yourself. You take the damage instead (reduced by your AC bonus, minimum 1). The ally gains temporary HP equal to your Presence modifier.",
		flavor: "Between the ally and the blade. Always.",
		eff: "Redirect ally damage to self + temp HP to ally.",
		disc: "Bureau casualty reports show Holy Knights take 300% more damage than other jobs. Survival rates remain at 98%. The math works.",
		dt: "",
		save: "",
		dc: 0,
		wpn: "shield",
	},
	{
		name: "Voltaic Chain Strike",
		lv: 4,
		cls: ["Technomancer"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Strike a creature and discharge a mana-electric chain through its body. On hit: normal damage + 3d8 lightning. The charge arcs to up to 2 additional creatures within 15 feet of the target: each takes 2d8 lightning (DC 16 AGI, half on success).",
		flavor: "One strike. Three targets. One invoice.",
		eff: "3d8 lightning primary + 2d8 chain to 2 others.",
		disc: "Bureau electrical engineers banned this technique indoors after it arced into a server room. The data loss was 'regrettable.'",
		dt: "lightning",
		save: "Agility",
		dc: 16,
		wpn: "melee",
	},
	{
		name: "Entropic Rend",
		lv: 4,
		cls: ["Revenant"],
		mode: "offensive",
		sch: "Necromancy",
		desc: "Infuse your weapon with pure entropy and strike. On hit: normal damage + 4d6 necrotic. Target's AC is reduced by 2 for 1 minute as its defensive mana-lattice corrodes. This reduction stacks with itself up to -4 AC.",
		flavor: "The armor remembers being new. Not for long.",
		eff: "4d6 necrotic + AC reduction (stacking to -4).",
		disc: "Bureau equipment requisition sees a 40% increase in armor replacements after Revenants join a gate team. Entropy is not kind to gear.",
		dt: "necrotic",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Pact Weapon Manifest",
		lv: 4,
		cls: ["Contractor"],
		mode: "offensive",
		sch: "Conjuration",
		desc: "Manifest a weapon from your patron's dimension. Choose any melee weapon form. It counts as magical, uses Presence for attack/damage, deals +2d6 damage of your patron's element, and can't be disarmed. Lasts 1 hour or until dismissed.",
		flavor:
			"The patron provides the weapon. The Contractor provides the violence.",
		eff: "Magical weapon + PRS-based + 2d6 patron element + can't be disarmed.",
		disc: "Each patron's weapon has a unique aesthetic. Bureau identification guides catalog 23 documented patterns.",
		dt: "",
		save: "",
		dc: 0,
		wpn: "conjured",
	},

	// ═══ LEVEL 5-7 ═══
	{
		name: "Meteor Fist",
		lv: 5,
		cls: ["Striker"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Concentrate all mana-kinetic force into a single punch that strikes with the impact of a falling star. Melee attack: 8d10 force damage. The target must make DC 17 STR save or be launched 30 feet and knocked prone. If it collides with a surface, both take 4d6 bludgeoning.",
		flavor: "The fist arrives. The target departs.",
		eff: "8d10 force + 30-foot launch + collision damage.",
		disc: "Bureau seismographs record a Meteor Fist impact as a magnitude 2.1 event. The closest station asked if there was an earthquake.",
		dt: "force",
		save: "Strength",
		dc: 17,
		wpn: "unarmed",
	},
	{
		name: "Demolition Wave",
		lv: 5,
		cls: ["Destroyer"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Strike the ground and send a devastating shockwave in a 30-foot cone. Each creature: DC 17 STR save, 6d10 force on failure, half on success. All structures, barriers, and constructs in the area take triple damage. Terrain becomes difficult.",
		flavor: "The ground has an opinion. It's disagreeing with everything.",
		eff: "6d10 force cone + triple vs structures + difficult terrain.",
		disc: "Bureau structural engineers no longer accompany Destroyers into gates. They just wait outside with calculators and resignation.",
		dt: "force",
		save: "Strength",
		dc: 17,
		wpn: "melee",
	},
	{
		name: "Mark of the Absolute",
		lv: 5,
		cls: ["Holy Knight"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Brand a creature with the Absolute's mark. On hit: normal damage + 5d8 radiant. For 1 minute, the marked creature takes 2d8 radiant at the start of each of its turns, sheds bright light 10 feet (can't hide), and all attacks against it from allies deal +1d6 radiant.",
		flavor: "The Absolute sees you now. It does not approve.",
		eff: "5d8 radiant + 2d8/round DOT + ally damage boost.",
		disc: "Bureau field chaplains report the mark is visible even through walls. Gate-anomalies have been observed fleeing from marked targets.",
		dt: "radiant",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Whirlwind Execution",
		lv: 5,
		cls: ["Assassin", "Stalker"],
		mode: "offensive",
		sch: "Transmutation",
		desc: "Spin through multiple targets with mana-enhanced speed. Make a melee attack against up to 5 creatures within reach. Each hit deals normal damage + 3d6 force. If you hit 3 or more targets, you become invisible until the start of your next turn.",
		flavor: "Five targets. One revolution. Gone before the blood falls.",
		eff: "Multi-target attack (up to 5) + 3d6 force + invisibility at 3+ hits.",
		disc: "Bureau surveillance footage shows the whirlwind as a 0.6-second blur. Target count confirmation requires frame-by-frame analysis.",
		dt: "force",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Graviton Slam",
		lv: 6,
		cls: ["Striker", "Destroyer"],
		mode: "offensive",
		sch: "Transmutation",
		desc: "Leap 30 feet into the air and slam down with gravity-multiplied force. Each creature within 15 feet of impact: DC 17 STR save, 8d8 force on failure, half on success. Targets that fail are knocked prone and their speed is 0 until end of their next turn.",
		flavor: "What goes up must come down. She went up with intent.",
		eff: "8d8 force in 15-foot radius + prone + speed 0.",
		disc: "Bureau structural assessments show Graviton Slam impacts creating 3-foot craters in reinforced concrete. The Striker was uninjured.",
		dt: "force",
		save: "Strength",
		dc: 17,
		wpn: "unarmed",
	},
	{
		name: "Eternal Slash",
		lv: 6,
		cls: ["Assassin"],
		mode: "offensive",
		sch: "Necromancy",
		desc: "Execute a blade strike infused with terminal entropy. On hit: normal damage + 6d8 necrotic. The wound cannot be healed by any means for 1 minute. If the target is reduced to 0 HP while the wound persists, it cannot be revived by spells below 7th level.",
		flavor: "The wound remembers. The wound doesn't close.",
		eff: "6d8 necrotic + unhealing wound + anti-revival rider.",
		disc: "Bureau medical teams classify wounds from Eternal Slash as 'temporally persistent.' Standard healing simply fails.",
		dt: "necrotic",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Resonance Blade Dance",
		lv: 6,
		cls: ["Idol"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Perform a combat dance that generates mana-blades of sound. For 1 minute, you can make ranged spell attacks (60 ft, 3d8 thunder) as a bonus action. While dancing, you gain +2 AC and your movement doesn't provoke opportunity attacks.",
		flavor: "She dances. Blades of sound follow. It's beautiful. It's lethal.",
		eff: "Bonus action 3d8 ranged thunder attacks + AC + free movement.",
		disc: "Bureau combat choreography assessors rate this as 'S-Tier performance art.' Audiences disagree — they rate it 'terrifying.'",
		dt: "thunder",
		save: "",
		dc: 0,
		wpn: "performance",
	},
	{
		name: "Gate Breaker Barrage",
		lv: 6,
		cls: ["Berserker"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Enter a 1-round rampage of mana-fueled strikes. Make 4 melee attacks with advantage. Each hit deals normal damage + 2d8 force. If you hit with all 4, the target must make DC 17 VIT save or be stunned for 1 round.",
		flavor: "Four hits. All of them meant to end things.",
		eff: "4 attacks with advantage, +2d8 force each, full combo stuns.",
		disc: "Bureau combat assessors clocked the full barrage at 1.2 seconds. The fourth impact arrives 0.1 seconds after the first.",
		dt: "force",
		save: "Vitality",
		dc: 17,
		wpn: "melee",
	},
	{
		name: "Dimensional Blade",
		lv: 7,
		cls: ["Assassin", "Stalker"],
		mode: "offensive",
		sch: "Conjuration",
		desc: "Manifest a blade that cuts through dimensional boundaries. For 1 minute: your weapon attacks ignore armor AC (targets use base 10 + DEX only), deal +3d8 force, and can hit creatures in adjacent gate-layers (invisible, ethereal, phase-shifted).",
		flavor:
			"The blade exists in every dimension simultaneously. Hiding is irrelevant.",
		eff: "Ignore armor AC + 3d8 force + hit across dimensions.",
		disc: "Bureau dimensional analysts confirmed the blade operates on 4 simultaneous dimensional frequencies. Nothing is out of reach.",
		dt: "force",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "Mountain Crusher",
		lv: 7,
		cls: ["Destroyer", "Berserker"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Channel your full mana reserve into a single world-breaking strike. Melee attack: normal damage + 10d10 force. All creatures within 30 feet of the impact: DC 18 STR save or knocked prone and pushed 20 feet. Structures within 30 feet take 100 force damage.",
		flavor:
			"She didn't break the mountain. The mountain broke itself trying to stop her.",
		eff: "10d10 force + 30-foot shockwave + structure destruction.",
		disc: "Bureau geological surveys detected Mountain Crusher usage from space. The impact was classified as a 'non-natural seismic event.'",
		dt: "force",
		save: "Strength",
		dc: 18,
		wpn: "melee",
	},

	// ═══ LEVEL 8-9 ═══
	{
		name: "Infinite Combo",
		lv: 8,
		cls: ["Striker"],
		mode: "offensive",
		sch: "Transmutation",
		desc: "Enter a mana-accelerated state where each consecutive hit builds momentum. Make melee attacks until you miss. Each hit after the first deals escalating damage: +1d10 per hit (2nd hit +1d10, 3rd +2d10, etc). If you land 5+ hits, the target is stunned for 1 minute (DC 19 VIT).",
		flavor: "She didn't stop. She couldn't stop. The target wished she would.",
		eff: "Escalating infinite combo; 5+ hits = stun.",
		disc: "The Bureau record for consecutive hits in an Infinite Combo is 11. The target was an A-Rank gate boss. It was no longer a gate boss.",
		dt: "force",
		save: "Vitality",
		dc: 19,
		wpn: "unarmed",
	},
	{
		name: "Absolute Execution",
		lv: 8,
		cls: ["Assassin"],
		mode: "offensive",
		sch: "Necromancy",
		desc: "Mark a target and study it for 1 round. On your next turn, make a single melee attack. This attack automatically hits, automatically crits, and deals maximum damage on all dice + 8d8 necrotic. If the target has 100 HP or fewer after damage, it dies instantly.",
		flavor: "Studied. Judged. Executed.",
		eff: "Auto-hit, auto-crit, max damage + 8d8 + execution threshold.",
		disc: "Bureau S-Rank assassination protocols list three requirements: intelligence, patience, and Absolute Execution. Two out of three are trainable.",
		dt: "necrotic",
		save: "",
		dc: 0,
		wpn: "melee",
	},
	{
		name: "World Splitter",
		lv: 9,
		cls: ["Destroyer"],
		mode: "offensive",
		sch: "Evocation",
		desc: "The ultimate Destroyer technique. Strike the ground and split reality in a 60-foot line, 20 feet wide. Everything in the area: DC 20 STR save, 15d10 force on failure, half on success. Structures are automatically destroyed. The fissure persists for 1 minute as impassable terrain.",
		flavor: "She split the world. The world let her.",
		eff: "15d10 force in 60x20 line + permanent terrain destruction.",
		disc: "Bureau records: one confirmed World Splitter. The resulting fissure is now a permanent geographical feature. Maps were updated.",
		dt: "force",
		save: "Strength",
		dc: 20,
		wpn: "melee",
	},
	{
		name: "Fist of the Infinite",
		lv: 9,
		cls: ["Striker"],
		mode: "offensive",
		sch: "Transmutation",
		desc: "Channel every mana gate, every circuit node, every ounce of kinetic potential into a single transcendent punch. Melee attack: 20d10 force damage. If this reduces the target to 0 HP, everything within 30 feet takes 10d10 force as the mana-shockwave propagates. You gain 5 levels of exhaustion.",
		flavor: "One punch. Everything she has. Everything she is.",
		eff: "20d10 force + kill-shockwave 10d10 in 30 feet + 5 exhaustion.",
		disc: "Bureau theoretical combat researchers calculated the energy output at 'approximately one small nuclear device.' The Striker was unfazed.",
		dt: "force",
		save: "",
		dc: 0,
		wpn: "unarmed",
	},
	{
		name: "Final Hunt",
		lv: 9,
		cls: ["Stalker", "Assassin"],
		mode: "offensive",
		sch: "Divination",
		desc: "Declare a Final Hunt against one creature you can see. For 24 hours: you always know its location regardless of distance or plane, all your attacks against it have advantage and deal +5d8 damage, and it can't benefit from healing, concealment, or dimensional travel. If you kill it, regain all spent resources.",
		flavor: "The hunt begins. It ends when she decides.",
		eff: "24-hour mark: advantage + 5d8 + heal/hide/travel denial + full resource recovery on kill.",
		disc: "Bureau classified. Two Final Hunts on record. Both targets were S-Rank gate bosses. Both hunts ended in under 4 hours.",
		dt: "",
		save: "",
		dc: 0,
		wpn: "any",
	},
	{
		name: "Resonance Apocalypse",
		lv: 9,
		cls: ["Idol"],
		mode: "offensive",
		sch: "Evocation",
		desc: "Perform the ultimate harmonic — a sound that resonates with the fundamental frequency of reality. All creatures within 120 feet (ally and enemy): DC 20 PRS save. Enemies on failure: 12d8 thunder, stunned 1 minute, deafened permanently. Allies on success: full HP, all conditions removed, +3 to all rolls for 1 minute.",
		flavor: "The sound that ends the concert. And everything else.",
		eff: "12d8 thunder + stun + permanent deaf to enemies; full heal + buff to allies.",
		disc: "Bureau records: one confirmed Resonance Apocalypse. The Idol collapsed after. The S-Rank gate was silent. Everything was silent.",
		dt: "thunder",
		save: "Presence",
		dc: 20,
		wpn: "performance",
	},
];
