// Techniques — 50 unique entries covering all martial + path-hybrid jobs
module.exports = [
	// ═══ DESTROYER (vanguard) ═══
	{ name:"Shield Bash", lv:1, cls:["Destroyer"], mode:"vanguard", style:"Weapon", dt:"bludgeoning", abl:"Strength", act:"action", desc:"Slam your shield or weapon flat into a creature within 5 feet. Make a melee attack using Strength; on hit, 1d8+STR bludgeoning damage and the target must make a DC 13 Strength save or be pushed 10 feet and knocked prone.", eff:"Attack + push + prone.", flavor:"The shield isn't for defense. Not right now." },
	{ name:"Iron Curtain", lv:3, cls:["Destroyer"], mode:"vanguard", style:"Defense", dt:"", abl:"Strength", act:"reaction", desc:"As a reaction when an ally within 10 feet is targeted by an attack, impose yourself. The attack targets you instead. You have +3 AC against it. If the attack misses you, you can make one melee weapon attack against the attacker as part of the same reaction.", eff:"Attack redirect + counterattack.", flavor:"Through me. Only through me." },
	{ name:"Anchor Slam", lv:5, cls:["Destroyer"], mode:"vanguard", style:"Weapon", dt:"force", abl:"Strength", act:"action", desc:"Slam your weapon into the ground, creating a 15-foot radius shockwave. Each creature makes DC 16 STR save: 5d8 force and knocked prone on failure, half on success. The area becomes difficult terrain for 1 minute.", eff:"AoE force + prone + terrain.", flavor:"The ground listens when she strikes it." },
	{ name:"Unyielding Fortress", lv:7, cls:["Destroyer"], mode:"vanguard", style:"Stance", dt:"", abl:"Strength", act:"bonus", desc:"Enter an immovable stance for 1 minute. You can't be moved, you have advantage on all Strength and Constitution saves, reduce all damage by 5, and can use your reaction to impose disadvantage on any attack targeting an ally within 10 feet.", eff:"Immovable + damage reduction + ally protection.", flavor:"I am the wall. I am the gate. Nothing passes." },
	{ name:"World Anchor", lv:9, cls:["Destroyer"], mode:"vanguard", style:"Ultimate", dt:"force", abl:"Strength", act:"action", desc:"Drive your weapon into the earth and become one with the battlefield. For 1 minute: you can't move but gain immunity to all conditions, reduce all damage by 15, and any creature that attacks an ally within 30 feet of you takes 5d10 force damage automatically. After the effect ends, gain 2 exhaustion.", eff:"Total defensive supremacy + auto-retaliation.", flavor:"She didn't move. Nothing else could." },

	// ═══ BERSERKER (brutal) ═══
	{ name:"Reckless Cleave", lv:1, cls:["Berserker"], mode:"brutal", style:"Weapon", dt:"slashing", abl:"Strength", act:"action", desc:"Make a melee weapon attack with advantage, but attacks against you also have advantage until the start of your next turn. On a hit, deal weapon damage plus 1d8 slashing damage to the target and each creature within 5 feet of it.", eff:"Advantaged AoE cleave + defensive tradeoff.", flavor:"All in. All the time." },
	{ name:"Savage Charge", lv:3, cls:["Berserker"], mode:"brutal", style:"Movement", dt:"bludgeoning", abl:"Strength", act:"action", desc:"Charge up to 30 feet in a straight line, then make a melee attack with advantage. On a hit, deal weapon damage plus 3d8 bludgeoning and the target must make DC 15 STR save or be knocked prone. If already in Overload, charge distance increases to 60 feet.", eff:"Charging attack + bonus damage + prone.", flavor:"The distance between us is a problem. Your problem." },
	{ name:"Carnage Wave", lv:5, cls:["Berserker"], mode:"brutal", style:"Weapon", dt:"slashing", abl:"Strength", act:"action", desc:"Sweep your weapon in a devastating arc. Make a melee weapon attack against each creature within 10 feet. On a hit, deal weapon damage plus 3d10 slashing. Creatures reduced to 0 HP explode (2d6 slashing to creatures within 5 feet of them).", eff:"Multi-target sweep + chain explosion.", flavor:"One swing. Everything dies or moves." },
	{ name:"Unstoppable Rampage", lv:7, cls:["Berserker"], mode:"brutal", style:"Stance", dt:"", abl:"Strength", act:"bonus", desc:"For 1 minute: you can make a melee attack against every creature you pass within 5 feet during your movement (once each), your speed can't be reduced, and you're immune to prone, grappled, and restrained. Each kill grants +5 temporary HP.", eff:"Mobile multi-attack + condition immunity + kill reward.", flavor:"She stopped when there was nothing left to hit." },
	{ name:"Extinction Strike", lv:9, cls:["Berserker"], mode:"brutal", style:"Ultimate", dt:"fire", abl:"Strength", act:"action", desc:"Channel maximum Overload into a single attack. Make a melee weapon attack. On a hit: weapon damage plus 15d12 fire damage. The target is launched 60 feet and everything in the path takes half damage. Miss: half damage to the target anyway. Usable once per long rest.", eff:"15d12 fire + launch + path damage. Even on miss.", flavor:"One hit. The last hit anything will ever need." },

	// ═══ ASSASSIN (precision) ═══
	{ name:"Vital Strike", lv:1, cls:["Assassin"], mode:"precision", style:"Weapon", dt:"piercing", abl:"Agility", act:"action", desc:"Target a vital point. If you have advantage or the target is within 5 feet of an ally, deal weapon damage plus 1d8 piercing and the target's AC is reduced by 1 until the end of its next turn (doesn't stack).", eff:"Sneak attack bonus + AC reduction.", flavor:"She doesn't aim for the body. She aims for the gap." },
	{ name:"Arterial Cut", lv:3, cls:["Assassin"], mode:"precision", style:"Weapon", dt:"slashing", abl:"Agility", act:"action", desc:"Slice a precise wound that bleeds. On a hit with advantage, deal weapon damage plus 3d6 slashing. The target takes 2d4 bleed damage at the start of each of its turns for 1 minute. A creature can use its action to staunch the wound (DC 14 Medicine).", eff:"Initial damage + persistent bleed.", flavor:"It's a small cut. You'll notice it in about three seconds." },
	{ name:"Organ Failure", lv:5, cls:["Assassin"], mode:"precision", style:"Weapon", dt:"necrotic", abl:"Agility", act:"action", desc:"Target a creature's internal mana node. If you have advantage, on a hit deal weapon damage plus 6d6 necrotic. The target must make DC 16 VIT save or be poisoned for 1 minute (its speed halved, disadvantage on attacks). Save ends.", eff:"Massive precision damage + debilitating poison.", flavor:"The outside looks fine. The inside doesn't." },
	{ name:"Deathmark Strike", lv:7, cls:["Assassin"], mode:"precision", style:"Weapon", dt:"necrotic", abl:"Agility", act:"action", desc:"Deliver the ideal strike. If you have advantage and the attack hits, it automatically crits. The critical deals maximum damage on all dice. The target must make DC 18 VIT save or be stunned for 1 round.", eff:"Guaranteed max crit + stun.", flavor:"The perfect angle. The perfect moment. The perfect end." },
	{ name:"Assassination Protocol", lv:9, cls:["Assassin"], mode:"precision", style:"Ultimate", dt:"necrotic", abl:"Agility", act:"action", desc:"Execute a flawless killing sequence. Make 3 attacks with advantage. Each that hits deals weapon damage plus 5d8 necrotic. If all three hit the same target and it has fewer than 150 HP afterward, it dies instantly (DC 20 VIT negates the instant kill, not the damage).", eff:"Triple precision attack + conditional instant kill.", flavor:"Three cuts. Done." },

	// ═══ STRIKER (unarmed) ═══
	{ name:"Nerve Disruption", lv:1, cls:["Striker"], mode:"unarmed", style:"Martial", dt:"bludgeoning", abl:"Agility", act:"action", desc:"Strike a nerve cluster. Make an unarmed attack; on hit, 1d8+AGI bludgeoning damage and the target must make DC 13 VIT save or lose its reaction until the end of your next turn.", eff:"Damage + reaction denial.", flavor:"The nerve she hit doesn't have a name. It has a number." },
	{ name:"Meridian Cascade", lv:3, cls:["Striker"], mode:"unarmed", style:"Martial", dt:"bludgeoning", abl:"Agility", act:"action", desc:"Strike 5 pressure points in rapid succession. Make 3 unarmed attacks. If 2+ hit the same target, it must make DC 15 VIT save or have its speed reduced to 0 and disadvantage on attacks until end of its next turn.", eff:"Triple attack + conditional paralysis-lite.", flavor:"Five points. Three seconds. Zero movement." },
	{ name:"Gate Breaker Fist", lv:5, cls:["Striker"], mode:"unarmed", style:"Martial", dt:"force", abl:"Agility", act:"action", desc:"Channel mana through your fist for a strike that ignores all resistances and immunities. Make an unarmed attack: 6d10+AGI force damage. Deals double damage to objects and structures. Can target ethereal/incorporeal creatures normally.", eff:"Massive force damage that ignores all defenses.", flavor:"She punches the concept of 'defense.' It breaks." },
	{ name:"One-Inch Impact", lv:7, cls:["Striker"], mode:"unarmed", style:"Martial", dt:"force", abl:"Agility", act:"action", desc:"Deliver a close-range strike of concentrated force. Touch range. On hit: 10d8 force damage and the target is launched 30 feet. If it collides with another creature, both make DC 18 STR saves or take 5d6 bludgeoning and are prone.", eff:"Massive close-range hit + launch + collateral.", flavor:"One inch of movement. Thirty feet of result." },
	{ name:"Final Form", lv:9, cls:["Striker"], mode:"unarmed", style:"Ultimate", dt:"force", abl:"Agility", act:"bonus", desc:"Achieve martial transcendence for 1 minute. Your unarmed strikes deal force damage, your attacks per Attack action become 6, your speed doubles, and you're immune to conditions. Each creature you hit has its AC permanently reduced by 1 (to minimum 10) for the encounter.", eff:"Sustained combat supremacy + AC shred.", flavor:"This is what the body was designed for. Everything before was practice." },

	// ═══ HOLY KNIGHT (radiant) ═══
	{ name:"Smite", lv:1, cls:["Holy Knight"], mode:"radiant", style:"Weapon", dt:"radiant", abl:"Strength", act:"bonus", desc:"Channel your oath through your weapon. On your next hit, deal an extra 2d8 radiant damage. Against undead or fiends, 3d8 instead.", eff:"Bonus radiant damage, extra vs undead/fiends.", flavor:"The light asks no questions. Neither does the blade." },
	{ name:"Radiant Cleave", lv:3, cls:["Holy Knight"], mode:"radiant", style:"Weapon", dt:"radiant", abl:"Strength", act:"action", desc:"Sweep your weapon in an arc of radiant fury. Each creature within 10 feet of you must make DC 15 AGI save: 3d8 radiant on failure, half on success. Allies are unaffected.", eff:"AoE radiant sweep, ally-safe.", flavor:"The light cuts. It cuts very precisely." },
	{ name:"Judgment Strike", lv:5, cls:["Holy Knight"], mode:"radiant", style:"Weapon", dt:"radiant", abl:"Strength", act:"action", desc:"On your next melee hit, deal weapon damage plus 6d8 radiant. The target must make DC 17 PRS save or be blinded until end of its next turn. If it's undead/fiend, it's also paralyzed for 1 round on a failed save.", eff:"Massive radiant + blind + conditional paralysis.", flavor:"The Absolute passes judgment. The sword delivers the verdict." },

	// ═══ TECHNOMANCER (engineered) ═══
	{ name:"Taser Fist", lv:1, cls:["Technomancer"], mode:"engineered", style:"Device", dt:"lightning", abl:"Intelligence", act:"action", desc:"Deliver an electrically charged punch through your combat gauntlet. Melee attack using INT: 1d8+INT lightning damage. On a hit, the target can't take reactions until end of its next turn.", eff:"Lightning melee + reaction denial.", flavor:"Shaking hands was never this exciting." },
	{ name:"EMP Burst", lv:3, cls:["Technomancer"], mode:"engineered", style:"Device", dt:"lightning", abl:"Intelligence", act:"action", desc:"Discharge an electromagnetic pulse in a 15-foot radius. Each creature must make DC 15 INT save: 3d8 lightning on failure, half on success. Constructs and creatures with metal armor have disadvantage on the save. All non-magical electronic devices in the area are disabled for 1 minute.", eff:"AoE lightning + anti-construct/metal + device disable.", flavor:"Everything electronic in the room just died. You're next." },
	{ name:"Railgun Shot", lv:5, cls:["Technomancer"], mode:"engineered", style:"Device", dt:"force", abl:"Intelligence", act:"action", desc:"Fire a hypersonic mana-accelerated projectile. Make a ranged attack (INT) against a creature within 300 feet. On a hit: 8d10 force damage. The projectile pierces through up to 3 creatures in a line — each makes a DC 17 AGI save for half.", eff:"Massive single-target + line pierce.", flavor:"The sound arrives after the impact. So does the pain." },

	// ═══ STALKER (pursuit) ═══
	{ name:"Hamstring", lv:1, cls:["Stalker"], mode:"pursuit", style:"Weapon", dt:"slashing", abl:"Agility", act:"action", desc:"Target a creature's mobility. On a weapon hit, deal weapon damage plus 1d6 slashing. The target's speed is reduced by 15 feet until the end of its next turn. If the target's speed is already reduced, it's also knocked prone.", eff:"Speed reduction + conditional prone.", flavor:"You can't run if you can't walk." },
	{ name:"Entangle Shot", lv:3, cls:["Stalker"], mode:"pursuit", style:"Weapon", dt:"piercing", abl:"Agility", act:"action", desc:"Fire a bolt or arrow wrapped in mana-wire. Ranged weapon attack. On a hit: weapon damage plus 2d6 piercing and the target must make DC 15 STR save or be restrained until it uses an action to break free (DC 15 Athletics/Acrobatics).", eff:"Ranged restraint + damage.", flavor:"The wire holds. The target doesn't." },
	{ name:"Predator's Leap", lv:5, cls:["Stalker"], mode:"pursuit", style:"Movement", dt:"", abl:"Agility", act:"bonus", desc:"Leap up to 40 feet to a space adjacent to a creature you've marked. This movement doesn't provoke opportunity attacks. Your next attack this turn has advantage and deals an extra 3d6 damage.", eff:"Long-range pounce + advantage + bonus damage.", flavor:"Airborne. Descending. Arriving." },

	// ═══ IDOL (dance/blade resonance) ═══
	{ name:"Rhythmic Strike", lv:1, cls:["Idol"], mode:"resonance", style:"Dance", dt:"thunder", abl:"Presence", act:"action", desc:"Channel K-pop fighting style into a flashy melee attack. On a hit, deal 1d8+PRS thunder damage. Each ally within 30 feet who can see you gains +1 to their next attack roll from the inspiring performance.", eff:"Damage + ally buff from performance.", flavor:"Every hit is choreographed. Every hit lands." },
	{ name:"Dance of Blades", lv:3, cls:["Idol"], mode:"resonance", style:"Blade", dt:"slashing", abl:"Presence", act:"action", desc:"Perform an acrobatic weapon flourish, attacking each creature within 5 feet. Make a melee attack against each: weapon damage + 1d6 slashing. For each creature hit, you gain +1 AC until the start of your next turn (max +3).", eff:"Multi-target flourish + scaling AC.", flavor:"The dance has a body count." },
	{ name:"Crescendo Finale", lv:5, cls:["Idol"], mode:"resonance", style:"Performance", dt:"thunder", abl:"Presence", act:"action", desc:"Build to a devastating performance climax. Make 3 melee attacks. Each hit deals weapon damage + 2d6 thunder. If all 3 hit, release a sonic burst: each hostile creature within 15 feet makes DC 16 VIT save or is stunned until end of its next turn.", eff:"Triple attack + conditional AoE stun.", flavor:"The final note. Everyone remembers the final note." },

	// ═══ HERALD (divine) ═══
	{ name:"Sacred Weapon", lv:1, cls:["Herald"], mode:"divine", style:"Weapon", dt:"radiant", abl:"Sense", act:"bonus", desc:"Bless your weapon with the Absolute's light for 1 minute. Your weapon attacks deal an extra 1d4 radiant damage and count as magical. You shed bright light in a 20-foot radius.", eff:"Weapon buff + light + magical damage.", flavor:"The weapon shines. What it hits does not." },
	{ name:"Spiritual Hammer", lv:3, cls:["Herald"], mode:"divine", style:"Summoned", dt:"radiant", abl:"Sense", act:"bonus", desc:"Summon a spectral weapon within 60 feet. As a bonus action each turn, make a melee spell attack (Sense): 2d8+SNS radiant damage. The hammer sheds light and can move 20 feet per turn.", eff:"Sustained bonus-action damage at range.", flavor:"She doesn't swing the hammer. The hammer swings itself." },
	{ name:"War God's Blessing", lv:5, cls:["Herald"], mode:"divine", style:"Blessing", dt:"", abl:"Sense", act:"reaction", desc:"As a reaction when an ally within 30 feet makes an attack roll, add +10 to the roll. Usable once per short rest.", eff:"+10 to an ally's attack roll.", flavor:"The Absolute ensures the blade finds its mark." },

	// ═══ CONTRACTOR (pact) ═══
	{ name:"Pact Blade", lv:1, cls:["Contractor"], mode:"pact", style:"Weapon", dt:"force", abl:"Presence", act:"bonus", desc:"Summon a weapon forged from your patron's essence. The pact blade uses PRS for attack and damage, deals 1d8+PRS force damage, counts as magical, and can be dismissed/resummoned as a bonus action.", eff:"CHA-based magical weapon.", flavor:"Your patron hands you a weapon. Terms and conditions apply." },
	{ name:"Eldritch Riposte", lv:3, cls:["Contractor"], mode:"pact", style:"Reaction", dt:"force", abl:"Presence", act:"reaction", desc:"As a reaction when a creature misses you with a melee attack, make a pact blade attack against it with advantage. On a hit, deal weapon damage plus 2d8 force and push the target 10 feet.", eff:"Counter-attack + force damage + push.", flavor:"You missed. Your patron didn't." },
	{ name:"Patron's Fury", lv:5, cls:["Contractor"], mode:"pact", style:"Weapon", dt:"force", abl:"Presence", act:"action", desc:"Channel your patron's wrath through your blade. Make 3 pact blade attacks. Each hit deals weapon damage plus 2d6 force. If all 3 hit the same target, your patron manifests briefly: the target must make DC 17 PRS save or be frightened for 1 minute.", eff:"Triple attack + conditional fear.", flavor:"Three swings. Three warnings. One patron watching." },

	// ═══ REVENANT (entropy) ═══
	{ name:"Withering Blade", lv:1, cls:["Revenant"], mode:"entropy", style:"Weapon", dt:"necrotic", abl:"Intelligence", act:"action", desc:"Channel entropy into your weapon. On your next hit, deal weapon damage plus 1d6 necrotic. You heal HP equal to the necrotic damage dealt.", eff:"Damage + self-heal.", flavor:"She takes what the blade gives. Fair exchange." },
	{ name:"Death's Reach", lv:3, cls:["Revenant"], mode:"entropy", style:"Weapon", dt:"necrotic", abl:"Intelligence", act:"action", desc:"Extend your weapon's reach with a tendril of necrotic energy. Make a melee weapon attack with 15-foot reach. On a hit, weapon damage plus 3d6 necrotic. The target can't regain HP until the start of your next turn.", eff:"Extended reach + anti-healing.", flavor:"Distance doesn't help. She reaches further." },
	{ name:"Entropy Surge", lv:5, cls:["Revenant"], mode:"entropy", style:"Weapon", dt:"necrotic", abl:"Intelligence", act:"action", desc:"On your next melee hit, deal weapon damage plus 5d8 necrotic. The target must make DC 17 VIT save or its maximum HP is reduced by the necrotic damage dealt until it finishes a long rest. You heal for half.", eff:"Massive necrotic + max HP reduction + self-heal.", flavor:"She doesn't just wound. She diminishes." },
];
