import type { RegentLockExpectation } from "./assertRegentLock";

const COMMON_FOUR_CADENCES = [
	"at-will",
	"long-rest",
	"once-per-day",
	"short-rest",
];
const COMMON_QUEST_PREREQUISITE = "Any base job";

export const REGENT_EXPECTATIONS = {
	umbral_regent: {
		id: "umbral_regent",
		theme: "Umbral and Death",
		quest: "Complete the Umbral Regent Ascension quest series",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 5,
		featureCount: 39,
		frequencies: COMMON_FOUR_CADENCES,
		grants: { spell: true, power: true, technique: false },
		progression: {
			1: ["Umbral Command", "Veilstep Supreme", "Umbral Dominion"],
			2: ["Essence Harvest", "Regent's Presence"],
			3: ["Legion of the Veil", "Umbral Mastery"],
			4: ["Army of the Damned"],
			5: ["Dimensional Regent", "Dimensional Authority"],
			7: ["Umbral Dominion", "Umbral God"],
			10: ["Absolute Umbral"],
		},
	},
	radiant_regent: {
		id: "radiant_regent",
		theme: "White Flames and Purification",
		quest: "Complete the Flame Regent Trials quest series",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 8,
		frequencies: COMMON_FOUR_CADENCES,
		grants: { spell: true, power: true, technique: false },
		progression: {
			1: ["White Flame Mastery", "Immolation Aura", "Flame Dominion"],
			2: ["Regent Power Resonance"],
			3: ["White Flame Burst", "Purification Flame", "Purifying Presence"],
			4: ["Regent Attribute Enhancement"],
			5: ["Seraphim Wings", "Flame Authority", "Phoenix Rebirth"],
			7: ["Flame God", "Purification Lord"],
			10: ["Absolute Flame"],
		},
	},
	steel_regent: {
		id: "steel_regent",
		theme: "Conceptual Invulnerability & Absolutist Defense",
		quest: "Complete the Steel Regent Ascension trials",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 8,
		frequencies: COMMON_FOUR_CADENCES,
		grants: { spell: false, power: true, technique: true },
		progression: {
			1: ["Iron Body", "Immovable Anchor", "Infinite Stamina"],
			2: ["Regent Power Resonance"],
			3: ["Steel Weaving", "Titan's Law", "Conceptual Invulnerability"],
			4: ["Regent Attribute Enhancement"],
			5: ["Iron Dominion", "Titan Authority", "Regeneration Lord"],
			7: ["Organic Manipulation", "Flesh God", "Regeneration Lord"],
			10: ["Steel Authority", "Absolute Flesh"],
		},
	},
	destruction_regent: {
		id: "destruction_regent",
		theme: "Primordial Destruction and Draconic Apocalypse",
		quest: "Complete the Path of Destruction quest series",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 8,
		frequencies: COMMON_FOUR_CADENCES,
		grants: { spell: true, power: true, technique: false },
		progression: {
			1: ["Breath of Annihilation", "Destruction Step", "Destruction Dominion"],
			2: ["Regent Power Resonance"],
			3: ["Annihilation Presence", "Destruction Mastery", "Aura of Ruin"],
			4: ["Regent Attribute Enhancement"],
			5: ["Decimation Field", "True Dragon Form", "Cataclysmic Rebirth"],
			7: ["Vortex Shield", "Destruction God", "Ruin Lord"],
			10: ["Annihilation Authority", "Absolute Destruction"],
		},
	},
	war_regent: {
		id: "war_regent",
		theme: "Tactical Battlefield Supremacy & Absolute Command",
		quest: "Complete the Command Regent Ascension trials",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 8,
		frequencies: COMMON_FOUR_CADENCES,
		grants: { spell: false, power: true, technique: true },
		progression: {
			1: ["Warlord's Command", "Leadership Aura", "War Dominion"],
			2: ["Vanguard Step", "Regent Power Resonance"],
			3: ["Conquest", "Command Mastery", "Leadership Presence"],
			4: ["Regent Attribute Enhancement"],
			5: ["Tactical Step", "Command Authority", "Army Rebirth"],
			7: ["Command Shield", "War God", "Tactical Lord"],
			10: ["Vanguard Authority", "Absolute War"],
		},
	},
	frost_regent: {
		id: "frost_regent",
		theme: "Eternal Winter & absolute Zero",
		quest: "Complete the Trial of the Frost Gate",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 26,
		frequencies: COMMON_FOUR_CADENCES,
		grants: { spell: true, power: true, technique: false },
		progression: {
			1: ["Ice Age Decree", "Frost Dominion"],
			2: ["Regent Power Resonance"],
			3: ["Absolute Zero Touch", "Glacial Eternity"],
			4: ["Regent Attribute Enhancement"],
			5: ["Winter's Immortality"],
			7: ["Cryogenic Prison"],
			10: ["Absolute Frost"],
		},
	},
	beast_regent: {
		id: "beast_regent",
		theme: "Primal Evolution & Apex Regentty",
		quest: "Complete the Trial of the Beast Gate",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 26,
		frequencies: ["at-will", "long-rest", "once-per-day"],
		grants: { spell: false, power: true, technique: true },
		progression: {
			1: ["Apex Form", "Alpha's Presence"],
			2: ["Beast King's Call"],
			3: ["Primordial Regeneration"],
			4: ["Regent Attribute Enhancement"],
			5: ["Evolutionary Leap"],
			7: ["Pack Tactics"],
			10: ["Absolute Beast"],
		},
	},
	plague_regent: {
		id: "plague_regent",
		theme: "Pandemic Incarnate",
		quest: "Complete the Trial of the Plague Gate",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 4,
		frequencies: ["at-will", "long-rest"],
		grants: { spell: true, power: true, technique: false },
		progression: {
			1: ["Typhoid Incarnate", "Insect God"],
			2: ["Pandemic Decree"],
			3: ["Billion Swarm"],
			4: ["Regent Attribute Enhancement"],
			5: ["Pathogen Mastery"],
			7: ["Plague Vector"],
			10: ["Absolute Plague"],
		},
	},
	spatial_regent: {
		id: "spatial_regent",
		theme: "Cosmic Weaving & Dimensional Void",
		quest: "Complete the Trial of the Spatial Gate",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 26,
		frequencies: ["at-will", "long-rest", "once-per-day"],
		grants: { spell: true, power: true, technique: false },
		progression: {
			1: ["Void Singularity", "Planar Blink"],
			2: ["Spatial Anchors"],
			3: ["Dimensional Sanctum"],
			4: ["Regent Attribute Enhancement"],
			5: ["Dimensional Lock"],
			7: ["Lattice Vision"],
			10: ["Absolute Spatial"],
		},
	},
	mimic_regent: {
		id: "mimic_regent",
		theme: "Infinite Forms",
		quest: "Complete the Trial of the Mimic Gate",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 5,
		frequencies: ["at-will", "long-rest"],
		grants: { spell: true, power: true, technique: true },
		progression: {
			1: ["Perfect Imitation", "Power Theft"],
			2: ["Reactive Evolution"],
			3: ["Quantum Existence"],
			4: ["Regent Attribute Enhancement"],
			5: ["Memory Access"],
			7: ["Form Archive"],
			10: ["Absolute Mimic"],
		},
	},
	blood_regent: {
		id: "blood_regent",
		theme: "Hemomancy & Sanguine Regentty",
		quest: "Complete the Sanguine Ritual of the Regent",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 26,
		frequencies: COMMON_FOUR_CADENCES,
		grants: { spell: true, power: true, technique: false },
		progression: {
			1: ["Sanguine Command", "Blood Shield"],
			2: ["Crimson Lance"],
			3: ["Life Drain Aura"],
			4: ["Regent Attribute Enhancement"],
			5: ["Sanguine Rebirth"],
			7: ["Hemocentric Control"],
			10: ["Absolute Blood"],
		},
	},
	gravity_regent: {
		id: "gravity_regent",
		theme: "Gravitational Mastery & Fundamental Force",
		quest: "Complete the Trial of the Star-Crusher",
		prerequisiteJob: COMMON_QUEST_PREREQUISITE,
		powerLevel: 10,
		featureCount: 26,
		frequencies: COMMON_FOUR_CADENCES,
		grants: { spell: true, power: true, technique: true },
		progression: {
			1: ["Gravity Well", "Weightless Step"],
			2: ["Crushing Blows"],
			3: ["Planetary Field"],
			4: ["Regent Attribute Enhancement"],
			5: ["Event Horizon"],
			7: ["Orbital Striker"],
			10: ["Absolute Weight"],
		},
	},
} as const satisfies Record<string, RegentLockExpectation>;
