-- =============================================
-- D&D 5E SRD MONSTERS - CR 1/2 to 4
-- Complete coverage of mid-level monsters
-- =============================================
-- Part 2: CR 1/2, 1, 2, 3, 4 monsters
-- Adapted for Solo Leveling manwha universe
-- Post-Reset Timeline: Supreme Deity (post-reset world)
-- All entries aligned with Solo Leveling setting, theme, tone, and aesthetic

INSERT INTO compendium_monsters (name, size, creature_type, alignment, cr, xp, armor_class, armor_type, hit_points_average, hit_points_formula, speed_walk, str, agi, vit, int, sense, pre, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, description, lore, gate_rank, is_boss, source_book, tags) VALUES

-- =============================================
-- CR 1/2 MONSTERS (D-Rank)
-- =============================================

('Ape', 'Medium', 'Beast', 'Unaligned', '1/2', 100, 12, NULL, 19, '3d8+6', 30, 16, 14, 14, 6, 12, 6, '{}', '{}', '{}', '{}', '{}', '{}', 'Powerful primates mutated by Gate mana in the post-reset world. They can grapple and throw hunters with incredible strength, having adapted to the dangerous Gate ecosystem.', 'After the reset, these apes have grown larger and more aggressive. The Supreme Deity''s influence has stabilized their mutations, creating distinct subspecies adapted to different Gate environments.', 'D', false, 'MM', '{"beast"}'),
('Black Bear', 'Medium', 'Beast', 'Unaligned', '1/2', 100, 11, NULL, 19, '3d8+6', 40, 15, 10, 14, 2, 13, 7, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Aggressive bears found in forest-themed Gates in the post-reset world. Their powerful claws and bite make them dangerous predators that have adapted to Gate environments.', 'After the reset, black bears have become more territorial and aggressive. Gate mana has enhanced their natural abilities, making them formidable opponents for D-Rank hunters.', 'D', false, 'MM', '{"beast"}'),
('Crocodile', 'Large', 'Beast', 'Unaligned', '1/2', 100, 12, NULL, 19, '3d10+3', 20, 15, 10, 13, 2, 10, 5, '{}', '{}', '{}', '{}', '{"passive Perception": 10}', '{}', 'Amphibious reptiles that ambush hunters from water in swamp-themed Gates. They can hold their breath for extended periods and drag hunters underwater in the post-reset world.', 'These crocodiles have grown larger since the reset, as Gate mana has enhanced their natural abilities. They are apex predators in aquatic Gate environments, striking fear into unprepared hunters.', 'D', false, 'MM', '{"beast", "aquatic"}'),
('Darkmantle', 'Small', 'Monstrosity', 'Unaligned', '1/2', 100, 11, NULL, 22, '5d6+5', 10, 16, 12, 13, 2, 11, 5, '{}', '{}', '{}', '{}', '{"blindsight": 60, "passive Perception": 11}', '{}', 'Flying monstrosities created by Gate mana that drop from ceilings in dark Gate corridors. They smother hunters and blend with shadows in the post-reset world.', 'Darkmantles can create magical darkness and use it to ambush hunters. These creatures were spawned from the dimensional rifts and have adapted to hunt in the Gate ecosystem.', 'D', false, 'MM', '{"monstrosity", "flying"}'),
('Deep Gnome (Svirfneblin)', 'Small', 'Humanoid', 'Neutral Good', '1/2', 100, 15, 'stone armor', 16, '3d6+6', 20, 15, 14, 14, 12, 10, 9, '{}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 10}', '{"Gnomish", "Terran", "Undercommon"}', 'Underground-dwelling gnomes with exceptional darkvision found in deep Gate caverns. Skilled miners and stonecrafters who have adapted to survive in the Gate ecosystem.', 'Deep Gnomes have advantage on stealth checks and are resistant to magic. In the post-reset world, they serve as guides for hunters exploring underground Gates, having learned the layout of these dangerous areas.', 'D', false, 'MM', '{"humanoid", "gnome"}'),
('Dust Mephit', 'Small', 'Elemental', 'Neutral Evil', '1/2', 100, 12, NULL, 17, '5d6', 30, 5, 14, 10, 9, 10, 11, '{}', '{}', '{}', '{"poisoned"}', '{"darkvision": 60, "passive Perception": 10}', '{"Auran", "Terran"}', 'Small elemental creatures of dust and sand manifested from Gate mana. Found in desert-themed Gates, they can blind hunters with dust clouds in the post-reset world.', 'When killed, Dust Mephits explode in a blinding cloud of dust. These elementals are formed from concentrated earth and air mana within Gates, serving as guardians of desert Gate environments.', 'D', false, 'MM', '{"elemental"}'),
('Gas Spore', 'Large', 'Plant', 'Unaligned', '1/2', 100, 5, NULL, 1, '1d4-1', 0, 5, 1, 8, 1, 3, 1, '{}', '{}', '{}', '{"poisoned"}', '{"blindsight": 30, "passive Perception": 6}', '{}', 'Floating fungal spores corrupted by Gate mana that mimic beholders. Found in Gate corridors, they explode when destroyed, spreading disease throughout the post-reset world.', 'Gas Spores are deadly traps created by Gate mana contamination - they look like beholders but explode on contact, infecting hunters with disease. These fungi have been enhanced by the System''s influence.', 'D', false, 'MM', '{"plant", "fungus"}'),
('Giant Goat', 'Large', 'Beast', 'Unaligned', '1/2', 100, 11, NULL, 19, '3d10+3', 40, 17, 11, 14, 8, 10, 8, '{}', '{}', '{}', '{}', '{}', '{}', 'Massive goats mutated by Gate mana found in mountainous Gates. Their powerful charges can knock down hunters with devastating force in the post-reset world.', 'After the reset, Giant Goats have grown larger and more aggressive. Gate mana has enhanced their natural charging ability, making them dangerous opponents for D-Rank hunters exploring mountain-themed Gates.', 'D', false, 'MM', '{"beast"}'),
('Giant Sea Horse', 'Large', 'Beast', 'Unaligned', '1/2', 100, 13, NULL, 16, '3d10', 0, 12, 15, 13, 2, 11, 5, '{}', '{}', '{}', '{}', '{"passive Perception": 11}', '{}', 'Massive sea horses enhanced by Gate mana, found in aquatic-themed Gates. Used as mounts by hunters, they can swim with great speed in the post-reset world.', 'These sea horses have been enhanced by Gate mana since the reset, becoming larger and faster. Some hunters train them as mounts for navigating underwater Gate sections.', 'D', false, 'MM', '{"beast", "aquatic"}'),
('Giant Wasp', 'Medium', 'Beast', 'Unaligned', '1/2', 100, 12, NULL, 13, '3d8', 10, 10, 14, 11, 1, 10, 3, '{}', '{}', '{}', '{}', '{"passive Perception": 10}', '{}', 'Massive wasps mutated by Gate mana, found in jungle and forest-themed Gates. Their potent stingers inject paralyzing venom that can incapacitate hunters in the post-reset world.', 'After the reset, these wasps have grown to massive sizes due to Gate mana exposure. Their venom has become more potent, making them a serious threat to unprepared hunters in forest Gate environments.', 'D', false, 'MM', '{"beast", "flying", "poison"}'),
('Gnoll', 'Medium', 'Humanoid', 'Chaotic Evil', '1/2', 100, 15, 'leather armor, shield', 22, '5d8', 30, 14, 12, 14, 8, 11, 7, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 11}', '{"Gnoll"}', 'Hyena-like humanoids corrupted by Gate mana that hunt in packs within Gates. Savage and cannibalistic, they raid Gate corridors and attack hunters in the post-reset world.', 'Gnolls have rampage ability, allowing them to move and make a bite attack as a bonus action when they reduce a hunter to 0 HP. These creatures have been enhanced by Gate mana, becoming more organized and dangerous since the reset.', 'D', false, 'MM', '{"humanoid", "gnoll", "rampage"}'),
('Gray Ooze', 'Medium', 'Ooze', 'Unaligned', '1/2', 100, 8, NULL, 22, '3d8+9', 10, 12, 6, 14, 1, 6, 2, '{"acid", "cold", "fire"}', '{}', '{}', '{"blinded", "charmed", "deafened", "exhaustion", "frightened", "prone"}', '{"blindsight": 60, "blind beyond this radius", "passive Perception": 8}', '{}', 'Amorphous oozes formed from Gate mana contamination that dissolve organic matter. Found throughout Gate corridors, they can corrode weapons and armor on contact in the post-reset world.', 'Gray Oozes are immune to most damage types and can split into smaller oozes. These are manifestations of Gate mana contamination, spreading through Gate environments as dangerous obstacles for hunters.', 'D', false, 'MM', '{"ooze"}'),
('Hobgoblin', 'Medium', 'Humanoid', 'Lawful Evil', '1/2', 100, 18, 'chain mail, shield', 11, '2d8+2', 30, 13, 12, 12, 10, 10, 11, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Common", "Goblin"}', 'Disciplined goblinoids enhanced by Gate mana that fight in organized formations within Gates. More dangerous than regular goblins, they coordinate attacks against hunters in the post-reset world.', 'Hobgoblins have martial advantage, dealing extra damage when an ally is within 5 feet. These creatures have adapted to the Gate ecosystem, becoming more organized and tactical since the reset under the Supreme Deity''s influence.', 'D', false, 'MM', '{"humanoid", "goblinoid", "martial-advantage"}'),
('Ice Mephit', 'Small', 'Elemental', 'Neutral Evil', '1/2', 100, 11, NULL, 21, '6d6+3', 30, 7, 13, 10, 9, 11, 12, '{}', '{"cold"}', '{"fire"}', '{"poisoned"}', '{"darkvision": 60, "passive Perception": 10}', '{"Aquan", "Auran"}', 'Small elemental creatures of ice manifested from Gate mana in frozen Gates. Found in arctic-themed Gates, they can breathe freezing mist that damages hunters in the post-reset world.', 'When killed, Ice Mephits explode in a burst of freezing shards. These elementals are formed from concentrated ice mana within Gates, serving as guardians of frozen Gate environments.', 'D', false, 'MM', '{"elemental", "cold"}'),
('Jackalwere', 'Medium', 'Humanoid', 'Chaotic Evil', '1/2', 100, 12, NULL, 18, '4d8', 40, 11, 15, 10, 13, 11, 11, '{}', '{}', '{}', '{"charmed"}', '{"passive Perception": 11}', '{"Common"}', 'Shape-changing jackals corrupted by Gate mana that can assume human form. Found in desert Gates, their gaze can put hunters to sleep in the post-reset world.', 'Jackalweres use sleep gaze to incapacitate hunters before attacking. These creatures have been enhanced by Gate mana, becoming more dangerous infiltrators since the reset.', 'D', false, 'MM', '{"humanoid", "shapechanger"}'),
('Lizardfolk', 'Medium', 'Humanoid', 'Neutral', '1/2', 100, 15, 'leather armor, shield', 22, '4d8+4', 30, 15, 10, 13, 7, 12, 12, '{}', '{}', '{}', '{}', '{}', '{"Draconic"}', 'Reptilian humanoids that dwell in swamp-themed Gates. Adapted to Gate environments, they can hold their breath for extended periods and have natural armor in the post-reset world.', 'Lizardfolk have adapted to survive in the Gate ecosystem. Some have learned to coexist with hunters, while others remain hostile. Their natural abilities have been enhanced by Gate mana since the reset.', 'D', false, 'MM', '{"humanoid", "lizardfolk"}'),
('Magma Mephit', 'Small', 'Elemental', 'Neutral Evil', '1/2', 100, 11, NULL, 22, '5d6+5', 30, 8, 12, 13, 10, 10, 10, '{}', '{"fire"}', '{"cold"}', '{"poisoned"}', '{"darkvision": 60, "passive Perception": 10}', '{"Ignan", "Terran"}', 'Small elemental creatures of magma manifested from Gate mana in volcanic Gates. Found in volcano-themed Gates, they can breathe fire that burns hunters in the post-reset world.', 'When killed, Magma Mephits explode in a burst of lava. These elementals are formed from concentrated fire and earth mana within Gates, serving as guardians of volcanic Gate environments.', 'D', false, 'MM', '{"elemental", "fire"}'),
('Magmin', 'Small', 'Elemental', 'Chaotic Neutral', '1/2', 100, 14, NULL, 9, '2d6+2', 30, 7, 15, 13, 8, 10, 10, '{}', '{"fire"}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Ignan"}', 'Small fire elementals manifested from Gate mana that ignite everything they touch. Found in volcanic Gates, they explode when killed, spreading fire in the post-reset world.', 'Magmins can set flammable objects on fire and deal fire damage to hunters that touch them. These elementals are formed from concentrated fire mana within Gates, making them dangerous to approach.', 'D', false, 'MM', '{"elemental", "fire"}'),
('Orc', 'Medium', 'Humanoid', 'Chaotic Evil', '1/2', 100, 13, 'hide armor', 15, '2d8+6', 30, 16, 12, 16, 7, 11, 10, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Common", "Orc"}', 'Brutish humanoids corrupted by Gate mana that dominate mid-rank Gates. They are strong but lack tactical sophistication, attacking hunters on sight in the post-reset world.', 'Orcs have aggressive ability, allowing them to move up to their speed toward hunters as a bonus action. These creatures have been enhanced by Gate mana, becoming more numerous and dangerous since the reset.', 'D', false, 'MM', '{"humanoid", "orc", "aggressive"}'),
('Piercer', 'Medium', 'Monstrosity', 'Unaligned', '1/2', 100, 15, NULL, 22, '4d8+4', 5, 10, 13, 13, 1, 14, 2, '{}', '{}', '{}', '{"blinded", "deafened", "frightened"}', '{"blindsight": 30, "passive Perception": 12}', '{}', 'Cave-dwelling monstrosities created by Gate mana that drop from ceilings in Gate caverns. They resemble stalactites until they strike hunters in the post-reset world.', 'Piercers have false appearance, appearing as normal stalactites until they attack. These creatures are perfect ambush predators, having adapted to blend with Gate cave environments since the reset.', 'D', false, 'MM', '{"monstrosity", "ambush"}'),
('Reef Shark', 'Medium', 'Beast', 'Unaligned', '1/2', 100, 12, NULL, 22, '4d8+4', 0, 14, 13, 13, 1, 10, 4, '{}', '{}', '{}', '{}', '{"blindsight": 30, "passive Perception": 12}', '{}', 'Aggressive sharks found in aquatic Gates. Attack when they smell blood.', 'Reef Sharks have blood frenzy, gaining advantage on attacks against bleeding creatures.', 'D', false, 'MM', '{"beast", "aquatic", "blood-frenzy"}'),
('Rust Monster', 'Medium', 'Monstrosity', 'Unaligned', '1/2', 100, 14, NULL, 27, '5d8+5', 40, 13, 12, 13, 2, 13, 6, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 13}', '{}', 'Monstrosities created by Gate mana that consume metal. Found throughout Gates, their antennae can rust and destroy hunters'' weapons and armor in the post-reset world.', 'Rust Monsters can destroy nonmagical metal objects instantly on contact. These creatures are feared by hunters for their ability to render equipment useless, having become more common since the reset.', 'D', false, 'MM', '{"monstrosity", "rust"}'),
('Sahuagin', 'Medium', 'Humanoid', 'Lawful Evil', '1/2', 100, 12, NULL, 22, '4d8+4', 30, 13, 11, 12, 12, 13, 9, '{}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 13}', '{"Sahuagin"}', 'Aquatic humanoids with shark-like features corrupted by Gate mana. Found in ocean-themed Gates, they are excellent swimmers and fierce warriors who attack hunters in the post-reset world.', 'Sahuagin have blood frenzy and can call sharks to their aid when underwater. These creatures have adapted to the Gate ecosystem, becoming more organized and dangerous since the reset.', 'D', false, 'MM', '{"humanoid", "aquatic", "blood-frenzy"}'),
('Satyr', 'Medium', 'Fey', 'Chaotic Neutral', '1/2', 100, 14, 'leather armor', 31, '7d8', 40, 12, 16, 11, 12, 10, 10, '{}', '{}', '{}', '{"charmed", "frightened"}', '{"passive Perception": 10}', '{"Common", "Elvish", "Sylvan"}', 'Musical fey creatures drawn to Gate mana, found in forest-themed Gates. With goat legs and magical pipes, they can charm hunters in the post-reset world.', 'Satyrs can use pipes to charm hunters, forcing them to dance helplessly. These fey are drawn to areas of high Gate mana concentration, using their connection to nature to manipulate Gate environments.', 'D', false, 'MM', '{"fey", "charm"}'),
('Scout', 'Medium', 'Humanoid', 'Any', '1/2', 100, 13, 'leather armor', 16, '3d8+3', 30, 11, 14, 12, 11, 13, 11, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Skilled rangers who patrol Gates, either serving as advance scouts for hunter teams or as independent explorers. Excellent trackers and archers in the post-reset world.', 'Scouts have keen hearing and sight, and excel at tracking and survival within Gate environments. Many are former hunters who specialize in reconnaissance and Gate exploration.', 'D', false, 'MM', '{"humanoid"}'),
('Shadow', 'Medium', 'Undead', 'Chaotic Evil', '1/2', 100, 12, NULL, 16, '3d8', 40, 6, 14, 13, 6, 10, 8, '{"acid", "cold", "fire", "lightning", "thunder"}', '{"necrotic", "poison"}', '{"radiant"}', '{"exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"}', '{"darkvision": 60, "passive Perception": 10}', '{}', 'Incorporeal undead that drain strength with their touch. In the post-reset world, the weakened boundary between life and death allows these shadows to persist longer and become more common in dark Gate corridors.', 'Shadows can hide as a bonus action and reduce Strength scores with their touch. These undead are drawn to areas of shadow mana, often found in Gates with strong necromantic energy.', 'D', false, 'MM', '{"undead", "incorporeal"}'),
('Swarm of Insects', 'Medium', 'Beast', 'Unaligned', '1/2', 100, 12, NULL, 22, '5d8', 20, 3, 13, 10, 1, 10, 3, '{"bludgeoning", "piercing", "slashing"}', '{}', '{}', '{"charmed", "frightened", "grappled", "paralyzed", "petrified", "prone", "restrained", "stunned"}', '{"blindsight": 10, "passive Perception": 8}', '{}', 'A cloud of biting insects mutated by Gate mana. Found throughout Gates, the swarm obscures vision and can cause disease among hunters in the post-reset world.', 'Swarms can blind hunters and spread disease through their bites. These insects have been enhanced by Gate mana, becoming larger and more aggressive since the reset, forming dangerous swarms in Gate environments.', 'D', false, 'MM', '{"beast", "swarm", "disease"}'),
('Troglodyte', 'Medium', 'Humanoid', 'Chaotic Evil', '1/2', 100, 11, NULL, 13, '2d8+4', 30, 14, 10, 12, 8, 10, 10, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Troglodyte"}', 'Reptilian humanoids corrupted by Gate mana that dwell in dark Gate caves. They emit a stench that can sicken hunters in the post-reset world.', 'Troglodytes have stench that forces nearby hunters to make Constitution saves or be poisoned. These creatures have adapted to Gate environments, becoming more common in underground Gate sections since the reset.', 'D', false, 'MM', '{"humanoid", "stench"}'),
('Vulture', 'Medium', 'Beast', 'Unaligned', '0', 0, 10, NULL, 5, '2d4', 10, 7, 10, 12, 2, 13, 3, '{}', '{}', '{}', '{}', '{}', '{}', 'Carrion birds that scavenge Gate battlefields in the post-reset world. They circle overhead when death is near, drawn to the aftermath of hunter-monster conflicts.', 'Vultures have learned to follow hunters into Gates, feeding on the remains of both monsters and fallen hunters. Their presence often signals danger ahead in Gate corridors.', 'E', false, 'MM', '{"beast", "flying"}'),
('Warhorse', 'Large', 'Beast', 'Unaligned', '1/2', 100, 11, NULL, 19, '3d10+3', 60, 18, 12, 13, 2, 11, 7, '{}', '{}', '{}', '{}', '{}', '{}', 'Trained warhorses used by mounted hunters for Gate exploration in the post-reset world. Well-trained and fearless in battle, they serve as reliable mounts for hunter teams.', 'Warhorses can be trained to attack monsters and are not easily frightened by Gate creatures. Some hunters specialize in mounted combat, using these horses to navigate large Gate areas more efficiently.', 'D', false, 'MM', '{"beast"}'),
('Warhorse Skeleton', 'Large', 'Undead', 'Lawful Evil', '1/2', 100, 13, NULL, 22, '3d10+6', 60, 18, 12, 16, 2, 8, 5, '{"bludgeoning"}', '{"poison"}', '{}', '{}', '{"darkvision": 60, "passive Perception": 8}', '{}', 'Undead horses animated by Gate necromancy that serve as mounts for skeletal riders. Found in Gates with strong undead presence, they never tire and never flee in the post-reset world.', 'In the post-reset world, the weakened boundary between life and death allows these undead mounts to persist longer. They are often encountered alongside skeletal warriors in necromantic Gate areas.', 'D', false, 'MM', '{"undead", "skeleton"}'),
('Worg', 'Large', 'Monstrosity', 'Neutral Evil', '1/2', 100, 13, NULL, 26, '4d10+4', 50, 16, 13, 13, 7, 11, 8, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 11}', '{"Goblin", "Worg"}', 'Giant, intelligent wolves created by Gate mana that serve goblinoids. Found in Gates, they can speak and are cunning pack hunters that coordinate attacks against hunters in the post-reset world.', 'Worgs can understand and speak languages, making them dangerous pack leaders. These monstrosities have been enhanced by Gate mana, becoming more intelligent and organized since the reset.', 'D', false, 'MM', '{"monstrosity", "pack-tactics"}'),

-- =============================================
-- CR 1 MONSTERS (D-Rank to C-Rank)
-- =============================================

('Brown Bear', 'Large', 'Beast', 'Unaligned', '1', 200, 11, NULL, 34, '4d10+12', 40, 19, 10, 16, 2, 13, 7, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Massive bears mutated by Gate mana with incredible strength. Found in forest-themed Gates, they can grapple and maul hunters with multiple attacks in the post-reset world.', 'After the reset, brown bears have grown larger and more aggressive. Gate mana has enhanced their natural abilities, making them apex predators in forest Gate environments that strike fear into D-Rank hunters.', 'D', false, 'MM', '{"beast"}'),
('Dire Wolf', 'Large', 'Beast', 'Unaligned', '1', 200, 14, NULL, 37, '5d10+10', 50, 17, 15, 15, 3, 12, 7, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Giant wolves mutated by Gate mana that hunt in packs within Gates. Their powerful bite can knock hunters prone, making them dangerous pack predators in the post-reset world.', 'Dire Wolves have pack tactics and can knock hunters prone with their bite. These beasts have been enhanced by Gate mana, becoming larger and more coordinated since the reset.', 'D', false, 'MM', '{"beast", "pack-tactics"}'),
('Giant Eagle', 'Large', 'Beast', 'Neutral Good', '1', 200, 13, NULL, 26, '4d10+4', 10, 16, 17, 13, 8, 14, 10, '{}', '{}', '{}', '{}', '{"keen Sight": true, "passive Perception": 14}', '{"Giant Eagle", "understands Common and Auran but cannot speak"}', 'Massive eagles enhanced by Gate mana that can serve as mounts for hunters. Intelligent and noble creatures found in mountain-themed Gates in the post-reset world.', 'Giant Eagles can be trained as mounts and are highly intelligent. Some hunters have formed bonds with these creatures, using them for aerial reconnaissance in high-altitude Gates.', 'D', false, 'MM', '{"beast", "flying"}'),
('Giant Hyena', 'Large', 'Beast', 'Unaligned', '1', 200, 12, NULL, 45, '7d10+7', 50, 16, 14, 14, 2, 13, 6, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Massive hyenas mutated by Gate mana that hunt in packs within Gates. Their unsettling laugh and powerful bite make them dangerous pack predators in the post-reset world.', 'Giant Hyenas have rampage ability, allowing them to move and bite as a bonus action when they reduce a hunter to 0 HP. These beasts have been enhanced by Gate mana, becoming more aggressive since the reset.', 'D', false, 'MM', '{"beast", "pack-tactics", "rampage"}'),
('Giant Octopus', 'Large', 'Beast', 'Unaligned', '1', 200, 11, NULL, 52, '8d10+8', 10, 17, 13, 13, 4, 10, 4, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{}', 'Massive octopuses enhanced by Gate mana found in aquatic Gates. They can grapple multiple hunters with their tentacles and change color to blend with Gate environments in the post-reset world.', 'Giant Octopuses can grapple with their tentacles and hold multiple hunters at once. These creatures have been enhanced by Gate mana, becoming larger and more intelligent since the reset.', 'D', false, 'MM', '{"beast", "aquatic", "grapple"}'),
('Giant Spider', 'Large', 'Beast', 'Unaligned', '1', 200, 14, NULL, 26, '4d10+4', 30, 14, 16, 12, 2, 11, 4, '{}', '{}', '{}', '{}', '{"blindsight": 10, "darkvision": 60, "passive Perception": 10}', '{}', 'Massive arachnids mutated by Gate mana with potent venom. Found in cave and forest Gates, they can spin webs to trap hunters in the post-reset world.', 'Giant Spiders can use webs to restrain hunters and poison them with their bite. These creatures have been enhanced by Gate mana, becoming larger and more aggressive since the reset.', 'D', false, 'MM', '{"beast", "poison", "web"}'),
('Giant Toad', 'Large', 'Beast', 'Unaligned', '1', 200, 11, NULL, 39, '7d10+3', 20, 15, 13, 13, 2, 11, 5, '{}', '{}', '{}', '{}', '{"darkvision": 30, "passive Perception": 11}', '{}', 'Massive toads mutated by Gate mana found in swamp-themed Gates. They can swallow small hunters whole, and their tongue can grapple larger targets in the post-reset world.', 'Giant Toads can grapple with their bite and swallow hunters smaller than themselves. These creatures have been enhanced by Gate mana, becoming larger and more aggressive since the reset.', 'D', false, 'MM', '{"beast", "amphibian", "swallow"}'),
('Giant Vulture', 'Large', 'Beast', 'Neutral Evil', '1', 200, 10, NULL, 22, '4d10', 10, 15, 10, 12, 2, 12, 7, '{}', '{}', '{}', '{}', '{"passive Perception": 12}', '{"understands Common but cannot speak"}', 'Massive vultures enhanced by Gate mana that scavenge Gate battlefields in the post-reset world. They attack injured hunters, drawn to the scent of blood and death in Gate environments.', 'These vultures have learned to follow hunters into Gates, feeding on both monster and hunter remains. Their presence often signals recent combat or danger ahead in Gate corridors.', 'D', false, 'MM', '{"beast", "flying"}'),
('Goblin Boss', 'Small', 'Humanoid', 'Neutral Evil', '1', 200, 17, 'leather armor, shield', 21, '6d6', 30, 10, 14, 12, 10, 10, 10, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Common", "Goblin"}', 'Goblins enhanced by Gate mana who have proven their worth in battle. They lead war bands and coordinate attacks against hunters within Gates in the post-reset world.', 'Goblin Bosses can command other goblins, allowing them to make an extra attack. These leaders have adapted to the Gate ecosystem, becoming more organized and tactical since the reset.', 'D', false, 'MM', '{"humanoid", "goblinoid", "leader"}'),
('Half-Ogre', 'Large', 'Giant', 'Chaotic Evil', '1', 200, 12, 'hide armor', 30, '4d10+8', 30, 17, 10, 15, 7, 10, 9, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Common", "Giant"}', 'Brutal half-breeds between ogres and humans, created through Gate mana corruption or dark experiments. Found in Gates, they are stronger and smarter than full ogres in the post-reset world.', 'Half-Ogres are the result of Gate mana experiments or curses that blend human and ogre essence. Some serve as elite warriors for monster armies within high-rank Gates.', 'D', false, 'MM', '{"giant"}'),
('Hippogriff', 'Large', 'Monstrosity', 'Unaligned', '1', 200, 11, NULL, 19, '3d10+3', 40, 17, 13, 13, 2, 12, 8, '{}', '{}', '{}', '{}', '{"passive Perception": 11}', '{}', 'Hybrid creatures created by Gate mana with the body of a horse and head of an eagle. Found in mountain-themed Gates, they can serve as flying mounts for hunters in the post-reset world.', 'Hippogriffs are perfect examples of Gate mana creating hybrid monstrosities. Some hunters have learned to train these creatures as mounts, using them for aerial Gate exploration.', 'D', false, 'MM', '{"monstrosity", "flying"}'),
('Lion', 'Large', 'Beast', 'Unaligned', '1', 200, 12, NULL, 26, '4d10+4', 50, 17, 15, 13, 3, 12, 8, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Powerful big cats mutated by Gate mana that hunt in prides within Gates. Found in savanna-themed Gates, their pounce can knock hunters prone in the post-reset world.', 'Lions use pounce to move and make a bite attack, potentially knocking hunters prone. These beasts have been enhanced by Gate mana, becoming larger and more coordinated since the reset.', 'D', false, 'MM', '{"beast", "pounce", "pack-tactics"}'),
('Quadrone', 'Medium', 'Construct', 'Lawful Neutral', '1', 200, 16, NULL, 22, '4d8+4', 30, 12, 14, 13, 10, 10, 11, '{}', '{"poison"}', '{}', '{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"}', '{"true Sight": 120, "passive Perception": 10}', '{"understands all languages but cannot speak"}', 'Modron constructs manifested by the System to patrol Gate boundaries. Found in organized Gate areas, they fight with mechanical precision in the post-reset world.', 'Quadrones are part of a hierarchy and can call for reinforcements. These constructs were created by powerful hunters or manifested by the System itself to serve as guardians within certain Gate types.', 'D', false, 'MM', '{"construct", "modron"}'),
('Quaggoth', 'Medium', 'Humanoid', 'Chaotic Neutral', '1', 200, 13, NULL, 45, '6d8+18', 30, 17, 12, 16, 6, 12, 9, '{}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 12}', '{"Undercommon"}', 'Fierce humanoids corrupted by Gate mana that dwell in deep Gate caves. They go berserk in battle, becoming more dangerous and unpredictable in the post-reset world.', 'Quaggoths have berserker ability, entering a rage when they take damage. These creatures have been enhanced by Gate mana, becoming more aggressive and powerful since the reset.', 'D', false, 'MM', '{"humanoid", "berserker"}'),
('Spy', 'Medium', 'Humanoid', 'Any', '1', 200, 12, NULL, 27, '6d8', 30, 10, 15, 12, 12, 11, 14, '{}', '{}', '{}', '{}', '{}', '{"Any two languages"}', 'Skilled infiltrators who gather information in Gates, either serving hunter guilds or operating independently. Excellent at stealth and disguise in the post-reset world.', 'Spies excel at stealth, disguise, and deception, making them valuable assets or dangerous adversaries. Some work for the Hunter Association, while others serve criminal organizations operating within Gates.', 'D', false, 'MM', '{"humanoid", "spy"}'),
('Swarm of Quippers', 'Medium', 'Beast', 'Unaligned', '1', 200, 13, NULL, 28, '8d8-8', 0, 13, 16, 11, 1, 7, 2, '{"bludgeoning", "piercing", "slashing"}', '{}', '{}', '{"charmed", "frightened", "grappled", "paralyzed", "petrified", "prone", "restrained", "stunned"}', '{"darkvision": 60}', '{}', 'A school of vicious piranha-like fish mutated by Gate mana. Found in aquatic Gates, the swarm can strip a hunter to bone in seconds in the post-reset world.', 'Swarms of Quippers are drawn to blood and deal extra damage to bleeding hunters. These fish have been enhanced by Gate mana, becoming larger and more aggressive since the reset.', 'D', false, 'MM', '{"beast", "swarm", "aquatic", "blood-frenzy"}'),
('Thug', 'Medium', 'Humanoid', 'Any Non-Lawful', '1', 200, 11, 'leather armor', 32, '5d8+10', 30, 15, 11, 14, 9, 10, 11, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Violent criminals who raid Gates for loot, using intimidation and force against hunters. They attack in groups and fight dirty in the post-reset world.', 'Thugs have pack tactics and can make two attacks per turn. These criminals operate in the shadows of the new world order, despite the Supreme Deity''s influence, raiding Gates for personal gain.', 'D', false, 'MM', '{"humanoid", "pack-tactics"}'),
('Tiger', 'Large', 'Beast', 'Unaligned', '1', 200, 12, NULL, 37, '5d10+10', 40, 17, 15, 14, 3, 12, 8, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 13}', '{}', 'Stealthy predators mutated by Gate mana that pounce from ambush in jungle-themed Gates. Their powerful pounce can knock hunters prone in the post-reset world.', 'Tigers use pounce to move and make a bite attack, potentially knocking hunters prone. These beasts have been enhanced by Gate mana, becoming larger and more dangerous since the reset.', 'D', false, 'MM', '{"beast", "pounce", "stealth"}'),
('Yuan-ti Pureblood', 'Medium', 'Humanoid', 'Neutral Evil', '1', 200, 11, NULL, 40, '9d8', 30, 11, 12, 11, 13, 10, 14, '{}', '{"poison"}', '{}', '{"poisoned"}', '{"darkvision": 60, "passive Perception": 10}', '{"Abyssal", "Common", "Draconic"}', 'Snake-like humanoids corrupted by Gate mana who can cast spells. Found in Gates and sometimes blending with human society, they infiltrate hunter organizations in the post-reset world.', 'Yuan-ti Purebloods have magic resistance and can cast spells like charm person. These creatures have been enhanced by Gate mana, becoming more dangerous infiltrators since the reset, using deception to operate within hunter society.', 'D', false, 'MM', '{"humanoid", "spellcaster", "magic-resistance"}')

ON CONFLICT (name) DO NOTHING;

-- Continue with CR 2-4 monsters in next part...

