-- =============================================
-- D&D 5E SRD MONSTERS - CR 0 to 1
-- Complete coverage of all low-level monsters
-- =============================================
-- This is Part 1 of the complete D&D 5e monster manual
-- Adapted for Solo Leveling manwha universe
-- Post-Reset Timeline: Supreme Deity (post-reset world)
-- All entries aligned with Solo Leveling setting, theme, tone, and aesthetic

INSERT INTO compendium_monsters (name, size, creature_type, alignment, cr, xp, armor_class, armor_type, hit_points_average, hit_points_formula, speed_walk, str, agi, vit, int, sense, pre, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, description, lore, gate_rank, is_boss, source_book, tags) VALUES

-- =============================================
-- CR 0 MONSTERS (E-Rank)
-- =============================================

-- Tiny Beasts
('Awakened Shrub', 'Small', 'Plant', 'Unaligned', '0', 0, 9, NULL, 10, '3d4+3', 20, 3, 8, 11, 10, 10, 9, '{}', '{"poison"}', '{"fire"}', '{}', '{}', '{"one language known by its creator"}', 'A shrub animated by druidic magic or Gate mana. It defends its territory with surprising ferocity.', NULL, 'E', false, 'MM', '{"plant"}'),
('Baboon', 'Small', 'Beast', 'Unaligned', '0', 0, 12, NULL, 3, '1d6', 30, 8, 14, 10, 4, 11, 4, '{}', '{}', '{}', '{}', '{}', '{}', 'Aggressive primates found in jungle-themed Gates. Attack in packs when threatened.', 'These creatures exhibit pack tactics, granting advantage when allies are nearby.', 'E', false, 'MM', '{"beast", "pack-tactics"}'),
('Badger', 'Tiny', 'Beast', 'Unaligned', '0', 0, 10, NULL, 3, '1d4+1', 20, 4, 11, 10, 2, 11, 2, '{}', '{}', '{}', '{}', '{"darkvision": 30}', '{}', 'Small burrowing mammals. Tenacious fighters despite their size.', NULL, 'E', false, 'MM', '{"beast"}'),
('Bat', 'Tiny', 'Beast', 'Unaligned', '0', 0, 12, NULL, 1, '1d4-1', 5, 2, 15, 8, 2, 12, 4, '{}', '{}', '{}', '{}', '{"blindsight": 60, "passive Perception": 11}', '{}', 'Flying mammals that roost in dark Gate chambers. Use echolocation to navigate.', NULL, 'E', false, 'MM', '{"beast", "flying"}'),
('Cat', 'Tiny', 'Beast', 'Unaligned', '0', 0, 12, NULL, 2, '1d4', 40, 3, 15, 10, 3, 12, 7, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 13}', '{}', 'Domesticated felines. Exceptionally agile but pose no real threat.', NULL, 'E', false, 'MM', '{"beast"}'),
('Commoner', 'Medium', 'Humanoid', 'Any', '0', 0, 10, NULL, 4, '1d8', 30, 10, 10, 10, 10, 10, 10, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Ordinary humans caught in Gates in the post-reset world. They flee rather than fight, hoping the Supreme Deity''s influence will protect them.', 'Commoners who survive Gate encounters sometimes awaken as E-Rank hunters. In the post-reset timeline, the System is more generous with awakenings, and the Supreme Deity''s presence has stabilized the world.', 'E', false, 'MM', '{"humanoid"}'),
('Crab', 'Tiny', 'Beast', 'Unaligned', '0', 0, 11, 'natural armor', 2, '1d4', 20, 2, 11, 10, 1, 10, 1, '{}', '{}', '{}', '{}', '{"blindsight": 30}', '{}', 'A small crustacean commonly found in coastal Gates. Harmless but numerous.', NULL, 'E', false, 'MM', '{"beast", "aquatic"}'),
('Deer', 'Medium', 'Beast', 'Unaligned', '0', 0, 13, NULL, 4, '1d8', 50, 11, 16, 10, 2, 14, 5, '{}', '{}', '{}', '{}', '{}', '{}', 'Swift herbivores found in forest Gates. Flee rather than fight.', NULL, 'E', false, 'MM', '{"beast"}'),
('Eagle', 'Small', 'Beast', 'Unaligned', '0', 0, 12, NULL, 3, '1d6', 10, 6, 15, 10, 2, 14, 7, '{}', '{}', '{}', '{}', '{"keen Sight": true, "passive Perception": 14}', '{}', 'Majestic birds of prey. Sharp vision makes them excellent scouts.', NULL, 'E', false, 'MM', '{"beast", "flying"}'),
('Frog', 'Tiny', 'Beast', 'Unaligned', '0', 0, 11, NULL, 1, '1d4-1', 20, 1, 13, 8, 1, 10, 1, '{}', '{}', '{}', '{}', '{"darkvision": 30}', '{}', 'Common amphibians found in damp Gate areas. Completely harmless.', NULL, 'E', false, 'MM', '{"beast", "amphibian"}'),
('Giant Fire Beetle', 'Small', 'Beast', 'Unaligned', '0', 0, 13, NULL, 4, '1d6+1', 30, 8, 10, 11, 1, 7, 3, '{}', '{}', '{}', '{}', '{"blindsight": 30, "passive Perception": 8}', '{}', 'Large beetles that glow with bioluminescence. Their light can illuminate dark Gates.', 'The glands that produce their light can be harvested for illumination.', 'E', false, 'MM', '{"beast"}'),
('Goat', 'Medium', 'Beast', 'Unaligned', '0', 0, 10, NULL, 4, '1d8', 40, 12, 10, 11, 3, 11, 5, '{}', '{}', '{}', '{}', '{}', '{}', 'Hardy mountain animals. Their charge can knock down unwary hunters.', NULL, 'E', false, 'MM', '{"beast"}'),
('Hawk', 'Tiny', 'Beast', 'Unaligned', '0', 0, 13, NULL, 1, '1d4-1', 10, 5, 16, 8, 2, 14, 8, '{}', '{}', '{}', '{}', '{"keen Sight": true, "passive Perception": 14}', '{}', 'Swift birds of prey. Excellent vision for scouting Gate terrain.', NULL, 'E', false, 'MM', '{"beast", "flying"}'),
('Homunculus', 'Tiny', 'Construct', 'Neutral', '0', 0, 13, NULL, 5, '2d4', 20, 4, 15, 11, 10, 10, 5, '{}', '{"poison"}', '{}', '{"charmed", "poisoned"}', '{"darkvision": 60, "passive Perception": 10}', '{"understands the languages of its creator but cannot speak"}', 'Tiny constructs created by mages. They serve as eyes and ears for their masters.', 'Homunculi can deliver touch spells for their creators from great distances.', 'E', false, 'MM', '{"construct"}'),
('Hyena', 'Medium', 'Beast', 'Unaligned', '0', 0, 11, NULL, 5, '2d4', 50, 11, 13, 12, 2, 12, 5, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Pack hunters that laugh as they attack. More dangerous in groups.', NULL, 'E', false, 'MM', '{"beast", "pack-tactics"}'),
('Jackal', 'Small', 'Beast', 'Unaligned', '0', 0, 12, NULL, 3, '1d6', 40, 8, 15, 10, 3, 12, 6, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Small canines that scavenge Gate remains. Travel in packs.', NULL, 'E', false, 'MM', '{"beast"}'),
('Lemure', 'Medium', 'Fiend', 'Lawful Evil', '0', 0, 7, NULL, 13, '3d8', 15, 10, 5, 11, 1, 11, 3, '{}', '{"fire", "poison"}', '{}', '{"charmed", "frightened", "poisoned"}', '{"darkvision": 120, "passive Perception": 10}', '{"understands Infernal but cannot speak"}', 'The lowest form of devil. Grotesque, writhing masses of flesh without clear form.', 'Lemures are created from damned souls and serve as cannon fodder in hell''s armies.', 'E', false, 'MM', '{"fiend", "devil"}'),
('Lizard', 'Tiny', 'Beast', 'Unaligned', '0', 0, 10, NULL, 2, '1d4', 20, 2, 11, 8, 1, 10, 3, '{}', '{}', '{}', '{}', '{"darkvision": 30}', '{}', 'Common reptiles found in warm Gates. Harmless.', NULL, 'E', false, 'MM', '{"beast"}'),
('Myconid Sprout', 'Small', 'Plant', 'Lawful Neutral', '0', 0, 10, NULL, 7, '2d4+2', 10, 6, 10, 11, 10, 10, 3, '{}', '{"poison"}', '{}', '{}', '{"darkvision": 120, "passive Perception": 10}', '{}', 'Young myconids that have not yet developed full intelligence. Found in underground Gate colonies.', NULL, 'E', false, 'MM', '{"plant", "fungus"}'),
('Octopus', 'Small', 'Beast', 'Unaligned', '0', 0, 12, NULL, 3, '1d6', 5, 4, 15, 11, 3, 13, 4, '{}', '{}', '{}', '{}', '{"darkvision": 30, "passive Perception": 13}', '{}', 'Intelligent cephalopods found in aquatic Gates. Can change color and squeeze through tight spaces.', NULL, 'E', false, 'MM', '{"beast", "aquatic"}'),
('Owl', 'Tiny', 'Beast', 'Unaligned', '0', 0, 11, NULL, 1, '1d4-1', 5, 3, 13, 8, 2, 15, 8, '{}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 13}', '{}', 'Nocturnal birds with exceptional night vision. Silent flight makes them excellent scouts.', NULL, 'E', false, 'MM', '{"beast", "flying"}'),
('Quipper', 'Tiny', 'Beast', 'Unaligned', '0', 0, 13, NULL, 1, '1d4-1', 0, 2, 16, 8, 1, 9, 2, '{}', '{}', '{}', '{}', '{"darkvision": 60}', '{}', 'Vicious piranha-like fish that attack in schools. Found in aquatic Gates.', 'These fish are drawn to blood and can strip a creature to bone in minutes.', 'E', false, 'MM', '{"beast", "aquatic", "swarm"}'),
('Rat', 'Tiny', 'Beast', 'Unaligned', '0', 0, 10, NULL, 1, '1d4-1', 20, 2, 11, 9, 2, 10, 4, '{}', '{}', '{}', '{}', '{"darkvision": 30}', '{}', 'Common pests that infest low-rank Gates in the post-reset world. Attack in swarms but are individually weak.', 'Gate Rats carry mana contamination from the System and can spread it to other creatures. After the reset, their numbers have increased as Gate mana has become more concentrated.', 'E', false, 'MM', '{"beast", "swarm"}'),
('Raven', 'Tiny', 'Beast', 'Unaligned', '0', 0, 12, NULL, 1, '1d4-1', 10, 2, 14, 8, 2, 12, 3, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Intelligent birds often used as familiars or scouts in Gates. Can mimic sounds.', NULL, 'E', false, 'MM', '{"beast", "flying"}'),
('Scorpion', 'Tiny', 'Beast', 'Unaligned', '0', 0, 11, NULL, 1, '1d4-1', 10, 2, 11, 8, 1, 9, 2, '{}', '{}', '{}', '{}', '{"blindsight": 10, "passive Perception": 9}', '{}', 'Small arachnids with a poisonous stinger. Found in desert Gates.', NULL, 'E', false, 'MM', '{"beast"}'),
('Sea Horse', 'Tiny', 'Beast', 'Unaligned', '0', 0, 11, NULL, 1, '1d4-1', 0, 1, 12, 8, 1, 10, 2, '{}', '{}', '{}', '{}', '{}', '{}', 'Tiny fish found in aquatic Gates. Completely harmless.', NULL, 'E', false, 'MM', '{"beast", "aquatic"}'),
('Shrieker', 'Medium', 'Plant', 'Unaligned', '0', 0, 5, NULL, 13, '3d8', 0, 1, 1, 10, 1, 3, 1, '{}', '{}', '{}', '{}', '{"blindsight": 30}', '{}', 'Fungus that emits loud shrieks when light or movement is detected. Alerts other monsters in the Gate.', 'These fungi are cultivated by intelligent monsters to serve as alarm systems. In the post-reset world, they have become more common as Gate ecosystems have stabilized under the Supreme Deity''s influence.', 'E', false, 'MM', '{"plant", "fungus"}'),
('Spider', 'Tiny', 'Beast', 'Unaligned', '0', 0, 12, NULL, 1, '1d4-1', 20, 2, 14, 8, 1, 10, 3, '{}', '{}', '{}', '{}', '{"darkvision": 30}', '{}', 'Small arachnids that spin webs in Gate corners. Weak venom causes mild irritation.', NULL, 'E', false, 'MM', '{"beast"}'),
('Vulture', 'Medium', 'Beast', 'Unaligned', '0', 0, 10, NULL, 5, '2d4', 10, 7, 10, 12, 2, 13, 3, '{}', '{}', '{}', '{}', '{}', '{}', 'Carrion birds that scavenge Gate battlefields. Circle overhead when death is near.', NULL, 'E', false, 'MM', '{"beast", "flying"}'),
('Weasel', 'Tiny', 'Beast', 'Unaligned', '0', 0, 13, NULL, 1, '1d4-1', 30, 3, 16, 8, 3, 12, 4, '{}', '{}', '{}', '{}', '{"passive Perception": 12}', '{}', 'Small, agile mammals. Known for their tenacity in battle.', NULL, 'E', false, 'MM', '{"beast"}'),

-- =============================================
-- CR 1/8 MONSTERS (E-Rank)
-- =============================================

('Bandit', 'Medium', 'Humanoid', 'Any Non-Lawful', '1/8', 25, 12, 'leather armor', 11, '2d8+2', 30, 11, 12, 12, 10, 10, 10, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Desperate criminals who raid Gates for loot in the post-reset world. Attack in groups and flee if outmatched.', 'Some bandits are former hunters who turned to crime after losing their guild membership. Despite the Supreme Deity''s influence, crime still exists in the shadows of the new world.', 'E', false, 'MM', '{"humanoid"}'),
('Blood Hawk', 'Small', 'Beast', 'Unaligned', '1/8', 25, 12, NULL, 7, '2d6', 10, 6, 14, 11, 3, 14, 8, '{}', '{}', '{}', '{}', '{"keen Sight": true, "passive Perception": 14}', '{}', 'Aggressive birds with red-tinted feathers. Attack in flocks and are drawn to blood.', 'Blood Hawks have pack tactics, gaining advantage when allies are within 5 feet.', 'E', false, 'MM', '{"beast", "flying", "pack-tactics"}'),
('Cultist', 'Medium', 'Humanoid', 'Any Non-Good', '1/8', 25, 12, 'leather armor', 9, '2d8', 30, 11, 10, 10, 10, 10, 10, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Fanatics who worship fallen Monarchs or oppose the Supreme Deity. Will die for their cause.', 'Cultists often conduct dark rituals to empower their masters within Gates. Some still worship the fallen Monarchs, refusing to accept the Supreme Deity as the new ruler of the post-reset world.', 'E', false, 'MM', '{"humanoid", "cult"}'),
('Flying Snake', 'Tiny', 'Beast', 'Unaligned', '1/8', 25, 14, NULL, 5, '2d4', 30, 4, 18, 11, 2, 12, 5, '{}', '{}', '{}', '{}', '{"blindsight": 10, "passive Perception": 11}', '{}', 'Winged serpents with vibrant colors. Their venom can paralyze small creatures.', NULL, 'E', false, 'MM', '{"beast", "flying"}'),
('Giant Crab', 'Medium', 'Beast', 'Unaligned', '1/8', 25, 15, 'natural armor', 13, '3d8', 30, 13, 15, 11, 1, 10, 3, '{}', '{}', '{}', '{}', '{"blindsight": 30, "passive Perception": 10}', '{}', 'Massive crustaceans that guard coastal Gates. Their claws can crush bones.', 'These crabs can grapple with their claws, holding prey while attacking.', 'E', false, 'MM', '{"beast", "aquatic"}'),
('Giant Rat', 'Small', 'Beast', 'Unaligned', '1/8', 25, 12, NULL, 7, '2d6', 30, 7, 15, 11, 2, 10, 4, '{}', '{}', '{}', '{}', '{"darkvision": 60}', '{}', 'Large rats contaminated by Gate mana in the post-reset world. More aggressive than their smaller kin.', 'Giant Rats carry diseases and can swarm hunters in tight spaces. Pack tactics make them dangerous. After the reset, their mutations have become more stable, creating distinct subspecies adapted to different Gate environments.', 'E', false, 'MM', '{"beast", "pack-tactics", "disease"}'),
('Giant Weasel', 'Medium', 'Beast', 'Unaligned', '1/8', 25, 13, NULL, 9, '2d8', 40, 11, 16, 10, 3, 12, 5, '{"nonmagical weapons"}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 12}', '{}', 'Large weasels with ferocious appetites. Their bite drains blood.', NULL, 'E', false, 'MM', '{"beast"}'),
('Guard', 'Medium', 'Humanoid', 'Any', '1/8', 25, 16, 'chain shirt, shield', 11, '2d8+2', 30, 13, 12, 12, 10, 11, 10, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Professional soldiers or Gate security personnel. Well-armed and trained.', 'Guards often patrol Gate entrances and can call for reinforcements.', 'E', false, 'MM', '{"humanoid"}'),
('Kobold', 'Small', 'Humanoid', 'Lawful Evil', '1/8', 25, 12, NULL, 5, '2d6-2', 30, 7, 15, 9, 8, 8, 8, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 8}', '{"Common", "Draconic"}', 'Cunning reptilian creatures that set traps in Gate corridors. Pack tactics make them dangerous in numbers.', 'Kobolds use sunlight sensitivity, gaining disadvantage in bright light. They excel at ambushes. In the post-reset world, they have adapted to the new Gate ecosystem, becoming more organized and dangerous.', 'E', false, 'MM', '{"humanoid", "pack-tactics", "sunlight-sensitivity"}'),
('Mastiff', 'Medium', 'Beast', 'Unaligned', '1/8', 25, 12, NULL, 5, '1d8+1', 40, 13, 14, 12, 3, 13, 6, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Loyal guard dogs trained for Gate security. Can knock down enemies with their charge.', NULL, 'E', false, 'MM', '{"beast"}'),
('Merfolk', 'Medium', 'Humanoid', 'Neutral', '1/8', 25, 11, NULL, 11, '2d8+2', 10, 10, 13, 11, 11, 10, 11, '{}', '{}', '{}', '{}', '{}', '{"Aquan", "Common"}', 'Aquatic humanoids found in water-themed Gates. Peaceful unless threatened.', NULL, 'E', false, 'MM', '{"humanoid", "aquatic"}'),
('Merrow', 'Large', 'Monstrosity', 'Chaotic Evil', '1', 200, 13, NULL, 45, '6d10+12', 10, 18, 10, 15, 8, 10, 7, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Abyssal", "Aquan"}', 'Corrupted merfolk transformed by dark magic. They feast on human flesh and attack on sight.', 'Merrow are merfolk who made pacts with dark forces, gaining strength at the cost of their humanity.', 'E', false, 'MM', '{"monstrosity", "aquatic"}'),
('Poisonous Snake', 'Tiny', 'Beast', 'Unaligned', '1/8', 25, 13, NULL, 2, '1d4', 30, 2, 16, 11, 1, 10, 3, '{}', '{}', '{}', '{}', '{"blindsight": 10, "passive Perception": 10}', '{}', 'Venomous serpents found in Gates. Their bite can poison hunters.', NULL, 'E', false, 'MM', '{"beast"}'),
('Pony', 'Medium', 'Beast', 'Unaligned', '1/8', 25, 10, NULL, 11, '2d8+2', 40, 15, 10, 13, 2, 11, 10, '{}', '{}', '{}', '{}', '{}', '{}', 'Small horses used for transportation. Can serve as mounts in Gates.', NULL, 'E', false, 'MM', '{"beast"}'),
('Stirge', 'Tiny', 'Beast', 'Unaligned', '1/8', 25, 14, NULL, 2, '1d4', 10, 4, 16, 8, 5, 12, 6, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 11}', '{}', 'Blood-sucking insects that attach to victims and drain their blood.', 'Stirges drain blood on hit and continue draining each turn they remain attached.', 'E', false, 'MM', '{"beast", "flying"}'),
('Tribal Warrior', 'Medium', 'Humanoid', 'Any', '1/8', 25, 12, 'leather armor, shield', 11, '2d8+2', 30, 13, 11, 12, 8, 11, 11, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Primitive warriors who guard their territories in Gates. Use simple weapons and tactics.', NULL, 'E', false, 'MM', '{"humanoid"}'),
('Twig Blight', 'Small', 'Plant', 'Neutral Evil', '1/8', 25, 13, NULL, 4, '1d6+1', 20, 6, 13, 8, 4, 8, 3, '{}', '{"poison"}', '{"fire"}', '{}', '{"blindsight": 60, "passive Perception": 3}', '{"understands Common but cannot speak"}', 'Animated plant creatures that ambush hunters in forest Gates. Blend with natural foliage.', 'Twig Blights are created when Gate mana corrupts plant life. They spread like weeds.', 'E', false, 'MM', '{"plant"}'),

-- =============================================
-- CR 1/4 MONSTERS (E-Rank to D-Rank)
-- =============================================

('Acolyte', 'Medium', 'Humanoid', 'Any', '1/4', 50, 10, NULL, 9, '2d8', 30, 10, 10, 10, 10, 13, 11, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Religious devotees who serve in Gate temples. Can cast simple healing spells.', 'Acolytes often guard Gate shrines and can call upon divine power.', 'E', false, 'MM', '{"humanoid", "spellcaster"}'),
('Axe Beak', 'Large', 'Beast', 'Unaligned', '1/4', 50, 11, NULL, 19, '3d10+3', 50, 14, 12, 13, 2, 10, 5, '{}', '{}', '{}', '{}', '{}', '{}', 'Large flightless birds with powerful kicks. Used as mounts in some Gates.', NULL, 'D', false, 'MM', '{"beast"}'),
('Blink Dog', 'Medium', 'Fey', 'Lawful Good', '1/4', 50, 13, NULL, 22, '4d8+4', 40, 12, 17, 12, 10, 13, 11, '{}', '{}', '{}', '{}', '{}', '{"Blink Dog", "understands Sylvan but cannot speak"}', 'Magical canines that can teleport short distances. Hunt in packs and are highly intelligent.', 'Blink Dogs are fey creatures that patrol planar boundaries. They protect against evil intruders.', 'D', false, 'MM', '{"fey", "pack-tactics"}'),
('Boar', 'Medium', 'Beast', 'Unaligned', '1/4', 50, 11, NULL, 11, '2d8+2', 40, 13, 11, 12, 2, 9, 5, '{}', '{}', '{}', '{}', '{}', '{}', 'Aggressive wild pigs with dangerous tusks. Their charge can knock down enemies.', NULL, 'E', false, 'MM', '{"beast"}'),
('Constrictor Snake', 'Large', 'Beast', 'Unaligned', '1/4', 50, 12, NULL, 13, '2d10+2', 30, 15, 14, 12, 1, 10, 3, '{}', '{}', '{}', '{}', '{"blindsight": 10, "passive Perception": 10}', '{}', 'Massive snakes that coil around prey and suffocate them.', 'These snakes can grapple with their bite and constrict each turn.', 'D', false, 'MM', '{"beast"}'),
('Draft Horse', 'Large', 'Beast', 'Unaligned', '1/4', 50, 10, NULL, 19, '3d10+3', 40, 18, 10, 14, 2, 11, 7, '{}', '{}', '{}', '{}', '{}', '{}', 'Powerful horses bred for strength. Can carry heavy loads through Gates.', NULL, 'E', false, 'MM', '{"beast"}'),
('Dretch', 'Small', 'Fiend', 'Chaotic Evil', '1/4', 50, 11, NULL, 18, '4d6+4', 20, 11, 11, 12, 5, 5, 3, '{}', '{"cold", "fire", "lightning"}', '{}', '{"poisoned"}', '{"darkvision": 60, "passive Perception": 8}', '{"Abyssal", "telepathy 60 ft."}', 'The weakest form of demon. Grotesque and smelly but still dangerous in numbers.', 'Dretches are created from corrupted souls and serve as cannon fodder in demonic armies.', 'E', false, 'MM', '{"fiend", "demon"}'),
('Drow', 'Medium', 'Humanoid', 'Neutral Evil', '1/4', 50, 15, 'leather armor', 13, '2d8+4', 30, 10, 14, 12, 11, 11, 11, '{}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 10}', '{"Elvish", "Undercommon"}', 'Dark elves who dwell in underground Gates. Excellent ambushers with poison-tipped weapons.', 'Drow have sunlight sensitivity and excel in dark environments. They use superior darkvision to advantage.', 'D', false, 'MM', '{"humanoid", "elf", "sunlight-sensitivity"}'),
('Elk', 'Large', 'Beast', 'Unaligned', '1/4', 50, 10, NULL, 13, '2d10+2', 50, 16, 10, 12, 2, 10, 6, '{}', '{}', '{}', '{}', '{}', '{}', 'Large deer with massive antlers. Their charge is devastating.', NULL, 'D', false, 'MM', '{"beast"}'),
('Flying Sword', 'Small', 'Construct', 'Unaligned', '1/4', 50, 17, NULL, 17, '5d6', 0, 12, 15, 11, 1, 10, 1, '{}', '{"poison", "psychic"}', '{}', '{"blinded", "charmed", "deafened", "frightened", "paralyzed", "petrified", "poisoned"}', '{"blindsight": 60, "passive Perception": 10}', '{}', 'Animated swords that float and fight independently. Created by Gate mages.', 'These constructs serve as guardians in magical Gates.', 'D', false, 'MM', '{"construct"}'),
('Giant Badger', 'Medium', 'Beast', 'Unaligned', '1/4', 50, 10, NULL, 13, '3d8', 30, 13, 10, 12, 2, 12, 5, '{}', '{}', '{}', '{}', '{"darkvision": 30}', '{}', 'Large badgers with powerful claws. Can burrow through earth and stone.', NULL, 'E', false, 'MM', '{"beast"}'),
('Giant Bat', 'Large', 'Beast', 'Unaligned', '1/4', 50, 13, NULL, 22, '4d10', 10, 15, 16, 11, 2, 12, 6, '{}', '{}', '{}', '{}', '{"blindsight": 60, "passive Perception": 11}', '{}', 'Massive bats that roost in cave Gates. Their echolocation works in complete darkness.', NULL, 'D', false, 'MM', '{"beast", "flying"}'),
('Giant Centipede', 'Small', 'Beast', 'Unaligned', '1/4', 50, 13, NULL, 4, '1d6+1', 30, 5, 14, 12, 1, 7, 3, '{}', '{}', '{}', '{}', '{"blindsight": 30, "passive Perception": 8}', '{}', 'Large centipedes with paralytic venom. Found in dark, damp Gate areas.', 'Their bite can paralyze victims for hours.', 'E', false, 'MM', '{"beast", "poison"}'),
('Giant Frog', 'Medium', 'Beast', 'Unaligned', '1/4', 50, 11, NULL, 18, '4d8', 30, 12, 13, 11, 2, 10, 5, '{}', '{}', '{}', '{}', '{"darkvision": 30, "passive Perception": 11}', '{}', 'Massive amphibians that can swallow small creatures whole.', 'Giant Frogs can grapple with their bite and swallow creatures smaller than themselves.', 'D', false, 'MM', '{"beast", "amphibian"}'),
('Giant Lizard', 'Large', 'Beast', 'Unaligned', '1/4', 50, 12, NULL, 19, '3d10+3', 30, 15, 12, 13, 2, 10, 5, '{}', '{}', '{}', '{}', '{"darkvision": 30}', '{}', 'Huge reptiles found in warm Gates. Some can climb or swim.', NULL, 'D', false, 'MM', '{"beast"}'),
('Giant Owl', 'Large', 'Beast', 'Neutral', '1/4', 50, 12, NULL, 19, '3d10+3', 5, 13, 15, 12, 8, 15, 12, '{}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 13}', '{"Common", "Giant Owl", "Elvish", "Sylvan"}', 'Massive owls with exceptional night vision. Can serve as intelligent mounts.', NULL, 'D', false, 'MM', '{"beast", "flying"}'),
('Giant Poisonous Snake', 'Medium', 'Beast', 'Unaligned', '1/4', 50, 14, NULL, 11, '2d8+2', 30, 10, 18, 11, 2, 10, 4, '{}', '{}', '{}', '{}', '{"blindsight": 10, "passive Perception": 10}', '{}', 'Large venomous serpents. Their bite can kill unprepared hunters.', 'Poison damage can drop hunters to 0 hit points.', 'D', false, 'MM', '{"beast", "poison"}'),
('Giant Rat', 'Small', 'Beast', 'Unaligned', '1/8', 25, 12, NULL, 7, '2d6', 30, 7, 15, 11, 2, 10, 4, '{}', '{}', '{}', '{}', '{"darkvision": 60}', '{}', 'Large rats contaminated by Gate mana. More aggressive than their smaller kin.', 'Giant Rats carry diseases and can swarm hunters in tight spaces.', 'E', false, 'MM', '{"beast", "disease", "pack-tactics"}'),
('Giant Weasel', 'Medium', 'Beast', 'Unaligned', '1/8', 25, 13, NULL, 9, '2d8', 40, 11, 16, 10, 3, 12, 5, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 12}', '{}', 'Large weasels with ferocious appetites. Their bite drains blood.', NULL, 'E', false, 'MM', '{"beast"}'),
('Goblin', 'Small', 'Humanoid', 'Neutral Evil', '1/4', 50, 15, 'leather armor, shield', 7, '2d6', 30, 8, 14, 10, 10, 8, 8, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 8}', '{"Common", "Goblin"}', 'The most common humanoid monster in low-rank Gates. They use crude weapons and attack in groups, swarming unprepared E-Rank hunters.', 'Goblins use nimble escape to disengage as a bonus action, making them hard to pin down. In the post-reset world, they have become more numerous as Gate mana has stabilized, creating ideal conditions for their reproduction.', 'E', false, 'MM', '{"humanoid", "goblinoid"}'),
('Grimlock', 'Medium', 'Humanoid', 'Neutral Evil', '1/4', 50, 11, NULL, 11, '2d8+2', 30, 16, 12, 13, 9, 14, 6, '{}', '{}', '{}', '{}', '{"blindsight": 30, "blind beyond this radius", "passive Perception": 12}', '{"Undercommon"}', 'Blind humanoids with exceptional hearing and smell. Hunt by scent in dark Gates.', 'Grimlocks are immune to being blinded and have advantage on Perception checks relying on hearing or smell.', 'E', false, 'MM', '{"humanoid", "blind"}'),
('Panther', 'Medium', 'Beast', 'Unaligned', '1/4', 50, 12, NULL, 13, '3d8', 50, 14, 15, 10, 3, 14, 7, '{}', '{}', '{}', '{}', '{"passive Perception": 14}', '{}', 'Stealthy predators that pounce from ambush. Their pounce can knock prey prone.', 'Panthers use pounce to move and make a bite attack, potentially knocking the target prone.', 'D', false, 'MM', '{"beast", "pounce"}'),
('Pseudo-Dragon', 'Tiny', 'Dragon', 'Neutral Good', '1/4', 50, 13, NULL, 7, '2d4+2', 15, 6, 15, 13, 10, 12, 10, '{}', '{}', '{}', '{}', '{"blindsight": 10, "darkvision": 60, "passive Perception": 12}', '{"understands Common and Draconic but cannot speak"}', 'Tiny dragons that serve as familiars. They have limited telepathy and a stinging tail.', 'Pseudo-dragons can deliver touch spells for their masters and communicate telepathically.', 'E', false, 'MM', '{"dragon"}'),
('Riding Horse', 'Large', 'Beast', 'Unaligned', '1/4', 50, 10, NULL, 13, '2d10+2', 60, 16, 10, 12, 2, 11, 7, '{}', '{}', '{}', '{}', '{}', '{}', 'Swift horses bred for speed. Ideal mounts for Gate travel.', NULL, 'E', false, 'MM', '{"beast"}'),
('Skeleton', 'Medium', 'Undead', 'Lawful Evil', '1/4', 50, 13, 'armor scraps', 13, '2d8+4', 30, 10, 14, 15, 6, 8, 5, '{"bludgeoning"}', '{"poison"}', '{}', '{}', '{"darkvision": 60, "passive Perception": 9}', '{"understands all languages it knew in life but cannot speak"}', 'Skeletal warriors animated by Gate mana and necromantic energy. They wield rusted weapons with surprising skill, remnants of their past lives.', 'Skeletons are vulnerable to bludgeoning damage and immune to poison. In the post-reset world, they are more common as the boundary between life and death has been weakened by the Supreme Deity''s power.', 'E', false, 'MM', '{"undead", "skeleton"}'),
('Smoke Mephit', 'Small', 'Elemental', 'Neutral Evil', '1/4', 50, 12, NULL, 22, '5d6+5', 30, 6, 14, 12, 10, 10, 11, '{}', '{"fire", "poison"}', '{}', '{"poisoned"}', '{"darkvision": 60, "passive Perception": 10}', '{"Auran", "Ignan"}', 'Small elemental creatures of smoke and fire. They can blind enemies with smoke clouds.', 'When killed, Smoke Mephits explode in a cloud of choking smoke.', 'E', false, 'MM', '{"elemental", "fire"}'),
('Sprite', 'Tiny', 'Fey', 'Neutral Good', '1/4', 50, 15, NULL, 2, '1d4', 10, 3, 18, 10, 14, 13, 11, '{}', '{}', '{}', '{}', '{"passive Perception": 11}', '{"Common", "Elvish", "Sylvan"}', 'Tiny winged fey with bows that can poison enemies. Helpful but mischievous.', 'Sprites can render foes unconscious with their poison arrows.', 'E', false, 'MM', '{"fey", "flying"}'),
('Steam Mephit', 'Small', 'Elemental', 'Neutral Evil', '1/4', 50, 10, NULL, 21, '6d6+3', 30, 5, 11, 13, 10, 10, 12, '{}', '{"fire"}', '{}', '{"poisoned"}', '{"darkvision": 60, "passive Perception": 10}', '{"Aquan", "Ignan"}', 'Small elemental creatures of steam. They can blind enemies with scalding steam.', 'When killed, Steam Mephits explode in a burst of scalding steam.', 'E', false, 'MM', '{"elemental", "fire"}'),
('Swarm of Bats', 'Medium', 'Beast', 'Unaligned', '1/4', 50, 12, NULL, 22, '5d8', 0, 5, 15, 10, 2, 12, 4, '{"bludgeoning", "piercing", "slashing"}', '{}', '{}', '{"charmed", "frightened", "grappled", "paralyzed", "petrified", "prone", "restrained", "stunned"}', '{"blindsight": 60, "passive Perception": 11}', '{}', 'A swirling cloud of bats that attacks as a single entity. The swarm obscures vision.', 'Swarms take half damage from single-target attacks and can occupy another creature''s space.', 'E', false, 'MM', '{"beast", "swarm", "flying"}'),
('Swarm of Rats', 'Medium', 'Beast', 'Unaligned', '1/4', 50, 10, NULL, 24, '7d8-7', 30, 9, 11, 9, 2, 10, 3, '{"bludgeoning", "piercing", "slashing"}', '{}', '{}', '{"charmed", "frightened", "grappled", "paralyzed", "petrified", "prone", "restrained", "stunned"}', '{"darkvision": 30}', '{}', 'A horde of rats that moves and attacks as one. Overwhelms enemies through numbers.', 'Swarm attacks can cause disease, and the swarm is resistant to most weapon damage.', 'E', false, 'MM', '{"beast", "swarm", "disease"}'),
('Swarm of Ravens', 'Medium', 'Beast', 'Unaligned', '1/4', 50, 12, NULL, 24, '7d8-7', 10, 6, 14, 8, 2, 13, 4, '{"bludgeoning", "piercing", "slashing"}', '{}', '{}', '{"charmed", "frightened", "grappled", "paralyzed", "petrified", "prone", "restrained", "stunned"}', '{}', '{}', 'A cloud of ravens that pecks and claws at enemies. Can obscure vision and distract.', 'Swarm attacks can blind enemies temporarily, making them easier targets.', 'E', false, 'MM', '{"beast", "swarm", "flying"}'),
('Velociraptor', 'Tiny', 'Beast', 'Unaligned', '1/4', 50, 13, NULL, 10, '3d4+3', 30, 6, 14, 13, 4, 12, 10, '{}', '{}', '{}', '{}', '{"passive Perception": 12}', '{}', 'Small predatory dinosaurs that hunt in packs. Their pack tactics make them deadly.', 'Velociraptors coordinate attacks, gaining advantage when allies are nearby.', 'E', false, 'MM', '{"beast", "dinosaur", "pack-tactics"}'),
('Wolf', 'Medium', 'Beast', 'Unaligned', '1/4', 50, 13, NULL, 11, '2d8+2', 40, 12, 15, 12, 3, 12, 6, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Pack hunters that work together to bring down prey. Their bite can knock enemies prone.', 'Wolves use pack tactics and can knock enemies prone with their bite attack.', 'E', false, 'MM', '{"beast", "pack-tactics"}'),
('Zombie', 'Medium', 'Undead', 'Neutral Evil', '1/4', 50, 8, NULL, 22, '3d8+9', 20, 13, 6, 16, 3, 6, 5, '{}', '{"poison"}', '{}', '{}', '{"darkvision": 60, "passive Perception": 8}', '{"understands all languages it knew in life but cannot speak"}', 'Mindless undead animated by Gate necromancy in the post-reset world. Slow but relentless, they are drawn to the living like moths to flame.', 'Zombies have undead fortitude, allowing them to survive lethal damage on a Constitution save. After the reset, their numbers have increased as necromantic energy has become more concentrated in certain Gate types.', 'E', false, 'MM', '{"undead", "zombie"}')

ON CONFLICT (name) DO NOTHING;

-- Continue with higher CR monsters in next migration file...

