-- =============================================
-- D&D 5E SRD MONSTERS - CR 11 to 20
-- Complete coverage adapted for Solo Leveling Universe
-- Post-Reset Timeline: Supreme Deity (post-reset world)
-- =============================================
-- Part 5: CR 11-20 monsters (A-Rank to S-Rank)
-- All entries aligned with Solo Leveling manwha setting, theme, tone, and aesthetic

INSERT INTO compendium_monsters (name, size, creature_type, alignment, cr, xp, armor_class, armor_type, hit_points_average, hit_points_formula, speed_walk, speed_fly, speed_swim, str, agi, vit, int, sense, pre, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, description, lore, gate_rank, is_boss, source_book, tags) VALUES

-- =============================================
-- CR 11 MONSTERS (A-Rank)
-- =============================================

('Efreeti', 'Large', 'Elemental', 'Lawful Evil', '11', 7200, 17, NULL, 200, '16d10+112', 40, NULL, NULL, 22, 12, 24, 16, 15, 16, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"fire"}', '{}', '{}', '{"darkvision": 120, "passive Perception": 15}', '{"Ignan"}', 'Fire genies of immense power who grant twisted wishes. They wield devastating flame magic and can command fire elementals.', 'Efreeti are among the most powerful fire elementals. In the post-reset world, they have become more common in volcanic Gates, drawn by the concentrated fire mana. They serve as guardians of the deepest Gate levels.', 'A', false, 'MM', '{"elemental", "fire", "genie"}'),
('Horned Devil', 'Large', 'Fiend', 'Lawful Evil', '11', 7200, 18, NULL, 178, '17d10+85', 30, NULL, NULL, 22, 17, 21, 12, 16, 17, '{"cold"}', '{"fire", "poison"}', '{}', '{"poisoned"}', '{"darkvision": 120, "passive Perception": 16}', '{"Infernal", "telepathy 120 ft."}', 'Elite devils with massive horns and infernal flames. They are among hell''s finest warriors and command legions of lesser devils.', 'Horned Devils serve as generals in the infernal hierarchy that persists even after the reset. They are intelligent, organized, and deadly opponents who fight with tactical brilliance.', 'A', false, 'MM', '{"fiend", "devil", "fire"}'),
('Remorhaz', 'Huge', 'Monstrosity', 'Unaligned', '11', 7200, 17, NULL, 195, '17d12+85', 30, NULL, NULL, 24, 13, 21, 4, 10, 5, '{"cold"}', '{"fire"}', '{}', '{}', '{"tremorsense": 60, "passive Perception": 10}', '{}', 'Centipede-like monsters that generate intense internal heat. Attacking them burns the attacker, and they can swallow prey whole.', 'Remorhazes are apex predators of arctic Gates. Their internal heat makes them nearly impossible to fight in melee, and they can burrow through ice and snow with ease.', 'A', false, 'MM', '{"monstrosity", "fire", "burrow"}'),
('Roc', 'Gargantuan', 'Beast', 'Unaligned', '11', 7200, 15, NULL, 248, '16d20+80', 20, NULL, NULL, 28, 10, 22, 3, 14, 9, '{}', '{}', '{}', '{}', '{"passive Perception": 14}', '{}', 'Massive birds of prey that can carry off elephants. They nest in the highest peaks and rule the skies of mountain Gates.', 'Rocs are among the largest flying creatures in Gates. They are territorial and will attack anything that enters their domain, including dragons.', 'A', false, 'MM', '{"beast", "flying", "gargantuan"}'),
('Behir', 'Huge', 'Monstrosity', 'Neutral Evil', '11', 7200, 17, NULL, 168, '16d12+64', 50, NULL, NULL, 23, 16, 18, 7, 14, 12, '{"lightning"}', '{}', '{}', '{}', '{"darkvision": 90, "passive Perception": 14}', '{"Draconic"}', 'Lightning-breathing serpents with multiple legs. They swallow prey whole and digest them alive, leaving only bones.', 'Behirs are the mortal enemies of dragons. They hunt dragons relentlessly and can absorb lightning attacks to power their own breath weapons.', 'A', false, 'MM', '{"monstrosity", "lightning", "dragon-hunter"}'),

-- =============================================
-- CR 12 MONSTERS (A-Rank)
-- =============================================

('Archmage', 'Medium', 'Humanoid', 'Any', '12', 8400, 12, NULL, 99, '18d8+18', 30, NULL, NULL, 10, 14, 12, 20, 15, 16, '{"damage from spells"}', '{}', '{}', '{}', '{}', '{"Any six languages"}', 'Powerful spellcasters who have mastered Gate magic. They can cast devastating spells and protect themselves with magical barriers and contingencies.', 'Archmages are among the most dangerous humanoid enemies in Gates. They combine intelligence with powerful magic, making them deadly opponents. In the post-reset world, they have gained access to new spells through the System.', 'A', false, 'MM', '{"humanoid", "spellcaster", "archmage"}'),
('Erinyes', 'Medium', 'Fiend', 'Lawful Evil', '12', 8400, 18, NULL, 153, '18d8+72', 30, NULL, NULL, 18, 16, 18, 14, 15, 18, '{"cold"}', '{"fire", "poison"}', '{}', '{"poisoned"}', '{"truesight": 120, "passive Perception": 15}', '{"Infernal", "telepathy 120 ft."}', 'Elite devils who serve as enforcers and assassins. They can fly, use magic, and their weapons cause wounds that never heal.', 'Erinyes are the elite soldiers of hell. They are beautiful but deadly, serving as both warriors and seductresses. In the post-reset world, they continue to serve the infernal hierarchy.', 'A', false, 'MM', '{"fiend", "devil", "flying", "wound"}'),
('Young Gold Dragon', 'Large', 'Dragon', 'Lawful Good', '10', 5900, 18, NULL, 178, '17d10+85', 40, NULL, 40, 23, 14, 21, 16, 13, 21, '{"fire"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 13}', '{"Common", "Draconic"}', 'Fire-breathing dragons that are the most powerful of the metallic dragons. They are paragons of good and justice, often serving as protectors.', 'Gold Dragons are the most powerful and noble of all metallic dragons. In the post-reset world, they have become allies of the Supreme Deity, serving as protectors and guardians against evil.', 'A', false, 'MM', '{"dragon", "fire", "good", "metallic"}'),
('Young Red Dragon', 'Large', 'Dragon', 'Chaotic Evil', '10', 5900, 18, NULL, 178, '17d10+85', 40, NULL, NULL, 23, 10, 21, 14, 11, 19, '{"fire"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 11}', '{"Common", "Draconic"}', 'Fire-breathing dragons of terrible power. Their flames melt steel and incinerate hunters. They are the most aggressive of all dragons.', 'Red Dragons are the most feared of all chromatic dragons. They are greedy, cruel, and territorial, attacking anything that enters their domain. Even in the post-reset world, they remain a threat to all hunters.', 'A', false, 'MM', '{"dragon", "fire"}'),

-- =============================================
-- CR 13 MONSTERS (A-Rank to S-Rank)
-- =============================================

('Adult Brass Dragon', 'Huge', 'Dragon', 'Chaotic Good', '13', 10000, 18, NULL, 172, '15d12+75', 40, NULL, NULL, 23, 10, 21, 14, 13, 17, '{"fire"}', '{}', '{}', '{}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 13}', '{"Common", "Draconic"}', 'Fire-breathing dragons that are talkative and social. They enjoy conversation and games, but can be deadly when angered.', 'Brass Dragons are among the most social of all dragons. They collect information and stories, often trading knowledge with hunters. In the post-reset world, they have become valuable allies.', 'A', false, 'MM', '{"dragon", "fire", "good"}'),
('Adult White Dragon', 'Huge', 'Dragon', 'Chaotic Evil', '13', 10000, 18, NULL, 200, '16d12+96', 40, NULL, 40, 22, 10, 22, 8, 12, 12, '{"cold"}', '{}', '{}', '{}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 12}', '{"Common", "Draconic"}', 'Ice-breathing dragons that are the most bestial of all dragons. They are territorial and attack anything that enters their frozen domain.', 'White Dragons are simple-minded but incredibly dangerous. They rule frozen Gates and hoard treasure in ice caves. Even after the reset, they remain a threat to all who enter their territory.', 'A', false, 'MM', '{"dragon", "cold"}'),
('Nalfeshnee', 'Large', 'Fiend', 'Chaotic Evil', '13', 10000, 18, NULL, 184, '16d10+96', 20, NULL, NULL, 21, 10, 22, 19, 12, 15, '{"cold", "fire", "lightning"}', '{"poison"}', '{}', '{"poisoned"}', '{"truesight": 120, "passive Perception": 12}', '{"Abyssal", "telepathy 120 ft."}', 'Massive demon lords with boar-like features. They can cast powerful spells and their presence can drive mortals insane.', 'Nalfeshnees are high-ranking demons who command legions of lesser demons. They are intelligent and powerful, serving as generals in the demonic armies that still threaten Gates.', 'A', false, 'MM', '{"fiend", "demon", "spellcaster"}'),
('Rakshasa', 'Medium', 'Fiend', 'Lawful Evil', '13', 10000, 16, NULL, 110, '13d8+52', 40, NULL, NULL, 14, 17, 18, 13, 16, 20, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 16}', '{"Common", "Infernal"}', 'Shape-changing fiends who infiltrate society. They can cast spells and are nearly immune to magic, making them deadly opponents.', 'Rakshasas are master manipulators who use their shape-changing abilities to infiltrate hunter guilds and corrupt from within. They are among the most dangerous fiends.', 'A', false, 'MM', '{"fiend", "shapechanger", "spellcaster"}'),
('Storm Giant', 'Huge', 'Giant', 'Chaotic Good', '13', 10000, 16, NULL, 230, '20d12+100', 50, NULL, 50, 29, 14, 22, 16, 16, 18, '{"cold", "thunder"}', '{}', '{}', '{}', '{"passive Perception": 16}', '{"Common", "Giant"}', 'Massive giants who command the weather. They are generally good-aligned and prefer to avoid conflict, but are devastating when angered.', 'Storm Giants are among the most powerful and noble of all giants. They dwell in cloud castles and serve as protectors. In the post-reset world, they have become allies of the Supreme Deity.', 'A', false, 'MM', '{"giant", "storm", "good"}'),
('Vampire', 'Medium', 'Undead', 'Lawful Evil', '13', 10000, 16, NULL, 144, '17d8+68', 30, NULL, NULL, 18, 18, 18, 17, 15, 18, '{"necrotic"}', '{"poison"}', '{"radiant"}', '{"charmed", "exhaustion", "frightened", "poisoned"}', '{"darkvision": 120, "passive Perception": 15}', '{"the languages it knew in life"}', 'Powerful undead who drain blood and create spawn. They can transform into mist or bats, and regenerate quickly unless exposed to sunlight or running water.', 'Vampires are among the most feared undead in Gates. They are intelligent, charismatic, and powerful. In the post-reset world, they have become more organized, building covens and territories.', 'A', false, 'MM', '{"undead", "vampire", "shapechanger", "spawn"}'),

-- =============================================
-- CR 14 MONSTERS (S-Rank)
-- =============================================

('Adult Black Dragon', 'Huge', 'Dragon', 'Chaotic Evil', '14', 11500, 19, NULL, 195, '17d12+85', 40, NULL, 80, 23, 14, 21, 14, 13, 17, '{"acid"}', '{}', '{}', '{}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 13}', '{"Common", "Draconic"}', 'Cunning acid dragons that ambush from murky waters. Their acid dissolves even magical protection, and they use the terrain to their advantage.', 'Black Dragons are among the most cunning and cruel of all dragons. They delight in the suffering of their victims and use ambush tactics. Even after the reset, they remain a deadly threat in swamp-themed S-Rank Gates.', 'S', false, 'MM', '{"dragon", "acid"}'),
('Adult Copper Dragon', 'Huge', 'Dragon', 'Chaotic Good', '14', 11500, 18, NULL, 184, '16d12+80', 40, NULL, 40, 23, 12, 20, 18, 15, 17, '{"acid"}', '{}', '{}', '{}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 15}', '{"Common", "Draconic"}', 'Acid-breathing dragons that are playful and enjoy tricks. Despite their playful nature, they are still dangerous when threatened.', 'Copper Dragons are among the most social of all dragons. They enjoy conversation and games, but can be deadly when angered. In the post-reset world, they have become valuable allies.', 'S', false, 'MM', '{"dragon", "acid", "good"}'),
('Ice Devil', 'Large', 'Fiend', 'Lawful Evil', '14', 11500, 18, NULL, 180, '19d10+76', 40, NULL, NULL, 18, 14, 20, 11, 12, 14, '{"bludgeoning, piercing, slashing from nonmagical attacks that aren''t silvered"}', '{"cold", "fire", "poison"}', '{}', '{"poisoned"}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 12}', '{"Infernal", "telepathy 120 ft."}', 'Devils of ice and cold that rule frozen Gates. Their touch freezes flesh and their weapons cause wounds that never heal.', 'Ice Devils serve the infernal hierarchy that persists even after the reset. They are among the most organized and dangerous of devils, commanding legions of lesser devils.', 'S', false, 'MM', '{"fiend", "devil", "cold", "wound"}'),
('Young Red Dragon', 'Large', 'Dragon', 'Chaotic Evil', '10', 5900, 18, NULL, 178, '17d10+85', 40, NULL, NULL, 23, 10, 21, 14, 11, 19, '{"fire"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 11}', '{"Common", "Draconic"}', 'Fire-breathing dragons of terrible power. Their flames melt steel and incinerate hunters. They are the most aggressive of all dragons.', 'Red Dragons are the most feared of all chromatic dragons. They are greedy, cruel, and territorial, attacking anything that enters their domain.', 'A', false, 'MM', '{"dragon", "fire"}'),

-- =============================================
-- CR 15 MONSTERS (S-Rank)
-- =============================================

('Mummy Lord', 'Medium', 'Undead', 'Lawful Evil', '15', 13000, 17, NULL, 97, '13d8+39', 20, NULL, NULL, 18, 10, 17, 11, 15, 18, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"necrotic", "poison"}', '{"fire"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "poisoned"}', '{"darkvision": 60, "passive Perception": 15}', '{"the languages it knew in life"}', 'Powerful undead mummies who were once pharaohs or high priests. They can cast spells and command legions of mummies.', 'Mummy Lords are ancient undead who have achieved a form of immortality through dark rituals. They guard ancient treasures and serve as gatekeepers for the deepest Gate levels.', 'S', false, 'MM', '{"undead", "mummy", "spellcaster"}'),
('Purple Worm', 'Gargantuan', 'Monstrosity', 'Unaligned', '15', 13000, 18, NULL, 247, '15d20+90', 50, NULL, 30, 28, 7, 22, 1, 8, 4, '{}', '{}', '{}', '{}', '{"blindsight": 30, "tremorsense": 60, "passive Perception": 8}', '{}', 'Massive burrowing worms that can swallow creatures whole. They are among the largest land-dwelling monsters in Gates.', 'Purple Worms are apex predators that burrow through earth and stone. They can sense vibrations and erupt from the ground to devour prey. Only the strongest S-Rank teams can hope to survive an encounter.', 'S', false, 'MM', '{"monstrosity", "burrow", "swallow"}'),

-- =============================================
-- CR 16 MONSTERS (S-Rank)
-- =============================================

('Adult Blue Dragon', 'Huge', 'Dragon', 'Lawful Evil', '16', 15000, 19, NULL, 225, '18d12+108', 40, NULL, NULL, 25, 10, 23, 16, 15, 19, '{"lightning"}', '{}', '{}', '{}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 15}', '{"Common", "Draconic"}', 'Lightning dragons that create devastating sandstorms. They rule desert-themed S-Rank Gates and command the very weather.', 'Blue Dragons are among the most organized and intelligent of all chromatic dragons. They build lairs in desert Gates and hoard treasure. Even after the reset, they remain a threat to all hunters.', 'S', false, 'MM', '{"dragon", "lightning"}'),
('Iron Golem', 'Large', 'Construct', 'Unaligned', '16', 15000, 20, NULL, 210, '20d10+100', 30, NULL, NULL, 24, 9, 20, 3, 11, 1, '{"bludgeoning, piercing, slashing from nonmagical attacks that aren''t adamantine"}', '{"fire", "poison", "psychic"}', '{"acid", "rust"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"}', '{"darkvision": 120, "passive Perception": 11}', '{"understands the languages of its creator but cannot speak"}', 'Nearly indestructible iron automatons. They exhale poison gas and shrug off magical attacks. Only the strongest weapons can damage them.', 'Iron Golems are among the most powerful constructs. They are nearly indestructible and serve as guardians for the most valuable treasures in S-Rank Gates. After the reset, they have become more common as mages push the boundaries of creation.', 'S', false, 'MM', '{"construct", "iron", "poison"}'),
('Marilith', 'Large', 'Fiend', 'Chaotic Evil', '16', 15000, 18, NULL, 189, '18d10+90', 30, NULL, NULL, 18, 20, 20, 18, 16, 20, '{"cold", "fire", "lightning"}', '{"poison"}', '{}', '{"poisoned", "charmed", "frightened"}', '{"truesight": 120, "passive Perception": 16}', '{"Abyssal", "telepathy 120 ft."}', 'Six-armed demon generals who command demonic armies. They can make multiple attacks per turn and cast powerful spells.', 'Mariliths are among the most powerful demons. They serve as generals in the demonic armies that still threaten Gates. Their six arms allow them to wield multiple weapons simultaneously.', 'S', false, 'MM', '{"fiend", "demon", "spellcaster", "multi-armed"}'),

-- =============================================
-- CR 17 MONSTERS (S-Rank)
-- =============================================

('Adult Red Dragon', 'Huge', 'Dragon', 'Chaotic Evil', '17', 18000, 19, NULL, 256, '19d12+133', 40, NULL, NULL, 27, 10, 25, 16, 13, 21, '{"fire"}', '{}', '{}', '{}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 13}', '{"Common", "Draconic"}', 'Legendary fire dragons that rule volcano Gates. Their breath can level city blocks, and only the strongest S-Rank teams can hope to survive an encounter.', 'Red Dragons are the most feared of all chromatic dragons. They are greedy, cruel, and territorial. Even after the reset, they remain a deadly threat, challenging the Supreme Deity''s authority in their domains.', 'S', false, 'MM', '{"dragon", "fire"}'),
('Androsphinx', 'Large', 'Monstrosity', 'Lawful Neutral', '17', 18000, 20, NULL, 199, '19d10+95', 40, NULL, NULL, 22, 10, 20, 16, 18, 23, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"psychic"}', '{}', '{"charmed", "frightened"}', '{"truesight": 120, "passive Perception": 18}', '{"Common", "Sphinx"}', 'Powerful sphinxes who guard ancient secrets and treasure. They can cast powerful spells and their riddles can trap victims for eternity.', 'Androsphinxes are guardians of ancient knowledge. They test those who seek their treasures with riddles and challenges. In the post-reset world, they have become more active, guarding Gate cores and System secrets.', 'S', false, 'MM', '{"monstrosity", "sphinx", "spellcaster", "riddle"}'),
('Dragon Turtle', 'Gargantuan', 'Dragon', 'Neutral', '17', 18000, 20, NULL, 341, '22d20+154', 20, NULL, 40, 25, 10, 20, 12, 13, 12, '{"fire"}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 13}', '{"Aquan", "Common", "Draconic"}', 'Massive aquatic dragons that can breathe steam and fire. They are territorial and will attack ships and hunters who enter their waters.', 'Dragon Turtles are among the largest aquatic creatures in Gates. They rule ocean-themed S-Rank Gates and can destroy entire fleets. Even after the reset, they remain a threat to all who enter their domain.', 'S', false, 'MM', '{"dragon", "aquatic", "fire"}'),

-- =============================================
-- CR 18 MONSTERS (S-Rank)
-- =============================================

('Gynosphinx', 'Large', 'Monstrosity', 'Lawful Neutral', '18', 20000, 17, NULL, 136, '16d10+48', 40, NULL, NULL, 18, 15, 16, 18, 19, 18, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"psychic"}', '{}', '{"charmed", "frightened"}', '{"truesight": 120, "passive Perception": 19}', '{"Common", "Sphinx"}', 'Powerful sphinxes who guard ancient secrets. They can cast powerful spells and their riddles can trap victims for eternity.', 'Gynosphinxes are guardians of ancient knowledge. They test those who seek their treasures with riddles and challenges. In the post-reset world, they guard Gate cores and System secrets.', 'S', false, 'MM', '{"monstrosity", "sphinx", "spellcaster", "riddle"}'),

-- =============================================
-- CR 19 MONSTERS (S-Rank)
-- =============================================

('Balor', 'Huge', 'Fiend', 'Chaotic Evil', '19', 22000, 19, NULL, 262, '21d12+126', 40, NULL, NULL, 26, 15, 22, 20, 16, 22, '{"cold", "fire", "lightning"}', '{"poison"}', '{}', '{"poisoned", "charmed", "frightened"}', '{"truesight": 120, "passive Perception": 16}', '{"Abyssal", "telepathy 120 ft."}', 'Demon lords of flame and shadow. Their death explosion can kill hunters who survive the battle, and they command legions of demons.', 'Balors are among the most powerful demons. They serve as generals in the demonic armies that still threaten Gates. Even after the reset, they remain a threat, challenging the Supreme Deity''s authority.', 'S', false, 'MM', '{"fiend", "demon", "fire", "death-explosion"}'),

-- =============================================
-- CR 20 MONSTERS (S-Rank)
-- =============================================

('Pit Fiend', 'Large', 'Fiend', 'Lawful Evil', '20', 25000, 19, NULL, 300, '24d10+168', 30, NULL, NULL, 26, 14, 24, 22, 14, 24, '{"cold"}', '{"fire", "poison"}', '{}', '{"poisoned"}', '{"truesight": 120, "passive Perception": 14}', '{"Infernal", "telepathy 120 ft."}', 'The generals of hell. They wield flaming maces and command devastating infernal magic. They are among the most powerful fiends in existence.', 'Pit Fiends are the highest-ranking devils. They serve as generals in hell''s armies and command legions of lesser devils. Even after the reset, they continue to serve the infernal hierarchy, challenging the Supreme Deity''s authority.', 'S', false, 'MM', '{"fiend", "devil", "fire", "spellcaster"}')

ON CONFLICT (name) DO NOTHING;

-- Continue with CR 21+ monsters in next file...

