-- =============================================
-- D&D 5E NAMED BOSSES - Solo Leveling Universe
-- Post-Reset Timeline: Supreme Deity (post-reset world)
-- =============================================
-- Iconic named boss monsters from D&D 5e
-- All entries aligned with Solo Leveling manwha setting, theme, tone, and aesthetic
-- These are legendary creatures with unique names and histories

INSERT INTO compendium_monsters (name, size, creature_type, alignment, cr, xp, armor_class, armor_type, hit_points_average, hit_points_formula, speed_walk, speed_fly, speed_swim, str, agi, vit, int, sense, pre, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, description, lore, gate_rank, is_boss, source_book, tags) VALUES

-- =============================================
-- NAMED DRAGON BOSSES (S-Rank)
-- =============================================

('Ashardalon, the Ancient Red', 'Gargantuan', 'Dragon', 'Chaotic Evil', '26', 90000, 22, NULL, 546, '28d20+252', 40, NULL, NULL, 30, 10, 29, 20, 17, 25, '{"fire"}', '{}', '{}', '{}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 17}', '{"Common", "Draconic", "Infernal"}', 'A legendary ancient red dragon who made a pact with a pit fiend, replacing his own heart with that of a demon. He is among the most powerful dragons in existence, ruling a network of volcano Gates.', 'Ashardalon is a unique dragon who achieved near-immortality through dark pacts. In the post-reset world, he challenges the Supreme Deity''s authority, claiming that even the Shadow Monarch cannot truly destroy him. His demonic heart makes him nearly invincible.', 'S', true, 'MM', '{"dragon", "fire", "ancient", "named", "demon-heart"}'),
('Chardalyn Dragon', 'Huge', 'Construct', 'Chaotic Evil', '11', 7200, 19, NULL, 200, '16d12+96', 40, NULL, NULL, 23, 10, 22, 10, 13, 16, '{"cold", "fire", "lightning", "poison"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"}', '{}', '{}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 13}', '{"understands the languages of its creator but cannot speak"}', 'A construct dragon made from chardalyn, a magical crystal that corrupts those who touch it. It breathes freezing cold and spreads corruption wherever it goes.', 'The Chardalyn Dragon is a unique construct created by dark mages. In the post-reset world, it has become more dangerous as chardalyn corruption spreads through certain Gate types. It serves as a warning of the dangers of unchecked magical experimentation.', 'A', true, 'MM', '{"construct", "dragon", "cold", "named", "corruption"}'),
('Dracolich', 'Gargantuan', 'Undead', 'Chaotic Evil', '17', 18000, 19, NULL, 256, '19d12+133', 40, NULL, NULL, 27, 10, 25, 20, 15, 19, '{"necrotic"}', '{"poison"}', '{"radiant"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "poisoned"}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 15}', '{"Common", "Draconic"}', 'An undead dragon who achieved immortality by binding its soul to a phylactery. It combines the power of a dragon with the resilience of undeath, making it nearly impossible to destroy permanently.', 'Dracoliches are dragons who have achieved lichdom. They are among the most feared undead in Gates. In the post-reset world, they have become more common as dragons seek immortality. Their phylacteries must be destroyed to truly defeat them.', 'S', true, 'MM', '{"undead", "dragon", "lich", "named", "immortal", "phylactery"}'),

-- =============================================
-- NAMED DEMON/DEVIL BOSSES (S-Rank)
-- =============================================

('Demogorgon, Prince of Demons', 'Gargantuan', 'Fiend', 'Chaotic Evil', '26', 90000, 22, NULL, 406, '28d20+224', 50, NULL, 50, 29, 14, 26, 20, 18, 24, '{"cold", "fire", "lightning"}', '{"poison"}', '{"radiant"}', '{"charmed", "frightened", "poisoned"}', '{"truesight": 120, "passive Perception": 18}', '{"Abyssal", "telepathy 120 ft."}', 'The most powerful demon prince, with two heads that think independently. He commands legions of demons and seeks to corrupt all of creation. His mere presence can drive mortals insane.', 'Demogorgon is the Prince of Demons, the most powerful of all demon lords. In the post-reset world, he challenges the Supreme Deity''s authority, claiming that chaos and corruption are the true nature of existence. Only the Shadow Monarch himself could truly defeat him.', 'S', true, 'MM', '{"fiend", "demon", "prince", "named", "two-headed", "insanity"}'),
('Orcus, Prince of Undeath', 'Gargantuan', 'Fiend', 'Chaotic Evil', '26', 90000, 20, NULL, 405, '27d20+189', 40, NULL, NULL, 27, 14, 24, 20, 17, 25, '{"cold", "fire", "lightning"}', '{"poison"}', '{"radiant"}', '{"charmed", "frightened", "poisoned"}', '{"truesight": 120, "passive Perception": 17}', '{"Abyssal", "telepathy 120 ft."}', 'A demon prince who commands all undead. He wields the Wand of Orcus, a legendary artifact that can raise the dead and command legions of undead. He seeks to transform all life into undeath.', 'Orcus is the Prince of Undeath, commanding all undead creatures. In the post-reset world, he challenges the Supreme Deity''s authority, claiming that death and undeath are the true nature of existence. His wand is one of the most powerful artifacts in existence.', 'S', true, 'MM', '{"fiend", "demon", "prince", "named", "undeath", "wand"}'),
('Asmodeus, Lord of the Nine Hells', 'Large', 'Fiend', 'Lawful Evil', '30', 155000, 21, NULL, 666, '36d10+468', 30, NULL, NULL, 29, 17, 26, 30, 24, 28, '{"cold", "fire", "poison"}', '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{}', '{"charmed", "exhaustion", "frightened", "poisoned"}', '{"truesight": 120, "passive Perception": 24}', '{"all", "telepathy 120 ft."}', 'The absolute ruler of the Nine Hells and the most powerful devil in existence. He commands all devils and seeks to corrupt all souls. His power rivals that of the Supreme Deity himself.', 'Asmodeus is the Lord of the Nine Hells, the absolute ruler of all devils. In the post-reset world, he challenges the Supreme Deity''s authority, claiming that order through tyranny is superior to chaos. His power is such that even the Shadow Monarch must take him seriously as a threat.', 'S', true, 'MM', '{"fiend", "devil", "lord", "named", "nine-hells", "archfiend"}'),

-- =============================================
-- NAMED UNDEAD BOSSES (S-Rank)
-- =============================================

('Acererak, the Demilich', 'Tiny', 'Undead', 'Neutral Evil', '21', 33000, 20, NULL, 80, '32d4', 0, NULL, NULL, 1, 20, 10, 20, 20, 20, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"cold", "fire", "lightning", "necrotic", "poison", "psychic"}', '{"radiant"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"}', '{"truesight": 120, "passive Perception": 20}', '{"Common plus up to five other languages", "telepathy 120 ft."}', 'A legendary lich who has transcended even lichdom, becoming a demilich. Only his skull remains, but he is more powerful than ever. He can trap souls and command legions of undead.', 'Acererak is a unique lich who has achieved demilichdom, transcending even normal lichdom. In the post-reset world, he challenges the Supreme Deity''s authority, claiming that true immortality comes from transcending all forms of existence. His skull is one of the most powerful artifacts in existence.', 'S', true, 'MM', '{"undead", "lich", "demilich", "named", "immortal", "skull"}'),
('Vecna, the Archlich', 'Medium', 'Undead', 'Neutral Evil', '26', 90000, 20, NULL, 272, '32d8+128', 30, NULL, NULL, 10, 16, 18, 20, 19, 24, '{"cold", "lightning", "necrotic"}', '{"poison"}', '{"radiant"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "poisoned"}', '{"truesight": 120, "passive Perception": 19}', '{"all", "telepathy 120 ft."}', 'A legendary archlich who achieved godhood through dark rituals. He wields the Hand and Eye of Vecna, legendary artifacts that grant incredible power. He seeks to become the supreme ruler of all existence.', 'Vecna is a unique archlich who achieved godhood. In the post-reset world, he challenges the Supreme Deity''s authority, claiming that he is the true god of secrets and undeath. His Hand and Eye are among the most powerful artifacts in existence, rivaling even the Supreme Deity''s power.', 'S', true, 'MM', '{"undead", "lich", "archlich", "named", "god", "hand-of-vecna", "eye-of-vecna"}'),

-- =============================================
-- NAMED ELEMENTAL BOSSES (S-Rank)
-- =============================================

('Imix, Prince of Evil Fire', 'Huge', 'Elemental', 'Chaotic Evil', '19', 22000, 17, NULL, 325, '26d12+156', 50, NULL, NULL, 25, 20, 24, 16, 15, 18, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"fire", "poison"}', '{}', '{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"}', '{"darkvision": 120, "passive Perception": 15}', '{"Ignan", "telepathy 120 ft."}', 'The Prince of Evil Fire, a massive fire elemental who commands all fire elementals. He seeks to burn all of creation and transform the world into a realm of eternal flame.', 'Imix is the Prince of Evil Fire, commanding all fire elementals. In the post-reset world, he challenges the Supreme Deity''s authority, claiming that fire and destruction are the true nature of existence. He rules volcano Gates with absolute power.', 'S', true, 'MM', '{"elemental", "fire", "prince", "named", "evil-fire"}'),
('Ogremoch, Prince of Evil Earth', 'Huge', 'Elemental', 'Lawful Evil', '20', 25000, 18, NULL, 526, '31d12+341', 30, NULL, NULL, 30, 8, 28, 12, 15, 18, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"poison"}', '{}', '{"exhaustion", "paralyzed", "petrified", "poisoned", "unconscious"}', '{"darkvision": 120, "tremorsense": 120, "passive Perception": 15}', '{"Terran", "telepathy 120 ft."}', 'The Prince of Evil Earth, a massive earth elemental who commands all earth elementals. He seeks to crush all of creation and transform the world into a realm of stone and dust.', 'Ogremoch is the Prince of Evil Earth, commanding all earth elementals. In the post-reset world, he challenges the Supreme Deity''s authority, claiming that stone and permanence are the true nature of existence. He rules underground Gates with absolute power.', 'S', true, 'MM', '{"elemental", "earth", "prince", "named", "evil-earth"}'),
('Olhydra, Princess of Evil Water', 'Huge', 'Elemental', 'Chaotic Evil', '18', 20000, 17, NULL, 324, '24d12+168', 50, NULL, 150, 24, 20, 24, 18, 17, 20, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"acid", "fire", "poison"}', '{}', '{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"}', '{"darkvision": 120, "passive Perception": 17}', '{"Aquan", "telepathy 120 ft."}', 'The Princess of Evil Water, a massive water elemental who commands all water elementals. She seeks to drown all of creation and transform the world into a realm of eternal ocean.', 'Olhydra is the Princess of Evil Water, commanding all water elementals. In the post-reset world, she challenges the Supreme Deity''s authority, claiming that water and change are the true nature of existence. She rules ocean Gates with absolute power.', 'S', true, 'MM', '{"elemental", "water", "princess", "named", "evil-water"}'),
('Yan-C-Bin, Prince of Evil Air', 'Huge', 'Elemental', 'Neutral Evil', '18', 20000, 19, NULL, 363, '22d12+220', 0, NULL, NULL, 24, 24, 26, 16, 17, 20, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"lightning", "thunder", "poison"}', '{}', '{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"}', '{"darkvision": 120, "passive Perception": 17}', '{"Auran", "telepathy 120 ft."}', 'The Prince of Evil Air, a massive air elemental who commands all air elementals. He seeks to scatter all of creation and transform the world into a realm of eternal wind.', 'Yan-C-Bin is the Prince of Evil Air, commanding all air elementals. In the post-reset world, he challenges the Supreme Deity''s authority, claiming that air and freedom are the true nature of existence. He rules sky Gates with absolute power.', 'S', true, 'MM', '{"elemental", "air", "prince", "named", "evil-air"}'),

-- =============================================
-- NAMED MONSTROSITY BOSSES (S-Rank)
-- =============================================

('Atropus, the World Born Dead', 'Gargantuan', 'Undead', 'Neutral Evil', '30', 155000, 25, NULL, 900, '40d20+480', 60, NULL, NULL, 30, 11, 30, 3, 11, 11, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"cold", "necrotic", "poison"}', '{"radiant"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "poisoned"}', '{"blindsight": 120, "passive Perception": 11}', '{"telepathy 120 ft."}', 'A massive undead moon that orbits the world, spreading death and undeath wherever it passes. It is a living world that died and now seeks to kill all other worlds.', 'Atropus is the World Born Dead, a unique undead entity that is an entire world that died and became undead. In the post-reset world, it challenges the Supreme Deity''s authority, claiming that death and undeath are the true nature of all existence. Only the Shadow Monarch himself could truly defeat it.', 'S', true, 'MM', '{"undead", "monstrosity", "world", "named", "moon", "world-ending"}'),

-- =============================================
-- NAMED CELESTIAL BOSSES (S-Rank, Good-Aligned)
-- =============================================

('Zariel, the Fallen Angel', 'Large', 'Fiend', 'Lawful Evil', '26', 90000, 21, NULL, 580, '40d10+360', 30, NULL, NULL, 27, 22, 28, 26, 24, 26, '{"cold"}', '{"fire", "poison"}', '{}', '{"poisoned", "charmed", "frightened"}', '{"truesight": 120, "passive Perception": 24}', '{"all", "telepathy 120 ft."}', 'A fallen angel who was once a celestial but fell from grace and became an archdevil. She commands the armies of Avernus, the first layer of hell, and seeks to corrupt all of creation.', 'Zariel is a unique being who was once a celestial but fell from grace. In the post-reset world, she challenges the Supreme Deity''s authority, claiming that her fall proves that even the highest beings can be corrupted. She serves as a warning of the dangers of pride and ambition.', 'S', true, 'MM', '{"fiend", "devil", "fallen-angel", "named", "archdevil", "avernus"}'),

-- =============================================
-- NAMED CONSTRUCT BOSSES (S-Rank)
-- =============================================

('The Terrasque', 'Gargantuan', 'Monstrosity', 'Unaligned', '30', 155000, 25, NULL, 676, '33d20+330', 40, NULL, NULL, 30, 11, 30, 3, 11, 11, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"fire", "poison"}', '{}', '{"charmed", "frightened", "paralyzed", "poisoned"}', '{"blindsight": 120, "passive Perception": 11}', '{}', 'The most powerful non-Monarch creature in existence. Its awakening signals the end of an era, and only the Supreme Deity can truly defeat it. It is nearly indestructible and can regenerate from any wound.', 'The Tarrasque is a world-ending monster that awakens only when the balance of power is threatened. In the post-reset world, it remains dormant, kept in check by the Supreme Deity''s power. Should it awaken, it would challenge even the Supreme Deity''s authority, requiring the full might of divine power to defeat. It is the ultimate test of the Supreme Deity''s power.', 'S', true, 'MM', '{"monstrosity", "world-ending", "regeneration", "indestructible", "named", "legendary"}')

ON CONFLICT (name) DO NOTHING;

-- All named bosses are marked as is_boss = true
-- These are legendary creatures with unique histories and powers
-- All aligned with Solo Leveling universe post-reset timeline

