-- =============================================
-- D&D 5E SRD MONSTERS - CR 5 to 10
-- Complete coverage adapted for Solo Leveling Universe
-- Post-Reset Timeline: Supreme Deity (post-reset world)
-- =============================================
-- Part 4: CR 5-10 monsters (B-Rank to A-Rank)
-- All entries aligned with Solo Leveling manwha setting, theme, tone, and aesthetic

INSERT INTO compendium_monsters (name, size, creature_type, alignment, cr, xp, armor_class, armor_type, hit_points_average, hit_points_formula, speed_walk, speed_fly, speed_swim, str, agi, vit, int, sense, pre, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, description, lore, gate_rank, is_boss, source_book, tags) VALUES

-- =============================================
-- CR 5 MONSTERS (B-Rank)
-- =============================================

('Air Elemental', 'Large', 'Elemental', 'Neutral', '5', 1800, 15, NULL, 90, '12d10+24', 0, NULL, NULL, 14, 20, 14, 6, 10, 6, '{"lightning", "thunder"}', '{"poison"}', '{}', '{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"}', '{"darkvision": 60, "passive Perception": 10}', '{"Auran"}', 'Manifestations of wind mana that swirl through high-altitude Gates. They can become whirlwinds and suffocate hunters in the post-reset world.', 'After the reset, air elementals became more common in sky-themed Gates. They serve as guardians of the upper realms, posing a threat to hunters exploring high-altitude Gate areas.', 'B', false, 'MM', '{"elemental", "air", "flying"}'),
('Barbed Devil', 'Medium', 'Fiend', 'Lawful Evil', '5', 1800, 15, NULL, 110, '13d8+52', 30, NULL, NULL, 16, 17, 18, 12, 14, 14, '{"cold"}', '{"fire", "poison"}', '{}', '{"poisoned"}', '{"darkvision": 120, "passive Perception": 14}', '{"Infernal", "telepathy 120 ft."}', 'Devils covered in sharp barbs that damage attackers. They serve the infernal hierarchy that persists even after the reset.', 'Barbed Devils patrol the deeper levels of high-rank Gates, enforcing the will of their infernal masters.', 'B', false, 'MM', '{"fiend", "devil"}'),
('Bulette', 'Large', 'Monstrosity', 'Unaligned', '5', 1800, 17, NULL, 94, '9d10+45', 40, NULL, 40, 19, 11, 17, 2, 6, 5, '{}', '{}', '{}', '{}', '{"darkvision": 60, "tremorsense": 60, "passive Perception": 6}', '{}', 'Land sharks that burrow through earth and stone. Found in subterranean Gates, they erupt from the ground to devour hunters whole in the post-reset world.', 'Bulettes are feared by hunters for their ambush tactics. They can sense vibrations through the earth and strike without warning, making them one of the most dangerous predators in underground Gate environments.', 'B', false, 'MM', '{"monstrosity", "burrow"}'),
('Crocodile, Giant', 'Huge', 'Beast', 'Unaligned', '5', 1800, 14, NULL, 85, '9d12+27', 30, NULL, 50, 21, 8, 17, 2, 10, 5, '{}', '{}', '{}', '{}', '{"passive Perception": 10}', '{}', 'Massive crocodiles enhanced by Gate mana that lurk in swamp and river Gates. They can hold their breath for hours and drag hunters underwater in the post-reset world.', 'These apex predators rule aquatic B-Rank Gates, ambushing hunters who venture too close to the water. Their size and power have been enhanced by Gate mana since the reset.', 'B', false, 'MM', '{"beast", "aquatic"}'),
('Earth Elemental', 'Large', 'Elemental', 'Neutral', '5', 1800, 17, NULL, 126, '12d10+60', 30, NULL, NULL, 20, 8, 20, 5, 10, 5, '{"bludgeoning", "piercing"}', '{"poison"}', '{}', '{"exhaustion", "paralyzed", "petrified", "poisoned", "unconscious"}', '{"darkvision": 60, "tremorsense": 60, "passive Perception": 10}', '{"Terran"}', 'Massive beings of stone and earth that guard underground Gates. They can move through stone and earth as if it were air.', 'Earth Elementals are the guardians of deep Gate dungeons. After the reset, they became more common in mining-themed Gates.', 'B', false, 'MM', '{"elemental", "earth"}'),
('Fire Elemental', 'Large', 'Elemental', 'Neutral', '5', 1800, 13, NULL, 102, '12d8+48', 50, NULL, NULL, 10, 17, 16, 6, 10, 7, '{"bludgeoning", "piercing", "slashing from nonmagical attacks"}', '{"fire", "poison"}', '{}', '{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"}', '{"darkvision": 60, "passive Perception": 10}', '{"Ignan"}', 'Blazing entities of pure fire mana that ignite everything they touch. They are drawn to volcanic Gates and areas of intense heat.', 'Fire Elementals became more powerful after the reset, as fire mana became more concentrated in certain Gate types.', 'B', false, 'MM', '{"elemental", "fire"}'),
('Flesh Golem', 'Medium', 'Construct', 'Neutral', '5', 1800, 9, NULL, 93, '11d8+44', 30, NULL, NULL, 19, 9, 18, 6, 10, 5, '{"bludgeoning", "piercing", "slashing from nonmagical attacks that aren''t adamantine"}', '{"lightning", "poison"}', '{"lightning"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"}', '{"darkvision": 60, "passive Perception": 10}', '{"understands the languages of its creator but cannot speak"}', 'Grotesque constructs stitched together from multiple corpses. Created by dark mages who experiment with Gate mana and necromancy.', 'Flesh Golems are abominations that violate the natural order. After the reset, their creation became more common as mages pushed boundaries.', 'B', false, 'MM', '{"construct", "undead", "flesh"}'),
('Giant Crocodile', 'Huge', 'Beast', 'Unaligned', '5', 1800, 14, NULL, 85, '9d12+27', 30, NULL, 50, 21, 8, 17, 2, 10, 5, '{}', '{}', '{}', '{}', '{"passive Perception": 10}', '{}', 'Massive crocodiles that rule swamp Gates. Their powerful jaws can crush bone and their death roll tears apart prey.', 'These apex predators have grown larger since the reset, as Gate mana has enhanced their natural abilities.', 'B', false, 'MM', '{"beast", "aquatic"}'),
('Gladiator', 'Medium', 'Humanoid', 'Any', '5', 1800, 16, 'studded leather, shield', 112, '15d8+45', 30, NULL, NULL, 18, 15, 16, 10, 12, 15, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Elite warriors who fight in Gate arenas for entertainment and glory. They have survived countless battles and honed their skills to perfection.', 'Gladiators are often former S-Rank hunters who chose to fight in controlled environments rather than face the dangers of high-rank Gates.', 'B', false, 'MM', '{"humanoid", "warrior"}'),
('Gorgon', 'Large', 'Monstrosity', 'Unaligned', '5', 1800, 19, NULL, 114, '12d10+48', 30, NULL, NULL, 20, 11, 19, 2, 12, 8, '{}', '{"petrified"}', '{}', '{}', '{"darkvision": 60, "passive Perception": 12}', '{}', 'Massive bull-like creatures with metallic hides. Their breath can turn living creatures to stone instantly.', 'Gorgons are rare but feared monsters that guard treasure hoards in B-Rank Gates. Their petrifying breath makes them nearly invincible.', 'B', false, 'MM', '{"monstrosity", "petrification"}'),
('Half-Red Dragon Veteran', 'Medium', 'Humanoid', 'Any', '5', 1800, 18, 'plate', 65, '10d8+20', 30, NULL, NULL, 17, 13, 14, 10, 11, 14, '{"fire"}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 11}', '{"Common", "Draconic"}', 'Veteran warriors who have been infused with dragon blood through Gate corruption or dark rituals. They can breathe fire and have draconic resilience.', 'Half-dragons are the result of experiments or curses that blend human and dragon essence. They are powerful but often unstable.', 'B', false, 'MM', '{"humanoid", "dragon", "fire"}'),
('Hill Giant', 'Huge', 'Giant', 'Chaotic Evil', '5', 1800, 13, NULL, 105, '10d12+40', 40, NULL, NULL, 21, 8, 19, 5, 9, 5, '{}', '{}', '{}', '{}', '{}', '{"Giant"}', 'Massive humanoids that dwell in mountainous Gates. They throw boulders with devastating accuracy and crush enemies with their clubs.', 'Hill Giants are the most common type of giant in B-Rank Gates. They are simple-minded but incredibly strong.', 'B', false, 'MM', '{"giant"}'),
('Ice Devil', 'Large', 'Fiend', 'Lawful Evil', '5', 1800, 18, NULL, 180, '19d10+76', 40, NULL, NULL, 18, 14, 20, 11, 12, 14, '{"bludgeoning, piercing, slashing from nonmagical attacks that aren''t silvered"}', '{"cold", "fire", "poison"}', '{}', '{"poisoned"}', '{"blindsight": 60, "darkvision": 120, "passive Perception": 12}', '{"Infernal", "telepathy 120 ft."}', 'Devils of ice and cold that rule frozen Gates. Their touch freezes flesh and their weapons cause wounds that never heal.', 'Ice Devils serve the infernal hierarchy that persists even after the reset. They are among the most organized and dangerous of devils.', 'B', false, 'MM', '{"fiend", "devil", "cold"}'),
('Nightmare', 'Large', 'Fiend', 'Neutral Evil', '5', 1800, 13, NULL, 68, '8d10+24', 60, NULL, NULL, 18, 15, 16, 10, 13, 15, '{}', '{"fire"}', '{}', '{}', '{"passive Perception": 13}', '{"understands Abyssal, Common, and Infernal but cannot speak"}', 'Fiendish horses wreathed in flame. They can travel through the ethereal plane and serve as mounts for powerful fiends.', 'Nightmares are the steeds of devils and demons. They can phase through dimensions and breathe fire.', 'B', false, 'MM', '{"fiend", "flying", "fire"}'),
('Owlbear', 'Large', 'Monstrosity', 'Unaligned', '3', 700, 13, NULL, 59, '7d10+21', 40, NULL, NULL, 20, 12, 17, 3, 13, 7, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 13}', '{"Owlbear"}', 'Iconic hybrid creatures with bear bodies and owl heads. Ferocious and territorial, they guard their Gate territories with deadly force.', 'Owlbears are among the most recognizable monsters in Gates. Their hybrid nature makes them unpredictable and dangerous.', 'C', false, 'MM', '{"monstrosity"}'),
('Roper', 'Large', 'Monstrosity', 'Neutral Evil', '5', 1800, 20, NULL, 93, '11d10+33', 10, NULL, NULL, 18, 8, 17, 7, 16, 6, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 16}', '{}', 'Cave-dwelling monsters that resemble stalactites. They use sticky tendrils to pull prey into their gaping maws.', 'Ropers are ambush predators that wait motionless for days until prey comes within range. Their false appearance makes them deadly.', 'B', false, 'MM', '{"monstrosity", "ambush"}'),
('Salamander', 'Large', 'Elemental', 'Neutral Evil', '5', 1800, 15, NULL, 90, '12d10+24', 30, NULL, NULL, 18, 14, 15, 11, 10, 12, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"fire"}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Ignan"}', 'Serpentine fire elementals that dwell in volcanic Gates. They can wrap around enemies and burn them with their touch.', 'Salamanders are drawn to areas of intense heat and fire mana. They serve as guardians of volcanic Gate cores.', 'B', false, 'MM', '{"elemental", "fire"}'),
('Shambling Mound', 'Large', 'Plant', 'Unaligned', '5', 1800, 15, NULL, 136, '16d10+48', 20, NULL, 20, 16, 8, 16, 5, 10, 5, '{"cold", "fire"}', '{"lightning"}', '{}', '{"blinded", "deafened", "exhaustion"}', '{"blindsight": 60, "blind beyond this radius": true, "passive Perception": 10}', '{}', 'Massive plant creatures that absorb lightning and grow stronger. They smother enemies and absorb their life force.', 'Shambling Mounds are created when Gate mana corrupts plant life. They absorb electrical energy and use it to grow.', 'B', false, 'MM', '{"plant", "lightning-absorption"}'),
('Triceratops', 'Huge', 'Beast', 'Unaligned', '5', 1800, 13, NULL, 95, '10d12+30', 50, NULL, NULL, 22, 9, 17, 2, 11, 5, '{}', '{}', '{}', '{}', '{"passive Perception": 11}', '{}', 'Massive herbivorous dinosaurs with three horns and a bony frill. Their charge is devastating and their horns can gore enemies.', 'Triceratops are found in prehistoric-themed Gates. They are territorial and will charge anything that threatens them.', 'B', false, 'MM', '{"beast", "dinosaur"}'),
('Troll', 'Large', 'Giant', 'Chaotic Evil', '5', 1800, 15, NULL, 84, '8d10+40', 30, NULL, NULL, 18, 13, 20, 7, 9, 7, '{}', '{}', '{"acid", "fire"}', '{}', '{"darkvision": 60, "passive Perception": 9}', '{"Giant"}', 'Regenerating horrors that must be killed with fire or acid. Their wounds close within seconds, making them nearly impossible to kill through normal means.', 'Trolls are among the most feared monsters in B-Rank Gates. Their regeneration makes them nearly invincible unless hunters know their weakness.', 'B', false, 'MM', '{"giant", "regeneration"}'),
('Unicorn', 'Large', 'Celestial', 'Lawful Good', '5', 1800, 12, NULL, 67, '9d10+18', 50, NULL, NULL, 18, 14, 15, 11, 17, 16, '{"poison"}', '{"charmed", "paralyzed", "poisoned"}', '{}', '{}', '{"darkvision": 60, "passive Perception": 17}', '{"Celestial", "Elvish", "Sylvan", "telepathy 60 ft."}', 'Pure-hearted celestial horses with a single horn. They can heal allies and teleport short distances. Serve as protectors of nature in Gates.', 'Unicorns are rare celestial beings that appear in Gates with strong nature mana. They protect the innocent and heal the wounded.', 'B', false, 'MM', '{"celestial", "healing", "teleport"}'),
('Vampire Spawn', 'Medium', 'Undead', 'Chaotic Evil', '5', 1800, 15, NULL, 82, '11d8+33', 30, NULL, NULL, 16, 16, 16, 11, 10, 12, '{"necrotic"}', '{"poison"}', '{"radiant"}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"the languages it knew in life"}', 'Lesser vampires that serve a vampire master. They drain blood to heal their wounds and can transform into mist or bats.', 'Vampire Spawn are created when a vampire drains a victim''s blood completely. They are bound to serve their creator until freed.', 'B', false, 'MM', '{"undead", "vampire", "shapechanger"}'),
('Water Elemental', 'Large', 'Elemental', 'Neutral', '5', 1800, 14, NULL, 114, '12d10+48', 0, NULL, 90, 18, 14, 18, 5, 10, 8, '{"acid", "fire"}', '{"poison"}', '{}', '{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"}', '{"darkvision": 60, "passive Perception": 10}', '{"Aquan"}', 'Massive beings of water that guard aquatic Gates. They can engulf enemies and drown them, or create powerful water blasts.', 'Water Elementals are common in ocean and river-themed Gates. They can move through water as if it were air.', 'B', false, 'MM', '{"elemental", "aquatic"}'),
('Werebear', 'Medium', 'Humanoid', 'Neutral Good', '5', 1800, 10, NULL, 135, '18d8+54', 30, NULL, 30, 19, 10, 17, 11, 12, 12, '{"bludgeoning, piercing, slashing from nonmagical attacks not made with silvered weapons"}', '{}', '{}', '{}', '{"passive Perception": 12}', '{"Common"}', 'Shape-changing humanoids cursed with lycanthropy. Can transform into bears or hybrid forms. Unlike other werecreatures, werebears are often good-aligned.', 'Werebears are protectors of nature who use their curse for good. They guard forest Gates and protect innocent travelers.', 'B', false, 'MM', '{"humanoid", "shapechanger", "lycanthrope"}'),
('Wraith', 'Medium', 'Undead', 'Chaotic Evil', '5', 1800, 13, NULL, 67, '9d8+27', 0, NULL, NULL, 6, 16, 14, 12, 12, 10, '{"acid", "cold", "fire", "lightning", "thunder"}', '{"necrotic", "poison"}', '{"radiant"}', '{"charmed", "exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"}', '{"darkvision": 60, "passive Perception": 12}', '{"the languages it knew in life"}', 'Powerful incorporeal undead that drain life force. They can create spawn from their victims and pass through walls and objects.', 'Wraiths are the spirits of those who died with great hatred or regret. After the reset, they became more common as the boundary between life and death weakened.', 'B', false, 'MM', '{"undead", "incorporeal", "spawn"}'),
('Xorn', 'Medium', 'Elemental', 'Neutral', '5', 1800, 19, NULL, 73, '7d10+35', 20, NULL, NULL, 17, 10, 22, 11, 10, 10, '{"piercing", "slashing"}', '{}', '{}', '{}', '{"darkvision": 60, "tremorsense": 60, "passive Perception": 10}', '{"Terran"}', 'Earth elementals that devour gems and precious metals. They can move through stone and detect valuable materials from great distances.', 'Xorns are drawn to treasure hoards in Gates. They can sense precious metals and gems, making them both valuable allies and dangerous enemies.', 'B', false, 'MM', '{"elemental", "earth", "treasure"}'),

-- =============================================
-- CR 6 MONSTERS (B-Rank)
-- =============================================

('Chimera', 'Large', 'Monstrosity', 'Chaotic Evil', '6', 2300, 14, NULL, 114, '12d10+48', 30, NULL, NULL, 19, 11, 19, 3, 14, 10, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 14}', '{"understands Draconic but cannot speak"}', 'Three-headed monstrosities with lion, goat, and dragon heads. Each head attacks independently and has its own breath weapon.', 'Chimeras are the result of dark experiments that blend multiple creatures. They are chaotic and unpredictable, attacking anything that moves.', 'B', false, 'MM', '{"monstrosity", "multi-headed"}'),
('Cyclops', 'Huge', 'Giant', 'Chaotic Neutral', '6', 2300, 14, NULL, 138, '12d12+60', 30, NULL, NULL, 22, 11, 20, 8, 6, 10, '{}', '{}', '{}', '{}', '{"passive Perception": 6}', '{"Giant"}', 'Massive one-eyed giants that dwell in island and coastal Gates. They throw massive boulders and wield tree-sized clubs.', 'Cyclopes are simple-minded but incredibly strong. They are often found guarding treasure hoards or serving as gatekeepers for powerful entities.', 'B', false, 'MM', '{"giant", "one-eyed"}'),
('Drider', 'Large', 'Monstrosity', 'Chaotic Evil', '6', 2300, 19, NULL, 123, '13d10+52', 30, NULL, NULL, 16, 16, 16, 13, 15, 13, '{"poison"}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 15}', '{"Elvish", "Undercommon"}', 'Drow who failed their goddess and were transformed into spider-drow hybrids. They are outcasts who dwell in the deepest Gate levels.', 'Driders are cursed drow who were punished for failing their dark goddess. They are bitter and hateful, attacking all who enter their territory.', 'B', false, 'MM', '{"monstrosity", "drow", "spider"}'),
('Invisible Stalker', 'Medium', 'Elemental', 'Neutral', '6', 2300, 14, NULL, 104, '16d8+32', 50, NULL, NULL, 16, 19, 14, 10, 15, 11, '{"bludgeoning, piercing, slashing from nonmagical attacks"}', '{"poison"}', '{}', '{"exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "unconscious"}', '{"darkvision": 60, "passive Perception": 15}', '{"Auran", "understands the languages of its creator but cannot speak"}', 'Invisible air elementals bound to serve a master. They are perfect assassins, able to track targets across vast distances.', 'Invisible Stalkers are created by powerful mages to serve as assassins and trackers. They are bound by magic and cannot disobey their creator.', 'B', false, 'MM', '{"elemental", "air", "invisible", "assassin"}'),
('Mage', 'Medium', 'Humanoid', 'Any', '6', 2300, 12, NULL, 40, '9d8', 30, NULL, NULL, 9, 14, 11, 17, 12, 11, '{}', '{}', '{}', '{}', '{}', '{"Any four languages"}', 'Powerful spellcasters who have mastered Gate magic. They can cast devastating spells and protect themselves with magical barriers.', 'Mages are among the most dangerous humanoid enemies in Gates. They combine intelligence with powerful magic, making them deadly opponents.', 'B', false, 'MM', '{"humanoid", "spellcaster", "mage"}'),
('Mammoth', 'Huge', 'Beast', 'Unaligned', '6', 2300, 13, NULL, 126, '11d12+55', 40, NULL, NULL, 24, 9, 21, 3, 11, 6, '{}', '{}', '{}', '{}', '{"passive Perception": 11}', '{}', 'Massive woolly elephants found in arctic Gates. Their tusks can gore enemies and their trample can crush entire formations.', 'Mammoths are powerful herd animals that travel in groups. They are territorial and will charge anything that threatens their herd.', 'B', false, 'MM', '{"beast", "trample"}'),
('Medusa', 'Medium', 'Monstrosity', 'Lawful Evil', '6', 2300, 15, NULL, 127, '17d8+51', 30, NULL, NULL, 10, 15, 16, 12, 13, 15, '{"poison"}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 13}', '{"Common"}', 'Serpent-haired humanoids whose gaze turns victims to stone. They dwell in ancient ruins and guard treasure hoards.', 'Medusas are cursed beings who were transformed by dark magic. They are bitter and hateful, turning all who look upon them to stone.', 'B', false, 'MM', '{"monstrosity", "petrification"}'),
('Vrock', 'Large', 'Fiend', 'Chaotic Evil', '6', 2300, 15, NULL, 104, '16d8+32', 40, NULL, NULL, 17, 15, 18, 8, 13, 8, '{"cold", "fire", "lightning"}', '{"poison"}', '{}', '{"poisoned"}', '{"darkvision": 120, "passive Perception": 13}', '{"Abyssal", "telepathy 120 ft."}', 'Vulture-like demons that serve the demon lords. They can shriek to stun enemies and spread disease with their spores.', 'Vrocks are among the most common demons in high-rank Gates. They serve as shock troops for demonic armies.', 'B', false, 'MM', '{"fiend", "demon", "flying"}'),
('Wyvern', 'Large', 'Dragon', 'Unaligned', '6', 2300, 13, NULL, 110, '13d10+39', 20, NULL, NULL, 19, 10, 16, 5, 12, 6, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 12}', '{}', 'Venomous flying dragons that nest in high-altitude Gates. Their tail stingers inject deadly poison that can kill in minutes.', 'Wyverns are smaller cousins of true dragons. They lack breath weapons but make up for it with their deadly venomous stings.', 'B', false, 'MM', '{"dragon", "flying", "poison"}'),
('Young White Dragon', 'Large', 'Dragon', 'Chaotic Evil', '6', 2300, 17, NULL, 133, '14d10+56', 40, NULL, 40, 18, 10, 18, 6, 11, 12, '{"cold"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 11}', '{"Common", "Draconic"}', 'Young ice dragons that rule frozen Gates. Their breath weapon creates cones of freezing cold that can freeze enemies solid.', 'White Dragons are the most bestial of all dragons. They are territorial and attack anything that enters their domain.', 'B', false, 'MM', '{"dragon", "cold"}'),

-- =============================================
-- CR 7 MONSTERS (B-Rank)
-- =============================================

('Giant Ape', 'Huge', 'Beast', 'Unaligned', '7', 2900, 12, NULL, 157, '15d12+60', 40, NULL, NULL, 23, 14, 18, 7, 12, 7, '{}', '{}', '{}', '{}', '{}', '{}', 'Massive apes found in jungle-themed Gates. They can throw boulders and crush enemies with their fists.', 'Giant Apes are territorial and will attack anything that threatens their territory. They are incredibly strong and agile.', 'B', false, 'MM', '{"beast", "ape"}'),
('Grick Alpha', 'Large', 'Monstrosity', 'Neutral', '7', 2900, 18, NULL, 75, '10d10+20', 30, NULL, 30, 18, 15, 16, 4, 14, 5, '{"bludgeoning, piercing, slashing from nonmagical attacks that aren''t adamantine"}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 14}', '{}', 'Massive worm-like predators with tentacles and beaks. They are pack leaders that coordinate attacks with their smaller kin.', 'Grick Alphas are the leaders of grick packs. They are more intelligent and dangerous than regular gricks.', 'B', false, 'MM', '{"monstrosity", "pack-leader"}'),
('Mind Flayer', 'Medium', 'Aberration', 'Lawful Evil', '7', 2900, 15, NULL, 71, '13d8+13', 30, NULL, NULL, 11, 12, 12, 19, 17, 17, '{}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 17}', '{"Deep Speech", "Undercommon", "telepathy 120 ft."}', 'Cephalopod-like aberrations with powerful psionic abilities. They can extract brains from victims and control minds.', 'Mind Flayers are among the most feared aberrations in Gates. They seek to dominate all intelligent life and build empires of thralls.', 'B', false, 'MM', '{"aberration", "psionic", "mind-control"}'),
('Oni', 'Large', 'Giant', 'Lawful Evil', '7', 2900, 16, NULL, 110, '13d10+39', 30, NULL, NULL, 19, 11, 16, 14, 13, 15, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 13}', '{"Common", "Giant"}', 'Shape-changing ogre mages who can cast spells and transform into other forms. They are intelligent and cunning.', 'Oni are ogres who have mastered magic. They are far more dangerous than regular ogres, combining brute strength with magical power.', 'B', false, 'MM', '{"giant", "spellcaster", "shapechanger"}'),
('Shield Guardian', 'Large', 'Construct', 'Unaligned', '7', 2900, 17, NULL, 142, '15d10+60', 30, NULL, NULL, 18, 8, 18, 7, 10, 3, '{"poison"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "poisoned"}', '{}', '{}', '{"blindsight": 10, "darkvision": 60, "passive Perception": 10}', '{"understands commands given in any language but cannot speak"}', 'Massive constructs that serve as bodyguards for powerful mages. They can absorb damage meant for their master and regenerate.', 'Shield Guardians are bound to an amulet held by their master. They will protect their master at all costs, even sacrificing themselves.', 'B', false, 'MM', '{"construct", "guardian"}'),
('Stone Giant', 'Huge', 'Giant', 'Neutral', '7', 2900, 17, NULL, 126, '11d12+55', 40, NULL, NULL, 23, 15, 20, 10, 12, 9, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 12}', '{"Giant"}', 'Massive giants who dwell in mountainous Gates. They can throw boulders with incredible accuracy and blend with stone.', 'Stone Giants are reclusive and prefer to be left alone. They attack only when their territory is threatened.', 'B', false, 'MM', '{"giant", "stone"}'),
('Young Black Dragon', 'Large', 'Dragon', 'Chaotic Evil', '7', 2900, 18, NULL, 127, '15d10+45', 40, NULL, 80, 19, 14, 17, 12, 11, 15, '{"acid"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 11}', '{"Common", "Draconic"}', 'Acid-breathing dragons that rule swamp-themed Gates. Their ambush tactics are legendary, and they use the terrain to their advantage.', 'Black Dragons are among the most cunning and cruel of all dragons. They delight in the suffering of their victims.', 'B', false, 'MM', '{"dragon", "acid"}'),
('Young Copper Dragon', 'Large', 'Dragon', 'Chaotic Good', '7', 2900, 17, NULL, 119, '14d10+42', 40, NULL, 40, 17, 12, 17, 16, 13, 15, '{"acid"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 13}', '{"Common", "Draconic"}', 'Playful acid dragons that enjoy tricks and pranks. Despite their playful nature, they are still dangerous when threatened.', 'Copper Dragons are among the most social of all dragons. They enjoy conversation and games, but can be deadly when angered.', 'B', false, 'MM', '{"dragon", "acid", "good"}'),

-- =============================================
-- CR 8 MONSTERS (B-Rank to A-Rank)
-- =============================================

('Assassin', 'Medium', 'Humanoid', 'Any', '8', 3900, 15, NULL, 78, '12d8+24', 30, NULL, NULL, 11, 16, 14, 13, 11, 10, '{"poison"}', '{}', '{}', '{}', '{"passive Perception": 11}', '{"Thieves'' Cant plus any two languages"}', 'Elite killers who specialize in eliminating high-value targets. They use poison, stealth, and precision strikes to eliminate enemies.', 'Assassins are often hired by guilds or powerful individuals to eliminate rivals. They are masters of stealth and death.', 'B', false, 'MM', '{"humanoid", "assassin", "poison"}'),
('Chain Devil', 'Large', 'Fiend', 'Lawful Evil', '8', 3900, 16, NULL, 85, '10d8+40', 30, NULL, NULL, 18, 15, 18, 11, 12, 14, '{"cold"}', '{"fire", "poison"}', '{}', '{"poisoned"}', '{"darkvision": 120, "passive Perception": 12}', '{"Infernal", "telepathy 120 ft."}', 'Devils wrapped in animate chains that entangle and torture their victims. They serve as jailers in the infernal hierarchy.', 'Chain Devils are among the most feared devils in high-rank Gates. They delight in prolonged torture and suffering.', 'B', false, 'MM', '{"fiend", "devil", "chains"}'),
('Cloaker', 'Large', 'Aberration', 'Chaotic Neutral', '8', 3900, 14, NULL, 78, '12d10+12', 10, NULL, NULL, 17, 15, 12, 13, 12, 14, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 12}', '{"Deep Speech", "understands Common but cannot speak"}', 'Bat-like aberrations that cling to ceilings and drop on prey. They can create phantasmal images and moan to disorient enemies.', 'Cloakers are ambush predators that use illusion and fear to confuse their prey. They are found in the deepest Gate levels.', 'B', false, 'MM', '{"aberration", "flying", "illusion"}'),
('Frost Giant', 'Huge', 'Giant', 'Neutral Evil', '8', 3900, 15, NULL, 138, '12d12+60', 40, NULL, NULL, 23, 9, 21, 9, 10, 12, '{"cold"}', '{}', '{}', '{}', '{}', '{"Giant"}', 'Ice-wielding giants that rule frozen Gates. Their greataxes are carved from glacial ice and their breath freezes enemies.', 'Frost Giants are among the most organized of all giants. They build fortresses in frozen Gates and raid lower-rank Gates for resources.', 'B', false, 'MM', '{"giant", "cold"}'),
('Hezrou', 'Large', 'Fiend', 'Chaotic Evil', '8', 3900, 16, NULL, 136, '13d10+65', 30, NULL, NULL, 19, 17, 20, 5, 12, 13, '{"cold", "fire", "lightning"}', '{"poison"}', '{}', '{"poisoned", "charmed", "frightened"}', '{"darkvision": 120, "passive Perception": 12}', '{"Abyssal", "telepathy 120 ft."}', 'Toad-like demons with powerful claws and a stench that can sicken enemies. They serve as shock troops for demon lords.', 'Hezrous are among the most common high-rank demons. Their stench makes them difficult to fight in close quarters.', 'B', false, 'MM', '{"fiend", "demon", "stench"}'),
('Hydra', 'Huge', 'Monstrosity', 'Unaligned', '8', 3900, 15, NULL, 172, '15d12+75', 30, NULL, 30, 20, 12, 20, 2, 10, 7, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{}', 'Massive serpents with multiple heads. When a head is cut off, two more grow in its place unless the stump is cauterized.', 'Hydras are among the most feared monsters in B-Rank Gates. Their regeneration makes them nearly impossible to kill without fire.', 'B', false, 'MM', '{"monstrosity", "multi-headed", "regeneration"}'),
('Spirit Naga', 'Large', 'Monstrosity', 'Chaotic Evil', '8', 3900, 15, NULL, 75, '10d10+20', 40, NULL, 40, 18, 17, 14, 16, 15, 16, '{"poison"}', '{}', '{}', '{"charmed", "poisoned"}', '{"darkvision": 60, "passive Perception": 15}', '{"Abyssal", "Common"}', 'Serpentine spellcasters that reform after death. They must be permanently destroyed or they will return to seek vengeance.', 'Spirit Nagas are immortal spellcasters who have achieved a form of undeath. They are bound to a phylactery and will reform if destroyed.', 'B', false, 'MM', '{"monstrosity", "spellcaster", "immortal"}'),
('Tyrannosaurus Rex', 'Huge', 'Beast', 'Unaligned', '8', 3900, 13, NULL, 136, '13d12+52', 50, NULL, NULL, 25, 10, 19, 2, 12, 9, '{}', '{}', '{}', '{}', '{"passive Perception": 12}', '{}', 'The apex predator of prehistoric Gates. Massive carnivorous dinosaurs with bone-crushing jaws and devastating strength.', 'T-Rexes are the most feared land predators in prehistoric-themed Gates. Their roar can shake the ground and their bite can crush armor.', 'B', false, 'MM', '{"beast", "dinosaur", "apex-predator"}'),
('Young Bronze Dragon', 'Large', 'Dragon', 'Lawful Good', '8', 3900, 18, NULL, 142, '15d10+60', 40, NULL, 40, 19, 10, 17, 14, 13, 17, '{"lightning"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 13}', '{"Common", "Draconic"}', 'Lightning-breathing dragons that rule coastal Gates. They are noble and just, often protecting innocent travelers.', 'Bronze Dragons are among the most noble of all dragons. They serve as protectors and guardians, fighting against evil.', 'B', false, 'MM', '{"dragon", "lightning", "good"}'),
('Young Green Dragon', 'Large', 'Dragon', 'Lawful Evil', '8', 3900, 18, NULL, 136, '16d10+48', 40, NULL, 40, 19, 12, 17, 16, 13, 15, '{"poison"}', '{}', '{}', '{"poisoned"}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 13}', '{"Common", "Draconic"}', 'Poison-breathing dragons that rule forest Gates. They are cunning and manipulative, using poison and deception to achieve their goals.', 'Green Dragons are among the most intelligent and manipulative of all dragons. They prefer to use poison and trickery over direct combat.', 'B', false, 'MM', '{"dragon", "poison"}'),

-- =============================================
-- CR 9 MONSTERS (A-Rank)
-- =============================================

('Bone Devil', 'Large', 'Fiend', 'Lawful Evil', '9', 5000, 19, NULL, 142, '15d10+60', 40, NULL, NULL, 18, 16, 18, 13, 14, 16, '{"cold"}', '{"fire", "poison"}', '{}', '{"poisoned"}', '{"darkvision": 120, "passive Perception": 14}', '{"Infernal", "telepathy 120 ft."}', 'Skeletal devils that command legions of the damned. Their stingers inject soul-rending poison and they fight with tactical brilliance.', 'Bone Devils are high-ranking officers in hell''s armies. They are intelligent and organized, making them deadly opponents.', 'A', false, 'MM', '{"fiend", "devil", "poison"}'),
('Clay Golem', 'Large', 'Construct', 'Unaligned', '9', 5000, 14, NULL, 133, '14d10+56', 20, NULL, NULL, 20, 9, 18, 3, 8, 1, '{"acid", "bludgeoning, piercing, slashing from nonmagical attacks that aren''t adamantine"}', '{"poison", "psychic"}', '{"acid"}', '{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"}', '{"darkvision": 60, "passive Perception": 8}', '{"understands the languages of its creator but cannot speak"}', 'Animated clay constructs that slow enemies with their touch. They are immune to most forms of damage but vulnerable to acid.', 'Clay Golems are created by powerful mages to serve as guardians. Their slow touch makes them dangerous in melee combat.', 'A', false, 'MM', '{"construct", "slow"}'),
('Cloud Giant', 'Huge', 'Giant', 'Neutral Good', '9', 5000, 14, NULL, 200, '16d12+96', 40, NULL, NULL, 27, 10, 22, 12, 16, 16, '{}', '{}', '{}', '{}', '{"passive Perception": 16}', '{"Common", "Giant"}', 'Massive giants who dwell in cloud castles floating above Gates. They are generally good-aligned and prefer to avoid conflict.', 'Cloud Giants are among the most intelligent and cultured of all giants. They build floating fortresses and collect art and knowledge.', 'A', false, 'MM', '{"giant", "cloud", "good"}'),
('Fire Giant', 'Huge', 'Giant', 'Lawful Evil', '9', 5000, 18, 'plate', 162, '13d12+78', 30, NULL, NULL, 25, 9, 23, 10, 14, 13, '{"fire"}', '{}', '{}', '{}', '{"passive Perception": 14}', '{"Giant"}', 'Massive giants who dwell in volcanic Gates. They are master smiths who forge weapons in the heart of volcanoes.', 'Fire Giants are organized and militaristic. They build fortresses in volcanic Gates and raid lower-rank Gates for resources and slaves.', 'A', false, 'MM', '{"giant", "fire", "smith"}'),
('Stone Golem', 'Large', 'Construct', 'Unaligned', '9', 5000, 17, NULL, 178, '17d10+85', 30, NULL, NULL, 22, 9, 20, 3, 11, 1, '{"bludgeoning, piercing, slashing from nonmagical attacks that aren''t adamantine"}', '{"poison", "psychic"}', '{}', '{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"}', '{"darkvision": 120, "passive Perception": 11}', '{"understands the languages of its creator but cannot speak"}', 'Animated stone warriors immune to most magic. Only the strongest attacks can crack their forms, and they regenerate slowly.', 'Stone Golems are among the most powerful constructs. They are nearly indestructible and serve as guardians for the most valuable treasures.', 'A', false, 'MM', '{"construct", "stone", "regeneration"}'),
('Young Silver Dragon', 'Large', 'Dragon', 'Lawful Good', '9', 5000, 18, NULL, 168, '16d10+80', 40, NULL, 40, 23, 10, 21, 14, 13, 19, '{"cold"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 13}', '{"Common", "Draconic"}', 'Cold-breathing dragons that rule mountain Gates. They are noble and just, often serving as protectors of innocent people.', 'Silver Dragons are among the most noble and good-aligned of all dragons. They fight against evil and protect the innocent.', 'A', false, 'MM', '{"dragon", "cold", "good"}'),
('Young Gold Dragon', 'Large', 'Dragon', 'Lawful Good', '9', 5000, 18, NULL, 178, '17d10+85', 40, NULL, 40, 23, 14, 21, 16, 13, 21, '{"fire"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 13}', '{"Common", "Draconic"}', 'Fire-breathing dragons that are the most powerful of the metallic dragons. They are paragons of good and justice.', 'Gold Dragons are the most powerful and noble of all metallic dragons. They serve as protectors and guardians, fighting against all forms of evil.', 'A', false, 'MM', '{"dragon", "fire", "good", "metallic"}'),

-- =============================================
-- CR 10 MONSTERS (A-Rank)
-- =============================================

('Aboleth', 'Large', 'Aberration', 'Lawful Evil', '10', 5900, 17, NULL, 135, '18d10+36', 10, NULL, 40, 21, 9, 15, 18, 15, 18, '{}', '{"charmed", "frightened"}', '{}', '{}', '{"darkvision": 120, "passive Perception": 15}', '{"Deep Speech", "telepathy 120 ft."}', 'Ancient aberrations that rule aquatic Gates. They can enslave minds, create illusions, and transform victims into aboleth spawn.', 'Aboleths are among the oldest and most powerful aberrations. They have existed since before the reset and seek to dominate all life.', 'A', false, 'MM', '{"aberration", "aquatic", "mind-control"}'),
('Deva', 'Medium', 'Celestial', 'Lawful Good', '10', 5900, 17, NULL, 136, '16d8+64', 30, NULL, NULL, 18, 18, 18, 17, 20, 20, '{"radiant"}', '{"charmed", "exhaustion", "frightened"}', '{}', '{}', '{"darkvision": 120, "passive Perception": 20}', '{"all", "telepathy 120 ft."}', 'Angelic beings who serve the Supreme Deity directly. They can heal allies, smite enemies, and change shape to appear as mortals.', 'Devas are the messengers and servants of the Supreme Deity. After the reset, they became more common as the Supreme Deity''s influence spread.', 'A', false, 'MM', '{"celestial", "angel", "healing", "shapechanger"}'),
('Guardian Naga', 'Large', 'Monstrosity', 'Lawful Good', '10', 5900, 18, NULL, 127, '15d10+45', 40, NULL, 40, 19, 18, 16, 16, 19, 19, '{"poison"}', '{}', '{}', '{"charmed", "poisoned"}', '{"darkvision": 60, "passive Perception": 19}', '{"Celestial", "Common"}', 'Serpentine spellcasters who serve as protectors of sacred sites. They can heal allies and cast powerful protective spells.', 'Guardian Nagas are the good-aligned counterparts to spirit nagas. They protect temples and sacred sites in Gates.', 'A', false, 'MM', '{"monstrosity", "spellcaster", "good", "healing"}'),
('Stone Golem', 'Large', 'Construct', 'Unaligned', '10', 5900, 17, NULL, 178, '17d10+85', 30, NULL, NULL, 22, 9, 20, 3, 11, 1, '{"bludgeoning, piercing, slashing from nonmagical attacks that aren''t adamantine"}', '{"poison", "psychic"}', '{}', '{"charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"}', '{"darkvision": 120, "passive Perception": 11}', '{"understands the languages of its creator but cannot speak"}', 'Animated stone warriors immune to most magic. Only the strongest attacks can crack their forms, and they regenerate slowly over time.', 'Stone Golems are among the most powerful constructs. They are nearly indestructible and serve as guardians for the most valuable treasures in A-Rank Gates.', 'A', false, 'MM', '{"construct", "stone", "regeneration"}'),
('Young Red Dragon', 'Large', 'Dragon', 'Chaotic Evil', '10', 5900, 18, NULL, 178, '17d10+85', 40, NULL, NULL, 23, 10, 21, 14, 11, 19, '{"fire"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 11}', '{"Common", "Draconic"}', 'Fire-breathing dragons of terrible power. Their flames melt steel and incinerate hunters. They are the most aggressive of all dragons.', 'Red Dragons are the most feared of all chromatic dragons. They are greedy, cruel, and territorial, attacking anything that enters their domain.', 'A', false, 'MM', '{"dragon", "fire"}'),
('Young Blue Dragon', 'Large', 'Dragon', 'Lawful Evil', '10', 5900, 18, NULL, 152, '16d10+64', 40, NULL, NULL, 21, 10, 19, 16, 15, 17, '{"lightning"}', '{}', '{}', '{}', '{"blindsight": 30, "darkvision": 120, "passive Perception": 15}', '{"Common", "Draconic"}', 'Lightning-breathing dragons that create devastating sandstorms. They rule desert-themed A-Rank Gates and command the very weather.', 'Blue Dragons are among the most organized and intelligent of all chromatic dragons. They build lairs in desert Gates and hoard treasure.', 'A', false, 'MM', '{"dragon", "lightning"}')

ON CONFLICT (name) DO NOTHING;

-- This completes CR 5-10 monsters
-- Higher CR monsters (11+) will be in the next migration file

