-- =============================================
-- D&D 5E SRD MONSTERS - CR 2 to 10 COMPLETE
-- All major monsters from D&D 5e SRD
-- =============================================
-- Part 3: CR 2-10 monsters (complete coverage)
-- Adapted for Solo Leveling manwha universe
-- Post-Reset Timeline: Supreme Deity (post-reset world)
-- All entries aligned with Solo Leveling setting, theme, tone, and aesthetic

INSERT INTO compendium_monsters (name, size, creature_type, alignment, cr, xp, armor_class, armor_type, hit_points_average, hit_points_formula, speed_walk, speed_fly, speed_swim, str, agi, vit, int, sense, pre, damage_resistances, damage_immunities, damage_vulnerabilities, condition_immunities, senses, languages, description, lore, gate_rank, is_boss, source_book, tags) VALUES

-- =============================================
-- CR 2 MONSTERS (D-Rank to C-Rank)
-- =============================================

('Allosaurus', 'Large', 'Beast', 'Unaligned', '2', 450, 13, NULL, 51, '6d10+18', 60, NULL, NULL, 19, 13, 17, 2, 12, 5, '{}', '{}', '{}', '{}', '{"passive Perception": 12}', '{}', 'Powerful predatory dinosaurs mutated by Gate mana found in prehistoric-themed Gates. They hunt in packs and use pounce attacks against hunters in the post-reset world.', 'After the reset, these ancient predators have been revived and enhanced by Gate mana. Their pack tactics make them formidable opponents for C-Rank hunters exploring primeval Gate environments.', 'D', false, 'MM', '{"beast", "dinosaur", "pounce"}'),
('Ankheg', 'Large', 'Monstrosity', 'Unaligned', '2', 450, 14, NULL, 39, '6d10+6', 30, NULL, NULL, 17, 11, 13, 1, 13, 6, '{}', '{}', '{}', '{}', '{"darkvision": 60, "tremorsense": 60, "passive Perception": 13}', '{}', 'Burrowing monsters with acid-spitting mandibles. Ambush from underground.', 'Ankhegs can burrow through earth and spit acid that damages multiple targets.', 'D', false, 'MM', '{"monstrosity", "burrow", "acid"}'),
('Awakened Tree', 'Huge', 'Plant', 'Unaligned', '2', 450, 13, NULL, 59, '7d12+14', 20, NULL, NULL, 19, 6, 15, 10, 10, 7, '{}', '{"bludgeoning", "piercing"}', '{"fire"}', '{}', '{}', '{"one language known by its creator"}', 'Massive trees animated by druidic magic or Gate mana. Found in forest-themed Gates, they defend their territory with surprising force in the post-reset world.', 'These ancient trees are infused with powerful mana, becoming sentient guardians of forest Gates. They are nearly impervious to physical attacks and can crush hunters with their limbs.', 'D', false, 'MM', '{"plant"}'),
('Azer', 'Medium', 'Elemental', 'Lawful Neutral', '2', 450, 17, 'chain mail, shield', 39, '7d8+7', 30, NULL, NULL, 17, 12, 13, 12, 10, 13, '{}', '{"fire", "poison"}', '{"poisoned"}', '{}', '{"passive Perception": 10}', '{"Ignan"}', 'Fire-dwelling humanoids who forge weapons in volcanic Gates.', 'Azers are immune to fire and can heat metal objects they touch.', 'D', false, 'MM', '{"elemental", "fire"}'),
('Bandit Captain', 'Medium', 'Humanoid', 'Any Non-Lawful', '2', 450, 15, 'studded leather', 65, '10d8+20', 30, NULL, NULL, 15, 14, 14, 14, 11, 15, '{}', '{}', '{}', '{}', '{}', '{"Any two languages"}', 'Skilled bandit leaders who coordinate raids. Excellent tacticians and fighters.', 'Bandit Captains can command other bandits, granting them extra attacks.', 'D', false, 'MM', '{"humanoid", "leader"}'),
('Berserker', 'Medium', 'Humanoid', 'Any Chaotic', '2', 450, 13, 'hide armor', 67, '9d8+27', 30, NULL, NULL, 16, 12, 17, 9, 11, 9, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Frenzied warriors who enter berserker rage. Fight until death or victory.', 'Berserkers can enter a rage that grants advantage on attacks and extra damage.', 'D', false, 'MM', '{"humanoid", "berserker"}'),
('Centaur', 'Large', 'Monstrosity', 'Neutral Good', '2', 450, 12, NULL, 45, '6d10+12', 50, NULL, NULL, 18, 14, 14, 9, 13, 10, '{}', '{}', '{}', '{}', '{}', '{"Elvish", "Sylvan"}', 'Half-human, half-horse creatures created by Gate mana, found in forest-themed Gates. Skilled warriors and archers who sometimes ally with or oppose hunters in the post-reset world.', 'Centaurs are hybrids formed by Gate mana experiments or ancient magic. Some have adapted to the new world order, serving as scouts or warriors in forest Gate environments.', 'D', false, 'MM', '{"monstrosity"}'),
 ('Cult Fanatic', 'Medium', 'Humanoid', 'Any Non-Good', '2', 450, 13, 'leather armor', 33, '6d8+6', 30, NULL, NULL, 11, 14, 12, 10, 13, 14, '{}', '{}', '{}', '{}', '{}', '{"Any two languages"}', 'Religious fanatics who serve dark entities. Can cast spells and inspire followers.', 'Cult Fanatics can cast spells like command and inflict wounds.', 'D', false, 'MM', '{"humanoid", "spellcaster", "cult"}'),
 ('Druid', 'Medium', 'Humanoid', 'Any', '2', 450, 11, 'leather armor', 27, '5d8+5', 30, NULL, NULL, 10, 12, 13, 12, 15, 11, '{}', '{}', '{}', '{}', '{}', '{"Druidic plus any two languages"}', 'Nature spellcasters who protect Gate ecosystems. Can shapechange and cast powerful spells.', 'Druids can wild shape into animals and cast nature-based spells.', 'D', false, 'MM', '{"humanoid", "spellcaster", "druid"}'),
 ('Gargoyle', 'Medium', 'Elemental', 'Chaotic Evil', '2', 450, 15, NULL, 52, '7d8+21', 30, NULL, NULL, 15, 11, 16, 6, 11, 7, '{}', '{"bludgeoning", "piercing", "slashing"}', '{"poison"}', '{"exhaustion", "petrified", "poisoned"}', '{"darkvision": 60, "passive Perception": 11}', '{"Terran"}', 'Stone creatures that animate when intruders enter their territory. Nearly impervious to mundane weapons.', 'Gargoyles can hold still and appear as inanimate statues, gaining advantage on stealth.', 'C', false, 'MM', '{"elemental", "construct"}'),
 ('Gelatinous Cube', 'Large', 'Ooze', 'Unaligned', '2', 450, 6, NULL, 84, '8d10+40', 15, NULL, NULL, 14, 3, 20, 1, 6, 1, '{}', '{}', '{}', '{"blinded", "charmed", "deafened", "exhaustion", "frightened", "prone"}', '{"blindsight": 60, "blind beyond this radius": true, "passive Perception": 6}', '{}', 'Giant transparent cubes of ooze that fill corridors. Dissolve everything they touch.', 'Gelatinous Cubes can engulf creatures and digest them slowly. Nearly invisible in dim light.', 'C', false, 'MM', '{"ooze", "transparent"}'),
 ('Ghoul', 'Medium', 'Undead', 'Chaotic Evil', '1', 200, 12, NULL, 22, '5d8', 30, NULL, NULL, 13, 15, 10, 7, 10, 6, '{}', '{"poison"}', '{}', '{"charmed", "exhaustion", "poisoned"}', '{"darkvision": 60, "passive Perception": 10}', '{"Common"}', 'Undead that feast on corpses in Gates. In the post-reset world, the weakened boundary between life and death allows these creatures to persist longer. Their claws can paralyze hunters.', 'Ghouls can paralyze hunters with their claws, making them easy targets. These undead are often found in necromantic Gate areas, drawn to the death and conflict that hunters bring.', 'D', false, 'MM', '{"undead", "paralysis"}'),
 ('Gibbering Mouther', 'Medium', 'Aberration', 'Neutral', '2', 450, 9, NULL, 67, '9d8+27', 10, NULL, 10, 10, 8, 17, 3, 10, 3, '{}', '{}', '{}', '{"prone"}', '{"darkvision": 60, "passive Perception": 10}', '{}', 'Grotesque masses of eyes and mouths created by Gate anomalies that babble constantly. Found in aberrant Gates, they can blind hunters with their gibbering in the post-reset world.', 'Gibbering Mouthers can blind hunters and cause ground to become difficult terrain. These aberrations are the result of dimensional instability within Gates, often appearing where reality breaks down.', 'D', false, 'MM', '{"aberration", "blinding"}'),
 ('Githyanki Warrior', 'Medium', 'Humanoid', 'Lawful Evil', '2', 450, 17, 'half plate', 49, '7d8+14', 30, NULL, NULL, 15, 14, 15, 14, 12, 13, '{}', '{}', '{}', '{}', '{}', '{"Gith"}', 'Astral-planar warriors who raid Gates for spoils. Skilled fighters with psionic abilities.', 'Githyanki can cast mage hand and have psionic resistance.', 'C', false, 'MM', '{"humanoid", "psionic"}'),
 ('Githzerai Monk', 'Medium', 'Humanoid', 'Lawful Neutral', '2', 450, 14, NULL, 38, '7d8+7', 30, NULL, NULL, 12, 15, 13, 14, 13, 13, '{}', '{}', '{}', '{}', '{}', '{"Gith"}', 'Monastic warriors from the plane of Limbo. Use unarmed combat and psionics.', 'Githzerai can cast shield and have psionic resistance.', 'C', false, 'MM', '{"humanoid", "psionic", "monk"}'),
 ('Gnoll Pack Lord', 'Medium', 'Humanoid', 'Chaotic Evil', '2', 450, 15, 'chain shirt', 49, '7d8+14', 30, NULL, NULL, 16, 12, 16, 8, 11, 9, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 11}', '{"Gnoll"}', 'Elite gnoll leaders who command war bands. More intelligent and organized than regular gnolls.', 'Gnoll Pack Lords have rampage ability and can command other gnolls.', 'D', false, 'MM', '{"humanoid", "gnoll", "rampage", "leader"}'),
 ('Grell', 'Medium', 'Aberration', 'Neutral Evil', '3', 700, 12, NULL, 55, '10d8+10', 10, NULL, NULL, 15, 14, 12, 12, 11, 12, '{}', '{"lightning"}', '{}', '{"prone"}', '{"blindsight": 60, "blind beyond this radius": true, "passive Perception": 11}', '{"Grell"}', 'Floating brain-like aberrations with tentacles created by Gate anomalies. Found in aberrant Gates, they paralyze hunters with their sting in the post-reset world.', 'Grells can paralyze hunters with their tentacles and are immune to lightning. These aberrations are products of dimensional instability within Gates, hunting intelligently despite their alien nature.', 'C', false, 'MM', '{"aberration", "flying", "paralysis"}'),
 ('Griffon', 'Large', 'Monstrosity', 'Unaligned', '2', 450, 12, NULL, 59, '7d10+21', 30, NULL, NULL, 18, 15, 16, 2, 13, 8, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 13}', '{}', 'Majestic hybrids of eagle and lion created by Gate mana. Found in mountain-themed Gates, they can serve as flying mounts for hunters in the post-reset world.', 'Griffons are perfect examples of Gate mana creating hybrid monstrosities. Some hunters have learned to train these creatures as mounts, using them for aerial Gate exploration.', 'C', false, 'MM', '{"monstrosity", "flying"}'),
 ('Hunter Shark', 'Large', 'Beast', 'Unaligned', '2', 450, 12, NULL, 45, '6d10+12', 0, NULL, 40, 18, 13, 15, 1, 10, 3, '{}', '{}', '{}', '{}', '{"blindsight": 30, "passive Perception": 12}', '{}', 'Large predatory sharks enhanced by Gate mana found in aquatic Gates. They attack when they smell blood, making them dangerous for hunters exploring water-filled Gates in the post-reset world.', 'Hunter Sharks have blood frenzy, gaining advantage on attacks against bleeding hunters. These sharks have been enhanced by Gate mana, becoming larger and more aggressive since the reset.', 'D', false, 'MM', '{"beast", "aquatic", "blood-frenzy"}'),
 ('Intellect Devourer', 'Tiny', 'Aberration', 'Lawful Evil', '2', 450, 12, NULL, 21, '3d6+9', 40, NULL, NULL, 6, 14, 13, 12, 13, 14, '{}', '{}', '{}', '{"blinded"}', '{"blindsight": 60, "blind beyond this radius": true, "passive Perception": 13}', '{"understands Deep Speech and telepathy 60 ft."}', 'Brain-like aberrations created by Gate anomalies that consume intelligence. Found in aberrant Gates, they can control hunter bodies by devouring brains in the post-reset world.', 'Intellect Devourers can reduce Intelligence scores and take control of hunter bodies. These aberrations are feared for their ability to turn hunters into puppets, making them one of the most dangerous threats in aberrant Gates.', 'C', false, 'MM', '{"aberration", "psionic", "mind-control"}'),
 ('Lizardfolk Shaman', 'Medium', 'Humanoid', 'Neutral', '2', 450, 13, 'scale mail', 27, '5d8+5', 30, NULL, 30, 13, 10, 13, 12, 13, 12, '{}', '{}', '{}', '{}', '{}', '{"Draconic"}', 'Spellcasting lizardfolk who commune with Gate spirits. Can cast nature spells.', 'Lizardfolk Shamans can cast spells like entangle and healing word.', 'D', false, 'MM', '{"humanoid", "lizardfolk", "spellcaster"}'),
 ('Merrow', 'Large', 'Monstrosity', 'Chaotic Evil', '2', 450, 13, NULL, 45, '6d10+12', 10, NULL, 40, 18, 10, 15, 8, 10, 7, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Abyssal", "Aquan"}', 'Corrupted merfolk transformed by Gate mana or dark magic. Found in aquatic Gates, they feast on human flesh and attack hunters on sight in the post-reset world.', 'Merrow are merfolk who made pacts with dark forces or were corrupted by Gate mana, gaining strength at the cost of their humanity. They serve as dangerous predators in water-filled Gates.', 'D', false, 'MM', '{"monstrosity", "aquatic"}'),
 ('Mimic', 'Medium', 'Monstrosity', 'Neutral', '2', 450, 12, NULL, 58, '9d8+18', 15, NULL, NULL, 17, 12, 15, 5, 13, 8, '{}', '{"acid"}', '{}', '{"prone"}', '{"darkvision": 60, "passive Perception": 11}', '{}', 'Shape-changing monstrosities created by Gate mana that disguise themselves as objects. Found throughout Gates, they attack hunters when touched in the post-reset world.', 'Mimics have false appearance and can grapple hunters with their adhesive form. These creatures are one of the most feared Gate traps, perfectly blending into their environment to ambush unsuspecting hunters.', 'C', false, 'MM', '{"monstrosity", "shapechanger", "adhesive"}'),
 ('Minotaur', 'Large', 'Monstrosity', 'Chaotic Evil', '3', 700, 14, NULL, 76, '9d10+27', 40, NULL, NULL, 18, 11, 16, 6, 16, 9, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 16}', '{"Abyssal"}', 'Bull-headed warriors that patrol Gate labyrinths. They charge with devastating force.', 'Minotaurs have labyrinthine recall and can use charge to deal extra damage.', 'C', false, 'MM', '{"monstrosity", "charge"}'),
 ('Nothic', 'Medium', 'Aberration', 'Neutral Evil', '2', 450, 15, NULL, 45, '6d8+18', 30, NULL, NULL, 14, 16, 16, 13, 13, 10, '{}', '{}', '{}', '{}', '{"truesight": 120, "passive Perception": 13}', '{"Undercommon"}', 'Cyclopean aberrations with one eye. Can see secrets and reduce ability scores.', 'Nothics can reduce ability scores with their rot gaze and learn secrets about creatures.', 'C', false, 'MM', '{"aberration", "psionic"}'),
 ('Ochre Jelly', 'Large', 'Ooze', 'Unaligned', '2', 450, 8, NULL, 45, '6d10+12', 10, NULL, NULL, 15, 6, 14, 2, 6, 1, '{}', '{"acid"}', '{}', '{"blinded", "charmed", "deafened", "exhaustion", "frightened", "prone"}', '{"blindsight": 60, "blind beyond this radius": true, "passive Perception": 8}', '{}', 'Amorphous oozes that dissolve organic matter. Split when hit with lightning or slashing.', 'Ochre Jellies split into two smaller jellies when hit with lightning or slashing damage.', 'D', false, 'MM', '{"ooze", "split"}'),
 ('Ogre', 'Large', 'Giant', 'Chaotic Evil', '2', 450, 11, 'hide armor', 59, '7d10+21', 40, NULL, NULL, 19, 8, 16, 5, 7, 7, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 7}', '{"Common", "Giant"}', 'Massive brutes enhanced by Gate mana that guard mid-rank Gate corridors. One swing of their clubs can crush hunter armor in the post-reset world.', 'Ogres have been enhanced by Gate mana since the reset, becoming larger and more common in mid-rank Gates. Their brute strength makes them formidable opponents despite their lack of intelligence.', 'C', false, 'MM', '{"giant"}'),
 ('Orc War Chief', 'Medium', 'Humanoid', 'Chaotic Evil', '4', 1100, 16, 'chain mail, shield', 93, '11d8+44', 30, NULL, NULL, 18, 12, 17, 11, 11, 16, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 11}', '{"Common", "Orc"}', 'Elite orc leaders who command war bands. More intelligent and organized than regular orcs.', 'Orc War Chiefs have aggressive ability and can command other orcs, granting them extra attacks.', 'C', false, 'MM', '{"humanoid", "orc", "aggressive", "leader"}'),
('Pegasus', 'Large', 'Celestial', 'Chaotic Good', '2', 450, 13, NULL, 59, '7d10+21', 60, NULL, NULL, 16, 15, 16, 10, 14, 13, '{}', '{}', '{}', '{"charmed", "frightened"}', '{"passive Perception": 14}', '{"Celestial", "Common", "Elvish", "Sylvan"}', 'Winged horses of pure good that serve the Supreme Deity. Found in high-altitude Gates, they can serve as flying mounts for worthy hunters in the post-reset world.', 'Pegasi are celestial beings that have aligned themselves with the Supreme Deity''s order. Some hunters have earned their trust, forming bonds with these noble creatures for aerial Gate exploration.', 'C', false, 'MM', '{"celestial", "flying"}'),
('Peryton', 'Large', 'Monstrosity', 'Chaotic Evil', '2', 450, 13, NULL, 33, '6d10', 20, NULL, NULL, 16, 12, 13, 9, 13, 10, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 13}', '{"understands Common and Elvish but cannot speak"}', 'Hybrid creatures with the body of a bird and head of a stag. Shadowy and evil.', 'Perytons cast no shadow and are drawn to humanoid hearts.', 'C', false, 'MM', '{"monstrosity", "flying", "shadow"}'),
('Plesiosaurus', 'Large', 'Beast', 'Unaligned', '2', 450, 13, NULL, 68, '8d10+24', 20, NULL, 50, 18, 15, 16, 2, 12, 5, '{}', '{}', '{}', '{}', '{"passive Perception": 12}', '{}', 'Large aquatic dinosaurs revived and enhanced by Gate mana, found in water-themed Gates. Powerful swimmers with long necks, they pose a threat to hunters in aquatic Gate environments in the post-reset world.', 'After the reset, these prehistoric sea creatures have been revived through Gate mana. Their size and power make them apex predators in aquatic Gates, capable of surprising hunters with their reach.', 'D', false, 'MM', '{"beast", "dinosaur", "aquatic"}'),
 ('Polar Bear', 'Large', 'Beast', 'Unaligned', '2', 450, 12, NULL, 42, '5d10+15', 40, NULL, 30, 20, 10, 17, 2, 13, 7, '{}', '{}', '{}', '{}', '{"passive Perception": 13}', '{}', 'Massive arctic bears mutated by Gate mana with thick fur. Found in ice-themed Gates, they can swim in icy waters and have powerful claws that threaten hunters in the post-reset world.', 'After the reset, polar bears have grown larger and more aggressive. Gate mana has enhanced their natural abilities, making them formidable predators in arctic Gate environments.', 'D', false, 'MM', '{"beast", "cold"}'),
 ('Priest', 'Medium', 'Humanoid', 'Any', '2', 450, 13, 'chain shirt', 27, '5d8+5', 25, NULL, NULL, 10, 10, 14, 11, 16, 13, '{}', '{}', '{}', '{}', '{}', '{"Any two languages"}', 'Religious spellcasters who serve in Gate temples. Can heal allies and harm enemies.', 'Priests can cast spells like cure wounds, guiding bolt, and spirit guardians.', 'D', false, 'MM', '{"humanoid", "spellcaster", "priest"}'),
 ('Rhinoceros', 'Large', 'Beast', 'Unaligned', '2', 450, 11, NULL, 45, '6d10+12', 40, NULL, NULL, 21, 8, 17, 2, 12, 6, '{}', '{}', '{}', '{}', '{"passive Perception": 12}', '{}', 'Massive herbivores mutated by Gate mana with powerful charges. Found in savanna-themed Gates, their horn can gore hunters with devastating force in the post-reset world.', 'Rhinoceroses can charge to deal extra damage with their horn attack. These beasts have been enhanced by Gate mana, becoming larger and more aggressive since the reset.', 'D', false, 'MM', '{"beast", "charge"}'),
 ('Rug of Smothering', 'Large', 'Construct', 'Unaligned', '2', 450, 12, NULL, 33, '6d10', 10, NULL, NULL, 17, 14, 10, 1, 3, 1, '{}', '{"bludgeoning", "poison", "psychic"}', '{}', '{"blinded", "charmed", "deafened", "frightened", "paralyzed", "petrified", "poisoned"}', '{"blindsight": 60, "blind beyond this radius": true, "passive Perception": 3}', '{}', 'Animated rugs created by Gate magic or hunter enchanters that smother hunters. Found in Gate corridors, they appear as normal rugs until they attack in the post-reset world.', 'Rugs of Smothering can engulf hunters and suffocate them. These constructs are often used as traps in high-rank Gates, perfect for ambushing unwary hunters exploring Gate interiors.', 'C', false, 'MM', '{"construct", "smother"}'),
 ('Saber-Toothed Tiger', 'Large', 'Beast', 'Unaligned', '2', 450, 12, NULL, 52, '7d10+14', 40, NULL, NULL, 18, 14, 15, 3, 12, 8, '{}', '{}', '{}', '{}', '{"passive Perception": 12}', '{}', 'Prehistoric big cats revived by Gate mana with massive fangs. Found in prehistoric-themed Gates, their pounce can knock hunters prone in the post-reset world.', 'Saber-Toothed Tigers use pounce to move and make a bite attack, potentially knocking hunters prone. These ancient predators have been revived through Gate mana, becoming larger and more dangerous than their historical counterparts.', 'D', false, 'MM', '{"beast", "pounce"}'),
 ('Sahuagin Priestess', 'Medium', 'Humanoid', 'Lawful Evil', '2', 450, 12, NULL, 33, '5d8+10', 30, NULL, 40, 13, 11, 14, 12, 14, 11, '{}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 14}', '{"Sahuagin"}', 'Spellcasting sahuagin who serve their demon god. Can cast water-based spells.', 'Sahuagin Priestesses can cast spells like bane and spiritual weapon.', 'D', false, 'MM', '{"humanoid", "aquatic", "spellcaster"}'),
('Sea Hag', 'Medium', 'Fey', 'Chaotic Evil', '2', 450, 14, NULL, 52, '7d8+21', 30, NULL, 40, 16, 13, 16, 12, 12, 13, '{}', '{}', '{}', '{"charmed", "frightened"}', '{"darkvision": 60, "passive Perception": 12}', '{"Aquan", "Common"}', 'Hags who dwell in aquatic Gates. Their gaze can frighten enemies.', 'Sea Hags have death glare that can frighten creatures, and can create illusions.', 'D', false, 'MM', '{"fey", "hag", "aquatic"}'),
('Spined Devil', 'Small', 'Fiend', 'Lawful Evil', '2', 450, 13, NULL, 22, '5d6+5', 20, NULL, NULL, 10, 14, 12, 11, 10, 11, '{}', '{"cold"}', '{}', '{"poisoned"}', '{"darkvision": 120, "passive Perception": 10}', '{"Infernal", "telepathy 120 ft."}', 'Small devils with spines they can fire at enemies. Serve as scouts in hell''s armies.', 'Spined Devils can shoot spines as ranged attacks and can fly.', 'D', false, 'MM', '{"fiend", "devil", "flying"}'),
('Swarm of Poisonous Snakes', 'Medium', 'Beast', 'Unaligned', '2', 450, 14, NULL, 36, '8d8', 30, NULL, 30, 8, 18, 11, 1, 10, 3, '{"bludgeoning", "piercing", "slashing"}', '{}', '{}', '{"charmed", "frightened", "grappled", "paralyzed", "petrified", "prone", "restrained", "stunned"}', '{"blindsight": 10, "passive Perception": 10}', '{}', 'A mass of venomous serpents mutated by Gate mana that attack as one. Found throughout Gates, the swarm poisons hunters in the post-reset world.', 'Swarms of Poisonous Snakes can poison multiple hunters and are resistant to weapon damage. These snakes have been enhanced by Gate mana, becoming larger and more aggressive since the reset.', 'D', false, 'MM', '{"beast", "swarm", "poison"}'),
('Wererat', 'Medium', 'Humanoid', 'Lawful Evil', '2', 450, 12, NULL, 33, '6d8+6', 30, NULL, NULL, 10, 15, 12, 11, 10, 8, '{"bludgeoning, piercing, slashing from nonmagical attacks not made with silvered weapons"}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Common"}', 'Shape-changing humanoids cursed with lycanthropy. Can transform into rats or hybrid forms.', 'Wererats are immune to nonmagical weapon damage unless silvered. Spread lycanthropy through bites.', 'D', false, 'MM', '{"humanoid", "shapechanger", "lycanthrope"}'),
('Will-o''-Wisp', 'Tiny', 'Undead', 'Chaotic Evil', '2', 450, 19, NULL, 22, '9d4', 0, NULL, NULL, 1, 28, 10, 13, 14, 11, '{"acid", "cold", "fire", "necrotic", "thunder"}', '{"lightning", "poison"}', '{}', '{"exhaustion", "grappled", "paralyzed", "poisoned", "prone", "restrained", "unconscious"}', '{"darkvision": 120, "passive Perception": 11}', '{}', 'Floating undead lights that lead travelers to their doom. Immune to most damage.', 'Will-o''-Wisps can consume life energy and are nearly impossible to hit with physical attacks.', 'C', false, 'MM', '{"undead", "incorporeal", "flying"}'),

-- =============================================
-- CR 3 MONSTERS (C-Rank)
-- =============================================

('Ankylosaurus', 'Huge', 'Beast', 'Unaligned', '3', 700, 15, NULL, 68, '8d12+16', 30, NULL, NULL, 19, 11, 15, 2, 12, 5, '{}', '{}', '{}', '{}', '{"passive Perception": 12}', '{}', 'Massive armored dinosaurs with club tails. Nearly impervious to attack from behind.', NULL, 'C', false, 'MM', '{"beast", "dinosaur", "armored"}'),
('Basilisk', 'Medium', 'Monstrosity', 'Unaligned', '3', 700, 15, NULL, 52, '8d8+16', 20, NULL, NULL, 16, 8, 15, 2, 8, 7, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 8}', '{}', 'Serpentine creatures whose gaze turns victims to stone. Must be fought indirectly.', 'Basilisks petrify creatures that meet their gaze, requiring indirect combat.', 'C', false, 'MM', '{"monstrosity", "petrification"}'),
('Bearded Devil', 'Medium', 'Fiend', 'Lawful Evil', '3', 700, 13, NULL, 52, '8d8+16', 30, NULL, NULL, 16, 15, 15, 9, 11, 11, '{}', '{"cold"}', '{}', '{"poisoned"}', '{"darkvision": 120, "passive Perception": 11}', '{"Infernal", "telepathy 120 ft."}', 'Devils with beards of writhing tendrils. Their weapons cause wounds that never heal.', 'Bearded Devils cause wounds with their glaives that prevent healing.', 'C', false, 'MM', '{"fiend", "devil", "wound"}'),
('Blue Dragon Wyrmling', 'Medium', 'Dragon', 'Lawful Evil', '3', 700, 17, NULL, 52, '8d8+16', 30, NULL, NULL, 17, 10, 15, 12, 11, 15, '{"lightning"}', '{}', '{}', '{}', '{"blindsight": 10, "darkvision": 60, "passive Perception": 13}', '{"Draconic"}', 'Young lightning dragons. Their breath weapon can chain between enemies.', NULL, 'C', false, 'MM', '{"dragon", "lightning"}'),
 ('Doppelganger', 'Medium', 'Monstrosity', 'Neutral', '3', 700, 14, NULL, 52, '8d8+16', 30, NULL, NULL, 11, 18, 14, 11, 12, 12, '{"charm"}', '{}', '{}', '{"charmed", "exhaustion"}', '{"darkvision": 60, "passive Perception": 12}', '{"Common"}', 'Shape-changing creatures that assume the forms of others. Use deception to infiltrate.', 'Doppelgangers can read minds and assume any humanoid form perfectly.', 'C', false, 'MM', '{"monstrosity", "shapechanger", "mind-reader"}'),
 ('Green Dragon Wyrmling', 'Medium', 'Dragon', 'Lawful Evil', '2', 450, 17, NULL, 38, '7d8+7', 30, NULL, 30, 15, 12, 13, 14, 11, 13, '{"poison"}', '{}', '{}', '{"poisoned"}', '{"blindsight": 10, "darkvision": 60, "passive Perception": 13}', '{"Draconic"}', 'Young poison dragons. Their breath weapon creates clouds of toxic gas.', NULL, 'C', false, 'MM', '{"dragon", "poison"}'),
 ('Green Hag', 'Medium', 'Fey', 'Neutral Evil', '3', 700, 17, NULL, 82, '11d8+33', 30, NULL, NULL, 18, 12, 16, 13, 14, 14, '{}', '{}', '{}', '{"charmed", "frightened"}', '{"darkvision": 60, "passive Perception": 14}', '{"Common", "Draconic"}', 'Hags who dwell in swamps and forests. Use illusion and deception.', 'Green Hags can create illusions and mimic voices to lure victims to their doom.', 'C', false, 'MM', '{"fey", "hag", "illusion"}'),
 ('Helmed Horror', 'Medium', 'Construct', 'Neutral', '4', 1100, 20, NULL, 60, '8d8+24', 30, NULL, NULL, 16, 13, 18, 10, 10, 1, '{}', '{"force", "necrotic", "poison"}', '{}', '{"blinded", "charmed", "deafened", "frightened", "paralyzed", "petrified", "poisoned"}', '{"blindsight": 60, "blind beyond this radius": true, "passive Perception": 10}', '{"understands the languages of its creator but cannot speak"}', 'Animated suits of armor that guard magical Gates. Immune to many spells.', 'Helmed Horrors are immune to specific spells chosen by their creator.', 'C', false, 'MM', '{"construct", "armor"}'),
 ('Hobgoblin Captain', 'Medium', 'Humanoid', 'Lawful Evil', '3', 700, 17, 'chain mail, shield', 39, '6d8+12', 30, NULL, NULL, 15, 14, 14, 12, 10, 13, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{"Common", "Goblin"}', 'Elite hobgoblin commanders. Excellent tacticians who coordinate war bands.', 'Hobgoblin Captains have martial advantage and can command other hobgoblins.', 'C', false, 'MM', '{"humanoid", "goblinoid", "martial-advantage", "leader"}'),
 ('Hook Horror', 'Large', 'Monstrosity', 'Neutral', '3', 700, 15, NULL, 75, '10d10+20', 30, NULL, NULL, 18, 10, 15, 9, 14, 10, '{}', '{}', '{}', '{}', '{"blindsight": 60, "tremorsense": 60, "blind beyond these radii": true, "passive Perception": 14}', '{"Hook Horror"}', 'Large monsters with hook-like claws. Use echolocation and tremorsense to hunt.', 'Hook Horrors are blind but use echolocation to "see" their surroundings perfectly.', 'C', false, 'MM', '{"monstrosity", "blind", "echolocation"}'),
 ('Killer Whale', 'Huge', 'Beast', 'Unaligned', '3', 700, 12, NULL, 90, '12d12+12', 0, NULL, 60, 19, 10, 13, 3, 12, 7, '{}', '{}', '{}', '{}', '{"blindsight": 120, "passive Perception": 12}', '{}', 'Massive orcas found in aquatic Gates. Highly intelligent pack hunters.', NULL, 'C', false, 'MM', '{"beast", "aquatic", "pack-tactics"}'),
('Knight', 'Medium', 'Humanoid', 'Any', '3', 700, 18, 'plate', 52, '8d8+16', 30, NULL, NULL, 16, 11, 15, 11, 10, 15, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Elite warriors in full plate armor. Serve as Gate guards and elite hunters.', 'Knights can rally allies and have heavy armor mastery.', 'C', false, 'MM', '{"humanoid", "knight", "leader"}'),
 ('Manticore', 'Large', 'Monstrosity', 'Lawful Evil', '3', 700, 14, NULL, 68, '8d10+24', 30, NULL, NULL, 17, 16, 17, 7, 12, 8, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 12}', '{"Common"}', 'Hybrid creatures with lion bodies, bat wings, and scorpion tails. Fire tail spikes at range.', 'Manticores can fire spikes from their tails and are excellent fliers.', 'C', false, 'MM', '{"monstrosity", "flying"}'),
 ('Owlbear', 'Large', 'Monstrosity', 'Unaligned', '3', 700, 13, NULL, 59, '7d10+21', 40, NULL, NULL, 20, 12, 17, 3, 13, 7, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 13}', '{"Owlbear"}', 'Iconic hybrid creatures with bear bodies and owl heads. Ferocious and territorial.', NULL, 'C', false, 'MM', '{"monstrosity"}'),
 ('Phase Spider', 'Large', 'Monstrosity', 'Unaligned', '3', 700, 13, NULL, 32, '5d10+5', 30, NULL, NULL, 15, 15, 12, 6, 10, 6, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 10}', '{}', 'Spiders that can phase between dimensions. Strike from the ethereal plane.', 'Phase Spiders can ethereal jaunt, becoming ethereal and moving through walls.', 'C', false, 'MM', '{"monstrosity", "ethereal", "poison"}'),
 ('Quaggoth Spore Servant', 'Medium', 'Plant', 'Unaligned', '1', 200, 13, NULL, 45, '6d8+18', 30, NULL, NULL, 17, 12, 16, 6, 12, 9, '{}', '{"poison"}', '{}', '{"blinded", "charmed", "frightened", "poisoned"}', '{"blindsight": 30, "blind beyond this radius": true, "passive Perception": 12}', '{}', 'Quaggoths corrupted by spore infestation. Mindless plant-creatures that attack all.', NULL, 'C', false, 'MM', '{"plant", "zombie"}'),
 ('Red Dragon Wyrmling', 'Medium', 'Dragon', 'Chaotic Evil', '4', 1100, 17, NULL, 75, '10d8+30', 30, NULL, NULL, 19, 10, 17, 14, 11, 16, '{"fire"}', '{}', '{}', '{}', '{"blindsight": 10, "darkvision": 60, "passive Perception": 13}', '{"Draconic"}', 'Young fire dragons. Their breath weapon creates cones of flame.', NULL, 'C', false, 'MM', '{"dragon", "fire"}'),
 ('Specter', 'Medium', 'Undead', 'Chaotic Evil', '1', 200, 12, NULL, 22, '5d8', 0, NULL, NULL, 1, 14, 11, 10, 10, 10, '{"acid", "cold", "fire", "lightning", "thunder"}', '{"necrotic", "poison"}', '{"radiant"}', '{"charmed", "exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"}', '{"darkvision": 60, "passive Perception": 10}', '{"understands all languages it knew in life but cannot speak"}', 'Incorporeal undead that drain life force. Pass through walls and objects.', 'Specters reduce maximum hit points with their touch and are nearly immune to physical damage.', 'C', false, 'MM', '{"undead", "incorporeal"}'),
('Veteran', 'Medium', 'Humanoid', 'Any', '3', 700, 17, 'splint', 58, '9d8+18', 30, NULL, NULL, 16, 13, 16, 10, 11, 14, '{}', '{}', '{}', '{}', '{}', '{"Any one language"}', 'Experienced warriors who have survived countless battles. Excellent fighters with multiple attacks.', 'Veterans can make two attacks per turn and have tactical expertise.', 'C', false, 'MM', '{"humanoid", "veteran"}'),
('Water Weird', 'Large', 'Elemental', 'Neutral', '3', 700, 13, NULL, 58, '9d10+9', 0, NULL, 60, 17, 16, 14, 11, 10, 11, '{}', '{"fire"}', '{}', '{}', '{"blindsight": 30, "passive Perception": 10}', '{"Aquan"}', 'Aquatic elementals that dwell in fountains and pools. Drag victims underwater.', 'Water Weirds can constrict and drown victims, and are immune to fire.', 'C', false, 'MM', '{"elemental", "aquatic"}'),
('Werewolf', 'Medium', 'Humanoid', 'Chaotic Evil', '3', 700, 11, NULL, 58, '9d8+18', 30, NULL, NULL, 15, 13, 14, 10, 11, 11, '{"bludgeoning, piercing, slashing from nonmagical attacks not made with silvered weapons"}', '{}', '{}', '{}', '{"passive Perception": 11}', '{"Common"}', 'Shape-changing humanoids cursed with lycanthropy. Can transform into wolves or hybrid forms.', 'Werewolves are immune to nonmagical weapon damage unless silvered. Spread lycanthropy through bites.', 'C', false, 'MM', '{"humanoid", "shapechanger", "lycanthrope"}'),
('Winter Wolf', 'Large', 'Monstrosity', 'Neutral Evil', '3', 700, 13, NULL, 75, '10d10+20', 50, NULL, NULL, 18, 13, 16, 7, 12, 8, '{}', '{"cold"}', '{}', '{}', '{"passive Perception": 13}', '{"Common", "Giant", "Winter Wolf"}', 'Giant wolves that breathe freezing mist. Hunt in packs in cold Gates.', 'Winter Wolves can breathe cold in a cone, freezing enemies solid.', 'C', false, 'MM', '{"monstrosity", "cold", "pack-tactics"}'),
('Wraith', 'Medium', 'Undead', 'Chaotic Evil', '5', 1800, 13, NULL, 67, '9d8+27', 0, NULL, NULL, 6, 16, 14, 12, 12, 10, '{"acid", "cold", "fire", "lightning", "thunder"}', '{"necrotic", "poison"}', '{"radiant"}', '{"charmed", "exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"}', '{"darkvision": 60, "passive Perception": 12}', '{"the languages it knew in life"}', 'Powerful incorporeal undead that drain life force. Can create spawn from their victims.', 'Wraiths reduce maximum hit points and can create specter spawn from slain humanoids.', 'C', false, 'MM', '{"undead", "incorporeal", "spawn"}'),
('Xorn', 'Medium', 'Elemental', 'Neutral', '5', 1800, 19, NULL, 73, '7d10+35', 20, NULL, NULL, 17, 10, 22, 11, 10, 10, '{"piercing", "slashing"}', '{}', '{}', '{}', '{"darkvision": 60, "tremorsense": 60, "passive Perception": 10}', '{"Terran"}', 'Earth elementals that devour gems and precious metals. Can move through stone.', 'Xorns can move through stone and detect precious metals and gems.', 'C', false, 'MM', '{"elemental", "earth"}'),

-- =============================================
-- CR 4 MONSTERS (C-Rank)
 -- =============================================

 ('Banshee', 'Medium', 'Undead', 'Chaotic Evil', '4', 1100, 12, NULL, 58, '13d8', 0, NULL, NULL, 1, 14, 10, 12, 13, 11, '{"acid", "fire", "lightning", "thunder"}', '{"necrotic", "poison"}', '{"radiant"}', '{"charmed", "exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"}', '{"darkvision": 60, "passive Perception": 13}', '{"Common", "Elvish"}', 'Undead elf spirits whose wail can kill instantly. Their touch reduces ability scores.', 'Banshees can use horrifying visage to frighten enemies and wail to potentially kill creatures.', 'C', false, 'MM', '{"undead", "incorporeal", "wail"}'),
 ('Black Pudding', 'Large', 'Ooze', 'Unaligned', '4', 1100, 7, NULL, 85, '10d10+30', 20, NULL, NULL, 16, 5, 16, 1, 6, 1, '{"acid", "cold", "fire"}', '{}', '{}', '{"blinded", "charmed", "deafened", "exhaustion", "frightened", "prone"}', '{"blindsight": 60, "blind beyond this radius": true, "passive Perception": 6}', '{}', 'Amorphous black oozes that dissolve organic matter. Split when hit with lightning or slashing.', 'Black Puddings split into two smaller puddings when hit with lightning or slashing damage.', 'C', false, 'MM', '{"ooze", "acid", "split"}'),
 ('Chuul', 'Large', 'Aberration', 'Chaotic Evil', '4', 1100, 16, NULL, 93, '11d10+33', 30, NULL, 30, 19, 10, 16, 5, 11, 5, '{"poison"}', '{}', '{}', '{"poisoned"}', '{"darkvision": 60, "passive Perception": 11}', '{"Deep Speech"}', 'Amphibious aberrations with powerful claws. Can paralyze victims with their tentacles.', 'Chuuls can paralyze creatures with their tentacles and are amphibious.', 'C', false, 'MM', '{"aberration", "aquatic", "paralysis"}'),
 ('Couatl', 'Large', 'Celestial', 'Lawful Good', '4', 1100, 19, NULL, 97, '13d10+26', 30, NULL, NULL, 16, 20, 17, 17, 20, 19, '{"radiant"}', '{"psychic"}', '{}', '{}', '{"truesight": 120, "passive Perception": 20}', '{"all", "telepathy 120 ft."}', 'Serpentine celestials with feathered wings. Can shapechange and cast powerful spells.', 'Couatls can shapechange and cast spells like greater restoration and plane shift.', 'C', false, 'MM', '{"celestial", "flying", "spellcaster", "shapechanger"}'),
('Death Dog', 'Medium', 'Monstrosity', 'Neutral Evil', '1', 200, 12, NULL, 39, '6d8+12', 40, NULL, NULL, 15, 14, 14, 3, 13, 6, '{}', '{}', '{}', '{}', '{"darkvision": 120, "passive Perception": 13}', '{}', 'Two-headed hounds that serve undead masters. Their bite causes disease.', 'Death Dogs spread disease with their bite and have advantage on tracking.', 'C', false, 'MM', '{"monstrosity", "disease", "two-headed"}'),
('Ghost', 'Medium', 'Undead', 'Any', '4', 1100, 11, NULL, 45, '10d8', 0, NULL, NULL, 7, 13, 10, 10, 12, 17, '{"acid", "cold", "fire", "lightning", "thunder"}', '{"necrotic", "poison"}', '{"radiant"}', '{"charmed", "exhaustion", "frightened", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained"}', '{"darkvision": 60, "passive Perception": 12}', '{"any languages it knew in life"}', 'Incorporeal undead bound to the Material Plane. Can possess living creatures.', 'Ghosts can possess humanoids, controlling their bodies, and have horrifying visage.', 'C', false, 'MM', '{"undead", "incorporeal", "possession"}'),
('Incubus', 'Medium', 'Fiend', 'Neutral Evil', '4', 1100, 15, NULL, 66, '12d8+12', 30, NULL, NULL, 8, 17, 13, 15, 12, 20, '{"cold", "fire", "lightning", "poison"}', '{}', '{"radiant"}', '{"charmed", "poisoned"}', '{"darkvision": 60, "passive Perception": 12}', '{"Common", "Infernal", "telepathy 60 ft."}', 'Shape-changing fiends who seduce and corrupt. Can charm and drain life force.', 'Incubi can charm creatures and drain life force through their touch. Spread corruption.', 'C', false, 'MM', '{"fiend", "shapechanger", "charm", "drain"}'),
('Lamia', 'Large', 'Monstrosity', 'Chaotic Evil', '4', 1100, 13, NULL, 97, '13d10+26', 30, NULL, NULL, 16, 13, 15, 14, 15, 16, '{}', '{}', '{}', '{}', '{"darkvision": 60, "passive Perception": 15}', '{"Abyssal", "Common"}', 'Seductive monsters with human upper bodies and lion lower bodies. Use charm and deception.', 'Lamia can charm humanoids and use them as thralls. Cast spells to dominate enemies.', 'C', false, 'MM', '{"monstrosity", "charm", "spellcaster"}'),
('Succubus', 'Medium', 'Fiend', 'Neutral Evil', '4', 1100, 15, NULL, 66, '12d8+12', 30, NULL, NULL, 8, 17, 13, 15, 12, 20, '{"cold", "fire", "lightning", "poison"}', '{}', '{"radiant"}', '{"charmed", "poisoned"}', '{"darkvision": 60, "passive Perception": 12}', '{"Abyssal", "Common", "Infernal", "telepathy 60 ft."}', 'Shape-changing fiends who seduce and corrupt. Can charm and drain life force.', 'Succubi can charm creatures and drain life force through their touch. Spread corruption.', 'C', false, 'MM', '{"fiend", "shapechanger", "charm", "drain"}'),
('Weretiger', 'Medium', 'Humanoid', 'Neutral', '4', 1100, 12, NULL, 120, '16d8+48', 30, NULL, NULL, 17, 15, 16, 10, 13, 11, '{"bludgeoning, piercing, slashing from nonmagical attacks not made with silvered weapons"}', '{}', '{}', '{}', '{"passive Perception": 13}', '{"Common"}', 'Shape-changing humanoids cursed with lycanthropy. Can transform into tigers or hybrid forms.', 'Weretigers are immune to nonmagical weapon damage unless silvered. Spread lycanthropy through bites.', 'C', false, 'MM', '{"humanoid", "shapechanger", "lycanthrope"}'),
('Wereboar', 'Medium', 'Humanoid', 'Neutral Evil', '2', 450, 10, NULL, 78, '12d8+24', 30, NULL, NULL, 17, 10, 15, 10, 11, 8, '{"bludgeoning, piercing, slashing from nonmagical attacks not made with silvered weapons"}', '{}', '{}', '{}', '{"passive Perception": 11}', '{"Common"}', 'Shape-changing humanoids cursed with lycanthropy. Can transform into boars or hybrid forms.', 'Wereboars are immune to nonmagical weapon damage unless silvered. Spread lycanthropy through bites.', 'C', false, 'MM', '{"humanoid", "shapechanger", "lycanthrope"}')

ON CONFLICT (name) DO NOTHING;

-- This continues with CR 5-10 monsters in the next file...

