-- COMPLETE EQUIPMENT CATALOG (Weapons, Armor, Adventuring Gear)
INSERT INTO compendium_equipment (name, equipment_type, cost_credits, weight, damage, damage_type, properties, armor_class, description, source_book) VALUES
-- SIMPLE MELEE WEAPONS
('Club', 'simple_melee', 10, 2, '1d4', 'bludgeoning', ARRAY['light'], NULL, 'A basic blunt weapon, often improvised from gate debris.', 'SRD'),
('Dagger', 'simple_melee', 200, 1, '1d4', 'piercing', ARRAY['finesse', 'light', 'thrown (20/60)'], NULL, 'A small blade favored by assassin-class ascendants.', 'SRD'),
('Greatclub', 'simple_melee', 20, 10, '1d8', 'bludgeoning', ARRAY['two-handed'], NULL, 'A massive club requiring both hands to wield.', 'SRD'),
('Handaxe', 'simple_melee', 500, 2, '1d6', 'slashing', ARRAY['light', 'thrown (20/60)'], NULL, 'A versatile axe that can be thrown at enemies.', 'SRD'),
('Javelin', 'simple_melee', 50, 2, '1d6', 'piercing', ARRAY['thrown (30/120)'], NULL, 'A throwing spear used for ranged engagement.', 'SRD'),
('Light Hammer', 'simple_melee', 200, 2, '1d4', 'bludgeoning', ARRAY['light', 'thrown (20/60)'], NULL, 'A small hammer that can be thrown.', 'SRD'),
('Mace', 'simple_melee', 500, 4, '1d6', 'bludgeoning', NULL, NULL, 'A weighted club used to crush armored foes.', 'SRD'),
('Quarterstaff', 'simple_melee', 20, 4, '1d6', 'bludgeoning', ARRAY['versatile (1d8)'], NULL, 'A wooden staff, versatile in combat applications.', 'SRD'),
('Sickle', 'simple_melee', 100, 2, '1d4', 'slashing', ARRAY['light'], NULL, 'A curved blade originally for harvesting.', 'SRD'),
('Spear', 'simple_melee', 100, 3, '1d6', 'piercing', ARRAY['thrown (20/60)', 'versatile (1d8)'], NULL, 'A polearm effective at range and in melee.', 'SRD'),
-- SIMPLE RANGED WEAPONS
('Crossbow, Light', 'simple_ranged', 2500, 5, '1d8', 'piercing', ARRAY['ammunition (80/320)', 'loading', 'two-handed'], NULL, 'A mechanical bow requiring less training than traditional bows.', 'SRD'),
('Dart', 'simple_ranged', 5, 0.25, '1d4', 'piercing', ARRAY['finesse', 'thrown (20/60)'], NULL, 'Small throwing weapons, easily concealed.', 'SRD'),
('Shortbow', 'simple_ranged', 2500, 2, '1d6', 'piercing', ARRAY['ammunition (80/320)', 'two-handed'], NULL, 'A compact bow suitable for quick shots.', 'SRD'),
('Sling', 'simple_ranged', 10, 0, '1d4', 'bludgeoning', ARRAY['ammunition (30/120)'], NULL, 'A primitive but effective ranged weapon.', 'SRD'),
-- MARTIAL MELEE WEAPONS
('Battleaxe', 'martial_melee', 1000, 4, '1d8', 'slashing', ARRAY['versatile (1d10)'], NULL, 'A heavy axe favored by striker-class ascendants.', 'SRD'),
('Flail', 'martial_melee', 1000, 2, '1d8', 'bludgeoning', NULL, NULL, 'A spiked ball on a chain, devastating against armor.', 'SRD'),
('Glaive', 'martial_melee', 2000, 6, '1d10', 'slashing', ARRAY['heavy', 'reach', 'two-handed'], NULL, 'A polearm with extended reach capabilities.', 'SRD'),
('Greataxe', 'martial_melee', 3000, 7, '1d12', 'slashing', ARRAY['heavy', 'two-handed'], NULL, 'A massive axe capable of cleaving through gates monsters.', 'SRD'),
('Greatsword', 'martial_melee', 5000, 6, '2d6', 'slashing', ARRAY['heavy', 'two-handed'], NULL, 'A large two-handed sword favored by elite ascendants.', 'SRD'),
('Halberd', 'martial_melee', 2000, 6, '1d10', 'slashing', ARRAY['heavy', 'reach', 'two-handed'], NULL, 'An axe-spear hybrid with extended reach.', 'SRD'),
('Lance', 'martial_melee', 1000, 6, '1d12', 'piercing', ARRAY['reach', 'special'], NULL, 'A jousting weapon, effective when mounted.', 'SRD'),
('Longsword', 'martial_melee', 1500, 3, '1d8', 'slashing', ARRAY['versatile (1d10)'], NULL, 'The quintessential ascendant sword, balanced and deadly.', 'SRD'),
('Maul', 'martial_melee', 1000, 10, '2d6', 'bludgeoning', ARRAY['heavy', 'two-handed'], NULL, 'A massive hammer for crushing gate monsters.', 'SRD'),
('Morningstar', 'martial_melee', 1500, 4, '1d8', 'piercing', NULL, NULL, 'A spiked mace that pierces armor.', 'SRD'),
('Pike', 'martial_melee', 500, 18, '1d10', 'piercing', ARRAY['heavy', 'reach', 'two-handed'], NULL, 'An extremely long spear for formation fighting.', 'SRD'),
('Rapier', 'martial_melee', 2500, 2, '1d8', 'piercing', ARRAY['finesse'], NULL, 'A precise thrusting sword favored by agility-based ascendants.', 'SRD'),
('Scimitar', 'martial_melee', 2500, 3, '1d6', 'slashing', ARRAY['finesse', 'light'], NULL, 'A curved blade for swift slashing attacks.', 'SRD'),
('Shortsword', 'martial_melee', 1000, 2, '1d6', 'piercing', ARRAY['finesse', 'light'], NULL, 'A compact sword for close-quarters combat.', 'SRD'),
('Trident', 'martial_melee', 500, 4, '1d6', 'piercing', ARRAY['thrown (20/60)', 'versatile (1d8)'], NULL, 'A three-pronged spear, throwable.', 'SRD'),
('War Pick', 'martial_melee', 500, 2, '1d8', 'piercing', NULL, NULL, 'A pointed hammer designed to pierce armor.', 'SRD'),
('Warhammer', 'martial_melee', 1500, 2, '1d8', 'bludgeoning', ARRAY['versatile (1d10)'], NULL, 'A heavy hammer for crushing blows.', 'SRD'),
('Whip', 'martial_melee', 200, 3, '1d4', 'slashing', ARRAY['finesse', 'reach'], NULL, 'A flexible weapon with extended reach.', 'SRD'),
-- MARTIAL RANGED WEAPONS
('Blowgun', 'martial_ranged', 1000, 1, '1', 'piercing', ARRAY['ammunition (25/100)', 'loading'], NULL, 'A silent weapon for delivering toxins.', 'SRD'),
('Crossbow, Hand', 'martial_ranged', 7500, 3, '1d6', 'piercing', ARRAY['ammunition (30/120)', 'light', 'loading'], NULL, 'A compact crossbow for one-handed use.', 'SRD'),
('Crossbow, Heavy', 'martial_ranged', 5000, 18, '1d10', 'piercing', ARRAY['ammunition (100/400)', 'heavy', 'loading', 'two-handed'], NULL, 'A powerful crossbow with exceptional range.', 'SRD'),
('Longbow', 'martial_ranged', 5000, 2, '1d8', 'piercing', ARRAY['ammunition (150/600)', 'heavy', 'two-handed'], NULL, 'A tall bow with impressive range and power.', 'SRD'),
('Net', 'martial_ranged', 100, 3, NULL, NULL, ARRAY['special', 'thrown (5/15)'], NULL, 'A throwing net to restrain enemies.', 'SRD'),
-- LIGHT ARMOR
('Padded Armor', 'light_armor', 500, 8, NULL, NULL, ARRAY['stealth disadvantage'], 11, 'Quilted layers of cloth and batting.', 'SRD'),
('Leather Armor', 'light_armor', 1000, 10, NULL, NULL, NULL, 11, 'Standard ascendant armor made from treated hides.', 'SRD'),
('Studded Leather', 'light_armor', 4500, 13, NULL, NULL, NULL, 12, 'Leather reinforced with metal rivets.', 'SRD'),
-- MEDIUM ARMOR
('Hide Armor', 'medium_armor', 1000, 12, NULL, NULL, NULL, 12, 'Crude armor made from thick monster hides.', 'SRD'),
('Chain Shirt', 'medium_armor', 5000, 20, NULL, NULL, NULL, 13, 'Interlocking metal rings forming a shirt.', 'SRD'),
('Scale Mail', 'medium_armor', 5000, 45, NULL, NULL, ARRAY['stealth disadvantage'], 14, 'Overlapping metal scales on leather.', 'SRD'),
('Breastplate', 'medium_armor', 40000, 20, NULL, NULL, NULL, 14, 'A fitted metal chest piece.', 'SRD'),
('Half Plate', 'medium_armor', 75000, 40, NULL, NULL, ARRAY['stealth disadvantage'], 15, 'Plate armor covering vital areas.', 'SRD'),
-- HEAVY ARMOR
('Ring Mail', 'heavy_armor', 3000, 40, NULL, NULL, ARRAY['stealth disadvantage'], 14, 'Leather with heavy rings sewn in.', 'SRD'),
('Chain Mail', 'heavy_armor', 7500, 55, NULL, NULL, ARRAY['stealth disadvantage', 'str 13'], 16, 'Full suit of interlocking metal rings.', 'SRD'),
('Splint Armor', 'heavy_armor', 20000, 60, NULL, NULL, ARRAY['stealth disadvantage', 'str 15'], 17, 'Metal strips riveted to leather.', 'SRD'),
('Plate Armor', 'heavy_armor', 150000, 65, NULL, NULL, ARRAY['stealth disadvantage', 'str 15'], 18, 'Full plate armor, the pinnacle of protection.', 'SRD'),
-- SHIELDS
('Shield', 'shield', 1000, 6, NULL, NULL, NULL, 2, 'A wooden or metal shield providing +2 AC.', 'SRD'),
-- ADVENTURING GEAR
('Backpack', 'gear', 200, 5, NULL, NULL, NULL, NULL, 'A standard pack for carrying equipment.', 'SRD'),
('Bedroll', 'gear', 100, 7, NULL, NULL, NULL, NULL, 'Portable sleeping gear for gate expeditions.', 'SRD'),
('Rope, Hempen (50 feet)', 'gear', 100, 10, NULL, NULL, NULL, NULL, 'Standard climbing and utility rope.', 'SRD'),
('Rope, Silk (50 feet)', 'gear', 1000, 5, NULL, NULL, NULL, NULL, 'Lightweight, strong rope.', 'SRD'),
('Torch', 'gear', 1, 1, NULL, NULL, NULL, NULL, 'Provides light in dark gates.', 'SRD'),
('Lantern, Hooded', 'gear', 500, 2, NULL, NULL, NULL, NULL, 'Controllable light source.', 'SRD'),
('Rations (1 day)', 'gear', 50, 2, NULL, NULL, NULL, NULL, 'Dried food for gate expeditions.', 'SRD'),
('Waterskin', 'gear', 20, 5, NULL, NULL, NULL, NULL, 'Holds water for hydration.', 'SRD'),
('Grappling Hook', 'gear', 200, 4, NULL, NULL, NULL, NULL, 'Metal hook for climbing.', 'SRD'),
('Crowbar', 'gear', 200, 5, NULL, NULL, NULL, NULL, 'Provides advantage on Strength checks to force open.', 'SRD'),
('Hammer', 'gear', 100, 3, NULL, NULL, NULL, NULL, 'A basic tool hammer.', 'SRD'),
('Piton', 'gear', 5, 0.25, NULL, NULL, NULL, NULL, 'Metal spike for climbing.', 'SRD'),
('Tinderbox', 'gear', 50, 1, NULL, NULL, NULL, NULL, 'Fire-starting kit.', 'SRD'),
('Healers Kit', 'gear', 500, 3, NULL, NULL, NULL, NULL, 'Contains 10 uses of medical supplies.', 'SRD'),
('Antitoxin', 'gear', 5000, 0, NULL, NULL, NULL, NULL, 'Grants advantage vs poison for 1 hour.', 'SRD'),
('Caltrops (bag of 20)', 'gear', 100, 2, NULL, NULL, NULL, NULL, 'Spiked metal pieces to slow pursuers.', 'SRD'),
('Ball Bearings (bag of 1000)', 'gear', 100, 2, NULL, NULL, NULL, NULL, 'Creates difficult terrain.', 'SRD'),
('Chain (10 feet)', 'gear', 500, 10, NULL, NULL, NULL, NULL, 'Metal chain for restraining.', 'SRD'),
('Manacles', 'gear', 200, 6, NULL, NULL, NULL, NULL, 'Metal restraints for prisoners.', 'SRD'),
('Mirror, Steel', 'gear', 500, 0.5, NULL, NULL, NULL, NULL, 'Useful for seeing around corners.', 'SRD'),
('Oil (flask)', 'gear', 10, 1, NULL, NULL, NULL, NULL, 'Flammable liquid.', 'SRD'),
('Acid (vial)', 'gear', 2500, 1, NULL, NULL, NULL, NULL, 'Deals 2d6 acid damage.', 'SRD'),
('Alchemist Fire', 'gear', 5000, 1, NULL, NULL, NULL, NULL, 'Ignites and deals 1d4 fire per turn.', 'SRD'),
('Holy Water', 'gear', 2500, 1, NULL, NULL, NULL, NULL, 'Deals 2d6 radiant to fiends/undead.', 'SRD'),
-- TOOLS
('Thieves Tools', 'tools', 2500, 1, NULL, NULL, NULL, NULL, 'Required for picking locks and disarming traps.', 'SRD'),
('Smiths Tools', 'tools', 2000, 8, NULL, NULL, NULL, NULL, 'For metalworking and weapon repair.', 'SRD'),
('Alchemists Supplies', 'tools', 5000, 8, NULL, NULL, NULL, NULL, 'For creating potions and alchemical items.', 'SRD'),
('Herbalism Kit', 'tools', 500, 3, NULL, NULL, NULL, NULL, 'For identifying and preparing herbs.', 'SRD'),
('Disguise Kit', 'tools', 2500, 3, NULL, NULL, NULL, NULL, 'For creating disguises.', 'SRD'),
('Forgery Kit', 'tools', 1500, 5, NULL, NULL, NULL, NULL, 'For creating false documents.', 'SRD'),
('Gaming Set', 'tools', 100, 0, NULL, NULL, NULL, NULL, 'Dice, cards, or other games.', 'SRD'),
('Musical Instrument', 'tools', 2000, 3, NULL, NULL, NULL, NULL, 'Various instruments for performance.', 'SRD'),
('Navigators Tools', 'tools', 2500, 2, NULL, NULL, NULL, NULL, 'For navigation and mapping gates.', 'SRD'),
('Poisoners Kit', 'tools', 5000, 2, NULL, NULL, NULL, NULL, 'For creating and applying poisons.', 'SRD'),
-- HUNTER SPECIFIC GEAR
('Rift Compass', 'hunter_gear', 10000, 1, NULL, NULL, NULL, NULL, 'Detects nearby gate activity and ranks.', 'SRD'),
('Mana Crystal (Small)', 'hunter_gear', 5000, 0.5, NULL, NULL, NULL, NULL, 'Stores small amounts of mana energy.', 'SRD'),
('Mana Crystal (Medium)', 'hunter_gear', 25000, 1, NULL, NULL, NULL, NULL, 'Stores moderate mana energy.', 'SRD'),
('Mana Crystal (Large)', 'hunter_gear', 100000, 2, NULL, NULL, NULL, NULL, 'Stores significant mana energy.', 'SRD'),
('System Interface Upgrade', 'hunter_gear', 50000, 0, NULL, NULL, NULL, NULL, 'Enhances system window clarity and features.', 'SRD'),
('Emergency Extraction Beacon', 'hunter_gear', 75000, 1, NULL, NULL, NULL, NULL, 'One-use device to signal for extraction from a gate.', 'SRD'),
('Rift Mapping Device', 'hunter_gear', 30000, 2, NULL, NULL, NULL, NULL, 'Records and displays gate layouts.', 'SRD'),
('Monster Core Extractor', 'hunter_gear', 15000, 3, NULL, NULL, NULL, NULL, 'Tool for extracting mana cores from slain monsters.', 'SRD'),
('Ascendant License Badge', 'hunter_gear', 0, 0, NULL, NULL, NULL, NULL, 'Official ascendant identification and rank display.', 'SRD'),
('Reinforced Storage Case', 'hunter_gear', 5000, 5, NULL, NULL, NULL, NULL, 'Protects valuable items and cores from damage.', 'SRD')
ON CONFLICT (name) DO NOTHING;
