ALTER TABLE public.characters
  ADD COLUMN IF NOT EXISTS job_id TEXT,
  ADD COLUMN IF NOT EXISTS path_id TEXT,
  ADD COLUMN IF NOT EXISTS background_id TEXT;

ALTER TABLE public.character_powers
  ADD COLUMN IF NOT EXISTS power_id TEXT;

ALTER TABLE public.character_features
  ADD COLUMN IF NOT EXISTS feature_id TEXT,
  ADD COLUMN IF NOT EXISTS feat_id TEXT;

ALTER TABLE public.character_equipment
  ADD COLUMN IF NOT EXISTS item_id TEXT;

ALTER TABLE public.character_spells
  ADD COLUMN IF NOT EXISTS spell_id TEXT;

CREATE OR REPLACE FUNCTION pg_temp.ra_canonical_slug(value TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT regexp_replace(
    regexp_replace(lower(trim(value)), '[^a-z0-9]+', '-', 'g'),
    '(^-|-$)',
    '',
    'g'
  )
$$;

WITH canonical_jobs(lookup_name, id) AS (
VALUES
  ('assassin', 'assassin'),
  ('berserker', 'berserker'),
  ('contractor', 'contractor'),
  ('destroyer', 'destroyer'),
  ('esper', 'esper'),
  ('herald', 'herald'),
  ('holy knight', 'holy-knight'),
  ('idol', 'idol'),
  ('mage', 'mage'),
  ('revenant', 'revenant'),
  ('stalker', 'stalker'),
  ('striker', 'striker'),
  ('summoner', 'summoner'),
  ('technomancer', 'technomancer')
)
UPDATE public.characters c
SET job_id = coalesce(cj.id, pg_temp.ra_canonical_slug(c.job))
FROM canonical_jobs cj
WHERE c.job_id IS NULL
  AND c.job IS NOT NULL
  AND lower(trim(c.job)) = cj.lookup_name;

UPDATE public.characters
SET job_id = pg_temp.ra_canonical_slug(job)
WHERE job_id IS NULL
  AND job IS NOT NULL
  AND trim(job) <> '';

WITH canonical_backgrounds(lookup_name, id) AS (
VALUES
  ('aether-scientist', 'b-18'),
  ('aetheric pulse', 'b-06'),
  ('ascendant academy graduate', 'b-03'),
  ('association bureaucrat', 'b-14'),
  ('awakened delinquent', 'b-19'),
  ('black market relic dealer', 'b-15'),
  ('construction worker', 'b-33'),
  ('corporate executive', 'b-27'),
  ('delivery driver', 'b-37'),
  ('e-sports champion', 'b-30'),
  ('elite breach-tactician', 'b-11'),
  ('firefighter', 'b-40'),
  ('gate-site scavenger', 'b-16'),
  ('gate-worshipping cultist', 'b-22'),
  ('guardian legionnaire', 'b-08'),
  ('guild master', 'b-04'),
  ('hunter crimes detective', 'b-20'),
  ('journalist', 'b-34'),
  ('k-pop idol', 'b-24'),
  ('mechanic', 'b-39'),
  ('mega-guild heir (chaebol)', 'b-21'),
  ('movie star', 'b-25'),
  ('occult investigator', 'b-12'),
  ('office worker', 'b-32'),
  ('order inscriber', 'b-09'),
  ('paramedic', 'b-31'),
  ('police officer', 'b-42'),
  ('private military operator (pmc)', 'b-17'),
  ('pro athlete', 'b-26'),
  ('regent''s chosen', 'b-07'),
  ('rift porter (logistics)', 'b-13'),
  ('rift survivor', 'b-02'),
  ('rift-displaced contractor', 'b-01'),
  ('rift-scout', 'b-05'),
  ('security guard', 'b-36'),
  ('social media influencer', 'b-29'),
  ('social worker', 'b-41'),
  ('street vendor', 'b-35'),
  ('teacher', 'b-38'),
  ('underground hacker', 'b-28'),
  ('vault warden', 'b-10'),
  ('viral streamer', 'b-23')
)
UPDATE public.characters c
SET background_id = cb.id
FROM canonical_backgrounds cb
WHERE c.background_id IS NULL
  AND c.background IS NOT NULL
  AND lower(trim(c.background)) = cb.lookup_name;

WITH canonical_paths(lookup_name, id) AS (
VALUES
  ('design: aether breacher', 'technomancer--aether-breacher-design'),
  ('design: resonance siege', 'technomancer--resonance-siege-design'),
  ('design: swarm conduit', 'technomancer--swarm-conduit-design'),
  ('design: synchronist binary', 'technomancer--synchronist-binary-design'),
  ('design: the aether chemist', 'technomancer--aether-chemist-design'),
  ('design: the aether vessel', 'technomancer--aether-vessel-design'),
  ('path of the absolute devotion', 'holy-knight--absolute-devotion'),
  ('path of the absolute spark', 'esper--absolute-spark'),
  ('path of the absolute zealot', 'berserker--absolute-zealot'),
  ('path of the aetheric anomaly', 'berserker--aetheric-anomaly'),
  ('path of the aetheric cascade', 'esper--aetheric-cascade'),
  ('path of the aetheric channeler', 'striker--aetheric-channeler'),
  ('path of the aetheric dragon', 'esper--draconic-lineage'),
  ('path of the aftershock', 'destroyer--phantom-blade'),
  ('path of the apex hunter', 'stalker--apex-hunter'),
  ('path of the apex predator', 'destroyer--apex-predator'),
  ('path of the apex shifter', 'summoner--apex-shifter'),
  ('path of the apex slayer', 'stalker--apex-slayer'),
  ('path of the atonement mandate', 'holy-knight--atonement-mandate'),
  ('path of the biome architect', 'summoner--biome-architect'),
  ('path of the blade conductor', 'striker--blade-conductor'),
  ('path of the blade dancer', 'assassin--blade-dancer'),
  ('path of the blade resonance', 'idol--blade-resonance'),
  ('path of the bulwark', 'destroyer--bulwark'),
  ('path of the combat mandate', 'herald--combat-mandate'),
  ('path of the cosmic conduit', 'summoner--cosmic-conduit'),
  ('path of the cursed blade', 'contractor--cursed-blade'),
  ('path of the deep dweller', 'contractor--deep-dweller'),
  ('path of the detonation specialist', 'mage--detonation-specialist'),
  ('path of the dominance mandate', 'holy-knight--dominance-mandate'),
  ('path of the dream weaver', 'summoner--dream-weaver'),
  ('path of the entropic flow', 'striker--entropic-flow'),
  ('path of the entropy blade', 'revenant--entropy-blade'),
  ('path of the entropy drinker', 'revenant--entropy-drinker'),
  ('path of the escalating resonance', 'berserker--escalating-resonance'),
  ('path of the exaltation mandate', 'holy-knight--exaltation-mandate'),
  ('path of the gate beast', 'berserker--gate-beast'),
  ('path of the gate runner', 'assassin--gate-runner'),
  ('path of the genesis resonance', 'idol--genesis-resonance'),
  ('path of the glamour weaver', 'contractor--glamour-weaver'),
  ('path of the harmonic surgeon', 'striker--harmonic-surgeon'),
  ('path of the hive synchronist', 'stalker--hive-synchronist'),
  ('path of the hypnotic resonance', 'idol--hypnotic-resonance'),
  ('path of the infernal conduit', 'contractor--infernal-conduit'),
  ('path of the kinetic core', 'striker--kinetic-core'),
  ('path of the knowledge mandate', 'herald--knowledge-mandate'),
  ('path of the last stand', 'destroyer--last-stand'),
  ('path of the lore resonance', 'idol--lore-resonance'),
  ('path of the mana scars', 'berserker--mana-scars'),
  ('path of the matter weaver', 'mage--matter-weaver'),
  ('path of the pack commander', 'summoner--pack-commander'),
  ('path of the pack leader', 'stalker--pack-leader'),
  ('path of the phantasmist', 'mage--phantasmist'),
  ('path of the phantom step', 'striker--phantom-step'),
  ('path of the plague weaver', 'revenant--plague-weaver'),
  ('path of the probability mandate', 'mage--probability-mandate'),
  ('path of the psionic breach', 'esper--aberrant-mind'),
  ('path of the radiance mandate', 'herald--radiance-mandate'),
  ('path of the radiant vessel', 'contractor--radiant-vessel'),
  ('path of the restoration mandate', 'herald--restoration-mandate'),
  ('path of the retribution mandate', 'holy-knight--retribution-mandate'),
  ('path of the rift caller', 'mage--rift-caller'),
  ('path of the rift storm', 'berserker--rift-storm'),
  ('path of the rift strider', 'stalker--rift-strider'),
  ('path of the shadow herald', 'assassin--shadow-herald'),
  ('path of the shadow resonance', 'idol--shadow-resonance'),
  ('path of the shield architect', 'mage--shield-compiler'),
  ('path of the spell breaker', 'destroyer--spell-breaker'),
  ('path of the storm mandate', 'herald--storm-mandate'),
  ('path of the symbiotic host', 'summoner--symbiotic-host'),
  ('path of the tactician', 'destroyer--tactician'),
  ('path of the tempest core', 'esper--storm-sorcery'),
  ('path of the terminus', 'assassin--terminus'),
  ('path of the threshold walker', 'revenant--threshold-walker'),
  ('path of the triage mandate', 'herald--triage-mandate'),
  ('path of the umbral hunter', 'stalker--umbral-hunter'),
  ('path of the vanguard outrider', 'assassin--vanguard-outrider'),
  ('path of the verdant mandate', 'holy-knight--verdant-mandate'),
  ('path of the void lord', 'revenant--void-lord'),
  ('path of the void resonance', 'esper--shadow-magic'),
  ('path of the void whisperer', 'contractor--void-whisperer'),
  ('path of the war anthem', 'idol--war-anthem'),
  ('path of the weave infiltrator', 'assassin--weave-infiltrator'),
  ('path of the wither guard', 'revenant--wither-guard')
)
UPDATE public.characters c
SET path_id = cp.id
FROM canonical_paths cp
WHERE c.path_id IS NULL
  AND c.path IS NOT NULL
  AND lower(trim(c.path)) = cp.lookup_name;

WITH canonical_powers(lookup_name, id) AS (
VALUES
  ('absolute zero', 'absolute-zero'),
  ('aegis of light', 'aegis-of-light'),
  ('aeon shield', 'aeon-shield'),
  ('arcane ascension', 'arcane-ascension'),
  ('arcane charm', 'arcane-charm'),
  ('arcane recovery', 'arcane-recovery'),
  ('assassin''s luck', 'assassin-luck'),
  ('avatar of battle', 'avatar-of-battle'),
  ('bio-luminescence', 'bio-luminescence'),
  ('blight touch', 'blight-touch'),
  ('bulwark resilience', 'bulwark-resilience'),
  ('celestial communion', 'celestial-communion'),
  ('celestial judgment', 'celestial-judgment'),
  ('chronos shift', 'chronos-shift'),
  ('demonic aura', 'demonic-aura'),
  ('dimensional rift', 'dimensional-rift'),
  ('divine smite', 'divine-smite'),
  ('dominate will', 'mind-control'),
  ('dragon breath', 'dragon-breath'),
  ('echo clone', 'echo-clone'),
  ('echoes of the past', 'echoes-of-the-past'),
  ('entropy field', 'entropy-field'),
  ('essence wings', 'angelic-wings'),
  ('forceful absorption', 'kinetic-absorption'),
  ('gaze of petrification', 'gaze-of-petrification'),
  ('glacial fortress', 'glacial-fortress'),
  ('glacier prison', 'glacier-prison'),
  ('gravity crush', 'gravity-crush'),
  ('gravity leap', 'gravity-leap'),
  ('gravity well', 'gravity-well'),
  ('infernal forge', 'infernal-forge'),
  ('invisibility', 'invisibility'),
  ('ki point', 'ki-point'),
  ('life transfer', 'life-transfer'),
  ('lycanthropy', 'lycanthropy'),
  ('mana burn', 'mana-burn'),
  ('nanite swarm', 'nanite-swarm'),
  ('nebula drift', 'nebula-drift'),
  ('necrotic tether', 'necrotic-tether'),
  ('neuro spike', 'neuro-spike'),
  ('obsidian carapace', 'obsidian-carapace'),
  ('obsidian wall', 'obsidian-wall'),
  ('omega pulse', 'omega-pulse'),
  ('phantom barrage', 'phantom-barrage'),
  ('plasma whip', 'plasma-whip'),
  ('precision kill', 'sneak-attack'),
  ('primal shift', 'wild-shape'),
  ('quantum entanglement', 'quantum-entanglement'),
  ('reality glitch', 'reality-glitch'),
  ('reality shear', 'reality-shear'),
  ('regeneration', 'regeneration'),
  ('regent''s will', 'divine-intervention'),
  ('sanctified aura', 'holy-aura'),
  ('seraph''s call', 'seraph-call'),
  ('shadow essence', 'shadow-essence'),
  ('shadow puppetry', 'shadow-puppetry'),
  ('shadow step', 'shadow-step'),
  ('solar flare', 'solar-flare'),
  ('soul binding', 'soul-binding'),
  ('soul rend', 'soul-rend'),
  ('spectral blade', 'spectral-blade'),
  ('star-fire lance', 'star-fire-lance'),
  ('starfall', 'starfall'),
  ('storm call', 'storm-call'),
  ('supernova blast', 'supernova-blast'),
  ('telepathy', 'telepathy'),
  ('thermal vent', 'thermal-vent'),
  ('titan''s strength', 'titan-strength'),
  ('true sight', 'true-sight'),
  ('vampiric touch', 'vampiric-touch'),
  ('venom blood', 'venom-blood'),
  ('void collapse', 'void-collapse'),
  ('void singularity', 'void-singularity'),
  ('vortex shield', 'vortex-shield'),
  ('warp strike', 'warp-strike'),
  ('warrior''s rage', 'warrior-rage')
)
UPDATE public.character_powers cpw
SET power_id = cp.id
FROM canonical_powers cp
WHERE cpw.power_id IS NULL
  AND cpw.name IS NOT NULL
  AND lower(trim(cpw.name)) = cp.lookup_name;

UPDATE public.character_powers
SET power_id = pg_temp.ra_canonical_slug(name)
WHERE power_id IS NULL
  AND name IS NOT NULL
  AND trim(name) <> '';

WITH canonical_spells(lookup_name, id) AS (
VALUES
  ('abyssal edge', 'spell-c-14'),
  ('abyssal shackle', 'spell-c-8'),
  ('abyssal siphon', 'spell-s-3'),
  ('abyssal strike', 'spell-c-4'),
  ('arctic burst', 'spell-b-10'),
  ('arctic lance', 'spell-d-7'),
  ('blood tear', 'spell-d-9'),
  ('bolt pulse', 'spell-b-12'),
  ('bright spike', 'spell-a-2'),
  ('bright tomb', 'spell-d-6'),
  ('carnage strike', 'spell-d-11'),
  ('carnage tear', 'spell-a-6'),
  ('celestial edge', 'spell-c-9'),
  ('chill lance', 'spell-d-1'),
  ('chill wave', 'spell-c-12'),
  ('corona burst', 'spell-c-2'),
  ('corona shackle', 'spell-a-5'),
  ('corona storm', 'spell-d-13'),
  ('crimson cleave', 'spell-d-8'),
  ('crimson shackle', 'spell-c-7'),
  ('crimson strike', 'spell-c-5'),
  ('dawn spike', 'spell-b-4'),
  ('decay of the ages', 'spell-s-15'),
  ('entropy lance', 'spell-b-1'),
  ('entropy siphon', 'spell-d-12'),
  ('frost grasp', 'spell-c-11'),
  ('frost judgment', 'spell-a-9'),
  ('frostbite convergence', 'spell-s-14'),
  ('glacial shackle', 'spell-s-11'),
  ('glacial tomb', 'spell-b-3'),
  ('gore shackle', 'spell-c-15'),
  ('heart tear', 'spell-b-9'),
  ('heart wave', 'spell-a-1'),
  ('ice lance', 'spell-d-15'),
  ('ichor edge', 'spell-b-2'),
  ('judgment of light', 'spell-s-6'),
  ('light burst', 'spell-a-4'),
  ('lightning lance', 'spell-d-14'),
  ('lightning strike', 'spell-a-10'),
  ('night storm', 'spell-d-10'),
  ('null spike', 'spell-c-6'),
  ('permafrost regent''s edge', 'spell-s-4'),
  ('pulse spike', 'spell-b-7'),
  ('pulse storm', 'spell-a-14'),
  ('radiant annihilation', 'spell-s-10'),
  ('radiant grasp', 'spell-c-13'),
  ('radiant shackle', 'spell-c-3'),
  ('radiant sovereign''s pulse', 'spell-s-2'),
  ('rime blast', 'spell-b-14'),
  ('rime of the ancient one', 'spell-s-8'),
  ('rime pulse', 'spell-a-8'),
  ('sanguine burst', 'spell-b-13'),
  ('sanguine strike', 'spell-d-5'),
  ('shadow zenith strike', 'spell-s-13'),
  ('shock spike', 'spell-a-11'),
  ('shock tear', 'spell-a-7'),
  ('singularity lance', 'spell-c-10'),
  ('solar burst', 'spell-b-5'),
  ('solar execution', 'spell-s-7'),
  ('surge grasp', 'spell-a-15'),
  ('surge storm', 'spell-d-4'),
  ('tempest binding', 'spell-d-3'),
  ('tempest lance', 'spell-s-1'),
  ('tempest shackle', 'spell-b-8'),
  ('thunder shackle', 'spell-d-2'),
  ('tomb of the sovereign', 'spell-s-9'),
  ('umbral erasure', 'spell-s-12'),
  ('umbral tear', 'spell-a-3'),
  ('void blast', 'spell-a-13'),
  ('void edge', 'spell-b-6'),
  ('void lance', 'spell-b-15'),
  ('void tomb', 'spell-b-11'),
  ('void wave', 'spell-c-1'),
  ('volt wave', 'spell-a-12'),
  ('world-breaker''s burst', 'spell-s-5')
)
UPDATE public.character_spells cs
SET spell_id = sp.id
FROM canonical_spells sp
WHERE cs.spell_id IS NULL
  AND cs.name IS NOT NULL
  AND lower(trim(cs.name)) = sp.lookup_name;

WITH canonical_equipment(lookup_name, id) AS (
VALUES
  ('abyssal dagger', 'item_p9_3'),
  ('abyssal field bow', 'gap_ranged_bow_epic_0'),
  ('abyssal hooded robe', 'gap_gear_attire_epic_3'),
  ('abyssal katana', 'item_p2_21'),
  ('abyssal longsword', 'item_p9_12'),
  ('abyssal mana band', 'gap_gear_ring_epic_5'),
  ('abyssal plate armor', 'abyssal-plate'),
  ('abyssal reliquary', 'artifact_7'),
  ('abyssal revolver', 'item_p9_14'),
  ('abyssal rod', 'gap_focus_wand_epic_2'),
  ('abyssal spear', 'item_p7_3'),
  ('abyssal staff', 'gap_melee_staff_epic_0'),
  ('abyssal warhammer', 'item_p6_24'),
  ('abyssal whip', 'item_p5_24'),
  ('adept''s bludgeon', 'gap_melee_bludgeon_heavy_uncommon_1'),
  ('adept''s bulwark', 'gap_armor_shield_uncommon_3'),
  ('adept''s cantrip scroll', 'gap_consumable_scroll_uncommon_8'),
  ('adept''s club', 'gap_melee_bludgeon_uncommon_5'),
  ('adept''s combat boots', 'gap_gear_boots_uncommon_6'),
  ('adept''s combat staff', 'gap_melee_staff_uncommon_4'),
  ('adept''s cuffs', 'gap_gear_restraint_uncommon_1'),
  ('adept''s field cloak', 'gap_armor_light_uncommon_0'),
  ('adept''s field stim', 'gap_consumable_stim_uncommon_1'),
  ('adept''s hammered band', 'gap_gear_ring_uncommon_17'),
  ('adept''s hunter''s mantle', 'gap_gear_attire_uncommon_10'),
  ('adept''s mana manual', 'gap_focus_tome_uncommon_1'),
  ('adept''s patrol bracer', 'gap_gear_bracer_uncommon_3'),
  ('adept''s scroll', 'gap_consumable_scroll_uncommon_15'),
  ('adept''s serum', 'gap_consumable_stim_uncommon_0'),
  ('adept''s spyglass', 'gap_gear_utility_uncommon_4'),
  ('adept''s tactical light', 'gap_gear_light_uncommon_1'),
  ('adept''s tower shield', 'gap_armor_shield_uncommon_7'),
  ('adept''s wand', 'gap_focus_wand_uncommon_5'),
  ('aegis bracers', 'item_p5_11'),
  ('aegis breastplate', 'item_p7_4'),
  ('aegis combat vest', 'item_p8_11'),
  ('aegis exo-suit', 'item_p6_5'),
  ('aegis shin guards', 'item_p9_32'),
  ('aegis spaulders', 'item_p7_23'),
  ('aegis trench coat', 'item_p5_48'),
  ('aether-plated bracers', 'item_p7_44'),
  ('aether-plated breastplate', 'item_p9_7'),
  ('aether-plated combat vest', 'item_p6_46'),
  ('aether-plated exo-suit', 'item_p9_47'),
  ('aether-plated spaulders', 'item_p7_37'),
  ('aether-plated tactical helmet', 'item_p7_2'),
  ('aetheric adrenal injector', 'gap_consumable_stim_rare_3'),
  ('aetheric combat pistol', 'gap_firearm_pistol_rare_3'),
  ('aetheric compact smg', 'gap_firearm_smg_rare_0'),
  ('aetheric crested ring', 'gap_gear_ring_rare_5'),
  ('aetheric dagger', 'item_p6_8'),
  ('aetheric diagnostic scanner', 'bg-aetheric-scanner'),
  ('aetheric footwraps', 'gap_gear_boots_rare_6'),
  ('aetheric forearm plate', 'gap_gear_bracer_rare_4'),
  ('aetheric gauntlets', 'item_p8_14'),
  ('aetheric hand axe', 'gap_melee_axe_rare_2'),
  ('aetheric katana', 'item_p2_46'),
  ('aetheric locket', 'gap_gear_amulet_rare_5'),
  ('aetheric longsword', 'item_p9_13'),
  ('aetheric mace', 'gap_melee_bludgeon_rare_4'),
  ('aetheric morningstar', 'gap_melee_bludgeon_rare_2'),
  ('aetheric nodachi', 'gap_melee_blade_heavy_rare_3'),
  ('aetheric revolver', 'gap_firearm_pistol_rare_2'),
  ('aetheric sniper rifle', 'item_p6_49'),
  ('aetheric spear', 'item_p4_33'),
  ('aetheric thermal bag', 'bg-thermal-bag'),
  ('aetheric warhammer', 'item_p5_44'),
  ('aetheric whip', 'item_p7_19'),
  ('anomaly blood potion', 'anomaly-blood-potion'),
  ('apex-forged field bow', 'gap_ranged_bow_legendary_0'),
  ('apex-forged sash', 'gap_gear_belt_legendary_0'),
  ('apocalypse cord charm', 'gap_gear_amulet_epic_6'),
  ('apocalypse crested ring', 'gap_gear_ring_epic_8'),
  ('apocalypse flail', 'gap_melee_bludgeon_epic_1'),
  ('apocalypse patrol boots', 'gap_gear_boots_epic_2'),
  ('apocalypse patrol helm', 'gap_armor_headgear_epic_1'),
  ('apocalypse pendant', 'gap_gear_amulet_epic_3'),
  ('apocalypse service brigandine', 'gap_armor_medium_epic_1'),
  ('apocalypse tome', 'gap_focus_tome_epic_1'),
  ('arcane focus', 'base-focus-arcane'),
  ('architect''s authority', 'rulers-authority'),
  ('architect''s battle scroll', 'gap_consumable_scroll_legendary_2'),
  ('architect''s wand', 'gap_focus_wand_legendary_1'),
  ('archon''s bludgeon', 'gap_melee_bludgeon_heavy_epic_0'),
  ('archon''s club', 'gap_melee_bludgeon_epic_0'),
  ('archon''s combat rifle', 'gap_firearm_rifle_epic_1'),
  ('archon''s conduit', 'gap_focus_caster_epic_0'),
  ('archon''s inset ring', 'gap_gear_ring_epic_7'),
  ('archon''s mantle', 'gap_gear_attire_epic_1'),
  ('archon''s sigil focus', 'gap_focus_caster_epic_1'),
  ('archon''s tomahawk', 'gap_melee_axe_epic_1'),
  ('archon''s trident', 'gap_melee_polearm_epic_0'),
  ('arrows (20)', 'base-ammo-arrows-20'),
  ('ascendant bureau badge', 'bg-police-badge'),
  ('ascendant field crossbow', 'gap_ranged_crossbow_epic_1'),
  ('ascendant patrol helm', 'gap_armor_headgear_epic_0'),
  ('ascendant stone charm', 'gap_gear_amulet_epic_1'),
  ('battleaxe', 'base-weapon-battleaxe'),
  ('black-market aetheric antidote', 'item_p9_30'),
  ('black-market amulet', 'gap_gear_amulet_uncommon_3'),
  ('black-market bastard sword', 'gap_melee_blade_heavy_uncommon_5'),
  ('black-market beast repellent', 'item_p6_43'),
  ('black-market brigandine', 'gap_armor_medium_uncommon_1'),
  ('black-market ceremonial robe', 'gap_gear_attire_uncommon_2'),
  ('black-market chakram', 'gap_ranged_thrown_uncommon_3'),
  ('black-market compound bow', 'gap_ranged_bow_uncommon_2'),
  ('black-market concussion grenade', 'gap_consumable_grenade_uncommon_2'),
  ('black-market forearm plate', 'gap_gear_bracer_uncommon_7'),
  ('black-market hammered band', 'gap_gear_ring_uncommon_15'),
  ('black-market health potion', 'item_p9_41'),
  ('black-market kusarigama', 'gap_melee_whip_uncommon_2'),
  ('black-market liquid shadow', 'item_p6_26'),
  ('black-market longsword', 'gap_melee_blade_versatile_uncommon_3'),
  ('black-market mana elixir', 'item_p8_7'),
  ('black-market marching boots', 'gap_gear_boots_uncommon_5'),
  ('black-market orb', 'gap_focus_caster_uncommon_0'),
  ('black-market rifle', 'gap_firearm_rifle_uncommon_2'),
  ('black-market scattergun', 'gap_firearm_shotgun_uncommon_0'),
  ('black-market sceptre', 'gap_focus_wand_uncommon_3'),
  ('black-market shortsword', 'gap_melee_blade_finesse_uncommon_3'),
  ('black-market stamina stim', 'item_p9_11'),
  ('black-market stone ring', 'gap_gear_ring_uncommon_13'),
  ('black-market throwing axes', 'gap_ranged_thrown_uncommon_2'),
  ('black-market twin band', 'gap_gear_ring_uncommon_5'),
  ('bloodstone amulet', 'bloodstone-amulet'),
  ('bloodthirsty greatsword', 'bloodthirsty-greatsword'),
  ('blowgun', 'base-weapon-blowgun'),
  ('bonded badge', 'gap_gear_credential_uncommon_0'),
  ('bonded battle scroll', 'gap_consumable_scroll_uncommon_17'),
  ('bonded conductor', 'gap_focus_wand_uncommon_7'),
  ('bonded draught', 'gap_consumable_potion_uncommon_3'),
  ('bonded insignia', 'gap_gear_misc_uncommon_2'),
  ('bonded lamp', 'gap_gear_light_uncommon_3'),
  ('bonded patrol shield', 'gap_armor_shield_uncommon_0'),
  ('bonded prism', 'gap_focus_caster_uncommon_1'),
  ('bonded rune ring', 'gap_gear_ring_uncommon_4'),
  ('bonded staff', 'gap_melee_staff_uncommon_3'),
  ('breastplate', 'base-armor-breastplate'),
  ('bureau-approved auto-rifle', 'gap_firearm_rifle_common_1'),
  ('bureau-approved band', 'gap_gear_ring_common_5'),
  ('bureau-approved bulwark plate', 'gap_armor_heavy_common_0'),
  ('bureau-approved chisel', 'gap_gear_utility_common_4'),
  ('bureau-approved credential', 'gap_gear_credential_common_3'),
  ('bureau-approved endurance serum', 'gap_consumable_stim_common_0'),
  ('bureau-approved field meal', 'gap_consumable_ration_common_3'),
  ('bureau-approved flare', 'gap_consumable_signal_common_2'),
  ('bureau-approved map', 'gap_gear_navigation_common_3'),
  ('bureau-approved pdw', 'gap_firearm_smg_common_2'),
  ('bureau-approved recovery pack', 'gap_consumable_ration_common_5'),
  ('bureau-approved submachine gun', 'gap_firearm_smg_common_1'),
  ('bureau-issue locator', 'gap_consumable_signal_common_1'),
  ('bureau-issue mess kit', 'gap_gear_utility_common_6'),
  ('bureau-issue pocket lantern', 'gap_gear_light_common_4'),
  ('bureau-issue saw', 'gap_gear_utility_common_7'),
  ('bureau-issue serum', 'gap_consumable_stim_common_3'),
  ('bureau-issue tactical sash', 'gap_gear_belt_common_3'),
  ('bureau-issue throwing spears', 'gap_ranged_thrown_common_2'),
  ('bureau-stamped baton', 'gap_focus_wand_common_1'),
  ('bureau-stamped battle gauntlets', 'gap_melee_gauntlet_common_1'),
  ('bureau-stamped climbing kit', 'gap_gear_utility_common_12'),
  ('bureau-stamped hooded lantern', 'gap_gear_light_common_1'),
  ('bureau-stamped lamp', 'gap_gear_light_common_2'),
  ('bureau-stamped locket', 'gap_gear_amulet_common_6'),
  ('bureau-stamped longsword', 'gap_melee_blade_versatile_common_1'),
  ('bureau-stamped mace', 'gap_melee_bludgeon_common_3'),
  ('bureau-stamped medical kit', 'gap_gear_kit_common_3'),
  ('bureau-stamped sawed-off', 'gap_firearm_shotgun_common_3'),
  ('bureau-stamped tanto', 'gap_melee_blade_finesse_common_0'),
  ('bureau-stamped twin sickles', 'gap_melee_sickle_common_1'),
  ('bureau-stamped war blade', 'gap_melee_blade_heavy_common_1'),
  ('bureau-stamped whetstone', 'gap_gear_utility_common_10'),
  ('bureau-stamped zweihander', 'gap_melee_blade_heavy_common_2'),
  ('burglar''s pack', 'base-gear-burglars-pack'),
  ('burner phone', 'base-tool-burner-phone'),
  ('cadet''s combat sash', 'gap_gear_belt_common_5'),
  ('cadet''s hand mirror', 'gap_gear_utility_common_3'),
  ('cadet''s mana mine', 'gap_consumable_grenade_common_5'),
  ('cadet''s stone charm', 'gap_gear_amulet_common_1'),
  ('cadet''s tracking drone', 'gap_gear_electronics_common_2'),
  ('cadet''s war axe', 'gap_melee_axe_common_3'),
  ('calamity aegis', 'artifact_10'),
  ('calamity core', 'artifact_9'),
  ('calamity edge', 'artifact_14'),
  ('case file binder', 'bg-case-binder'),
  ('cataclysmic breach charge', 'gap_consumable_grenade_epic_2'),
  ('cataclysmic cantrip scroll', 'gap_consumable_scroll_epic_2'),
  ('cataclysmic draught', 'gap_consumable_potion_epic_2'),
  ('cataclysmic kite shield', 'gap_armor_shield_epic_2'),
  ('cataclysmic potion', 'gap_consumable_potion_epic_0'),
  ('cataclysmic robe', 'gap_gear_attire_epic_2'),
  ('cataclysmic stim', 'gap_consumable_stim_epic_1'),
  ('ceramic bracers', 'item_p9_40'),
  ('ceramic exo-suit', 'item_p3_33'),
  ('ceramic shin guards', 'item_p7_47'),
  ('ceramic spaulders', 'item_p6_47'),
  ('ceramic trench coat', 'item_p4_27'),
  ('chain mail', 'base-armor-chain-mail'),
  ('chain shirt', 'base-armor-chain-shirt'),
  ('club', 'base-weapon-club'),
  ('collapsible market stall', 'bg-market-stall'),
  ('component pouch', 'base-focus-component-pouch'),
  ('concentrated aetheric antidote', 'item_p9_24'),
  ('concentrated beast repellent', 'item_p9_6'),
  ('concentrated liquid shadow', 'item_p7_6'),
  ('concentrated mana elixir', 'item_p6_6'),
  ('concentrated stamina stim', 'item_p9_38'),
  ('conscript''s channel stone', 'gap_focus_caster_common_0'),
  ('conscript''s charge', 'gap_consumable_grenade_common_1'),
  ('conscript''s greathelm', 'gap_armor_headgear_common_2'),
  ('conscript''s loop', 'gap_gear_ring_common_4'),
  ('conscript''s mana-weave jacket', 'gap_armor_light_common_1'),
  ('conscript''s phial', 'gap_consumable_potion_common_3'),
  ('conscript''s pocket token', 'gap_gear_misc_common_1'),
  ('conscript''s recurve bow', 'gap_ranged_bow_common_3'),
  ('conscript''s revolver', 'gap_firearm_pistol_common_0'),
  ('conscript''s spiked mace', 'gap_melee_bludgeon_common_4'),
  ('conscript''s syringe', 'gap_consumable_stim_common_2'),
  ('conscript''s truncheon', 'gap_melee_bludgeon_common_1'),
  ('cracked-screen laptop', 'bg-cracked-laptop'),
  ('crimson bastard sword', 'gap_melee_blade_heavy_rare_5'),
  ('crimson buckler', 'gap_armor_shield_rare_0'),
  ('crimson footwraps', 'gap_gear_boots_rare_2'),
  ('crimson gauntlets', 'item_p8_42'),
  ('crimson halberd', 'item_p4_43'),
  ('crimson heavy cuirass', 'gap_armor_heavy_rare_1'),
  ('crimson javelins', 'gap_ranged_thrown_rare_1'),
  ('crimson layered mail', 'gap_armor_medium_rare_4'),
  ('crimson longsword', 'item_p9_1'),
  ('crimson loop', 'gap_gear_ring_rare_6'),
  ('crimson plate armor', 'gap_armor_heavy_rare_2'),
  ('crimson revolver', 'item_p2_3'),
  ('crimson sniper rifle', 'item_p7_14'),
  ('crimson spear', 'item_p9_42'),
  ('crimson warhammer', 'item_p2_25'),
  ('crisis de-escalation guide', 'bg-deescalation-guide'),
  ('crossbow bolts (20)', 'base-ammo-bolts-20'),
  ('crown of sense', 'crown-of-sense'),
  ('crownbearer''s cutlass', 'gap_melee_blade_versatile_epic_0'),
  ('crownbearer''s heir casting staff', 'gap_melee_staff_legendary_0'),
  ('crownbearer''s rune scroll', 'gap_consumable_scroll_epic_6'),
  ('crownbearer''s tactical sash', 'gap_gear_belt_epic_0'),
  ('crumpled business suit', 'bg-business-suit'),
  ('cursed combat boots', 'gap_gear_boots_legendary_0'),
  ('cursed scroll', 'gap_consumable_scroll_legendary_3'),
  ('cursed truncheon', 'gap_melee_bludgeon_legendary_0'),
  ('custom-built laptop', 'base-tool-custom-laptop'),
  ('custom-forged bone pendant', 'gap_gear_amulet_uncommon_6'),
  ('custom-forged charge', 'gap_consumable_grenade_uncommon_5'),
  ('custom-forged combat shield', 'gap_armor_shield_uncommon_6'),
  ('custom-forged cord charm', 'gap_gear_amulet_uncommon_9'),
  ('custom-forged cutlass', 'gap_melee_blade_versatile_uncommon_1'),
  ('custom-forged diagnostic tool', 'gap_gear_electronics_uncommon_2'),
  ('custom-forged half-plate', 'gap_armor_medium_uncommon_3'),
  ('custom-forged longbow', 'gap_ranged_bow_uncommon_4'),
  ('custom-forged mace', 'gap_melee_bludgeon_uncommon_4'),
  ('custom-forged operator''s coat', 'gap_gear_attire_uncommon_0'),
  ('custom-forged restorative vial', 'gap_consumable_purifier_uncommon_3'),
  ('custom-forged service pistol', 'gap_firearm_pistol_uncommon_3'),
  ('custom-forged shield', 'gap_armor_shield_uncommon_1'),
  ('custom-forged throwing stars', 'gap_ranged_thrown_uncommon_0'),
  ('custom-forged war pike', 'gap_melee_polearm_uncommon_1'),
  ('custom-forged ward scroll', 'gap_consumable_scroll_uncommon_4'),
  ('customer ledger', 'bg-customer-ledger'),
  ('dagger', 'base-weapon-dagger'),
  ('dart', 'base-weapon-dart'),
  ('darts (10)', 'base-ammo-darts-10'),
  ('dawnbringer''s ceremonial robe', 'gap_gear_attire_legendary_0'),
  ('dawnbringer''s greataxe', 'gap_melee_axe_legendary_0'),
  ('decorated band', 'gap_gear_ring_uncommon_11'),
  ('decorated belt', 'gap_gear_belt_uncommon_8'),
  ('decorated casting scroll', 'gap_consumable_scroll_uncommon_9'),
  ('decorated charm', 'gap_gear_amulet_uncommon_2'),
  ('decorated combat plate', 'gap_armor_heavy_uncommon_3'),
  ('decorated counter-agent', 'gap_consumable_purifier_uncommon_2'),
  ('decorated field greaves', 'gap_gear_boots_uncommon_9'),
  ('decorated half-plate', 'gap_armor_medium_uncommon_2'),
  ('decorated hand axe', 'gap_melee_axe_uncommon_1'),
  ('decorated mace', 'gap_melee_bludgeon_uncommon_2'),
  ('decorated mana crystal', 'gap_focus_caster_uncommon_3'),
  ('decorated phial', 'gap_consumable_potion_uncommon_0'),
  ('decorated rune scroll', 'gap_consumable_scroll_uncommon_1'),
  ('decorated salve', 'gap_consumable_potion_uncommon_5'),
  ('decorated war axe', 'gap_melee_axe_uncommon_3'),
  ('dented hard hat', 'bg-dented-hardhat'),
  ('department-issue tactical vest', 'bg-tactical-vest'),
  ('digital voice recorder', 'bg-voice-recorder'),
  ('dimensional compass', 'dimensional-compass'),
  ('dimensional field crossbow', 'gap_ranged_crossbow_epic_0'),
  ('dimensional inscription', 'gap_consumable_scroll_epic_1'),
  ('dimensional lattice crystal', 'gap_focus_caster_epic_2'),
  ('dimensional strike gauntlets', 'gap_melee_gauntlet_epic_0'),
  ('dimensional suppressed pistol', 'gap_firearm_pistol_epic_0'),
  ('diplomat''s pack', 'base-gear-diplomats-pack'),
  ('dissolved corporation id badge', 'bg-company-badge'),
  ('doom-forged cinch belt', 'gap_gear_belt_epic_2'),
  ('doom-forged combat mail', 'gap_armor_medium_epic_0'),
  ('doom-forged operator''s coat', 'gap_gear_attire_epic_0'),
  ('doom-forged patrol shield', 'gap_armor_shield_epic_1'),
  ('doom-forged revolver', 'gap_firearm_pistol_epic_1'),
  ('doom-forged sigil bracer', 'gap_gear_bracer_epic_0'),
  ('doom-forged ward scroll', 'gap_consumable_scroll_epic_0'),
  ('doombound combat vest', 'gap_armor_light_legendary_0'),
  ('doombound inset ring', 'gap_gear_ring_legendary_2'),
  ('dreamfire anchor line', 'gap_gear_utility_rare_0'),
  ('dreamfire channel stone', 'gap_focus_caster_rare_0'),
  ('dreamfire morningstar', 'gap_melee_bludgeon_rare_1'),
  ('dreamfire spell scroll', 'gap_consumable_scroll_rare_1'),
  ('dungeoneer''s pack', 'base-gear-dungeoneers-pack'),
  ('echo of origin reinforced mask', 'gap_armor_headgear_legendary_0'),
  ('echo of origin stone charm', 'gap_gear_amulet_legendary_0'),
  ('eclipse cord charm', 'gap_gear_amulet_epic_7'),
  ('eclipse round shield', 'gap_armor_shield_epic_0'),
  ('eclipse wand', 'gap_focus_wand_epic_0'),
  ('eclipse ward scroll', 'gap_consumable_scroll_epic_8'),
  ('ember buckler', 'gap_armor_shield_rare_3'),
  ('ember combat shield', 'gap_armor_shield_rare_2'),
  ('ember combat staff', 'gap_melee_staff_rare_4'),
  ('ember combat whip', 'gap_melee_whip_rare_1'),
  ('ember cordial', 'gap_consumable_potion_rare_1'),
  ('ember holdout pistol', 'gap_firearm_pistol_rare_0'),
  ('ember mana manual', 'gap_focus_tome_rare_0'),
  ('ember patrol coat', 'gap_armor_light_rare_0'),
  ('ember pdw', 'gap_firearm_smg_rare_2'),
  ('ember receiver', 'gap_gear_electronics_rare_1'),
  ('ember recorder', 'gap_gear_electronics_rare_2'),
  ('ember recurve crossbow', 'gap_ranged_crossbow_rare_3'),
  ('ember spell scroll', 'gap_consumable_scroll_rare_14'),
  ('ember talisman', 'gap_gear_amulet_rare_11'),
  ('ember uniform', 'gap_gear_attire_rare_8'),
  ('emergency medical responder uniform', 'bg-emr-uniform'),
  ('encrypted contact notebook', 'bg-encrypted-notebook'),
  ('endless service blade', 'gap_melee_blade_versatile_legendary_0'),
  ('endless wand', 'gap_focus_wand_legendary_0'),
  ('entertainer''s pack', 'base-gear-entertainers-pack'),
  ('essence collector', 'essence-collector'),
  ('essence potion', 'essence-potion'),
  ('explorer''s pack', 'base-gear-explorers-pack'),
  ('field-issue chisel', 'gap_gear_utility_common_5'),
  ('field-issue conductor', 'gap_focus_wand_common_0'),
  ('field-issue glow rod', 'gap_gear_light_common_5'),
  ('field-issue light crossbow', 'gap_ranged_crossbow_common_2'),
  ('field-issue quartermaster''s token', 'gap_gear_misc_common_2'),
  ('field-issue receiver', 'gap_gear_electronics_common_1'),
  ('field-issue rope', 'gap_gear_utility_common_11'),
  ('field-issue rune scroll', 'gap_consumable_scroll_common_5'),
  ('field-issue spyglass', 'gap_gear_utility_common_0'),
  ('field-issue submachine gun', 'gap_firearm_smg_common_0'),
  ('field-issue throwing spears', 'gap_ranged_thrown_common_3'),
  ('field-issue tracking kit', 'gap_gear_kit_common_0'),
  ('field-tested auto-shotgun', 'gap_firearm_shotgun_uncommon_1'),
  ('field-tested battle scroll', 'gap_consumable_scroll_uncommon_6'),
  ('field-tested belt', 'gap_gear_belt_uncommon_6'),
  ('field-tested breach kit', 'gap_gear_kit_uncommon_3'),
  ('field-tested combat mace', 'gap_melee_bludgeon_uncommon_0'),
  ('field-tested combat pistol', 'gap_firearm_pistol_uncommon_0'),
  ('field-tested combat shield', 'gap_armor_shield_uncommon_4'),
  ('field-tested crested ring', 'gap_gear_ring_uncommon_8'),
  ('field-tested cuff', 'gap_gear_bracer_uncommon_6'),
  ('field-tested field cloak', 'gap_armor_light_uncommon_1'),
  ('field-tested field computer', 'gap_gear_electronics_uncommon_3'),
  ('field-tested insignia', 'gap_gear_credential_uncommon_2'),
  ('field-tested lattice scroll', 'gap_consumable_scroll_uncommon_13'),
  ('field-tested recall beacon', 'gap_consumable_signal_uncommon_2'),
  ('field-tested sigil scroll', 'gap_consumable_scroll_uncommon_10'),
  ('field-tested talisman', 'gap_gear_amulet_uncommon_13'),
  ('first-aid trauma kit', 'bg-trauma-kit'),
  ('first-awakened bound ring', 'gap_gear_ring_legendary_3'),
  ('first-awakened cloak', 'gap_gear_attire_legendary_1'),
  ('flail', 'base-weapon-flail'),
  ('frontier bullpup', 'gap_firearm_rifle_uncommon_3'),
  ('frontier cinch belt', 'gap_gear_belt_uncommon_9'),
  ('frontier claymore', 'gap_melee_blade_heavy_uncommon_1'),
  ('frontier combat belt', 'gap_gear_belt_uncommon_3'),
  ('frontier combat whip', 'gap_melee_whip_uncommon_0'),
  ('frontier field pack', 'gap_consumable_ration_uncommon_0'),
  ('frontier hammer', 'gap_gear_utility_uncommon_3'),
  ('frontier hardened bracer', 'gap_gear_bracer_uncommon_0'),
  ('frontier kama', 'gap_melee_sickle_uncommon_0'),
  ('frontier pump-action', 'gap_firearm_shotgun_uncommon_3'),
  ('frontier sigil tome', 'gap_focus_tome_uncommon_2'),
  ('frontier warhammer', 'gap_melee_bludgeon_heavy_uncommon_0'),
  ('frost axe', 'frost-axe'),
  ('frost bracer', 'gap_gear_bracer_rare_1'),
  ('frost combat bow', 'gap_ranged_bow_rare_2'),
  ('frost combat mail', 'gap_armor_medium_rare_3'),
  ('frost combat rifle', 'gap_firearm_rifle_rare_1'),
  ('frost cord charm', 'gap_gear_amulet_rare_4'),
  ('frost draught', 'gap_consumable_potion_rare_4'),
  ('frost greathelm', 'gap_armor_headgear_rare_2'),
  ('frost heavy cuirass', 'gap_armor_heavy_rare_0'),
  ('frost mana locket', 'gap_gear_amulet_rare_1'),
  ('frost sigil focus', 'gap_focus_caster_rare_2'),
  ('frost utility belt', 'gap_gear_belt_rare_6'),
  ('frost war pick', 'gap_melee_bludgeon_rare_0'),
  ('gate-forged bracers', 'item_p8_28'),
  ('gate-forged breastplate', 'item_p8_4'),
  ('gate-forged combat vest', 'item_p7_46'),
  ('gate-forged shin guards', 'item_p3_29'),
  ('gate-forged spaulders', 'item_p8_30'),
  ('gate-forged tactical helmet', 'item_p9_31'),
  ('gate-zone department radio', 'bg-dept-radio'),
  ('gate-zone gps device', 'bg-gate-gps'),
  ('genesis hammered band', 'gap_gear_ring_legendary_1'),
  ('genesis mine', 'gap_consumable_grenade_legendary_0'),
  ('genesis service brigandine', 'gap_armor_medium_legendary_0'),
  ('genesis sigil scroll', 'gap_consumable_scroll_legendary_1'),
  ('genesis stone charm', 'gap_gear_amulet_legendary_2'),
  ('glacial boots', 'gap_gear_boots_rare_0'),
  ('glacial bullpup', 'gap_firearm_rifle_rare_3'),
  ('glacial catalyst', 'gap_focus_caster_rare_1'),
  ('glacial claymore', 'gap_melee_blade_heavy_rare_2'),
  ('glacial crested ring', 'gap_gear_ring_rare_9'),
  ('glacial field crossbow', 'gap_ranged_crossbow_rare_0'),
  ('glacial purifier', 'gap_consumable_purifier_rare_1'),
  ('glacial reach spear', 'gap_melee_polearm_rare_1'),
  ('glacial recovery kit', 'gap_gear_kit_rare_1'),
  ('glacial reference codex', 'gap_focus_tome_rare_1'),
  ('glacial sceptre', 'gap_focus_wand_rare_3'),
  ('glacial spell scroll', 'gap_consumable_scroll_rare_5'),
  ('glacial twin band', 'gap_gear_ring_rare_11'),
  ('glaive', 'base-weapon-glaive'),
  ('government-issued id', 'bg-govt-id'),
  ('greataxe', 'base-weapon-greataxe'),
  ('greatclub', 'base-weapon-greatclub'),
  ('greater aetheric antidote', 'item_p6_39'),
  ('greater health potion', 'item_p9_37'),
  ('greater liquid shadow', 'item_p8_12'),
  ('greater mana elixir', 'item_p9_28'),
  ('greater stamina stim', 'item_p5_41'),
  ('greatsword', 'base-weapon-greatsword'),
  ('grimoire', 'base-focus-grimoire'),
  ('guild-issue dagger', 'item_p8_29'),
  ('guild-issue halberd', 'item_p9_39'),
  ('guild-issue katana', 'item_p7_17'),
  ('guild-issue longsword', 'item_p8_46'),
  ('guild-issue revolver', 'item_p9_26'),
  ('guild-issue spear', 'item_p6_1'),
  ('guild-issue warhammer', 'item_p6_35'),
  ('guild-issue whip', 'item_p3_16'),
  ('guild-reinforced tactical jacket', 'bg-fire-jacket'),
  ('guild-standard aetheric antidote', 'item_p7_40'),
  ('guild-standard beast repellent', 'item_p6_36'),
  ('guild-standard liquid shadow', 'item_p4_0'),
  ('guild-standard stamina stim', 'item_p9_15'),
  ('hacking tools', 'base-tool-hacking-tools'),
  ('halberd', 'base-weapon-halberd'),
  ('half plate', 'base-armor-half-plate'),
  ('halligan bar', 'bg-halligan-bar'),
  ('hand crossbow', 'base-weapon-hand-crossbow'),
  ('handaxe', 'base-weapon-handaxe'),
  ('hardened auto-crossbow', 'gap_ranged_crossbow_uncommon_1'),
  ('hardened axe', 'gap_melee_axe_uncommon_4'),
  ('hardened carapace armor', 'gap_armor_heavy_uncommon_1'),
  ('hardened casting baton', 'gap_focus_wand_uncommon_4'),
  ('hardened catalyst', 'gap_focus_caster_uncommon_5'),
  ('hardened conduit', 'gap_focus_caster_uncommon_4'),
  ('hardened field garb', 'gap_gear_attire_uncommon_6'),
  ('hardened holster', 'gap_gear_belt_uncommon_0'),
  ('hardened locket', 'gap_gear_amulet_uncommon_10'),
  ('hardened operator helm', 'gap_armor_headgear_uncommon_2'),
  ('hardened spotter lens', 'gap_gear_electronics_uncommon_4'),
  ('hardened stride boots', 'gap_gear_boots_uncommon_4'),
  ('heavy crossbow', 'base-weapon-heavy-crossbow'),
  ('heavy-duty multi-tool', 'bg-heavy-multitool'),
  ('hexbound belt', 'gap_gear_belt_rare_1'),
  ('hexbound bound ring', 'gap_gear_ring_rare_17'),
  ('hexbound breach kit', 'gap_gear_kit_rare_0'),
  ('hexbound composite bow', 'gap_ranged_bow_rare_0'),
  ('hexbound endurance serum', 'gap_consumable_stim_rare_2'),
  ('hexbound manacles', 'gap_gear_restraint_rare_0'),
  ('hexbound potion', 'gap_consumable_potion_rare_0'),
  ('hexbound sawed-off', 'gap_firearm_shotgun_rare_1'),
  ('hexbound spell scroll', 'gap_consumable_scroll_rare_2'),
  ('hexbound survey map', 'gap_gear_navigation_rare_1'),
  ('hexbound tread boots', 'gap_gear_boots_rare_4'),
  ('hide armor', 'base-armor-hide'),
  ('hierophant''s combat vest', 'gap_armor_light_epic_0'),
  ('hierophant''s scroll', 'gap_consumable_scroll_epic_4'),
  ('hierophant''s wristguard', 'gap_gear_bracer_epic_2'),
  ('high-end streaming laptop', 'base-tool-streaming-laptop'),
  ('high-grade aetheric antidote', 'item_p8_32'),
  ('high-grade beast repellent', 'item_p8_17'),
  ('high-grade health potion', 'item_p9_44'),
  ('high-grade liquid shadow', 'item_p9_23'),
  ('high-grade mana elixir', 'item_p3_41'),
  ('holy pump-action', 'gap_firearm_shotgun_epic_0'),
  ('hunter''s dagger', 'item_p8_15'),
  ('hunter''s halberd', 'item_p7_12'),
  ('hunter''s katana', 'item_p8_13'),
  ('hunter''s longsword', 'item_p4_42'),
  ('hunter''s sniper rifle', 'item_p9_18'),
  ('hunter''s spear', 'item_p7_10'),
  ('hunter''s warhammer', 'item_p8_34'),
  ('inferno boots', 'gap_gear_boots_epic_0'),
  ('inferno bound ring', 'gap_gear_ring_epic_2'),
  ('inferno cantrip scroll', 'gap_consumable_scroll_epic_7'),
  ('inferno kunai', 'gap_melee_blade_finesse_epic_1'),
  ('inferno loop', 'gap_gear_ring_epic_1'),
  ('inspector''s chain shirt', 'gap_armor_medium_common_3'),
  ('inspector''s composite bow', 'gap_ranged_bow_common_1'),
  ('inspector''s heavy crossbow', 'gap_ranged_crossbow_common_3'),
  ('inspector''s holster', 'gap_gear_belt_common_0'),
  ('inspector''s identification plate', 'gap_gear_credential_common_0'),
  ('inspector''s lantern', 'gap_gear_light_common_3'),
  ('inspector''s lattice pendant', 'gap_gear_amulet_common_5'),
  ('inspector''s locket', 'gap_gear_amulet_common_2'),
  ('inspector''s mail shirt', 'gap_armor_medium_common_2'),
  ('inspector''s patrol bracer', 'gap_gear_bracer_common_1'),
  ('inspector''s patrol shield', 'gap_armor_shield_common_2'),
  ('inspector''s pendant', 'gap_gear_amulet_common_7'),
  ('inspector''s rapier', 'gap_melee_blade_finesse_common_2'),
  ('inspector''s throwing stars', 'gap_ranged_thrown_common_1'),
  ('issue-standard crystal pendant', 'gap_gear_amulet_common_4'),
  ('issue-standard distress beacon', 'gap_consumable_signal_common_3'),
  ('issue-standard footwraps', 'gap_gear_boots_common_1'),
  ('issue-standard half-plate', 'gap_armor_medium_common_0'),
  ('issue-standard pike', 'gap_melee_polearm_common_1'),
  ('issue-standard reaping blade', 'gap_melee_sickle_common_0'),
  ('issue-standard tome', 'gap_focus_tome_common_2'),
  ('javelin', 'base-weapon-javelin'),
  ('kamish''s wrath', 'artifact_1'),
  ('lance', 'base-weapon-lance'),
  ('lattice-scale breastplate', 'item_p6_13'),
  ('lattice-scale combat vest', 'item_p9_36'),
  ('lattice-scale exo-suit', 'item_p8_33'),
  ('lattice-scale mail', 'lattice-scale-mail'),
  ('lattice-scale spaulders', 'item_p8_38'),
  ('lattice-scale tactical helmet', 'item_p9_45'),
  ('lattice-stable adrenal injector', 'gap_consumable_stim_uncommon_2'),
  ('lattice-stable bastard sword', 'gap_melee_blade_heavy_uncommon_7'),
  ('lattice-stable battle staff', 'gap_melee_staff_uncommon_1'),
  ('lattice-stable combat mail', 'gap_armor_medium_uncommon_7'),
  ('lattice-stable operator helm', 'gap_armor_headgear_uncommon_3'),
  ('lattice-stable pendant', 'gap_gear_amulet_uncommon_11'),
  ('lattice-stable recon sheet', 'gap_gear_navigation_uncommon_3'),
  ('lattice-stable robe', 'gap_gear_attire_uncommon_7'),
  ('lattice-stable stone ring', 'gap_gear_ring_uncommon_0'),
  ('lattice-stable suppressed pistol', 'gap_firearm_pistol_uncommon_2'),
  ('lattice-stable tactical boots', 'gap_gear_boots_uncommon_3'),
  ('lattice-stable ward scroll', 'gap_consumable_scroll_uncommon_7'),
  ('leather armor', 'base-armor-leather'),
  ('lesser aetheric antidote', 'item_p9_46'),
  ('lesser beast repellent', 'item_p7_16'),
  ('lesser health potion', 'item_p5_29'),
  ('lesser liquid shadow', 'item_p8_16'),
  ('lesser mana elixir', 'item_p6_33'),
  ('lesser stamina stim', 'item_p7_5'),
  ('light crossbow', 'base-weapon-light-crossbow'),
  ('light hammer', 'base-weapon-light-hammer'),
  ('lightning blade', 'lightning-blade'),
  ('lightseeker''s bow', 'gap_ranged_bow_rare_1'),
  ('lightseeker''s casting scroll', 'gap_consumable_scroll_rare_13'),
  ('lightseeker''s cloak', 'gap_gear_attire_rare_4'),
  ('lightseeker''s crystal pendant', 'gap_gear_amulet_rare_6'),
  ('lightseeker''s kunai', 'gap_melee_blade_finesse_rare_0'),
  ('lightseeker''s lattice scroll', 'gap_consumable_scroll_rare_15'),
  ('lightseeker''s potion', 'gap_consumable_potion_rare_2'),
  ('lightseeker''s ring', 'gap_gear_ring_rare_14'),
  ('lightseeker''s staff', 'gap_melee_staff_rare_2'),
  ('lightseeker''s throwing dagger', 'gap_melee_blade_finesse_rare_2'),
  ('longbow', 'base-weapon-longbow'),
  ('longsword', 'base-weapon-longsword'),
  ('lucky first-sale coin', 'bg-lucky-coin'),
  ('lunar battle scroll', 'gap_consumable_scroll_rare_11'),
  ('lunar cord charm', 'gap_gear_amulet_rare_13'),
  ('lunar footwraps', 'gap_gear_boots_rare_5'),
  ('lunar prism', 'gap_focus_caster_rare_4'),
  ('lunar repel rig', 'gap_gear_utility_rare_1'),
  ('lunar sealed inscription', 'gap_consumable_scroll_rare_10'),
  ('lunar twin band', 'gap_gear_ring_rare_10'),
  ('mace', 'base-weapon-mace'),
  ('mana-inert handcuffs', 'bg-mana-handcuffs'),
  ('mana-infused dagger', 'item_p9_0'),
  ('mana-infused halberd', 'item_p9_5'),
  ('mana-infused katana', 'item_p2_16'),
  ('mana-infused longsword', 'item_p3_24'),
  ('mana-infused sniper rifle', 'item_p3_35'),
  ('mana-infused spear', 'item_p9_34'),
  ('mana-infused warhammer', 'item_p3_6'),
  ('mana-infused whip', 'item_p8_2'),
  ('mana-treated band', 'gap_gear_ring_uncommon_3'),
  ('mana-treated battle gauntlets', 'gap_melee_gauntlet_uncommon_1'),
  ('mana-treated chain shirt', 'gap_armor_medium_uncommon_5'),
  ('mana-treated cord charm', 'gap_gear_amulet_uncommon_1'),
  ('mana-treated hammered band', 'gap_gear_ring_uncommon_16'),
  ('mana-treated lattice scroll', 'gap_consumable_scroll_uncommon_0'),
  ('mana-treated necklace', 'gap_gear_amulet_uncommon_5'),
  ('mana-treated operator belt', 'gap_gear_belt_uncommon_4'),
  ('mana-treated reaver sword', 'gap_melee_blade_heavy_uncommon_2'),
  ('mana-treated recurve crossbow', 'gap_ranged_crossbow_uncommon_4'),
  ('mana-treated regalia', 'gap_gear_attire_uncommon_3'),
  ('mana-treated rune ring', 'gap_gear_ring_uncommon_2'),
  ('mana-treated sealed ring', 'gap_gear_ring_uncommon_10'),
  ('mana-treated tome', 'gap_focus_tome_uncommon_3'),
  ('mana-treated truncheon', 'gap_melee_bludgeon_uncommon_1'),
  ('manaforged claymore', 'gap_melee_blade_heavy_rare_0'),
  ('manaforged field launcher', 'gap_firearm_launcher_rare_0'),
  ('manaforged manual', 'gap_focus_tome_rare_2'),
  ('manaforged sidearm', 'gap_firearm_pistol_rare_4'),
  ('manaforged talisman', 'gap_gear_amulet_rare_10'),
  ('manaforged telemetry device', 'gap_gear_electronics_rare_0'),
  ('maul', 'base-weapon-maul'),
  ('modern charge', 'gap_consumable_grenade_common_0'),
  ('modern conduit', 'gap_focus_caster_common_1'),
  ('modern crested ring', 'gap_gear_ring_common_1'),
  ('modern forearm plate', 'gap_gear_bracer_common_2'),
  ('modern gate atlas', 'gap_gear_navigation_common_2'),
  ('modern grenade launcher', 'gap_firearm_launcher_common_0'),
  ('modern lattice pendant', 'gap_gear_amulet_common_3'),
  ('modern mess kit', 'gap_gear_utility_common_9'),
  ('modern repeater', 'gap_ranged_crossbow_common_1'),
  ('modern sealed inscription', 'gap_consumable_scroll_common_1'),
  ('modern shield', 'gap_armor_shield_common_0'),
  ('modern sigil wand', 'gap_focus_wand_common_3'),
  ('modern ward scroll', 'gap_consumable_scroll_common_4'),
  ('modified security radio', 'bg-guild-radio'),
  ('morningstar', 'base-weapon-morningstar'),
  ('musical instrument', 'base-tool-instrument'),
  ('nano-weave bracers', 'item_p6_30'),
  ('nano-weave breastplate', 'item_p5_27'),
  ('nano-weave combat vest', 'item_p7_31'),
  ('nano-weave exo-suit', 'item_p2_17'),
  ('nano-weave shin guards', 'item_p9_21'),
  ('nano-weave spaulders', 'item_p5_33'),
  ('nano-weave tactical helmet', 'item_p7_42'),
  ('nano-weave trench coat', 'item_p7_22'),
  ('nebular battle scroll', 'gap_consumable_scroll_epic_9'),
  ('nebular casting scroll', 'gap_consumable_scroll_epic_5'),
  ('nebular holster', 'gap_gear_belt_epic_3'),
  ('nebular sigil bracer', 'gap_gear_bracer_epic_1'),
  ('nebular smoke charge', 'gap_consumable_grenade_epic_1'),
  ('nebular sprint boots', 'gap_gear_boots_epic_3'),
  ('nebular staff', 'gap_melee_staff_epic_1'),
  ('oathbound baton', 'gap_focus_wand_rare_7'),
  ('oathbound crested ring', 'gap_gear_ring_rare_16'),
  ('oathbound locket', 'gap_gear_amulet_rare_3'),
  ('oathbound longbow', 'gap_ranged_bow_rare_3'),
  ('oathbound tower shield', 'gap_armor_shield_rare_5'),
  ('obsidian dagger', 'item_p8_44'),
  ('obsidian gauntlets', 'item_p9_22'),
  ('obsidian halberd', 'item_p8_3'),
  ('obsidian longsword', 'item_p2_24'),
  ('obsidian revolver', 'item_p9_27'),
  ('obsidian sniper rifle', 'item_p8_45'),
  ('obsidian spear', 'item_p4_22'),
  ('obsidian whip', 'item_p3_28'),
  ('oil-stained coveralls', 'bg-oil-coveralls'),
  ('operative''s auto-rifle', 'gap_firearm_rifle_uncommon_0'),
  ('operative''s bo staff', 'gap_melee_staff_uncommon_5'),
  ('operative''s caster''s bead', 'gap_focus_caster_uncommon_2'),
  ('operative''s casting scroll', 'gap_consumable_scroll_uncommon_12'),
  ('operative''s combat vest', 'gap_armor_light_uncommon_2'),
  ('operative''s compact smg', 'gap_firearm_smg_uncommon_2'),
  ('operative''s falchion', 'gap_melee_blade_heavy_uncommon_4'),
  ('operative''s field axe', 'gap_melee_axe_uncommon_2'),
  ('operative''s field kit', 'gap_gear_kit_uncommon_2'),
  ('operative''s field knife', 'gap_melee_blade_finesse_uncommon_2'),
  ('operative''s kunai', 'gap_melee_blade_finesse_uncommon_1'),
  ('operative''s recall beacon', 'gap_consumable_signal_uncommon_1'),
  ('operative''s reflex bow', 'gap_ranged_bow_uncommon_1'),
  ('operative''s rod', 'gap_focus_wand_uncommon_2'),
  ('operative''s triage kit', 'gap_gear_kit_uncommon_0'),
  ('operative''s zweihander', 'gap_melee_blade_heavy_uncommon_0'),
  ('order focus', 'base-focus-system'),
  ('origin aegis', 'artifact_11'),
  ('origin edge', 'artifact_13'),
  ('origin reliquary', 'artifact_6'),
  ('origin-crowned carbine', 'gap_firearm_rifle_legendary_0'),
  ('origin-crowned draught', 'gap_consumable_potion_legendary_0'),
  ('origin-crowned focus', 'gap_focus_caster_legendary_0'),
  ('origin-crowned necklace', 'gap_gear_amulet_legendary_3'),
  ('origin-crowned tome', 'gap_focus_tome_legendary_0'),
  ('origin-crowned tower shield', 'gap_armor_shield_legendary_0'),
  ('padded armor', 'base-armor-padded'),
  ('patrol casting baton', 'gap_focus_wand_common_2'),
  ('patrol casting scroll', 'gap_consumable_scroll_common_2'),
  ('patrol chart', 'gap_gear_navigation_common_1'),
  ('patrol field garb', 'gap_gear_attire_common_4'),
  ('patrol gate atlas', 'gap_gear_navigation_common_0'),
  ('patrol hood', 'gap_gear_attire_common_5'),
  ('patrol injector', 'gap_consumable_stim_common_1'),
  ('patrol loop', 'gap_gear_ring_common_6'),
  ('patrol mantle', 'gap_gear_attire_common_3'),
  ('patrol patrol boots', 'gap_gear_boots_common_0'),
  ('patrol payload', 'gap_consumable_grenade_common_4'),
  ('patrol piton set', 'gap_gear_utility_common_2'),
  ('patrol rapier', 'gap_melee_blade_finesse_common_1'),
  ('patrol reinforced plate', 'gap_armor_heavy_common_1'),
  ('patrol robe', 'gap_gear_attire_common_2'),
  ('patrol two-hander', 'gap_melee_blade_heavy_common_0'),
  ('phantom battle gauntlets', 'gap_melee_gauntlet_rare_1'),
  ('phantom battle strap', 'gap_gear_belt_rare_4'),
  ('phantom breach charge', 'gap_consumable_grenade_rare_0'),
  ('phantom breastplate', 'item_p8_31'),
  ('phantom casting scroll', 'gap_consumable_scroll_rare_4'),
  ('phantom combat vest', 'item_p7_7'),
  ('phantom crested ring', 'gap_gear_ring_rare_8'),
  ('phantom hammered band', 'gap_gear_ring_rare_13'),
  ('phantom maul', 'gap_melee_bludgeon_heavy_rare_2'),
  ('phantom pager', 'bg-phantom-pager'),
  ('phantom rune ring', 'gap_gear_ring_rare_12'),
  ('phantom shin guards', 'item_p4_30'),
  ('phantom spaulders', 'item_p4_46'),
  ('phantom tactical helmet', 'item_p7_32'),
  ('phantom wakizashi', 'gap_melee_blade_versatile_rare_0'),
  ('pike', 'base-weapon-pike'),
  ('plate armor', 'base-armor-plate'),
  ('portable camera', 'base-tool-portable-camera'),
  ('portable wi-fi hotspot', 'base-tool-wifi-hotspot'),
  ('priest''s pack', 'base-gear-priests-pack'),
  ('primal focus', 'base-focus-primal'),
  ('provisional credential', 'gap_gear_credential_common_1'),
  ('provisional distress beacon', 'gap_consumable_signal_common_4'),
  ('provisional elixir', 'gap_consumable_potion_common_2'),
  ('provisional field bow', 'gap_ranged_bow_common_2'),
  ('provisional inset ring', 'gap_gear_ring_common_2'),
  ('provisional lattice toolkit', 'gap_gear_kit_common_2'),
  ('provisional mana cuffs', 'gap_gear_restraint_common_0'),
  ('provisional mre', 'gap_consumable_ration_common_2'),
  ('provisional ration', 'gap_consumable_ration_common_4'),
  ('provisional sprint boots', 'gap_gear_boots_common_4'),
  ('provisional stim bar', 'gap_consumable_ration_common_0'),
  ('provisional throwing stars', 'gap_ranged_thrown_common_0'),
  ('provisional ward scroll', 'gap_consumable_scroll_common_7'),
  ('purified aetheric antidote', 'item_p9_17'),
  ('purified beast repellent', 'item_p8_8'),
  ('purified health potion', 'item_p8_47'),
  ('purified mana elixir', 'item_p8_49'),
  ('purified stamina stim', 'item_p5_6'),
  ('quartermaster''s battle blade', 'gap_melee_blade_versatile_common_2'),
  ('quartermaster''s cleanser', 'gap_consumable_purifier_common_1'),
  ('quartermaster''s darts', 'gap_ranged_thrown_common_4'),
  ('quartermaster''s draught', 'gap_consumable_potion_common_1'),
  ('quartermaster''s gauntlets', 'gap_melee_gauntlet_common_0'),
  ('quartermaster''s kusarigama', 'gap_melee_whip_common_0'),
  ('quartermaster''s potion', 'gap_consumable_potion_common_0'),
  ('quartermaster''s purifier', 'gap_consumable_purifier_common_0'),
  ('quartermaster''s wakizashi', 'gap_melee_blade_versatile_common_0'),
  ('quarterstaff', 'base-weapon-quarterstaff'),
  ('rapier', 'base-weapon-rapier'),
  ('reclaimed field garb', 'gap_gear_attire_uncommon_5'),
  ('reclaimed field plate', 'gap_armor_heavy_uncommon_0'),
  ('reclaimed frag charge', 'gap_consumable_grenade_uncommon_1'),
  ('reclaimed hand mirror', 'gap_gear_utility_uncommon_0'),
  ('reclaimed id chip', 'gap_gear_credential_uncommon_1'),
  ('reclaimed knuckles', 'gap_melee_gauntlet_uncommon_0'),
  ('reclaimed layout plate', 'gap_gear_navigation_uncommon_2'),
  ('reclaimed magnum', 'gap_firearm_pistol_uncommon_5'),
  ('reclaimed pendant', 'gap_gear_amulet_uncommon_4'),
  ('reclaimed scattergun', 'gap_firearm_shotgun_uncommon_2'),
  ('reclaimed sceptre', 'gap_focus_wand_uncommon_6'),
  ('reclaimed service rifle', 'gap_firearm_rifle_uncommon_4'),
  ('reclaimed zweihander', 'gap_melee_blade_heavy_uncommon_3'),
  ('recruit''s axe', 'gap_melee_axe_common_0'),
  ('recruit''s bullseye lantern', 'gap_gear_light_common_0'),
  ('recruit''s diagnostic tool', 'gap_gear_electronics_common_4'),
  ('recruit''s forensic kit', 'gap_gear_kit_common_4'),
  ('recruit''s reach spear', 'gap_melee_polearm_common_0'),
  ('recruit''s reach staff', 'gap_melee_staff_common_0'),
  ('recruit''s reinforced robe', 'gap_armor_light_common_0'),
  ('recruit''s service boots', 'gap_gear_boots_common_5'),
  ('red grading pen', 'bg-red-pen'),
  ('refit battle staff', 'gap_melee_staff_uncommon_2'),
  ('refit bedroll', 'gap_gear_utility_uncommon_2'),
  ('refit draught', 'gap_consumable_potion_uncommon_1'),
  ('refit footwraps', 'gap_gear_boots_uncommon_8'),
  ('refit forearm plate', 'gap_gear_bracer_uncommon_1'),
  ('refit hardened bracer', 'gap_gear_bracer_uncommon_4'),
  ('refit hood', 'gap_gear_attire_uncommon_8'),
  ('refit mantle', 'gap_gear_attire_uncommon_1'),
  ('refit pdw', 'gap_firearm_smg_uncommon_3'),
  ('refit reach spear', 'gap_melee_polearm_uncommon_2'),
  ('refit schematic', 'gap_gear_navigation_uncommon_1'),
  ('refit war blade', 'gap_melee_blade_heavy_uncommon_6'),
  ('reflective delivery uniform', 'bg-delivery-uniform'),
  ('regent of dread''s longsword', 'artifact_2'),
  ('regent-slayer''s scroll', 'gap_consumable_scroll_legendary_0'),
  ('regent-slayer''s stone charm', 'gap_gear_amulet_legendary_1'),
  ('regent''s combat knife', 'gap_melee_blade_finesse_legendary_0'),
  ('regent''s combat sash', 'gap_gear_belt_legendary_1'),
  ('regent''s edge', 'artifact_18'),
  ('regent''s shadow dagger', 'regents-shadow-dagger'),
  ('regent''s two-hander', 'gap_melee_blade_heavy_legendary_0'),
  ('reinforced authentication token', 'gap_gear_credential_common_2'),
  ('reinforced battle strap', 'gap_gear_belt_common_2'),
  ('reinforced combat helm', 'gap_armor_headgear_common_1'),
  ('reinforced crowbar', 'gap_gear_utility_common_13'),
  ('reinforced hammer', 'gap_gear_utility_common_8'),
  ('reinforced rune ring', 'gap_gear_ring_common_7'),
  ('reinforced safety vest', 'bg-safety-vest'),
  ('reinforced sawed-off', 'gap_firearm_shotgun_common_0'),
  ('reinforced security uniform', 'bg-security-uniform'),
  ('reinforced tether', 'gap_gear_utility_common_1'),
  ('reinforced tower shield', 'gap_armor_shield_common_1'),
  ('reinforced twin band', 'gap_gear_ring_common_3'),
  ('reissue combat shield', 'gap_armor_shield_uncommon_2'),
  ('reissue combat shotgun', 'gap_firearm_shotgun_uncommon_4'),
  ('reissue kama', 'gap_melee_sickle_uncommon_2'),
  ('reissue mana-weave jacket', 'gap_armor_light_uncommon_3'),
  ('reissue pendant', 'gap_gear_amulet_uncommon_7'),
  ('reissue scroll', 'gap_consumable_scroll_uncommon_2'),
  ('reissue service brigandine', 'gap_armor_medium_uncommon_6'),
  ('reissue smg', 'gap_firearm_smg_uncommon_0'),
  ('reissue spear', 'gap_melee_polearm_uncommon_0'),
  ('reissue tomahawk', 'gap_melee_axe_uncommon_0'),
  ('reissue vanguard plate', 'gap_armor_heavy_uncommon_2'),
  ('renegade antidote', 'gap_consumable_purifier_uncommon_1'),
  ('renegade beacon light', 'gap_gear_light_uncommon_2'),
  ('renegade breach charge', 'gap_consumable_grenade_uncommon_4'),
  ('renegade broadsword', 'gap_melee_blade_versatile_uncommon_2'),
  ('renegade forearm plate', 'gap_gear_bracer_uncommon_5'),
  ('renegade greatcoat', 'gap_gear_attire_uncommon_4'),
  ('renegade javelins', 'gap_ranged_thrown_uncommon_1'),
  ('renegade magnum', 'gap_firearm_pistol_uncommon_4'),
  ('renegade mana manual', 'gap_focus_tome_uncommon_0'),
  ('renegade marching boots', 'gap_gear_boots_uncommon_7'),
  ('renegade necklace', 'gap_gear_amulet_uncommon_0'),
  ('renegade patrol shield', 'gap_armor_shield_uncommon_5'),
  ('renegade reaping blade', 'gap_melee_sickle_uncommon_1'),
  ('renegade recon sheet', 'gap_gear_navigation_uncommon_0'),
  ('renegade rocket launcher', 'gap_firearm_launcher_uncommon_2'),
  ('renegade survival kit', 'gap_gear_kit_uncommon_1'),
  ('renegade webbing', 'gap_gear_belt_uncommon_5'),
  ('resonant band', 'gap_gear_ring_epic_3'),
  ('resonant buckled belt', 'gap_gear_belt_epic_1'),
  ('resonant codex', 'gap_focus_tome_epic_0'),
  ('resonant comm set', 'gap_gear_electronics_epic_0'),
  ('resonant scroll', 'gap_consumable_scroll_epic_3'),
  ('riftbound auto-shotgun', 'gap_firearm_shotgun_rare_2'),
  ('riftbound greataxe', 'gap_melee_axe_rare_0'),
  ('riftbound hooded lantern', 'gap_gear_light_rare_1'),
  ('riftbound inscribed manual', 'gap_focus_tome_rare_3'),
  ('riftbound layout plate', 'gap_gear_navigation_rare_0'),
  ('riftbound orb', 'gap_focus_caster_rare_3'),
  ('riftbound patrol boots', 'gap_gear_boots_rare_7'),
  ('riftbound sigil scroll', 'gap_consumable_scroll_rare_8'),
  ('riftforged field crossbow', 'gap_ranged_crossbow_rare_1'),
  ('riftforged flask', 'gap_consumable_potion_rare_5'),
  ('riftforged longsword', 'gap_melee_blade_versatile_rare_1'),
  ('riftforged scale mail', 'gap_armor_medium_rare_0'),
  ('riftforged service robe', 'gap_armor_light_rare_1'),
  ('riftforged tactical boots', 'gap_gear_boots_rare_1'),
  ('ring light', 'base-tool-ring-light'),
  ('ring mail', 'base-armor-ring-mail'),
  ('rune-modified wrench set', 'bg-rune-wrenches'),
  ('salvaged auto-crossbow', 'gap_ranged_crossbow_uncommon_5'),
  ('salvaged battle hammer', 'gap_melee_bludgeon_heavy_uncommon_2'),
  ('salvaged buckled belt', 'gap_gear_belt_uncommon_2'),
  ('salvaged cleanser', 'gap_consumable_purifier_uncommon_0'),
  ('salvaged combat injector', 'gap_consumable_stim_uncommon_3'),
  ('salvaged concussion grenade', 'gap_consumable_grenade_uncommon_3'),
  ('salvaged flail', 'gap_melee_bludgeon_uncommon_3'),
  ('salvaged grenade', 'gap_consumable_grenade_uncommon_0'),
  ('salvaged hammered band', 'gap_gear_ring_uncommon_9'),
  ('salvaged katana', 'gap_melee_blade_versatile_uncommon_0'),
  ('salvaged mana locket', 'gap_gear_amulet_uncommon_8'),
  ('salvaged rod', 'gap_focus_wand_uncommon_1'),
  ('salvaged service coin', 'gap_gear_misc_uncommon_0'),
  ('salvaged snub-frame', 'gap_firearm_pistol_uncommon_1'),
  ('sanctified battle plate', 'gap_armor_heavy_epic_1'),
  ('sanctified dagger', 'gap_melee_blade_finesse_epic_0'),
  ('sanctified flask', 'gap_consumable_potion_epic_1'),
  ('sanctified grenade launcher', 'gap_firearm_launcher_epic_0'),
  ('sanctified katana', 'gap_melee_blade_versatile_epic_1'),
  ('sanctified locket', 'gap_gear_amulet_epic_2'),
  ('sanctioned bo staff', 'gap_melee_staff_uncommon_0'),
  ('sanctioned casting scroll', 'gap_consumable_scroll_uncommon_16'),
  ('sanctioned combat boots', 'gap_gear_boots_uncommon_1'),
  ('sanctioned compact smg', 'gap_firearm_smg_uncommon_1'),
  ('sanctioned concussion grenade', 'gap_consumable_grenade_uncommon_6'),
  ('sanctioned crossbow', 'gap_ranged_crossbow_uncommon_3'),
  ('sanctioned grimoire', 'gap_focus_tome_uncommon_5'),
  ('sanctioned hammer', 'gap_gear_utility_uncommon_5'),
  ('sanctioned inset ring', 'gap_gear_ring_uncommon_14'),
  ('sanctioned operator helm', 'gap_armor_headgear_uncommon_4'),
  ('sanctioned recovery pack', 'gap_consumable_ration_uncommon_1'),
  ('sanctioned reflex bow', 'gap_ranged_bow_uncommon_3'),
  ('sanctioned regalia', 'gap_gear_attire_uncommon_9'),
  ('sanctioned sash', 'gap_gear_belt_uncommon_7'),
  ('sanctioned service brigandine', 'gap_armor_medium_uncommon_0'),
  ('sanctioned shortbow', 'gap_ranged_bow_uncommon_5'),
  ('sanctioned tactical sash', 'gap_gear_belt_uncommon_1'),
  ('sanguine bomb', 'gap_consumable_grenade_rare_2'),
  ('sanguine combat mail', 'gap_armor_medium_rare_2'),
  ('sanguine compound bow', 'gap_ranged_bow_rare_4'),
  ('sanguine crested ring', 'gap_gear_ring_rare_3'),
  ('sanguine field garb', 'gap_gear_attire_rare_7'),
  ('sanguine reinforced mask', 'gap_armor_headgear_rare_3'),
  ('sanguine service rifle', 'gap_firearm_rifle_rare_2'),
  ('sanguine sigil amulet', 'gap_gear_amulet_rare_2'),
  ('sanguine signal beacon', 'gap_consumable_signal_rare_0'),
  ('sanguine twin sickles', 'gap_melee_sickle_rare_0'),
  ('scale mail', 'base-armor-scale-mail'),
  ('scholar''s pack', 'base-gear-scholars-pack'),
  ('scimitar', 'base-weapon-scimitar'),
  ('service belt', 'gap_gear_belt_common_4'),
  ('service club', 'gap_melee_bludgeon_common_2'),
  ('service magnum', 'gap_firearm_pistol_common_3'),
  ('service mana crystal', 'gap_focus_caster_common_3'),
  ('service manacles', 'gap_gear_restraint_common_1'),
  ('service purifier', 'gap_consumable_purifier_common_3'),
  ('service quartermaster''s token', 'gap_gear_misc_common_3'),
  ('service war blade', 'gap_melee_blade_heavy_common_3'),
  ('service-grade bludgeon', 'gap_melee_bludgeon_heavy_common_0'),
  ('service-grade conduit', 'gap_focus_caster_common_2'),
  ('service-grade gate atlas', 'gap_gear_navigation_common_4'),
  ('service-grade marching boots', 'gap_gear_boots_common_3'),
  ('service-grade ration', 'gap_consumable_ration_common_1'),
  ('service-grade sash', 'gap_gear_belt_common_1'),
  ('service-grade scattergun', 'gap_firearm_shotgun_common_2'),
  ('service-grade smg', 'gap_firearm_smg_common_3'),
  ('service-grade tracking kit', 'gap_gear_kit_common_1'),
  ('service-grade ward scroll', 'gap_consumable_scroll_common_6'),
  ('service-grade wristguard', 'gap_gear_bracer_common_0'),
  ('shadow bound ring', 'gap_gear_ring_rare_2'),
  ('shadow bracers', 'item_p6_40'),
  ('shadow combat injector', 'gap_consumable_stim_rare_0'),
  ('shadow combat vest', 'item_p9_49'),
  ('shadow elixir', 'shadow-elixir'),
  ('shadow exo-suit', 'item_p9_20'),
  ('shadow lens', 'shadow-lens'),
  ('shadow necklace', 'gap_gear_amulet_rare_12'),
  ('shadow orb', 'shadow-orb'),
  ('shadow regent''s mantle', 'artifact_3'),
  ('shadow reinforced robe', 'gap_armor_light_rare_2'),
  ('shadow robe', 'gap_gear_attire_rare_3'),
  ('shadow rod', 'gap_focus_wand_rare_1'),
  ('shadow shin guards', 'item_p7_29'),
  ('shadow sigil bracer', 'gap_gear_bracer_rare_0'),
  ('shadow spaulders', 'item_p9_9'),
  ('shadow tactical helmet', 'item_p9_19'),
  ('shattered dagger', 'item_p5_16'),
  ('shattered gauntlets', 'item_p6_19'),
  ('shattered halberd', 'item_p5_32'),
  ('shattered katana', 'item_p7_26'),
  ('shattered longsword', 'item_p5_28'),
  ('shattered sniper rifle', 'item_p6_23'),
  ('shattered spear', 'item_p8_37'),
  ('shattered warhammer', 'item_p8_36'),
  ('shield', 'base-armor-shield'),
  ('shortbow', 'base-weapon-shortbow'),
  ('shortsword', 'base-weapon-shortsword'),
  ('sickle', 'base-weapon-sickle'),
  ('singular boots', 'gap_gear_boots_legendary_1'),
  ('singular combat pistol', 'gap_firearm_pistol_legendary_0'),
  ('singular reinforced plate', 'gap_armor_heavy_legendary_0'),
  ('singularity axe', 'gap_melee_axe_epic_0'),
  ('singularity falchion', 'gap_melee_blade_heavy_epic_0'),
  ('singularity patrol boots', 'gap_gear_boots_epic_1'),
  ('singularity signet', 'gap_gear_ring_epic_9'),
  ('singularity zweihander', 'gap_melee_blade_heavy_epic_1'),
  ('skyveil bo staff', 'gap_melee_staff_rare_3'),
  ('skyveil breaching shotgun', 'gap_firearm_shotgun_rare_0'),
  ('skyveil casting scroll', 'gap_consumable_scroll_rare_6'),
  ('skyveil cinch belt', 'gap_gear_belt_rare_3'),
  ('skyveil crystal pendant', 'gap_gear_amulet_rare_7'),
  ('skyveil hand axe', 'gap_melee_axe_rare_4'),
  ('skyveil holdout pistol', 'gap_firearm_pistol_rare_1'),
  ('skyveil mana mine', 'gap_consumable_grenade_rare_1'),
  ('skyveil reach spear', 'gap_melee_polearm_rare_0'),
  ('skyveil reference codex', 'gap_focus_tome_rare_4'),
  ('skyveil robe', 'gap_gear_attire_rare_0'),
  ('skyveil sealed inscription', 'gap_consumable_scroll_rare_3'),
  ('skyveil throwing stars', 'gap_ranged_thrown_rare_0'),
  ('skywyrm''s gauntlet', 'skywyrms-gauntlet'),
  ('sling', 'base-weapon-sling'),
  ('smartphone (high-end camera)', 'base-tool-smartphone-camera'),
  ('sovereign aegis', 'artifact_15'),
  ('sovereign crown', 'artifact_19'),
  ('sovereign edge', 'artifact_5'),
  ('sovereign reliquary', 'artifact_8'),
  ('spear', 'base-weapon-spear'),
  ('specialist''s auto-crossbow', 'gap_ranged_crossbow_uncommon_2'),
  ('specialist''s combat injector', 'gap_consumable_stim_uncommon_4'),
  ('specialist''s cord whip', 'gap_melee_whip_uncommon_1'),
  ('specialist''s dagger', 'gap_melee_blade_finesse_uncommon_0'),
  ('specialist''s elixir', 'gap_consumable_potion_uncommon_2'),
  ('specialist''s endurance serum', 'gap_consumable_stim_uncommon_5'),
  ('specialist''s field cowl', 'gap_armor_headgear_uncommon_1'),
  ('specialist''s lattice bomb', 'gap_consumable_grenade_uncommon_7'),
  ('specialist''s recorder', 'gap_gear_electronics_uncommon_1'),
  ('specialist''s scroll', 'gap_consumable_scroll_uncommon_11'),
  ('specialist''s spotter lens', 'gap_gear_electronics_uncommon_0'),
  ('specialist''s stone ring', 'gap_gear_ring_uncommon_7'),
  ('specialist''s tactical light', 'gap_gear_light_uncommon_0'),
  ('splint armor', 'base-armor-splint'),
  ('standard battle staff', 'gap_melee_staff_common_2'),
  ('standard bomb', 'gap_consumable_grenade_common_3'),
  ('standard combat bow', 'gap_ranged_bow_common_0'),
  ('standard heavy crossbow', 'gap_ranged_crossbow_common_0'),
  ('standard kite shield', 'gap_armor_shield_common_3'),
  ('standard reach staff', 'gap_melee_staff_common_3'),
  ('standard recall beacon', 'gap_consumable_signal_common_0'),
  ('standard rifle', 'gap_firearm_rifle_common_0'),
  ('standard sidearm', 'gap_firearm_pistol_common_2'),
  ('standard suppressed pistol', 'gap_firearm_pistol_common_1'),
  ('standard tome', 'gap_focus_tome_common_0'),
  ('standard-pattern binders', 'gap_gear_restraint_common_2'),
  ('standard-pattern bo staff', 'gap_melee_staff_common_1'),
  ('standard-pattern casting scroll', 'gap_consumable_scroll_common_3'),
  ('standard-pattern cloak', 'gap_gear_attire_common_0'),
  ('standard-pattern codex', 'gap_focus_tome_common_3'),
  ('standard-pattern marksman rifle', 'gap_firearm_rifle_common_3'),
  ('standard-pattern quartermaster''s token', 'gap_gear_misc_common_0'),
  ('standard-pattern recorder', 'gap_gear_electronics_common_3'),
  ('standard-pattern regalia', 'gap_gear_attire_common_1'),
  ('standard-pattern service boots', 'gap_gear_boots_common_2'),
  ('standard-pattern shotgun', 'gap_firearm_shotgun_common_1'),
  ('standard-pattern survey map', 'gap_gear_navigation_common_5'),
  ('stargazer''s cinch belt', 'gap_gear_belt_rare_0'),
  ('stargazer''s operator''s coat', 'gap_gear_attire_rare_9'),
  ('stargazer''s scroll', 'gap_consumable_scroll_rare_12'),
  ('stargazer''s submachine gun', 'gap_firearm_smg_rare_1'),
  ('stargazer''s truncheon', 'gap_melee_bludgeon_rare_3'),
  ('starlight casting baton', 'gap_focus_wand_epic_1'),
  ('starlight dagger', 'item_p3_0'),
  ('starlight gauntlets', 'item_p9_16'),
  ('starlight halberd', 'item_p6_44'),
  ('starlight longbow', 'gap_ranged_bow_epic_1'),
  ('starlight longsword', 'item_p5_49'),
  ('starlight marksman rifle', 'gap_firearm_rifle_epic_0'),
  ('starlight revolver', 'item_p4_48'),
  ('starlight sniper rifle', 'item_p3_23'),
  ('starlight spear', 'item_p6_4'),
  ('starlight talisman', 'gap_gear_amulet_epic_0'),
  ('starlight warhammer', 'item_p9_48'),
  ('stormcaller inset ring', 'gap_gear_ring_rare_15'),
  ('stormcaller layered mail', 'gap_armor_medium_rare_1'),
  ('stormcaller pendant', 'gap_gear_amulet_rare_0'),
  ('stormcaller potion', 'gap_consumable_potion_rare_3'),
  ('stormcaller rune scroll', 'gap_consumable_scroll_rare_9'),
  ('studded leather armor', 'base-armor-studded-leather'),
  ('sworn ankle cuffs', 'gap_gear_restraint_uncommon_0'),
  ('sworn auto-rifle', 'gap_firearm_rifle_uncommon_1'),
  ('sworn band', 'gap_gear_ring_uncommon_1'),
  ('sworn draught', 'gap_consumable_potion_uncommon_4'),
  ('sworn field axe', 'gap_melee_axe_uncommon_5'),
  ('sworn locket', 'gap_gear_amulet_uncommon_12'),
  ('sworn operator''s coat', 'gap_gear_attire_uncommon_11'),
  ('sworn reinforced mask', 'gap_armor_headgear_uncommon_0'),
  ('sworn ring', 'gap_gear_ring_uncommon_12'),
  ('sworn rocket launcher', 'gap_firearm_launcher_uncommon_0'),
  ('sworn sealed inscription', 'gap_consumable_scroll_uncommon_5'),
  ('sworn sigil bracer', 'gap_gear_bracer_uncommon_2'),
  ('sworn sigil scroll', 'gap_consumable_scroll_uncommon_14'),
  ('sworn spellbook', 'gap_focus_tome_uncommon_4'),
  ('tactical crystal pendant', 'gap_gear_amulet_common_0'),
  ('tactical cudgel', 'gap_melee_bludgeon_common_0'),
  ('tactical flashlight baton', 'bg-tactical-flashlight'),
  ('tactical kusarigama', 'gap_melee_whip_common_1'),
  ('tactical lattice scroll', 'gap_consumable_scroll_common_8'),
  ('tactical mana mine', 'gap_consumable_grenade_common_2'),
  ('tactical sealed inscription', 'gap_consumable_scroll_common_0'),
  ('tactical sledge', 'gap_melee_bludgeon_heavy_common_1'),
  ('tactical war axe', 'gap_melee_axe_common_1'),
  ('teacher''s leather satchel', 'bg-teacher-satchel'),
  ('tempered bound ring', 'gap_gear_ring_rare_7'),
  ('tempered bracer', 'gap_gear_bracer_rare_5'),
  ('tempered combat bracer', 'gap_gear_bracer_rare_2'),
  ('tempered hammered band', 'gap_gear_ring_rare_0'),
  ('tempered lattice pendant', 'gap_gear_amulet_rare_9'),
  ('tempered lattice scroll', 'gap_consumable_scroll_rare_0'),
  ('tempered mantle', 'gap_gear_attire_rare_1'),
  ('tempered rune scroll', 'gap_consumable_scroll_rare_7'),
  ('tempered sealed inscription', 'gap_consumable_scroll_rare_17'),
  ('tempered tactical visor', 'gap_armor_headgear_rare_0'),
  ('tempest baton', 'gap_focus_wand_epic_3'),
  ('tempest bulwark plate', 'gap_armor_heavy_epic_0'),
  ('tempest hood', 'gap_gear_attire_epic_4'),
  ('tempest kama', 'gap_melee_sickle_epic_0'),
  ('tempest mail shirt', 'gap_armor_medium_epic_2'),
  ('tempest mana locket', 'gap_gear_amulet_epic_5'),
  ('tempest syringe', 'gap_consumable_stim_epic_0'),
  ('thieves'' tools', 'base-tool-thieves'),
  ('time turner', 'time-turner'),
  ('tinker''s tools', 'base-tool-tinker'),
  ('titanium bracers', 'item_p8_35'),
  ('titanium breastplate', 'item_p9_43'),
  ('titanium combat vest', 'item_p3_21'),
  ('titanium spaulders', 'item_p3_27'),
  ('titanium tactical helmet', 'item_p9_33'),
  ('titanium trench coat', 'item_p8_9'),
  ('toxic band', 'gap_gear_ring_rare_1'),
  ('toxic charge', 'gap_consumable_grenade_rare_4'),
  ('toxic combat helm', 'gap_armor_headgear_rare_1'),
  ('toxic combat knife', 'gap_melee_blade_finesse_rare_1'),
  ('toxic crusher', 'gap_melee_bludgeon_heavy_rare_0'),
  ('toxic detonator', 'gap_consumable_grenade_rare_3'),
  ('toxic dose', 'gap_consumable_stim_rare_1'),
  ('toxic field greaves', 'gap_gear_boots_rare_3'),
  ('toxic inscription', 'gap_consumable_scroll_rare_16'),
  ('toxic war axe', 'gap_melee_axe_rare_3'),
  ('trainee casting codex', 'gap_focus_tome_common_1'),
  ('trainee grenade launcher', 'gap_firearm_launcher_common_1'),
  ('trainee hardened bracer', 'gap_gear_bracer_common_3'),
  ('trainee lattice scroll', 'gap_consumable_scroll_common_9'),
  ('trainee mana sensor', 'gap_gear_electronics_common_0'),
  ('trainee marker', 'gap_gear_misc_common_4'),
  ('trainee marksman rifle', 'gap_firearm_rifle_common_2'),
  ('trainee operator helm', 'gap_armor_headgear_common_0'),
  ('trainee restorative vial', 'gap_consumable_purifier_common_2'),
  ('trainee rune ring', 'gap_gear_ring_common_0'),
  ('trainee scale mail', 'gap_armor_medium_common_1'),
  ('trainee tomahawk', 'gap_melee_axe_common_2'),
  ('trident', 'base-weapon-trident'),
  ('umbral band', 'gap_gear_ring_rare_4'),
  ('umbral baton', 'gap_focus_wand_rare_6'),
  ('umbral casting baton', 'gap_focus_wand_rare_2'),
  ('umbral cleanser', 'gap_consumable_purifier_rare_0'),
  ('umbral combat belt', 'gap_gear_belt_rare_7'),
  ('umbral grenade launcher', 'gap_firearm_launcher_rare_1'),
  ('umbral hardened bracer', 'gap_gear_bracer_rare_3'),
  ('umbral kite shield', 'gap_armor_shield_rare_1'),
  ('umbral mana wand', 'gap_focus_wand_rare_5'),
  ('umbral mantle', 'gap_gear_attire_rare_2'),
  ('umbral operator belt', 'gap_gear_belt_rare_5'),
  ('umbral patrol shield', 'gap_armor_shield_rare_4'),
  ('umbral rifle', 'gap_firearm_rifle_rare_0'),
  ('umbral robe', 'gap_gear_attire_rare_6'),
  ('umbral smoke charge', 'gap_consumable_grenade_rare_5'),
  ('umbral spear', 'gap_melee_polearm_rare_2'),
  ('umbral wand', 'gap_focus_wand_rare_0'),
  ('unstable aetheric antidote', 'item_p8_26'),
  ('unstable beast repellent', 'item_p5_38'),
  ('unstable health potion', 'item_p8_6'),
  ('unstable liquid shadow', 'item_p5_2'),
  ('unstable mana elixir', 'item_p8_48'),
  ('usb drive collection', 'base-tool-usb-drives'),
  ('vanguard bracers', 'item_p7_8'),
  ('vanguard breastplate', 'item_p7_48'),
  ('vanguard exo-suit', 'item_p5_26'),
  ('vanguard shin guards', 'item_p9_10'),
  ('vanguard tactical helmet', 'item_p6_34'),
  ('veteran brigandine', 'gap_armor_medium_uncommon_4'),
  ('veteran bureau marker', 'gap_gear_misc_uncommon_1'),
  ('veteran claws', 'gap_melee_gauntlet_uncommon_2'),
  ('veteran conductor', 'gap_focus_wand_uncommon_0'),
  ('veteran field crossbow', 'gap_ranged_crossbow_uncommon_0'),
  ('veteran hand drill', 'gap_gear_utility_uncommon_1'),
  ('veteran locator', 'gap_consumable_signal_uncommon_0'),
  ('veteran marksman rifle', 'gap_firearm_rifle_uncommon_5'),
  ('veteran reflex bow', 'gap_ranged_bow_uncommon_0'),
  ('veteran rocket launcher', 'gap_firearm_launcher_uncommon_1'),
  ('veteran rune scroll', 'gap_consumable_scroll_uncommon_3'),
  ('veteran service boots', 'gap_gear_boots_uncommon_2'),
  ('veteran signet', 'gap_gear_ring_uncommon_6'),
  ('veteran tread boots', 'gap_gear_boots_uncommon_0'),
  ('void gauntlets', 'item_p9_35'),
  ('void halberd', 'item_p8_41'),
  ('void katana', 'item_p6_25'),
  ('void longsword', 'item_p2_12'),
  ('void revolver', 'item_p7_0'),
  ('void sniper rifle', 'item_p7_30'),
  ('void spear', 'item_p7_38'),
  ('void warhammer', 'item_p9_4'),
  ('void whip', 'item_p8_39'),
  ('voidtouched beacon light', 'gap_gear_light_rare_0'),
  ('voidtouched combat belt', 'gap_gear_belt_rare_2'),
  ('voidtouched greatmaul', 'gap_melee_bludgeon_heavy_rare_1'),
  ('voidtouched half-plate', 'gap_armor_medium_rare_5'),
  ('voidtouched heavy crossbow', 'gap_ranged_crossbow_rare_2'),
  ('voidtouched hooded robe', 'gap_gear_attire_rare_5'),
  ('voidtouched reach staff', 'gap_melee_staff_rare_1'),
  ('voidtouched two-hander', 'gap_melee_blade_heavy_rare_1'),
  ('war pick', 'base-weapon-war-pick'),
  ('warhammer', 'base-weapon-warhammer'),
  ('weathered press badge', 'bg-press-badge'),
  ('whip', 'base-weapon-whip'),
  ('world history textbook', 'bg-ironic-textbook'),
  ('world-eater sealed ring', 'gap_gear_ring_legendary_0'),
  ('world-ender crown', 'artifact_16'),
  ('world-ender reliquary', 'artifact_4'),
  ('worldbreaker''s greatsword', 'gap_melee_blade_heavy_epic_2'),
  ('worldbreaker''s mana band', 'gap_gear_ring_epic_4'),
  ('worldbreaker''s mine', 'gap_consumable_grenade_epic_0'),
  ('worldbreaker''s pdw', 'gap_firearm_smg_epic_0'),
  ('wraithtouched casting staff', 'gap_melee_staff_rare_0'),
  ('wraithtouched combat knuckles', 'gap_melee_gauntlet_rare_0'),
  ('wraithtouched katana', 'gap_melee_blade_versatile_rare_2'),
  ('wraithtouched kusarigama', 'gap_melee_whip_rare_0'),
  ('wraithtouched reaping blade', 'gap_melee_sickle_rare_1'),
  ('wraithtouched reaver sword', 'gap_melee_blade_heavy_rare_4'),
  ('wraithtouched stone charm', 'gap_gear_amulet_rare_8'),
  ('wraithtouched wand', 'gap_focus_wand_rare_4'),
  ('wraithtouched war axe', 'gap_melee_axe_rare_1'),
  ('wyrmflame band', 'gap_gear_ring_epic_6'),
  ('wyrmflame hammered band', 'gap_gear_ring_epic_0'),
  ('wyrmflame lattice pendant', 'gap_gear_amulet_epic_4')
)
UPDATE public.character_equipment ce
SET item_id = eq.id
FROM canonical_equipment eq
WHERE ce.item_id IS NULL
  AND ce.name IS NOT NULL
  AND lower(trim(ce.name)) = eq.lookup_name;

WITH canonical_feats(lookup_name, id) AS (
VALUES
  ('adaptive resistance', 'adaptive-resistance'),
  ('adrenaline overdrive', 'adrenaline-overdrive'),
  ('adrenaline overdrive limiter', 'adrenaline-overdrive-limiter'),
  ('aetheric reflex augment', 'aetheric-reflex-augment'),
  ('annihilation style', 'annihilation-style'),
  ('apex assassin strike', 'apex-assassin-strike'),
  ('apex negotiator decree', 'apex-negotiator-protocol'),
  ('apex negotiator mandate', 'apex-negotiator-algorithm'),
  ('apex scent tracking', 'apex-scent-tracking'),
  ('arcane overseer eye', 'arcane-overseer-eye'),
  ('battle channeler', 'battle-channeler'),
  ('berserker blood frenzy', 'berserker-blood-frenzy'),
  ('berserker bloodlust', 'berserker-bloodlust'),
  ('boss reader', 'boss-reader'),
  ('circuit breaker', 'circuit-breaker'),
  ('cognitive firewall', 'cognitive-firewall'),
  ('combat aether-sight analyzer', 'combat-hud-analyzer'),
  ('critical shadow', 'critical-shadow'),
  ('daily quest discipline', 'daily-quest-discipline'),
  ('deadeye decree', 'deadeye-protocol'),
  ('destroyer''s resolve', 'destroyer-resolve'),
  ('dimensional scavenger', 'dimensional-scavenger'),
  ('dimensional shifter dodge', 'dimensional-shifter-dodge'),
  ('dimensional step evader', 'dimensional-step-evader'),
  ('dimensional step expert', 'dimensional-step-expert'),
  ('dimensional teleport expert', 'dimensional-teleport-expert'),
  ('dimensional vault master', 'dimensional-vault-master'),
  ('dimensional vault optimization', 'dimensional-vault-optimization'),
  ('domain of shadows', 'domain-of-shadows'),
  ('double awakening', 'double-awakening'),
  ('echo-location sonar', 'echo-location-sonar'),
  ('emergency extraction', 'emergency-extraction'),
  ('endurance optimization', 'endurance-optimization'),
  ('essence absorption', 'essence-absorption'),
  ('exarch''s authority', 'rulers-authority'),
  ('forceful force shover', 'kinetic-force-shover'),
  ('forceful redirection', 'kinetic-redirection'),
  ('forceful redirection expert', 'kinetic-redirection-expert'),
  ('fortress conditioning', 'fortress-conditioning'),
  ('gate anchor specialist', 'gate-anchor-specialist'),
  ('gate engineer', 'gate-engineer'),
  ('gate guardian stance', 'gate-guardian-stance'),
  ('gate master navigator', 'gate-master-navigator'),
  ('gate raid veteran', 'gate-raid-veteran'),
  ('gate sense', 'gate-sense'),
  ('gate structural engineer', 'gate-structural-engineer'),
  ('gate vanguard stance', 'gate-vanguard-stance'),
  ('gate-hardened', 'gate-hardened'),
  ('gatekeeper''s reach', 'gatekeepers-reach'),
  ('ghost recon drone', 'ghost-recon-drone'),
  ('ghost recon drone link', 'ghost-recon-drone-link'),
  ('guild command decree', 'guild-command-protocol'),
  ('guild leader decree', 'ascendant-guild-leader'),
  ('heavy plating integration', 'heavy-plating-integration'),
  ('heavy plating specialist', 'heavy-armor-specialist-v2'),
  ('heavy weapon annihilator', 'heavy-weapon-annihilator'),
  ('heavy weapon calibration', 'heavy-weapon-calibration'),
  ('interface optimization', 'system-interface-optimization'),
  ('internal mana battery', 'internal-mana-battery'),
  ('iron vanguard', 'iron-vanguard'),
  ('iron vitality', 'iron-vitality'),
  ('kill count momentum', 'kill-count-momentum'),
  ('last stand decree', 'last-stand-protocol'),
  ('latent potential', 'latent-potential'),
  ('logic payload hack', 'logic-payload-hack'),
  ('mana battery core', 'mana-battery-core'),
  ('mana blade dancer', 'mana-blade-dancer'),
  ('mana blade resonance', 'mana-blade-resonance'),
  ('mana burn specialist', 'mana-burn-specialist'),
  ('mana capacitor armor', 'mana-capacitor-armor'),
  ('mana leech fangs', 'mana-leech-fangs'),
  ('mana leech mandate', 'mana-leech-algorithm'),
  ('mana leech strike', 'mana-leech-strike'),
  ('mana overflow', 'mana-overflow'),
  ('mana shield capacitor', 'mana-shield-capacitor'),
  ('mana shield capacitor link', 'mana-shield-capacitor-link'),
  ('mana siphon', 'mana-siphon'),
  ('mana surge catalyst', 'mana-surge-catalyst'),
  ('mana surge vanguard', 'mana-surge-vanguard'),
  ('mana weaver ritualist', 'mana-weaver-ritualist'),
  ('mana well font', 'mana-well-font'),
  ('mana-medic expert', 'mana-medic-expert'),
  ('omniscience eyes', 'system-omniscience-eyes'),
  ('order analyst', 'system-analyst'),
  ('order data analyst', 'system-data-analyst'),
  ('order diagnostic medic', 'system-diagnostic-medic'),
  ('order executioner', 'system-executioner'),
  ('order fortress body', 'system-fortress-body'),
  ('order interceptor', 'system-interceptor'),
  ('order linguist', 'umbral-binding-expert'),
  ('order overclock', 'system-overclock'),
  ('order scholar', 'system-scholar'),
  ('overseer eyes', 'system-overseer-eyes'),
  ('party sync', 'party-sync'),
  ('phantom limb manifestation', 'phantom-limb-manifestation'),
  ('phantom limb technique', 'phantom-limb-technique'),
  ('phantom mandate strike', 'phantom-algorithm-strike'),
  ('plating specialist', 'heavy-armor-mastery-v2'),
  ('quest log intuition', 'quest-log-intuition'),
  ('reality sunder blade', 'reality-sunder-blade'),
  ('recon specialist', 'system-recon-specialist'),
  ('regent command decree', 'regent-command-protocol'),
  ('shadow armor', 'shadow-armor'),
  ('shadow attunement', 'shadow-attunement'),
  ('shadow dance', 'shadow-dance'),
  ('shadow step reflex', 'shadow-step-reflex'),
  ('shadow weapon mastery', 'shadow-weapon-mastery'),
  ('sonar pulse echo', 'sonar-pulse-echo'),
  ('spiritual duelist sync', 'neural-duelist-sync'),
  ('spiritual link tactician', 'neural-link-tactician'),
  ('spiritual network hacker', 'neural-network-hacker'),
  ('spiritual sync sharpshooter', 'neural-sync-sharpshooter'),
  ('stalker''s grace', 'stalker-grace'),
  ('threat ping', 'threat-ping'),
  ('transcendent vessel', 'transcendent-vessel'),
  ('twin fang technique', 'twin-fang-technique'),
  ('urban parkour expert', 'urban-parkour-expert'),
  ('urban parkour specialist', 'urban-parkour-specialist'),
  ('void blade mastery', 'void-blade-mastery'),
  ('void rifter', 'void-rifter'),
  ('void shifter reflex', 'void-shifter-reflex'),
  ('void step striker', 'void-step-striker'),
  ('warden', 'system-administrator')
)
UPDATE public.character_features cf
SET feat_id = ft.id
FROM canonical_feats ft
WHERE cf.feat_id IS NULL
  AND cf.name IS NOT NULL
  AND lower(trim(cf.name)) = ft.lookup_name
  AND lower(coalesce(cf.source, '')) LIKE '%feat%';

UPDATE public.character_features
SET feat_id = pg_temp.ra_canonical_slug(name)
WHERE feat_id IS NULL
  AND name IS NOT NULL
  AND trim(name) <> ''
  AND lower(coalesce(source, '')) LIKE '%feat%';

CREATE INDEX IF NOT EXISTS idx_characters_job_id
  ON public.characters (job_id)
  WHERE job_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_characters_path_id
  ON public.characters (path_id)
  WHERE path_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_characters_background_id
  ON public.characters (background_id)
  WHERE background_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_character_powers_power_id
  ON public.character_powers (power_id)
  WHERE power_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_character_spells_character_spell_id
  ON public.character_spells (character_id, spell_id)
  WHERE spell_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_character_features_feature_id
  ON public.character_features (feature_id)
  WHERE feature_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_character_features_feat_id
  ON public.character_features (feat_id)
  WHERE feat_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_character_equipment_item_id
  ON public.character_equipment (item_id)
  WHERE item_id IS NOT NULL;
