-- Add missing powers from the PHB (Tiers 5-9 and additional power types)
INSERT INTO compendium_powers (name, power_level, casting_time, range, duration, description, concentration, source_book) VALUES
-- Tier 5
('Tier 5 Blast', 5, '1 action', '90 feet', 'Instantaneous', 'You release a focused burst of destructive energy. Make a ranged spell attack against a creature you can see within range. On a hit, the target takes 7d8 damage of a type appropriate to your Job or Path (such as force, fire, cold, or psychic). When you cast this spell using a higher-tier slot, increase the damage by 1d8 for each tier above its base tier.', false, 'PHB'),
('Tier 5 Guardian Shell', 5, '1 action', 'Self or 30 feet', 'Concentration, up to 10 minutes', 'Protective energy surrounds you or an ally you can see. The target gains temporary hit points equal to 2 × your proficiency bonus × 5 and a +1 bonus to AC. While the temporary hit points last, the target has advantage on saving throws against being frightened.', true, 'PHB'),
('Tier 5 Coordinated Recovery', 5, '1 action', '30 feet', 'Instantaneous', 'You rapidly coordinate triage with the System''s help. Choose up to three creatures in range. Each target regains hit points equal to your casting ability modifier + 5d4. A creature that regains hit points this way can use its reaction to move up to half its speed without provoking opportunity attacks.', false, 'PHB'),
('Tier 5 Area Burst', 5, '1 action', '60 feet', 'Instantaneous', 'You detonate a controlled explosion of power at a point you can see. Each creature in a 15-foot-radius sphere must make a Dexterity saving throw. A creature takes 6d6 damage on a failed save, or half as much damage on a successful one. Damage type matches your Job or Path''s theme.', false, 'PHB'),
('Tier 5 Zone of Control', 5, '1 action', '60 feet', 'Concentration, up to 1 minute', 'You alter a 10-foot-radius sphere of the battlefield with difficult terrain, swirling energy, or oppressive force. A creature that enters the area for the first time on a turn or starts its turn there must succeed on a Strength or Dexterity saving throw or take 1d6 damage and have its speed reduced by 10 feet until the start of its next turn.', true, 'PHB'),
('Tier 5 System Scan', 5, '1 action', 'Self', 'Concentration, up to 10 minutes', 'You query the System for information about a Rift, Relic, or creature. For the duration, you have advantage on Intellect (Arcana/Tech) and Sense checks related to the chosen target. The DM can provide additional hints or warnings about major threats.', true, 'PHB'),

-- Tier 6
('Tier 6 Blast', 6, '1 action', '90 feet', 'Instantaneous', 'You release a focused burst of destructive energy. Make a ranged spell attack against a creature you can see within range. On a hit, the target takes 8d8 damage of a type appropriate to your Job or Path. When you cast this spell using a higher-tier slot, increase the damage by 1d8 for each tier above its base tier.', false, 'PHB'),
('Tier 6 Guardian Shell', 6, '1 action', 'Self or 30 feet', 'Concentration, up to 10 minutes', 'Protective energy surrounds you or an ally you can see. The target gains temporary hit points equal to 2 × your proficiency bonus × 6 and a +1 bonus to AC. While the temporary hit points last, the target has advantage on saving throws against being frightened.', true, 'PHB'),
('Tier 6 Coordinated Recovery', 6, '1 action', '30 feet', 'Instantaneous', 'You rapidly coordinate triage with the System''s help. Choose up to three creatures in range. Each target regains hit points equal to your casting ability modifier + 6d4. A creature that regains hit points this way can use its reaction to move up to half its speed without provoking opportunity attacks.', false, 'PHB'),
('Tier 6 Area Burst', 6, '1 action', '60 feet', 'Instantaneous', 'You detonate a controlled explosion of power at a point you can see. Each creature in a 15-foot-radius sphere must make a Dexterity saving throw. A creature takes 7d6 damage on a failed save, or half as much damage on a successful one. Damage type matches your Job or Path''s theme.', false, 'PHB'),
('Tier 6 Zone of Control', 6, '1 action', '60 feet', 'Concentration, up to 1 minute', 'You alter a 10-foot-radius sphere of the battlefield with difficult terrain, swirling energy, or oppressive force. A creature that enters the area for the first time on a turn or starts its turn there must succeed on a Strength or Dexterity saving throw or take 1d6 damage and have its speed reduced by 10 feet until the start of its next turn.', true, 'PHB'),
('Tier 6 System Scan', 6, '1 action', 'Self', 'Concentration, up to 10 minutes', 'You query the System for information about a Rift, Relic, or creature. For the duration, you have advantage on Intellect (Arcana/Tech) and Sense checks related to the chosen target. The DM can provide additional hints or warnings about major threats.', true, 'PHB'),

-- Tier 7
('Tier 7 Blast', 7, '1 action', '90 feet', 'Instantaneous', 'You release a focused burst of destructive energy. Make a ranged spell attack against a creature you can see within range. On a hit, the target takes 9d8 damage of a type appropriate to your Job or Path. When you cast this spell using a higher-tier slot, increase the damage by 1d8 for each tier above its base tier.', false, 'PHB'),
('Tier 7 Guardian Shell', 7, '1 action', 'Self or 30 feet', 'Concentration, up to 10 minutes', 'Protective energy surrounds you or an ally you can see. The target gains temporary hit points equal to 2 × your proficiency bonus × 7 and a +1 bonus to AC. While the temporary hit points last, the target has advantage on saving throws against being frightened.', true, 'PHB'),
('Tier 7 Coordinated Recovery', 7, '1 action', '30 feet', 'Instantaneous', 'You rapidly coordinate triage with the System''s help. Choose up to three creatures in range. Each target regains hit points equal to your casting ability modifier + 7d4. A creature that regains hit points this way can use its reaction to move up to half its speed without provoking opportunity attacks.', false, 'PHB'),
('Tier 7 Area Burst', 7, '1 action', '60 feet', 'Instantaneous', 'You detonate a controlled explosion of power at a point you can see. Each creature in a 15-foot-radius sphere must make a Dexterity saving throw. A creature takes 8d6 damage on a failed save, or half as much damage on a successful one. Damage type matches your Job or Path''s theme.', false, 'PHB'),
('Tier 7 Zone of Control', 7, '1 action', '60 feet', 'Concentration, up to 1 minute', 'You alter a 10-foot-radius sphere of the battlefield with difficult terrain, swirling energy, or oppressive force. A creature that enters the area for the first time on a turn or starts its turn there must succeed on a Strength or Dexterity saving throw or take 1d6 damage and have its speed reduced by 10 feet until the start of its next turn.', true, 'PHB'),
('Tier 7 System Scan', 7, '1 action', 'Self', 'Concentration, up to 10 minutes', 'You query the System for information about a Rift, Relic, or creature. For the duration, you have advantage on Intellect (Arcana/Tech) and Sense checks related to the chosen target. The DM can provide additional hints or warnings about major threats.', true, 'PHB'),

-- Tier 8
('Tier 8 Blast', 8, '1 action', '90 feet', 'Instantaneous', 'You release a focused burst of destructive energy. Make a ranged spell attack against a creature you can see within range. On a hit, the target takes 10d8 damage of a type appropriate to your Job or Path. When you cast this spell using a higher-tier slot, increase the damage by 1d8 for each tier above its base tier.', false, 'PHB'),
('Tier 8 Guardian Shell', 8, '1 action', 'Self or 30 feet', 'Concentration, up to 10 minutes', 'Protective energy surrounds you or an ally you can see. The target gains temporary hit points equal to 2 × your proficiency bonus × 8 and a +1 bonus to AC. While the temporary hit points last, the target has advantage on saving throws against being frightened.', true, 'PHB'),
('Tier 8 Coordinated Recovery', 8, '1 action', '30 feet', 'Instantaneous', 'You rapidly coordinate triage with the System''s help. Choose up to three creatures in range. Each target regains hit points equal to your casting ability modifier + 8d4. A creature that regains hit points this way can use its reaction to move up to half its speed without provoking opportunity attacks.', false, 'PHB'),
('Tier 8 Area Burst', 8, '1 action', '60 feet', 'Instantaneous', 'You detonate a controlled explosion of power at a point you can see. Each creature in a 15-foot-radius sphere must make a Dexterity saving throw. A creature takes 9d6 damage on a failed save, or half as much damage on a successful one. Damage type matches your Job or Path''s theme.', false, 'PHB'),
('Tier 8 Zone of Control', 8, '1 action', '60 feet', 'Concentration, up to 1 minute', 'You alter a 10-foot-radius sphere of the battlefield with difficult terrain, swirling energy, or oppressive force. A creature that enters the area for the first time on a turn or starts its turn there must succeed on a Strength or Dexterity saving throw or take 1d6 damage and have its speed reduced by 10 feet until the start of its next turn.', true, 'PHB'),
('Tier 8 System Scan', 8, '1 action', 'Self', 'Concentration, up to 10 minutes', 'You query the System for information about a Rift, Relic, or creature. For the duration, you have advantage on Intellect (Arcana/Tech) and Sense checks related to the chosen target. The DM can provide additional hints or warnings about major threats.', true, 'PHB'),

-- Tier 9
('Tier 9 Blast', 9, '1 action', '90 feet', 'Instantaneous', 'You release a focused burst of destructive energy. Make a ranged spell attack against a creature you can see within range. On a hit, the target takes 11d8 damage of a type appropriate to your Job or Path.', false, 'PHB'),
('Tier 9 Guardian Shell', 9, '1 action', 'Self or 30 feet', 'Concentration, up to 10 minutes', 'Protective energy surrounds you or an ally you can see. The target gains temporary hit points equal to 2 × your proficiency bonus × 9 and a +1 bonus to AC. While the temporary hit points last, the target has advantage on saving throws against being frightened.', true, 'PHB'),
('Tier 9 Coordinated Recovery', 9, '1 action', '30 feet', 'Instantaneous', 'You rapidly coordinate triage with the System''s help. Choose up to three creatures in range. Each target regains hit points equal to your casting ability modifier + 9d4. A creature that regains hit points this way can use its reaction to move up to half its speed without provoking opportunity attacks.', false, 'PHB'),
('Tier 9 Area Burst', 9, '1 action', '60 feet', 'Instantaneous', 'You detonate a controlled explosion of power at a point you can see. Each creature in a 15-foot-radius sphere must make a Dexterity saving throw. A creature takes 10d6 damage on a failed save, or half as much damage on a successful one. Damage type matches your Job or Path''s theme.', false, 'PHB'),
('Tier 9 Zone of Control', 9, '1 action', '60 feet', 'Concentration, up to 1 minute', 'You alter a 10-foot-radius sphere of the battlefield with difficult terrain, swirling energy, or oppressive force. A creature that enters the area for the first time on a turn or starts its turn there must succeed on a Strength or Dexterity saving throw or take 1d6 damage and have its speed reduced by 10 feet until the start of its next turn.', true, 'PHB'),
('Tier 9 System Scan', 9, '1 action', 'Self', 'Concentration, up to 10 minutes', 'You query the System for information about a Rift, Relic, or creature. For the duration, you have advantage on Intellect (Arcana/Tech) and Sense checks related to the chosen target. The DM can provide additional hints or warnings about major threats.', true, 'PHB')
ON CONFLICT DO NOTHING;
-- Add more relics from the PHB/Reliquary
INSERT INTO compendium_relics (name, item_type, rarity, requires_attunement, description, source_book) VALUES
-- Common Relics
('Rift-Touched Armor Lining', 'Armor', 'common', false, 'This subtle reinforcement layer fits under normal armor or clothing. While wearing it, you gain a +1 bonus to AC against the first attack made against you each combat. The lining can absorb only minor traces of corruption; on a critical hit against you, it may tear or burn out at the DM''s discretion.', 'PHB'),
('Tracker''s Lens', 'Wondrous Item', 'common', false, 'A monocle or visor overlay that highlights heat and motion. You gain advantage on Sense checks to track creatures within 60 feet in dim light. Once per short rest, you can focus for 1 minute to see faint traces of recent movement (footprints, disturbed debris).', 'PHB'),
('Echo-Recording Commlink', 'Wondrous Item', 'common', false, 'A communication device that records System anomalies. You can replay the last minute of nearby System messages or Rift noises. While carrying it, you have advantage on checks to resist forced movement from minor Rift fluctuations.', 'PHB'),

-- Uncommon Relics
('Pulsebreaker Shield', 'Shield', 'uncommon', true, 'A shield reinforced with anti-Rift circuitry. While wielding this shield, you have resistance to the damage of the first area-of-effect attack that hits you each combat. Once per long rest, you can project a brief barrier as a reaction to impose disadvantage on a ranged spell attack that targets you.', 'PHB'),
('Rapid-Deploy Grav Harness', 'Wondrous Item', 'uncommon', true, 'A harness with Rift-derived gravitic nodes. You can cast a limited feather fall on yourself without expending a power slot, once per short rest. When you would take falling damage, you can instead treat the fall as 20 feet shorter.', 'PHB'),

-- Rare Relics
('Monarch-Splitter Blade', 'Weapon', 'rare', true, 'A heavy weapon infused with traces of Monarch energy. This weapon grants a +1 bonus to attack and damage rolls. When you hit a creature that is currently benefiting from magical damage resistance or temporary hit points, you deal an extra 1d8 force damage. On a critical hit, you can force the target to make a Presence saving throw or lose ongoing damage resistance for 1 minute (once per long rest).', 'PHB'),
('Chrono-Shift Band', 'Wondrous Item', 'rare', true, 'A band that compresses personal time for a moment. Once per long rest, you can treat yourself as if under a haste-like effect for 1 turn: your speed is doubled and you gain one additional action that can be used to take the Attack (one weapon attack only), Dash, Disengage, or Use an Object action. After using this effect, you cannot take reactions until the end of your next turn.', 'PHB'),
('Gatewalker Cloak', 'Wondrous Item', 'rare', true, 'A cloak that seems to shimmer like an open Rift. While wearing it, you gain advantage on Stealth checks in dim light and near Rift energy. Once per short rest, you can teleport up to 30 feet to an unoccupied space you can see.', 'PHB'),
('System-Linked Gauntlet', 'Wondrous Item', 'rare', true, 'A gauntlet that interfaces directly with the System. You can use the gauntlet as a focus for powers. Once per long rest, you can ask the System for a tactical hint, gaining advantage on one attack roll, ability check, or saving throw declared before rolling.', 'PHB'),

-- Very Rare Relics
('Aegis of the Fallen Raid', 'Shield', 'very_rare', true, 'A relic shield constructed from the remains of a failed Rift team''s gear. Grants a +2 bonus to AC. While attuned, your maximum hit points increase by 10 and your movement speed increases by 10 feet. Once per long rest, you can unleash a devastating area attack, dealing 8d8 force damage in a 30-foot radius sphere (Dexterity save for half). Each use of the area attack increases your corruption, potentially attracting Monarch attention.', 'PHB'),
('Crown of the Emergent Apex', 'Wondrous Item', 'very_rare', true, 'A crown-like construct of energy and metal. While attuned, you can communicate telepathically with allies within 60 feet. Once per long rest, you can enter an apex state for 1 minute, gaining temporary hit points equal to twice your Ascendant level and adding your Presence modifier to all saving throws. At the end of this state, you must succeed on a Presence saving throw or suffer a level of exhaustion.', 'PHB'),
('System Root Key', 'Wondrous Item', 'legendary', true, 'A mysterious device rumored to interface with the System''s deepest layers. While attuned, you gain advantage on checks to interact with System consoles, artifacts, and anomalies. Once per campaign arc, the DM may allow the Root Key to bypass or rewrite a single major System restriction, with significant narrative consequences.', 'PHB')
ON CONFLICT DO NOTHING;
-- Create a feats table for character options
CREATE TABLE IF NOT EXISTS public.compendium_feats (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  prerequisites TEXT,
  description TEXT NOT NULL,
  benefits TEXT[],
  source_book TEXT DEFAULT 'PHB',
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
-- Enable RLS
ALTER TABLE public.compendium_feats ENABLE ROW LEVEL SECURITY;
-- Create read policy
CREATE POLICY "Compendium feats are publicly readable" 
ON public.compendium_feats 
FOR SELECT 
USING (true);
-- Insert feats from the PHB
INSERT INTO compendium_feats (name, prerequisites, description, benefits, source_book) VALUES
('Coordinated Healer', 'Healer Job or access to at least one healing power', 'You''re practiced at delivering aid efficiently in combat.', ARRAY['When you restore hit points to an ally with an ability, power, or Relic, that ally can use its reaction to move up to half its speed without provoking opportunity attacks.', 'You have advantage on checks made to stabilize dying creatures.', 'Once per long rest, when you roll the maximum on at least one die to restore hit points, you can reroll one of the other dice and add the new result.'], 'PHB'),
('Steady Trigger', 'Proficiency with a ranged weapon', 'You know how to squeeze every bit of accuracy out of ranged shots.', ARRAY['When you make a ranged weapon attack against a creature that has not moved since your last turn, you gain a +1 bonus to the attack roll.', 'You ignore half cover when making ranged weapon attacks.', 'If you take the Ready action to make a ranged attack, you can add your proficiency bonus to the damage of that attack if it hits.'], 'PHB'),
('Arcane Efficiency', 'Mage, Contractor, or Esper Job', 'You''ve learned to squeeze more work out of your power slots.', ARRAY['When you use a Tier 1 power that restores hit points or deals damage, you can choose to treat it as if it were used with a Tier 0 (cantrip-equivalent) slot; the power''s effects are halved, but it does not expend a higher-tier slot.', 'Once per long rest, when you expend a Tier 3 or higher slot, you can immediately regain one expended Tier 1 slot.'], 'PHB'),
('Brutal Finisher', 'Destroyer, Striker, or Assassin Job; Strength or Agility 15 or higher', 'You specialize in ending fights decisively.', ARRAY['When you hit a creature with a melee weapon attack and reduce it to 0 hit points, you can make one weapon attack against another creature within reach as a bonus action.', 'Once per turn when you score a critical hit with a melee attack, you can add your proficiency bonus to the damage roll.'], 'PHB'),
('Relic Bond', 'Proficiency in Arcana/Tech or a Relic-related tool', 'You form unusually strong connections with your Relics.', ARRAY['Choose one Relic you are attuned to. While you remain attuned, you have advantage on saving throws against being disarmed of or separated from that Relic.', 'Once per long rest, if you would be reduced to 0 hit points while wielding or wearing that Relic, you can drop to 1 hit point instead, and the Relic gains a point of corruption at the DM''s discretion.'], 'PHB'),
('Guild-Forged Reputation', 'Member of a recognized guild or organization', 'Your guild connections provide social advantages.', ARRAY['You have advantage on Charisma (Persuasion) checks made to negotiate contracts or payouts with official guild representatives.', 'When your party completes a Rift contract, add a small Reputation bonus as described in your DMG.', 'Once per arc, you can call in a favor from your guild: temporary access to a specialist, a Relic on loan, or expedited processing.'], 'PHB'),
('Rift Scholar', 'Intellect 13 or higher', 'You''ve studied the theory and history of Rifts.', ARRAY['You have advantage on checks to recall lore about Rifts, Monarchs, and known Rift catastrophes.', 'Once per short rest, when your party is considering entering a Rift, you can ask the DM one additional question about its likely nature, which must be answered truthfully but may be cryptic.'], 'PHB'),
('Monarch-Touched', 'Exposure to Monarch-tier power (DM approval)', 'You have survived direct interaction with Monarch power, leaving a permanent mark.', ARRAY['You gain resistance to one damage type associated with the Monarch (chosen when you gain this feat).', 'Once per long rest, you can add 1d6 to a saving throw you make against an effect with a similar theme.', 'The System occasionally flags you as a potential threat or asset in ways the DM can use as a narrative hook.'], 'PHB'),
('System-Favored', 'DM approval', 'The System pays unusual attention to you.', ARRAY['You gain a small pool of System Favor points (typically 2) that you regain when you finish a long rest.', 'You can spend 1 point of System Favor to reroll an attack roll, ability check, or saving throw you just made, taking the new result.', 'The DM may offer you special System Quests or prompts as part of this feat.'], 'PHB'),
('Combat Analyst', 'Intellect or Sense 13 or higher', 'You read combat situations with exceptional clarity.', ARRAY['After observing a creature for 1 round in combat, you can use your bonus action to analyze it. Until the end of your next turn, you and allies who can hear you gain a +1 bonus to attack rolls against that creature.', 'Once per short rest, you can use your reaction when a creature you can see makes an attack to impose disadvantage on that attack roll.'], 'PHB'),
('Resilient Mind', 'Presence or Intellect 13 or higher', 'Your mind is hardened against psychic strain.', ARRAY['You gain proficiency in Presence saving throws. If you already have proficiency, you instead gain expertise (double proficiency) on Presence saves against psychic or fear effects.', 'You have advantage on saving throws against effects that would charm or frighten you.'], 'PHB'),
('Heavy Weapon Specialist', 'Strength 15 or higher; proficiency with heavy weapons', 'You are skilled at handling large, unwieldy weapons.', ARRAY['Attacking with heavy weapons no longer imposes disadvantage on your attack rolls due to size differences between you and the weapon.', 'When you roll a 1 or 2 on a damage die for a heavy weapon attack, you can reroll the die and must use the new roll.', 'You have advantage on saving throws against exhaustion from forced marches, starvation, or similar environmental threats.'], 'PHB'),
('Efficient Caster', 'Ability to use at least one Tier 2 power', 'You''ve mastered small efficiencies in your casting.', ARRAY['When you use a Tier 1 power that has a duration of 1 minute or longer, you can choose to extend its duration by 1 additional minute without expending a higher-tier slot. You can do this a number of times per long rest equal to your proficiency bonus.', 'Once per short rest, you can reduce the activation time of a Tier 1 self-targeted power from 1 action to 1 bonus action.'], 'PHB'),
('Shadow Operative', 'Assassin or Ranger Job; proficiency in Stealth', 'You are especially effective while unseen.', ARRAY['When you are hidden from a creature and miss it with a ranged attack, making the attack doesn''t reveal your position.', 'You can attempt to hide even when you are only lightly obscured if there is significant environmental clutter or distraction.'], 'PHB'),
('Mobile Defender', 'Any Job, proficiency with shields or defensive Relics', 'You interpose yourself between danger and your allies.', ARRAY['When a creature you can see attacks a target other than you that is within 5 feet of you, you can use your reaction to impose disadvantage on the attack roll.', 'If the attack still hits, you can choose to take the damage instead of the original target, provided you are within 5 feet of both the attacker and the original target.'], 'PHB'),
('Twin-Path Adept', 'Level 8 or higher, at least one Path', 'You have begun to blend the lessons of multiple Paths.', ARRAY['You gain one feature from a Path other than your own, choosing from features available at or below your level. This feature must not duplicate one you already have.', 'The DM may require story justification for how you accessed this alternate Path''s training.'], 'PHB'),
('Relic Tuner', 'Relic Savant feat or similar', 'You can fine-tune the output of your Relics.', ARRAY['When you finish a long rest, you can adjust one numerical parameter on a Relic you are attuned to by ±1 (such as the number of charges or a small bonus), to a maximum change of ±1. This adjustment lasts until you finish your next long rest and cannot break global caps.', 'Once per day, you can suppress a minor corruption effect from one Relic for 24 hours.'], 'PHB'),
('Rift Logistician', 'Intellect 13 or higher', 'You plan Rift runs with enviable efficiency.', ARRAY['When your party prepares for a Rift with at least 1 hour of planning, you can designate one standard consumable item (such as a potion or talisman) per party member; each designated item is treated as if the party has one additional copy of it.', 'Once per long rest, you can retroactively declare that you packed the right tool for this, gaining advantage on a single tool check during a Rift.'], 'PHB'),
('Synchronized Squad', 'At least two party members share this feat', 'Your team trains together to act as a cohesive unit.', ARRAY['When rolling initiative, any party member with this feat can choose to use the highest initiative result among party members who also have this feat.', 'Once per short rest, as a reaction when an ally you can see makes an attack, you can grant a +2 bonus to that attack roll.'], 'PHB')
ON CONFLICT DO NOTHING;
