-- Make the API-role grants explicit so every environment matches production.
--
-- Supabase stopped granting table privileges to anon, authenticated, and
-- service_role by default for new projects (May 30, 2026), and current local
-- stacks start the same way. This project is older: production still has the
-- legacy defaults, so most tables carry ALL for the three API roles and RLS
-- decides access. A clean replay of these migrations lacked those grants, so
-- local checks did not reflect production and a new project would be broken.
--
-- Every statement below is a GRANT production already holds. They were
-- generated from a production schema dump on 2026-09-30 by comparing its ACLs
-- with a clean local replay (only missing privileges are listed), so this
-- migration changes nothing in production. The default privileges likewise
-- restate production's, so tables and functions created by later migrations
-- get the same grants everywhere. RLS remains the access boundary.
BEGIN;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO service_role;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE
  public.active_sessions,
  public.admin_audit_log,
  public.art_assets,
  public.assets,
  public.bureau_contracts,
  public.campaign_character_shares,
  public.campaign_combat_sessions,
  public.campaign_combatants,
  public.campaign_details,
  public.campaign_encounter_entries,
  public.campaign_encounters,
  public.campaign_extras,
  public.campaign_inventory,
  public.campaign_invite_audit_logs,
  public.campaign_invites,
  public.campaign_loot_drops,
  public.campaign_member_characters,
  public.campaign_members,
  public.campaign_messages,
  public.campaign_notes,
  public.campaign_relic_instances,
  public.campaign_roll_events,
  public.campaign_rule_events,
  public.campaign_rules,
  public.campaign_session_events,
  public.campaign_session_logs,
  public.campaign_sessions,
  public.campaign_tool_states,
  public.campaign_vehicles,
  public.campaign_wiki_articles,
  public.campaigns,
  public.character_abilities,
  public.character_active_spells,
  public.character_backups,
  public.character_crafting_projects,
  public.character_equipment,
  public.character_extras,
  public.character_feature_choices,
  public.character_features,
  public.character_journal,
  public.character_materials,
  public.character_monarch_unlocks,
  public.character_powers,
  public.character_recipes,
  public.character_regent_unlock_grants,
  public.character_regent_unlocks,
  public.character_regents,
  public.character_requisition_profiles,
  public.character_rune_inscriptions,
  public.character_rune_knowledge,
  public.character_shadow_army,
  public.character_shares,
  public.character_sheet_state,
  public.character_sigil_inscriptions,
  public.character_spell_slots,
  public.character_spells,
  public.character_tattoos,
  public.character_techniques,
  public.character_umbral_legionnaires,
  public.character_vehicles,
  public.characters,
  public.combat_actions,
  public.combat_participants,
  public."compendium_Anomalies",
  public.compendium_artifacts,
  public.compendium_backgrounds,
  public.compendium_conditions,
  public.compendium_equipment,
  public.compendium_feats,
  public.compendium_feature_choice_groups,
  public.compendium_feature_choice_options,
  public.compendium_items,
  public.compendium_job_features,
  public.compendium_job_paths,
  public.compendium_jobs,
  public.compendium_locations,
  public.compendium_monarch_features,
  public.compendium_monarchs,
  public.compendium_monster_actions,
  public.compendium_monster_traits,
  public.compendium_notes,
  public.compendium_pantheon,
  public.compendium_paths,
  public.compendium_powers,
  public.compendium_regent_features,
  public.compendium_regents,
  public.compendium_relics,
  public.compendium_rules,
  public.compendium_runes,
  public.compendium_shadow_soldier_abilities,
  public.compendium_shadow_soldier_actions,
  public.compendium_shadow_soldier_traits,
  public.compendium_shadow_soldiers,
  public.compendium_sigils,
  public.compendium_skills,
  public.compendium_sovereign_features,
  public.compendium_sovereigns,
  public.compendium_spells,
  public.compendium_tattoos,
  public.compendium_techniques,
  public.craft_formula_research,
  public.craft_formulas_m3,
  public.craft_projects_m3,
  public.daily_quest_configs,
  public.daily_quest_instances,
  public.daily_quest_templates,
  public.guild_join_requests,
  public.guild_members,
  public.guild_quests,
  public.guilds,
  public.homebrew_content,
  public.homebrew_content_versions,
  public.marketplace_items,
  public.marketplace_reviews,
  public.profiles,
  public.quest_completions,
  public.quest_rewards_log,
  public.regent_unresolved_ability_grants,
  public.roll_history,
  public.session_participants,
  public.session_quests,
  public.user_favorites,
  public.user_marketplace_entitlements,
  public.user_notifications,
  public.user_profiles,
  public.user_tool_states
TO anon;

GRANT SELECT ON TABLE
  public.campaign_tamed_anomalies,
  public.character_tamed_anomalies,
  public.companion_attempt_adjudications,
  public.companion_bond_attempts,
  public.companion_bonds,
  public.companion_control_events,
  public.companion_instances,
  public.material_definitions,
  public.material_lot_discoveries,
  public.material_lot_operations,
  public.material_lot_reservations,
  public.material_lots,
  public.sovereign_attachment_operations
TO anon;

GRANT DELETE, INSERT, UPDATE ON TABLE
  public.campaigns_public_listings,
  public.saved_sovereigns
TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE
  public.active_sessions,
  public.admin_audit_log,
  public.art_assets,
  public.assets,
  public.bureau_contracts,
  public.campaign_character_shares,
  public.campaign_details,
  public.campaign_encounter_entries,
  public.campaign_encounters,
  public.campaign_extras,
  public.campaign_inventory,
  public.campaign_invite_audit_logs,
  public.campaign_invites,
  public.campaign_loot_drops,
  public.campaign_member_characters,
  public.campaign_members,
  public.campaign_messages,
  public.campaign_notes,
  public.campaign_relic_instances,
  public.campaign_roll_events,
  public.campaign_rule_events,
  public.campaign_rules,
  public.campaign_session_events,
  public.campaign_session_logs,
  public.campaign_sessions,
  public.campaign_tool_states,
  public.campaign_vehicles,
  public.campaign_wiki_articles,
  public.campaigns,
  public.character_backups,
  public.character_shares,
  public.combat_actions,
  public.combat_participants,
  public."compendium_Anomalies",
  public.compendium_artifacts,
  public.compendium_backgrounds,
  public.compendium_conditions,
  public.compendium_equipment,
  public.compendium_feats,
  public.compendium_feature_choice_groups,
  public.compendium_feature_choice_options,
  public.compendium_items,
  public.compendium_job_features,
  public.compendium_job_paths,
  public.compendium_jobs,
  public.compendium_locations,
  public.compendium_monarch_features,
  public.compendium_monarchs,
  public.compendium_monster_actions,
  public.compendium_monster_traits,
  public.compendium_notes,
  public.compendium_pantheon,
  public.compendium_paths,
  public.compendium_powers,
  public.compendium_regent_features,
  public.compendium_regents,
  public.compendium_relics,
  public.compendium_rules,
  public.compendium_runes,
  public.compendium_shadow_soldier_abilities,
  public.compendium_shadow_soldier_actions,
  public.compendium_shadow_soldier_traits,
  public.compendium_shadow_soldiers,
  public.compendium_sigils,
  public.compendium_skills,
  public.compendium_sovereign_features,
  public.compendium_sovereigns,
  public.compendium_spells,
  public.compendium_tattoos,
  public.compendium_techniques,
  public.daily_quest_configs,
  public.daily_quest_instances,
  public.daily_quest_templates,
  public.guild_join_requests,
  public.guild_members,
  public.guild_quests,
  public.guilds,
  public.homebrew_content,
  public.homebrew_content_versions,
  public.marketplace_items,
  public.marketplace_reviews,
  public.profiles,
  public.quest_completions,
  public.quest_rewards_log,
  public.roll_history,
  public.session_participants,
  public.session_quests,
  public.user_favorites,
  public.user_marketplace_entitlements,
  public.user_notifications,
  public.user_profiles,
  public.user_tool_states
TO authenticated;

GRANT DELETE, INSERT, UPDATE ON TABLE
  public.campaigns_public_listings,
  public.character_abilities,
  public.character_active_spells,
  public.character_crafting_projects,
  public.character_equipment,
  public.character_feature_choices,
  public.character_features,
  public.character_journal,
  public.character_monarch_unlocks,
  public.character_regent_unlock_grants,
  public.character_regent_unlocks,
  public.character_regents,
  public.character_requisition_profiles,
  public.character_rune_inscriptions,
  public.character_rune_knowledge,
  public.character_shadow_army,
  public.character_sheet_state,
  public.character_sigil_inscriptions,
  public.character_spell_slots,
  public.character_tattoos,
  public.character_umbral_legionnaires,
  public.craft_formula_research,
  public.craft_formulas_m3,
  public.craft_projects_m3,
  public.regent_unresolved_ability_grants
TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE
  public.active_sessions,
  public.admin_audit_log,
  public.art_assets,
  public.assets,
  public.bureau_contracts,
  public.campaign_character_shares,
  public.campaign_combat_sessions,
  public.campaign_combatants,
  public.campaign_details,
  public.campaign_encounter_entries,
  public.campaign_encounters,
  public.campaign_extras,
  public.campaign_inventory,
  public.campaign_invite_audit_logs,
  public.campaign_invites,
  public.campaign_loot_drops,
  public.campaign_member_characters,
  public.campaign_members,
  public.campaign_messages,
  public.campaign_notes,
  public.campaign_relic_instances,
  public.campaign_roll_events,
  public.campaign_rule_events,
  public.campaign_rules,
  public.campaign_session_events,
  public.campaign_session_logs,
  public.campaign_sessions,
  public.campaign_tamed_anomalies,
  public.campaign_tool_states,
  public.campaign_vehicles,
  public.campaign_wiki_articles,
  public.campaigns,
  public.campaigns_public_listings,
  public.character_abilities,
  public.character_active_spells,
  public.character_backups,
  public.character_crafting_projects,
  public.character_equipment,
  public.character_extras,
  public.character_feature_choices,
  public.character_features,
  public.character_journal,
  public.character_materials,
  public.character_monarch_unlocks,
  public.character_pending_regent_grants,
  public.character_powers,
  public.character_recipes,
  public.character_regent_resonance,
  public.character_regent_resonance_spends,
  public.character_regent_unlock_grants,
  public.character_regent_unlocks,
  public.character_regents,
  public.character_requisition_profiles,
  public.character_rune_inscriptions,
  public.character_rune_knowledge,
  public.character_shadow_army,
  public.character_shares,
  public.character_sheet_state,
  public.character_sigil_inscriptions,
  public.character_spell_slots,
  public.character_spells,
  public.character_tamed_anomalies,
  public.character_tattoos,
  public.character_techniques,
  public.character_umbral_legionnaires,
  public.character_vehicles,
  public.characters,
  public.combat_actions,
  public.combat_participants,
  public.companion_attempt_adjudications,
  public.companion_bond_attempts,
  public.companion_bonds,
  public.companion_control_events,
  public.companion_instances,
  public."compendium_Anomalies",
  public.compendium_artifacts,
  public.compendium_backgrounds,
  public.compendium_conditions,
  public.compendium_equipment,
  public.compendium_feats,
  public.compendium_feature_choice_groups,
  public.compendium_feature_choice_options,
  public.compendium_items,
  public.compendium_job_features,
  public.compendium_job_paths,
  public.compendium_jobs,
  public.compendium_locations,
  public.compendium_monarch_features,
  public.compendium_monarchs,
  public.compendium_monster_actions,
  public.compendium_monster_traits,
  public.compendium_notes,
  public.compendium_pantheon,
  public.compendium_paths,
  public.compendium_powers,
  public.compendium_regent_features,
  public.compendium_regents,
  public.compendium_relics,
  public.compendium_rules,
  public.compendium_runes,
  public.compendium_shadow_soldier_abilities,
  public.compendium_shadow_soldier_actions,
  public.compendium_shadow_soldier_traits,
  public.compendium_shadow_soldiers,
  public.compendium_sigils,
  public.compendium_skills,
  public.compendium_sovereign_features,
  public.compendium_sovereigns,
  public.compendium_spells,
  public.compendium_tattoos,
  public.compendium_techniques,
  public.craft_formula_research,
  public.craft_formulas_m3,
  public.craft_projects_m3,
  public.daily_quest_configs,
  public.daily_quest_instances,
  public.daily_quest_templates,
  public.guild_join_requests,
  public.guild_members,
  public.guild_quests,
  public.guilds,
  public.harvest_attempts_m2,
  public.harvest_authorizations_m2,
  public.homebrew_content,
  public.homebrew_content_versions,
  public.marketplace_items,
  public.marketplace_reviews,
  public.material_definitions,
  public.material_lot_discoveries,
  public.material_lot_operations,
  public.material_lot_reservations,
  public.material_lots,
  public.profiles,
  public.quest_completions,
  public.quest_rewards_log,
  public.regent_catch_up_options,
  public.regent_unresolved_ability_grants,
  public.roll_history,
  public.saved_sovereigns,
  public.session_participants,
  public.session_quests,
  public.sovereign_attachment_operations,
  public.user_favorites,
  public.user_marketplace_entitlements,
  public.user_notifications,
  public.user_profiles,
  public.user_tool_states
TO service_role;

GRANT SELECT, USAGE ON SEQUENCE
  public.campaign_session_events_id_seq
TO anon;

GRANT SELECT, USAGE ON SEQUENCE
  public.campaign_session_events_id_seq
TO authenticated;

GRANT SELECT, USAGE ON SEQUENCE
  public.campaign_session_events_id_seq
TO service_role;

GRANT EXECUTE ON FUNCTION
  public.accept_bureau_contract(p_contract_id uuid, p_guild_id uuid),
  public.add_ascendant_character_to_campaign(p_campaign_id uuid, p_character_id uuid, p_invite_token text),
  public.add_campaign_session_log(p_campaign_id uuid, p_session_id uuid, p_log_type text, p_title text, p_content text, p_metadata jsonb, p_is_player_visible boolean),
  public.add_companion_to_combat(p_session_id uuid, p_companion_instance_id uuid, p_initiative integer, p_initiative_mode text, p_anchor_character_id uuid),
  public.add_player_character_to_campaign(p_campaign_id uuid, p_character_id uuid, p_invite_token text),
  public.add_user_notification(p_user_id uuid, p_type text, p_title text, p_message text, p_priority text, p_category text, p_payload jsonb, p_link text, p_expires_at timestamp with time zone),
  public.add_user_notification_unchecked(p_user_id uuid, p_type text, p_title text, p_message text, p_priority text, p_category text, p_payload jsonb, p_link text, p_expires_at timestamp with time zone),
  public.adjust_material_lot_m1(p_lot_id uuid, p_delta numeric, p_expected_version bigint, p_operation_id text),
  public.adjust_material_lot_m1_unchecked(p_lot_id uuid, p_delta numeric, p_expected_version bigint, p_operation_id text),
  public.admin_set_user_ban(p_target uuid, p_banned boolean),
  public.admin_set_user_role(p_target uuid, p_role text),
  public.advance_combat_turn(p_session_id uuid),
  public.approve_guild_join_request(p_request_id uuid, p_role text),
  public.approve_harvest_yield_m2(p_campaign_id uuid, p_character_id uuid, p_source_kind text, p_source_id text, p_source_rank text, p_source_note text, p_method text, p_material_definition_id text, p_quantity numeric, p_duration_minutes integer, p_tool_kind text, p_tool_evidence text, p_warden_dc integer, p_operation_id text),
  public.approve_pending_regent_grant(p_pending_id uuid, p_unlock_id uuid, p_campaign_id uuid),
  public.asset_exists(p_path text),
  public.assign_campaign_loot(p_campaign_id uuid, p_items jsonb, p_encounter_id uuid, p_session_id uuid, p_assigned_to_member_id uuid),
  public.assign_campaign_loot_unchecked(p_campaign_id uuid, p_items jsonb, p_encounter_id uuid, p_session_id uuid, p_assigned_to_member_id uuid),
  public.assign_campaign_relic(p_campaign_id uuid, p_relic_id uuid, p_name text, p_rarity text, p_properties jsonb, p_value_credits numeric, p_bound_to_member_id uuid, p_tradeable boolean),
  public.assign_campaign_relic_unchecked(p_campaign_id uuid, p_relic_id uuid, p_name text, p_rarity text, p_properties jsonb, p_value_credits numeric, p_bound_to_member_id uuid, p_tradeable boolean),
  public.assign_daily_quests(p_character_id uuid),
  public.assign_daily_quests_unchecked(p_character_id uuid),
  public.attach_campaign_member_character(p_campaign_id uuid, p_member_id uuid, p_character_id uuid),
  public.attach_saved_sovereign(p_character_id uuid, p_sovereign_id uuid, p_operation_id text),
  public.attempt_taming(p_campaign_id uuid, p_character_id uuid, p_anomaly_id text, p_roll_total integer, p_dc integer, p_initial_hp integer, p_bond_initial integer, p_nickname text),
  public.attempt_taming_unchecked(p_campaign_id uuid, p_character_id uuid, p_anomaly_id text, p_roll_total integer, p_dc integer, p_initial_hp integer, p_bond_initial integer, p_nickname text),
  public.attempt_taming_with_source(p_campaign_id uuid, p_character_id uuid, p_anomaly_id text, p_roll_total integer, p_dc integer, p_initial_hp integer, p_source_snapshot jsonb, p_bond_initial integer, p_nickname text),
  public.begin_craft_experiment_m4(p_character_id uuid, p_formula_id text),
  public.bureau_guild_leaderboard(),
  public.calculate_character_hp(level integer, constitution_score integer, hit_dice text),
  public.calculate_proficiency_bonus(level integer),
  public.can_manage_homebrew_content(p_homebrew_id uuid, p_user_id uuid),
  public.can_view_homebrew_content(p_homebrew_id uuid, p_user_id uuid),
  public.cancel_craft_project_m3(p_project_id uuid, p_expected_version bigint, p_operation_id text),
  public.capture_homebrew_version_snapshot(),
  public.claim_anomaly_controller(p_tamed_id uuid, p_character_id uuid),
  public.claim_quest_rewards(p_quest_id uuid, p_character_id uuid),
  public.claim_quest_rewards_unchecked(p_quest_id uuid, p_character_id uuid),
  public.clear_companion_rider(p_companion_instance_id uuid),
  public.complete_regent_catch_up(p_unlock_id uuid),
  public.complete_session_quest(p_quest_id uuid, p_completion_notes text),
  public.configure_regent_unlock_offer(p_grant_id uuid, p_candidate_regent_ids text[]),
  public.consume_regent_unlock_grant(p_grant_id uuid, p_regent_id text),
  public.create_campaign_invite(p_campaign_id uuid, p_role text, p_expires_at timestamp with time zone, p_max_uses integer, p_invite_email text),
  public.create_campaign_with_code(p_name text, p_description text, p_warden_id uuid),
  public.create_guild_with_code(p_name text, p_description text, p_motto text, p_leader_user_id uuid, p_campaign_id uuid, p_character_id uuid),
  public.create_material_lot_m1(p_character_id uuid, p_material_definition_id text, p_quantity numeric, p_operation_id text, p_notes text),
  public.create_material_lot_m1_unchecked(p_character_id uuid, p_material_definition_id text, p_quantity numeric, p_operation_id text, p_notes text),
  public.create_regent_unlock_offer(p_character_id uuid, p_quest_id text, p_quest_title text, p_candidate_regent_ids text[], p_request_id uuid),
  public.create_session_quest(p_campaign_id uuid, p_title text, p_description text, p_objectives text[], p_rewards jsonb),
  public.deploy_campaign_encounter(p_encounter_id uuid),
  public.detach_campaign_member_character(p_campaign_id uuid, p_member_id uuid, p_character_id uuid),
  public.discover_character_rune(p_character_id uuid, p_rune_key text, p_is_mastered boolean, p_learned_from text),
  public.end_active_session(p_session_id uuid),
  public.end_session_combat(p_session_id uuid),
  public.enforce_campaign_listing_cap(),
  public.enforce_character_limit(),
  public.ensure_campaign_member_character_consistency(),
  public.export_campaign_bundle(p_campaign_id uuid),
  public.generate_campaign_join_code(p_length integer),
  public.generate_character_share_token(p_length integer),
  public.generate_character_share_token_for_character(p_character_id uuid),
  public.generate_share_code(),
  public.get_campaign_by_share_code(p_share_code text),
  public.get_campaign_invite_by_token(p_token text),
  public.get_campaign_linked_characters(p_campaign_id uuid),
  public.get_campaign_member_count(p_campaign_id uuid),
  public.get_campaign_roster(p_campaign_id uuid),
  public.get_character_by_share_token(p_character_id uuid, p_share_token text),
  public.gift_marketplace_item(p_item_id uuid, p_recipient_user_id uuid, p_message text),
  public.guild_member_role(p_guild_id uuid, p_uid uuid),
  public.handle_new_user(),
  public.hash_campaign_invite_token(p_token text),
  public.hypopg_reset(),
  public.import_craft_state_authority(p_original_character_id uuid, p_target_character_id uuid, p_lot_id_map jsonb, p_operation_id text),
  public.import_material_lots_m1(p_character_id uuid, p_definitions jsonb, p_lots jsonb, p_discoveries jsonb, p_operation_id text),
  public.import_material_lots_m1_unchecked(p_character_id uuid, p_definitions jsonb, p_lots jsonb, p_discoveries jsonb, p_operation_id text),
  public.import_regent_grant_authority(p_original_grant_id uuid, p_grant_kind text, p_target_unlock_id uuid),
  public.import_regent_resonance_state(p_original_character_id uuid, p_target_character_id uuid, p_requested_points integer),
  public.import_regent_unlock_authority(p_original_unlock_id uuid, p_target_character_id uuid, p_expected_regent_id text),
  public.is_campaign_active(p_campaign_id uuid),
  public.is_campaign_dm(p_campaign_id uuid, p_user_id uuid),
  public.is_campaign_member(p_campaign_id uuid, p_user_id uuid),
  public.is_campaign_system(p_campaign_id uuid, p_user_id uuid),
  public.is_campaign_warden(p_campaign_id uuid, p_user_id uuid),
  public.is_dm_or_admin(p_user_id uuid),
  public.is_warden_or_admin(p_user_id uuid),
  public.join_campaign_by_code(p_code text, p_character_id uuid),
  public.join_campaign_by_id(p_campaign_id uuid, p_character_id uuid),
  public.log_campaign_invite_event(p_campaign_id uuid, p_invite_id uuid, p_action text, p_details jsonb, p_actor_id uuid),
  public.mark_user_notification_read(p_notification_id uuid),
  public.normalize_campaign_invite_role(p_role text),
  public.on_long_rest_assign_quests(p_character_id uuid),
  public.on_long_rest_assign_quests_unchecked(p_character_id uuid),
  public.prepare_companion_attempt_adjudication(p_campaign_id uuid, p_character_id uuid, p_target_source_id text, p_attempt_kind text, p_companion_instance_id uuid, p_roll_mode text, p_proficiency_mode text, p_specialization_mode text, p_retry_of_attempt_id uuid, p_reason text),
  public.prepare_search_text(p_text text),
  public.record_marketplace_download(p_item_id uuid, p_user_id uuid),
  public.record_marketplace_download_unchecked(p_item_id uuid, p_user_id uuid),
  public.redeem_campaign_invite(p_token text, p_character_id uuid),
  public.redeem_campaign_invite_unchecked(p_token text, p_character_id uuid),
  public.refill_regent_resonance(p_character_id uuid),
  public.register_character_vehicle_mount(p_vehicle_link_id uuid, p_source_snapshot jsonb),
  public.release_anomaly_controller(p_tamed_id uuid),
  public.remove_campaign_member(p_campaign_id uuid, p_member_id uuid),
  public.remove_campaign_tamed_anomaly(p_tamed_id uuid),
  public.remove_regent_unlock(p_unlock_id uuid),
  public.request_to_join_guild(p_share_code text, p_character_id uuid, p_message text),
  public.reserve_craft_project_m3(p_character_id uuid, p_formula_id text, p_inputs jsonb, p_operation_id text),
  public.resolve_campaign_invite(p_access_key text),
  public.resolve_companion_bond_attempt_c2(p_campaign_id uuid, p_character_id uuid, p_companion_instance_id uuid, p_expected_source_id text, p_roll_primary integer, p_roll_secondary integer, p_adjudication_id uuid),
  public.resolve_companion_tame_attempt_c2(p_campaign_id uuid, p_character_id uuid, p_anomaly_id text, p_source_snapshot jsonb, p_roll_primary integer, p_roll_secondary integer, p_adjudication_id uuid, p_nickname text),
  public.resolve_companion_tame_attempt_c2_unchecked(p_campaign_id uuid, p_character_id uuid, p_anomaly_id text, p_source_snapshot jsonb, p_roll_primary integer, p_roll_secondary integer, p_adjudication_id uuid, p_nickname text),
  public.resolve_craft_project_m3(p_project_id uuid, p_expected_version bigint, p_operation_id text),
  public.resolve_guild_quest(p_quest_id uuid, p_success boolean),
  public.resolve_guild_quest_unchecked(p_quest_id uuid, p_success boolean),
  public.resolve_harvest_attempt_m2(p_authorization_id uuid, p_skill text, p_operation_id text),
  public.rest_companions_for_character(p_character_id uuid, p_rest_kind text),
  public.revoke_campaign_invite(p_invite_id uuid, p_reason text),
  public.revoke_harvest_approval_m2(p_authorization_id uuid),
  public.revoke_regent_unlock_offer(p_grant_id uuid),
  public.save_campaign_encounter(p_campaign_id uuid, p_encounter_id uuid, p_name text, p_description text, p_difficulty jsonb, p_entries jsonb, p_loot jsonb),
  public.save_sovereign_v2_definition(p_definition jsonb, p_operation_id text, p_is_public boolean),
  public.search_compendium_jobs(p_query text, p_limit integer, p_offset integer),
  public.search_compendium_monarchs(p_query text, p_limit integer, p_offset integer),
  public.search_compendium_monsters(p_query text, p_limit integer, p_offset integer),
  public.search_compendium_paths(p_query text, p_limit integer, p_offset integer),
  public.search_compendium_powers(p_query text, p_limit integer, p_offset integer),
  public.search_compendium_relics(p_query text, p_limit integer, p_offset integer),
  public.set_campaign_member_role(p_campaign_id uuid, p_member_id uuid, p_role text),
  public.set_campaign_tamed_hp(p_tamed_id uuid, p_current_hp integer),
  public.set_companion_rider(p_companion_instance_id uuid, p_rider_character_id uuid, p_rider_size text, p_terrain text, p_has_tack boolean, p_is_trained boolean),
  public.set_homebrew_content_status(p_homebrew_id uuid, p_status text, p_visibility_scope text, p_campaign_id uuid),
  public.set_primary_regent_unlock(p_unlock_id uuid),
  public.set_regent_catch_up_options(p_unlock_id uuid, p_campaign_id uuid, p_options jsonb),
  public.spend_companion_hit_dice(p_companion_instance_id uuid, p_dice integer, p_hp_recovered integer),
  public.spend_regent_resonance(p_character_id uuid, p_grant_kind text, p_grant_id uuid, p_request_id uuid),
  public.start_active_session(p_campaign_id uuid, p_title text, p_description text),
  public.start_session_combat(p_session_id uuid, p_participants jsonb),
  public.sync_compendium_data(),
  public.update_campaign_session_logs_updated_at(),
  public.update_campaign_sessions_updated_at(),
  public.update_character_sheet_state_updated_at(),
  public.update_character_spell_slots_updated_at(),
  public.update_character_templates_updated_at(),
  public.update_character_xp(character_id uuid, xp_amount integer, campaign_id uuid, reason text),
  public.update_marketplace_items_updated_at(),
  public.update_marketplace_reviews_updated_at(),
  public.update_modified_column(),
  public.update_updated_at_column(),
  public.update_user_marketplace_entitlements_updated_at(),
  public.upsert_campaign_session(p_campaign_id uuid, p_session_id uuid, p_title text, p_description text, p_scheduled_for timestamp with time zone, p_status text, p_location text, p_recurrence_rule text, p_recurrence_parent_id uuid),
  public.upsert_campaign_session_unchecked(p_campaign_id uuid, p_session_id uuid, p_title text, p_description text, p_scheduled_for timestamp with time zone, p_status text, p_location text, p_recurrence_rule text, p_recurrence_parent_id uuid),
  public.upsert_marketplace_review(p_item_id uuid, p_rating integer, p_comment text, p_user_id uuid),
  public.upsert_marketplace_review_unchecked(p_item_id uuid, p_rating integer, p_comment text, p_user_id uuid),
  public.warden_grant_character_equipment(p_campaign_id uuid, p_items jsonb),
  public.work_craft_project_m3(p_project_id uuid, p_expected_version bigint, p_operation_id text)
TO service_role;

COMMIT;
