-- Modern-day backgrounds for System Ascendant
-- 8 new backgrounds fitting contemporary/urban settings

INSERT INTO compendium_backgrounds (
  name, description, feature_name, feature_description,
  skill_proficiencies, tool_proficiencies, starting_equipment, starting_credits,
  language_count, personality_traits, ideals, bonds, flaws,
  source_book, source_kind, tags, theme_tags
) VALUES
(
  'Viral Streamer',
  'Before the System chose you, you were already famous—or at least internet-famous. Your live streams, reaction videos, or documentary content had built an audience of thousands, maybe millions. When gates started opening and hunters started awakening, you pointed your camera at the chaos and never looked away. Now that you''ve awakened yourself, your audience watches your ascension in real time.',
  'Viral Reach',
  'Your online following gives you access to information networks. You can spend 1 hour broadcasting a request to your followers to gain advantage on one Intelligence (Investigation) or Charisma (Persuasion) check within the next 24 hours as your audience crowdsources answers or applies social pressure.',
  ARRAY['Performance','Persuasion'],
  ARRAY['Streaming Equipment','Video Editing Software'],
  'A high-end streaming laptop, a ring light and portable camera, a branded hoodie with your channel logo, a portable Wi-Fi hotspot, a belt pouch containing 15 gp',
  15, 0,
  ARRAY['I narrate everything I do as if someone is watching—because someone usually is.','I can''t resist documenting a dramatic moment, even in the middle of danger.','I speak in catchphrases and memes that I''ve made famous.','I treat every social interaction like an interview opportunity.'],
  ARRAY['Authenticity. My audience trusts me because I never fake it. (Good)','Fame. More followers means more power, and power is everything. (Neutral)','Connection. I stream because loneliness is a disease the internet can cure. (Any)','Truth. I use my platform to expose corruption and injustice. (Lawful)'],
  ARRAY['My first subscriber stuck with me from zero—I''d do anything for them.','A corporation tried to buy my silence about a gate incident I streamed live.','My streaming rival disappeared after exploring a gate on camera.','I accidentally captured classified Hunter Association footage and now I''m a target.'],
  ARRAY['I can''t stop checking my viewer count, even during life-or-death moments.','I''ll take insane risks for content that will go viral.','I''ve built a persona so thick I''ve forgotten who I actually am.','I overshare everything online and have no concept of operational security.'],
  'System Ascendant Canon', 'homebrew',
  ARRAY['modern','media','technology','fame'],
  ARRAY['modern','urban','celebrity']
),
(
  'K-Pop Idol',
  'You were one of the brightest stars in the entertainment industry—a trained performer whose face graced billboards, whose songs topped charts, and whose every movement was choreographed to perfection. Then the System awakened you, and suddenly your stage presence became something far more dangerous.',
  'Stage Presence',
  'Your years of idol training have given you supernatural charisma. When you perform for at least 1 minute, all friendly creatures within 30 feet gain temporary hit points equal to your Charisma modifier + your proficiency bonus. This can be used once per short rest.',
  ARRAY['Performance','Acrobatics'],
  ARRAY['Musical Instrument (any one)','Disguise Kit'],
  'A designer stage outfit, a musical instrument of your choice, a disguise kit, a signed photo collection from your group, a belt pouch containing 25 gp',
  25, 1,
  ARRAY['I maintain perfect posture and appearance at all times—training never ends.','I count beats in my head during combat, turning every fight into choreography.','I bow to everyone I meet, a habit from years of fan meets.','I practice my smile so often it''s become my default expression, even when I''m terrified.'],
  ARRAY['Perfection. I trained 16 hours a day for years—I refuse to accept anything less than my best. (Lawful)','Inspiration. My purpose is to give people hope through my art. (Good)','Freedom. The agency controlled my life—never again. (Chaotic)','Legacy. I want to be remembered for more than just a pretty face and catchy songs. (Any)'],
  ARRAY['My former group members are scattered across different hunter guilds—I need to find them.','My agency still holds my contract and wants me back, dead or alive.','A sasaeng fan awakened the same day I did and is obsessed with following my ascension.','I dedicated my last song to someone who disappeared into a gate—I''ll find them.'],
  ARRAY['I am terrified of being seen without makeup or my stage persona.','I instinctively try to please everyone, even enemies.','I can''t handle being ignored—I need to be the center of attention.','Years of strict dieting have left me with a complicated relationship with food and rest.'],
  'System Ascendant Canon', 'homebrew',
  ARRAY['modern','entertainment','performance','fame'],
  ARRAY['modern','urban','celebrity']
),
(
  'Movie Star',
  'Hollywood royalty, box office gold, the face that launched a thousand franchises—that was your life before the gates. You had everything: mansions, private jets, adoring fans. Then the System chose you, and suddenly the action scenes weren''t choreographed anymore.',
  'Method Actor',
  'Your acting training lets you assume identities with frightening accuracy. You have advantage on Charisma (Deception) checks when impersonating a specific person you have observed for at least 10 minutes. Additionally, you can perfectly mimic accents and speech patterns.',
  ARRAY['Performance','Deception'],
  ARRAY['Disguise Kit','Vehicles (land)'],
  'A set of luxury clothes, a disguise kit, an autographed headshot (your own), a pair of designer sunglasses, a belt pouch containing 30 gp',
  30, 0,
  ARRAY['I quote my own movies in conversation and expect people to recognize the reference.','I approach every situation like it''s a scene—I need motivation, stakes, and a dramatic arc.','I am genuinely kind to fans but ruthless in negotiations.','I''ve played so many characters that I sometimes lose track of my real personality.'],
  ARRAY['Art. Acting taught me empathy—I''ve lived a thousand lives and understand them all. (Good)','Power. Fame is just another word for influence, and influence changes the world. (Neutral)','Authenticity. I''m tired of pretending—I want to be someone real for once. (Any)','Justice. I''ve seen how the powerful exploit the weak, and I won''t stand for it. (Lawful)'],
  ARRAY['My stunt double was killed when a gate opened on set—I carry their memory.','A director I trust implicitly has been asking me to investigate strange gate activity.','My co-star awakened as a villain, and only I know their true identity.','I promised my late parent I''d use my platform to help people.'],
  ARRAY['I need an audience to function—I freeze when no one is watching.','I''ve been pampered so long that roughing it genuinely distresses me.','I trust my agent''s judgment over my own, even when it''s clearly wrong.','I can''t resist a dramatic entrance, even when stealth is critical.'],
  'System Ascendant Canon', 'homebrew',
  ARRAY['modern','entertainment','fame','deception'],
  ARRAY['modern','urban','celebrity']
),
(
  'Pro Athlete',
  'You were at the top of your game—a professional athlete whose name was synonymous with peak human performance. Your body was a finely tuned instrument, honed through years of brutal training and competition. When the System awakened you, it took that foundation and built something superhuman on top of it.',
  'Peak Conditioning',
  'Your professional training has pushed your body to its limits. You can add your proficiency bonus to Constitution saving throws against exhaustion, and you require only 4 hours of sleep to gain the benefits of a long rest.',
  ARRAY['Athletics','Intimidation'],
  ARRAY['Sports Equipment (any one)','Vehicles (land)'],
  'A set of athletic wear, sports equipment of your choice, a championship medal or trophy replica, a training journal, a belt pouch containing 20 gp',
  20, 0,
  ARRAY['I turn everything into a competition, even eating breakfast.','I maintain a strict training regimen no matter what—6 AM runs in the dungeon if I have to.','I motivate others with intense pre-battle speeches that sound like locker room pep talks.','I keep detailed stats on everything: kills, damage dealt, gates cleared, personal bests.'],
  ARRAY['Excellence. Second place is first loser—I will be the absolute best. (Lawful)','Teamwork. No champion wins alone—I protect my team above all else. (Good)','Glory. I fight so the world will remember my name. (Neutral)','Resilience. It''s not about how hard you hit—it''s about how hard you can get hit and keep going. (Any)'],
  ARRAY['My coach was killed by a gate beast and I fight in their memory.','My old team was my family—I''d cross dimensions to protect them.','A rival athlete awakened with powers that dwarf mine, and I refuse to fall behind.','I still have a contract with my sports team, and they expect me to play AND clear gates.'],
  ARRAY['I push myself past my limits and refuse to admit when I''m injured.','I can''t stand losing—a defeat sends me into a spiral of self-doubt.','I rely too heavily on my physical abilities and neglect studying or planning.','I have a massive ego that makes cooperation with equals difficult.'],
  'System Ascendant Canon', 'homebrew',
  ARRAY['modern','sports','competition','physical'],
  ARRAY['modern','urban','athletic']
),
(
  'Corporate Executive',
  'Corner office, seven-figure salary, a name that made markets move—you were a titan of industry before the gates changed everything. When the System awakened you, you treated it like any other hostile takeover: assess, strategize, dominate.',
  'Corporate Connections',
  'Your business network spans industries and governments. You can call in a favor once per week to arrange meetings with powerful figures, access restricted corporate facilities, or obtain classified market information. The favor''s scope is at the Warden''s discretion.',
  ARRAY['Persuasion','Insight'],
  ARRAY['Forgery Kit'],
  'A tailored business suit, a leather briefcase, a corporate ID badge, a burner phone, a belt pouch containing 50 gp',
  50, 1,
  ARRAY['I evaluate every person I meet in terms of their usefulness to me.','I schedule everything, including leisure time, in 15-minute increments.','I speak in corporate buzzwords and motivational quotes without realizing it.','I always have an exit strategy—for meetings, relationships, and combat.'],
  ARRAY['Order. Systems and hierarchies exist for a reason—they create efficiency. (Lawful)','Ambition. Power flows to those who seize it. I intend to be at the top. (Neutral)','Innovation. The old world is dying. The System is the future, and I will shape it. (Any)','Responsibility. With great power comes great fiduciary responsibility to stakeholders. (Lawful)'],
  ARRAY['My company is secretly funding gate research, and I know things that could topple governments.','My family''s wealth was built on exploiting hunters, and I''m trying to make it right.','A business rival has awakened and is using their powers for corporate espionage.','I owe my position to a mentor who disappeared into an S-Rank gate.'],
  ARRAY['I treat people like assets to be leveraged rather than individuals.','I am addicted to control and become erratic when things don''t go according to plan.','I will sacrifice almost anything—including allies—to protect my reputation.','I look down on people who lack ambition or education.'],
  'System Ascendant Canon', 'homebrew',
  ARRAY['modern','business','leadership','wealth'],
  ARRAY['modern','urban','corporate']
),
(
  'Underground Hacker',
  'In the digital shadows, you were a ghost—a phantom who moved through firewalls like they were tissue paper. When the System awakened you, you realized that reality itself was just another system to hack.',
  'Digital Ghost',
  'You can interface with electronic systems and security networks with supernatural ease. You have advantage on Intelligence checks related to technology, hacking, or digital systems. Once per long rest, you can spend 10 minutes to access a secured digital system without leaving a trace.',
  ARRAY['Investigation','Stealth'],
  ARRAY['Hacking Tools','Thieves'' Tools'],
  'A custom-built laptop with encrypted drives, a set of nondescript clothes, hacking tools, a collection of USB drives with unknown data, a belt pouch containing 10 gp',
  10, 0,
  ARRAY['I see the world as systems and code—everything can be hacked if you know where to look.','I use a different alias for every situation and never give my real name.','I compulsively encrypt everything, including handwritten notes.','I speak in technical jargon that no one else understands and refuse to simplify it.'],
  ARRAY['Freedom. Information wants to be free, and so do people. (Chaotic)','Knowledge. Data is power, and I want to know everything. (Neutral)','Justice. I hack the powerful to protect the powerless. (Good)','Chaos. The old systems are broken—I''m just helping them fall faster. (Chaotic)'],
  ARRAY['My hacker collective was targeted by a hunter guild for exposing their corruption.','I found something in the Hunter Association''s classified servers that terrified me.','The System''s code structure reminds me of something I''ve seen before, and I need to find the connection.','A fellow hacker was forcibly recruited by a shadow organization—I''m going to get them out.'],
  ARRAY['I trust machines more than people.','I am paranoid about surveillance and sometimes see conspiracies where there are none.','I can''t resist poking at secure systems, even when it''s suicidal to try.','I''ve spent so long online that I have serious difficulty with face-to-face social interaction.'],
  'System Ascendant Canon', 'homebrew',
  ARRAY['modern','technology','stealth','information'],
  ARRAY['modern','urban','digital']
),
(
  'Social Media Influencer',
  'Likes, shares, followers, brand deals—that was your world. You built an empire of content, turning your personality into a product and your life into a performance. When the System chose you, your audience exploded overnight.',
  'Influencer''s Reach',
  'You can sway public opinion with a single post. Once per long rest, you can make a Charisma (Persuasion) check to influence the attitude of a community or organization toward a person, idea, or cause. The DC is set by the Warden based on how controversial the stance is.',
  ARRAY['Persuasion','Deception'],
  ARRAY['Photography Equipment'],
  'A smartphone with high-end camera, a portable ring light, a curated wardrobe of trendy clothes, brand partnership contracts, a belt pouch containing 20 gp',
  20, 0,
  ARRAY['I instinctively pose when someone points anything at me that might be a camera.','I rate everything on a 1-to-10 scale and share my opinion whether asked or not.','I genuinely care about my followers and consider them an extended family.','I curate my life so carefully that I sometimes forget what''s real and what''s a brand.'],
  ARRAY['Community. My platform connects people—that matters more than money. (Good)','Image. Perception is reality, and I control how people perceive me. (Neutral)','Growth. Every day is a chance to reach more people and expand my brand. (Any)','Truth. I refuse to promote anything I don''t believe in, even if it costs me sponsors. (Lawful)'],
  ARRAY['My followers funded my first gate expedition through crowdfunding.','A rival influencer has been spreading lies about me and my hunter abilities.','I promised to document the truth about gates for the public, no matter how dangerous.','My brand manager knows my darkest secret and uses it as leverage.'],
  ARRAY['My self-worth is entirely tied to engagement metrics and follower counts.','I''ll do almost anything for content, including putting others at risk.','I can''t handle negative comments—criticism sends me into a tailspin.','I present a perfect life online but I''m deeply insecure underneath it all.'],
  'System Ascendant Canon', 'homebrew',
  ARRAY['modern','media','social','fame'],
  ARRAY['modern','urban','social']
),
(
  'E-Sports Champion',
  'You were the best—or close to it. Your reflexes were measured in milliseconds, your strategic thinking could dismantle world-class teams. When the System awakened you, it was like the ultimate game had finally begun.',
  'Tactical Overlay',
  'Years of competitive gaming have trained your brain to process complex tactical information instantly. You can take the Help action as a bonus action once per short rest. Additionally, you have advantage on Intelligence checks to analyze tactical situations, traps, or puzzles.',
  ARRAY['Perception','Investigation'],
  ARRAY['Gaming Equipment','Vehicles (land)'],
  'A custom gaming peripheral set, a team jersey, a tournament trophy replica, energy drinks (1 week supply), a belt pouch containing 15 gp',
  15, 0,
  ARRAY['I call out ability names when I use them, like a character in a game.','I analyze everyone''s build and suggest optimizations whether they want them or not.','I treat real combat encounters like raid bosses—I need strategy, roles, and a shot caller.','I use gaming terminology for everything: aggro, DPS, tank, res me.'],
  ARRAY['Strategy. Every problem has an optimal solution—you just have to find it. (Lawful)','Competition. I don''t just want to win—I want to be the undisputed best. (Neutral)','Teamwork. No carry is complete without a team. I protect my squad. (Good)','Innovation. The meta is always evolving, and I evolve with it. (Any)'],
  ARRAY['My former esports team was my real family—I''d queue into an S-Rank gate for them.','My biggest rival in gaming awakened the same day I did, and we''re still competing.','I was scouted by a hunter guild specifically because they saw my tactical ability in tournaments.','My gaming sponsor is secretly a front for an organization researching System mechanics.'],
  ARRAY['I sometimes forget that death in real life doesn''t have a respawn timer.','I min-max everything, including relationships.','I can be incredibly toxic when we''re losing—old gaming habits die hard.','I''ve spent so many years indoors that I''m physically underdeveloped compared to other hunters.'],
  'System Ascendant Canon', 'homebrew',
  ARRAY['modern','gaming','technology','competition'],
  ARRAY['modern','urban','gaming']
)
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  feature_name = EXCLUDED.feature_name,
  feature_description = EXCLUDED.feature_description,
  skill_proficiencies = EXCLUDED.skill_proficiencies,
  tool_proficiencies = EXCLUDED.tool_proficiencies,
  starting_equipment = EXCLUDED.starting_equipment,
  starting_credits = EXCLUDED.starting_credits,
  language_count = EXCLUDED.language_count,
  personality_traits = EXCLUDED.personality_traits,
  ideals = EXCLUDED.ideals,
  bonds = EXCLUDED.bonds,
  flaws = EXCLUDED.flaws,
  source_book = EXCLUDED.source_book,
  source_kind = EXCLUDED.source_kind,
  tags = EXCLUDED.tags,
  theme_tags = EXCLUDED.theme_tags;
