// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { error as logError, warn as logWarn, log } from '@/lib/logger';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  logError('Missing Supabase environment variables. Please check your .env file.');
  logError('Required: VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  (() => {
    const url = SUPABASE_URL;
    if (!url) {
      throw new Error('Missing SUPABASE_URL environment variable. Please set it in your .env file.');
    }
    return url;
  })(),
  (() => {
    const key = SUPABASE_PUBLISHABLE_KEY;
    if (!key) {
      throw new Error('Missing SUPABASE_PUBLISHABLE_KEY environment variable. Please set it in your .env file.');
    }
    return key;
  })(),
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

// Test connection on initialization (non-blocking)
// Only run in development, and never during Vitest (happy-dom teardown aborts in-flight fetches).
const shouldTestConnection =
  import.meta.env.DEV &&
  import.meta.env.MODE !== 'test' &&
  typeof window !== 'undefined' &&
  Boolean(SUPABASE_URL) &&
  Boolean(SUPABASE_PUBLISHABLE_KEY);

if (shouldTestConnection) {
  void (async () => {
    try {
      await supabase.from('characters').select('id').limit(1);
      log('✅ Supabase connection successful');
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      logWarn('⚠️ Supabase connection test failed:', message);
      logWarn('The app will continue to work, but database features may be limited.');
    }
  })();
}