// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { warn as logWarn, log } from '@/lib/logger';
import { AppError } from '@/lib/appError';
import { getRuntimeEnvValue } from '@/lib/runtimeEnv';

const SUPABASE_URL = getRuntimeEnvValue('VITE_SUPABASE_URL');
const SUPABASE_PUBLISHABLE_KEY =
  getRuntimeEnvValue('VITE_SUPABASE_PUBLISHABLE_KEY') || getRuntimeEnvValue('VITE_SUPABASE_ANON_KEY');

export const isSupabaseConfigured = Boolean(SUPABASE_URL) && Boolean(SUPABASE_PUBLISHABLE_KEY);

// Validate environment variables (non-fatal; app can run in setup/guest mode)
if (!isSupabaseConfigured) {
  logWarn('Supabase is not configured. Running in setup/guest mode.');
  logWarn('Required: VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)');
}

// Use safe fallbacks so module imports never throw. All network calls are blocked when unconfigured.
const SUPABASE_URL_FALLBACK = 'http://localhost:54321';
const SUPABASE_KEY_FALLBACK = 'public-anon-key';

const baseFetch: typeof fetch | undefined =
  typeof globalThis !== 'undefined'
    ? (globalThis.fetch as typeof fetch | undefined)
    : undefined;

const guardedFetch: typeof fetch = async (input, init) => {
  if (!isSupabaseConfigured) {
    return new Response(
      JSON.stringify({
        error: 'Supabase is not configured',
        hint: 'Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)',
      }),
      {
        status: 503,
        headers: { 'Content-Type': 'application/json' },
      }
    );
  }

  if (!baseFetch) {
    throw new AppError('Global fetch is not available', 'CONFIG');
  }

  return baseFetch(input, init);
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  isSupabaseConfigured ? SUPABASE_URL! : SUPABASE_URL_FALLBACK,
  isSupabaseConfigured ? SUPABASE_PUBLISHABLE_KEY! : SUPABASE_KEY_FALLBACK,
  {
    global: {
      fetch: guardedFetch,
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

// Test connection on initialization (non-blocking)
// Only run in development, and never during Vitest (happy-dom teardown aborts in-flight fetches).
const shouldTestConnection =
  import.meta.env.DEV &&
  import.meta.env.MODE !== 'test' &&
  typeof window !== 'undefined' &&
  isSupabaseConfigured;

if (shouldTestConnection) {
  void (async () => {
    try {
      await supabase.from('characters').select('id').limit(1);
      log('Supabase connection successful');
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      logWarn('Supabase connection test failed:', message);
      logWarn('The app will continue to work, but database features may be limited.');
    }
  })();
}
