import type { DailyQuestTemplate } from './types';

export const DEFAULT_DAILY_QUEST_TEMPLATES: DailyQuestTemplate[] = [
  {
    id: 'training_pushups',
    name: 'Physical Conditioning: Push-ups',
    description: 'Complete a set of push-ups to build upper body strength.',
    tags: ['physical', 'strength'],
    tier: 'I',
    category: 'Training',
    requirements: {
      type: 'check_count',
      skill: 'ATH',
      target: 3,
      difficulty: 'DC 10',
    },
    default_scaling: {
      type: 'proficiency_bonus',
      multiplier: 1,
      offset: 0,
    },
    base_rewards: {
      system_favor: 2,
      description: 'Basic conditioning reward',
      custom_rewards: {},
    },
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'training_squats',
    name: 'Physical Conditioning: Squats',
    description: 'Complete a set of squats to build lower body strength.',
    tags: ['physical', 'strength'],
    tier: 'I',
    category: 'Training',
    requirements: {
      type: 'check_count',
      skill: 'ATH',
      target: 3,
      difficulty: 'DC 10',
    },
    default_scaling: {
      type: 'proficiency_bonus',
      multiplier: 1,
      offset: 0,
    },
    base_rewards: {
      system_favor: 2,
      description: 'Basic conditioning reward',
      custom_rewards: {},
    },
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'training_running',
    name: 'Endurance Training',
    description: 'Maintain a steady pace for extended distance.',
    tags: ['physical', 'endurance'],
    tier: 'I',
    category: 'Training',
    requirements: {
      type: 'check_count',
      skill: 'ATH',
      target: 2,
      difficulty: 'DC 12',
    },
    default_scaling: {
      type: 'proficiency_bonus',
      multiplier: 1,
      offset: 0,
    },
    base_rewards: {
      system_favor: 3,
      description: 'Endurance building reward',
      custom_rewards: {},
    },
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'combat_precision',
    name: 'Combat Precision',
    description: 'Land successful attacks in combat scenarios.',
    tags: ['combat', 'precision'],
    tier: 'II',
    category: 'Combat',
    requirements: {
      type: 'combat_encounters',
      target: 1,
      require_hits: 3,
    },
    default_scaling: {
      type: 'character_level',
      multiplier: 0.5,
      offset: 0,
    },
    base_rewards: {
      system_favor: 5,
      description: 'Combat training reward',
      custom_rewards: {},
    },
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'combat_spellcasting',
    name: 'Spell Combat Practice',
    description: 'Cast spells successfully in combat.',
    tags: ['combat', 'magic'],
    tier: 'II',
    category: 'Combat',
    requirements: {
      type: 'combat_encounters',
      target: 1,
      require_spells: 2,
    },
    default_scaling: {
      type: 'character_level',
      multiplier: 0.5,
      offset: 0,
    },
    base_rewards: {
      system_favor: 5,
      description: 'Spell combat practice reward',
      custom_rewards: {},
    },
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'exploration_mapping',
    name: 'Area Mapping',
    description: 'Explore and map new territory.',
    tags: ['exploration', 'mapping'],
    tier: 'I',
    category: 'Exploration',
    requirements: {
      type: 'check_count',
      skill: 'SURV',
      target: 2,
      difficulty: 'DC 13',
    },
    default_scaling: {
      type: 'proficiency_bonus',
      multiplier: 1,
      offset: 0,
    },
    base_rewards: {
      system_favor: 3,
      description: 'Exploration reward',
      custom_rewards: {},
    },
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mana_meditation',
    name: 'Mana Meditation',
    description: 'Focus and restore magical energy through meditation.',
    tags: ['magic', 'meditation'],
    tier: 'I',
    category: 'Mana',
    requirements: {
      type: 'training_minutes',
      target: 30,
    },
    default_scaling: {
      type: 'proficiency_bonus',
      multiplier: 1,
      offset: 0,
    },
    base_rewards: {
      system_favor: 2,
      description: 'Mana restoration reward',
      custom_rewards: {},
    },
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crafting_basic',
    name: 'Basic Crafting',
    description: 'Create or repair basic equipment.',
    tags: ['crafting', 'repair'],
    tier: 'I',
    category: 'Crafting',
    requirements: {
      type: 'craft_or_loot',
      target: 1,
      item_types: ['equipment', 'consumable'],
    },
    default_scaling: {
      type: 'proficiency_bonus',
      multiplier: 1,
      offset: 0,
    },
    base_rewards: {
      system_favor: 3,
      description: 'Crafting practice reward',
      custom_rewards: {},
    },
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
