// Generated by scripts/generate-sovereign-source-catalog.ts. Do not edit.
//
// Canonical Job, Path, and Regent sources for /api/sovereign. Vercel runs api/
// files as plain Node modules, which cannot load the app's aliased compendium,
// so the function reads this generated copy. The parity test
// src/lib/__tests__/sovereignSourceCatalog.test.ts keeps it equal to the
// static compendium.

export type SovereignSourceKind = "job" | "path" | "regent";

export interface SovereignSourceRecord {
	kind: SovereignSourceKind;
	id: string;
	name: string;
	display_name?: string;
	title?: string;
	theme?: string;
	description?: string;
	hit_die?: number;
	primary_abilities?: string[];
	job_id?: string;
}

export const SOVEREIGN_SOURCES: readonly SovereignSourceRecord[] = [
	{
		kind: "job",
		id: "assassin",
		name: "Assassin",
		description:
			"The Assassin is an Awakened identity that specializes in the Dimensional Phase Operative and Umbral Walker mandate. As an Ascendant of this lineage, their consciousness partially exists between realities, granting them the ability to phase through the physical world and strike from impossible angles. In the modern era, the Assassin is the supreme specialist in surgical rift-clearing and high-value target extraction within high-rank Rifts.",
		hit_die: 8,
		primary_abilities: ["Agility", "Intelligence"],
	},
	{
		kind: "job",
		id: "berserker",
		name: "Berserker",
		description:
			"The Berserker is an Awakened identity that specializes in the Overload Tank and Unstable Resonance mandate. As an Ascendant of this lineage, their core is defined by an unstable connection to the Absolute, flooding their physiology with raw energy under stress. In the modern world, Berserkers are walking spectacles of power—visible mana veins flare across their skin as their muscles swell with crystallized essence. The Ascendant Bureau classifies them as high-risk but indispensable assets who specialize in the controlled demolition of high-rank Rifts.",
		hit_die: 12,
		primary_abilities: ["Strength", "Vitality"],
	},
	{
		kind: "job",
		id: "contractor",
		name: "Contractor",
		description:
			"The Contractor is an Awakened identity that specializes in the Rift-Pact Vessel mandate. As an Ascendant of this lineage, their Awakening was not a gift from the Absolute — it was a bargain with an extraplanar entity whose sigil is literally branded onto their vessel. They draw power through an aetheric umbilical to their patron, trading autonomy for aetheric bandwidth that vastly exceeds their rank. In the modern world, Contractors are both the Bureau's most flexible pact-specialists and its most-watched liability; every pact is registered with Extraplanar Affairs, and every Contractor is subject to monthly resonance audits.",
		hit_die: 8,
		primary_abilities: ["Presence", "Vitality"],
	},
	{
		kind: "job",
		id: "destroyer",
		name: "Destroyer",
		description:
			"The Destroyer is an Awakened identity that specializes in the Living Siege Engine mandate. As an Ascendant of this lineage, their physiology is fundamentally restructured with crystallized mana, granting them bone density and combat instincts that surpass the human limit. They possess an innate Aetheric-Sight that perceives the structural weaknesses of enemies and Rifts alike. In the modern world, the Destroyer is the premier frontline asset of the Ascendant Bureau, their presence stabilizing the absolute order during Rift eruptions.",
		hit_die: 10,
		primary_abilities: ["Strength", "Vitality"],
	},
	{
		kind: "job",
		id: "esper",
		name: "Esper",
		description:
			"The Esper is an Awakened identity that specializes in the Reality Distorter and Unfiltered Vessel mandate. As the SA version of an Esper, their connection to the Aetheric-Weave is raw and volatile—mana bleeds from their body like radiation, reshaping reality through sheer willpower. In modern society, Espers are celebrities and pariahs in equal measure; their aetheric flares reshape the tapestry of existence with absolute authority.",
		hit_die: 6,
		primary_abilities: ["Presence", "Vitality"],
	},
	{
		kind: "job",
		id: "herald",
		name: "Herald",
		description:
			"The Herald is an Awakened identity that specializes in the Absolute Transmission mandate. As an Ascendant of this lineage, their nervous system was restructured at Awakening into a living antenna — a receiver tuned to the Absolute's broadcast, translating sanctified resonance into restorative, radiant, and reality-correcting mantras. In the modern world, Heralds are the Ascendant Bureau's field chaplains and raid medics; their very presence re-anchors an ally's vitals, and their mantras can mend shattered bones or incinerate unholy anomalies with equal authority. They are the bridge between civilians and the Absolute's will.",
		hit_die: 8,
		primary_abilities: ["Presence", "Sense"],
	},
	{
		kind: "job",
		id: "holy-knight",
		name: "Holy Knight",
		description:
			"The Holy Knight is an Awakened identity that specializes in the Oath-Bound Enforcer and Absolute Covenant mandate. As an Ascendant of this lineage, they serve as the ultimate guardians of modern society, their power fueled by a binding oath to the Absolute itself—a literal covenant inscribed into their mana pathways. They work as guild leaders, Ascendant Bureau enforcement officers, and public defenders against Rift threats. The oath grants devastating combat power, but break its tenets and the power is revoked painfully. They channel radiant Absolute energy through weapons, heal allies, and project protective auras.",
		hit_die: 10,
		primary_abilities: ["Strength", "Presence"],
	},
	{
		kind: "job",
		id: "idol",
		name: "Idol",
		description:
			"The Idol is an Awakened identity that specializes in the Frequency Manipulator and Resonance Caster mandate. As an Ascendant of this lineage, their power is attuned to the Absolute's harmonic frequencies, allowing them to broadcast buffs and hype with absolute presence. In modern society, Idols are the most publicly visible ascendants — they have millions of followers, record albums infused with mana, headline gate-clearance livestreams, and their Hype abilities make them the ultimate party buffers.",
		hit_die: 8,
		primary_abilities: ["Presence", "Agility"],
	},
	{
		kind: "job",
		id: "mage",
		name: "Mage",
		description:
			"The Mage is an Awakened identity that specializes in the Arcane Custodian and Aetheric Scholar mandate. As an Ascendant of this lineage, their Awakening provides a direct attunement to the Aetheric-Weave—the fundamental tapestry of absolute magical phenomena. In the modern world, Mages treat magic with the analytical rigor of higher mathematics, optimizing their rites with a precision that defines the modern era of aetheric research.",
		hit_die: 6,
		primary_abilities: ["Intelligence", "Sense"],
	},
	{
		kind: "job",
		id: "revenant",
		name: "Revenant",
		description:
			"The Revenant is an Awakened identity bound to the End-Cycle mandate of Marthos, the Dragon-King of Void and Harbinger of Annihilation. As an Ascendant of this lineage, their body no longer runs on life - it runs on death. Sustained by the Void-Breath and by Remnants (fragments of severed life-essence reclaimed at the instant a creature dies), the Revenant is an unarmored drain tank that holds the line by feeding on the dying around it. They wear no armor and need none; entropy itself sheathes them, and the wounds that would fell others only deepen the harvest. The Ascendant Bureau deploys Revenants as immovable anchors at the worst Rift breaks - the figure who walks into annihilation and walks back out, fuller than before.",
		hit_die: 8,
		primary_abilities: ["Intelligence", "Vitality"],
	},
	{
		kind: "job",
		id: "stalker",
		name: "Stalker",
		description:
			"The Stalker is an Awakened identity that specializes in the Dimensional Predator mandate. As an Ascendant of this lineage, their body was restructured for pursuit — their leg musculature, lung capacity, and cardiovascular system are optimized for sustained high-speed chase, and their aetheric sense is permanently tuned to dimensional anomalies. In the modern world, Stalkers are the Bureau's preferred bounty and extraction specialists; they work alone, they always catch their mark, and when their name appears on a contract the global bounty network goes quiet.",
		hit_die: 10,
		primary_abilities: ["Agility", "Sense"],
	},
	{
		kind: "job",
		id: "striker",
		name: "Striker",
		description:
			"The Striker is an Awakened identity that specializes in the Neural Overdrive and Impulse Channeling mandate. As an Ascendant of this lineage, their entire nervous system was rewired into a mana-conductive network, allowing them to channel kinetic force through their limbs like living railguns. In modern society, Strikers are the premier rapid-response assets for urban Rift eruptions, utilizing their impossible speed to neutralize threats with absolute precision.",
		hit_die: 8,
		primary_abilities: ["Agility", "Sense"],
	},
	{
		kind: "job",
		id: "summoner",
		name: "Summoner",
		description:
			"The Summoner is an Awakened identity granted the mandate of the Hive-Mother. As an Ascendant of this lineage, their mana is harmonized with the extraterrestrial ecosystems that bleed through the Rifts. They do not merely fight; they command the very flora and fauna of the Rift dimensions. In modern society, Summoners are the premier ecologists of the Ascendant Bureau, serving as the bridge between human civilization and the rapidly evolving lifeforms of the Rift-Era. They shapeshift into Rift creatures, command Rift environments, and are the only ascendants who can predict boss spawns by reading resonance markers.",
		hit_die: 8,
		primary_abilities: ["Sense", "Intelligence"],
	},
	{
		kind: "job",
		id: "technomancer",
		name: "Technomancer",
		description:
			"The Technomancer is an Awakened identity that specializes in the Absolute Architect and Aetheric Design mandate. As an Ascendant of this lineage, their Awakening provides architectural access to the Weave-Resonance layer—the fundamental interface between magic and physical matter. In the modern world, Technomancers are the most commercially valuable ascendants, turning Silicon Valley and Shenzhen into hubs of Aetheric innovation. They build devices that redefine reality: mana-powered drones, self-repairing gear, and resonance-enabled technologies.",
		hit_die: 8,
		primary_abilities: ["Intelligence", "Vitality"],
	},
	{
		kind: "path",
		id: "assassin--blade-dancer",
		name: "Path of the Blade Dancer",
		description:
			"The Blade Dancer mandate designates an Ascendant who has mastered the lethal fluidity of phase-step combat. They do not merely fight; they move with an impossible, aetheric grace that makes every encounter look like a choreographed display of violence. In modern high-society duels and televised gate-raids, only the most skilled Dancers can maintain the frequency of the Absolute while moving through a sea of blades without a single scratch.",
		job_id: "assassin",
	},
	{
		kind: "path",
		id: "assassin--gate-runner",
		name: "Path of the Gate Runner",
		description:
			"A Gate Runner is an Ascendant whose essence has been tuned to the phase-spaces between the physical world and the Rifts. They possess a fluidity of movement that allows them to slip through barriers—both physical and aetheric—as if they were nothing more than mist. In the modern world, they are the specialized assets recruited for high-stakes recovery operations and urgent scouting, moving through hostile territory with a grace that defies the Absolute's own laws of permanence.",
		job_id: "assassin",
	},
	{
		kind: "path",
		id: "assassin--shadow-herald",
		name: "Path of the Shadow Herald",
		description:
			"The Shadow Herald mandate is granted to those whose aetheric resonance allows them to perceive the 'echoes' of intent before they even manifest. They are the master strategists and information brokers of the high-tier guilds, weaving networks of intelligence from the fundamental static of the Absolute. In a world where a single secret can topple a corporation or clear a Rift, the Herald is the most valuable asset on any tactical roster.",
		job_id: "assassin",
	},
	{
		kind: "path",
		id: "assassin--terminus",
		name: "Path of the Terminus",
		description:
			"The Terminus mandate is reserved for those who embody the absolute finality of the reaper. They are the surgical edge of the Absolute, capable of delivering a clinical end to any existence with a single, unanswerable strike. In the modern world, they are the ghosts of the battlefield, their presence known only by the sudden, absolute silence they leave in their wake. When a Terminus marks a target, the Absolute itself acknowledges the inevitability of their transition.",
		job_id: "assassin",
	},
	{
		kind: "path",
		id: "assassin--vanguard-outrider",
		name: "Path of the Vanguard Outrider",
		description:
			"The Vanguard Outrider is the advance resonance of the mandate—the first to enter a Rift and the last to leave. They have mastered aetheric recon, using phase-shifted sonar to map hostile terrain and relay vital intel through the weave. In the modern world of Rift containment, they are the indispensable scouts whose ability to survive behind enemy resonances ensures the success of every mission.",
		job_id: "assassin",
	},
	{
		kind: "path",
		id: "assassin--weave-infiltrator",
		name: "Path of the Weave Infiltrator",
		description:
			"The Weave Infiltrator mandate allows an Ascendant to harmonize their phase-shifted essence with the primordial weave of the Absolute. They do not just hide; they exist within the static of the local mana-field, capable of intercepting aetheric flows and stealing the resonances of other casters mid-manifestation. In a world of complex gate-wards and magical defenses, they are the ultimate locksmiths of reality.",
		job_id: "assassin",
	},
	{
		kind: "path",
		id: "berserker--absolute-zealot",
		name: "Path of the Absolute Zealot",
		description:
			"The Absolute Zealot is an Ascendant whose devotion to the primordial force transcended mere faith and became a physical anchor. They do not see their power as a 'connection' but as a divine mandate to be executed. Often seen leading extremist fellowships or streaming their gate-raids as grand aetheric sermons, they possess a terrifying resilience, as the Absolute itself seems to refuse their passing until their work is finished. To them, every strike is a prayer, and every kill is an offering.",
		job_id: "berserker",
	},
	{
		kind: "path",
		id: "berserker--aetheric-anomaly",
		name: "Path of the Aetheric Anomaly",
		description:
			"The Aetheric Anomaly is an Ascendant whose connection to the Absolute was shattered and reformed during a violent gate-collapse. They are walking anchors of instability whose every Overload triggers random, reality-warping discharges. While guilds often fear their unpredictability, they are prized for their ability to bypass conventional defensive measures and turn any battlefield into a chaotic domain where only they can truly thrive.",
		job_id: "berserker",
	},
	{
		kind: "path",
		id: "berserker--escalating-resonance",
		name: "Path of the Escalating Resonance",
		description:
			"The Path of the Escalating Resonance is walked by those whose spirits vibrate with the most unstable aetheric frequencies. In the modern world, they are the high-octane headliners of underground fight clubs and elite gate-clearance units, where pain is not an obstacle but a catalyst. Each drop of blood spilled acts as a conductor for their internal mana, fueling a recursive cycle of violence that ends only when the enemy—or the Ascendant themselves—is thoroughly spent. They are living batteries of escalating fury, held together only by the Absolute's merciless mandate.",
		job_id: "berserker",
	},
	{
		kind: "path",
		id: "berserker--gate-beast",
		name: "Path of the Gate Beast",
		description:
			"The Gate Beast represents an Awakened who has harmonized their essence with the primal aetheric fauna found within the shadows of the Rifts. They do not merely observe nature; they consume its most violent aspects to fuel their own ascendant power. In modern tactical guilds, they are the trackers and frontline skirmishers who can transition from human strategist to mindless predator in a heartbeat, channeling the echoes of ancient beasts to protect or destroy with animalistic clarity.",
		job_id: "berserker",
	},
	{
		kind: "path",
		id: "berserker--mana-scars",
		name: "Path of the Mana Scars",
		description:
			"Those who walk the Path of the Mana Scars are living testaments to the Absolute's traumatic touch. Their bodies are maps of ancient gate-breaks and survived overloads, the luminous scar tissue acting as high-capacity conductors for defensive mana. While the modern world might see them as grizzled survivors of the first gate-age, their true purpose is to serve as the unbreakable anchors of a guild resonance, turning the pain of their history into the armor of the present.",
		job_id: "berserker",
	},
	{
		kind: "path",
		id: "berserker--rift-storm",
		name: "Path of the Rift Storm",
		description:
			"The Rift Storm represents an Ascendant who has survived the epicenter of a catastrophic gate-collapse and emerged saturated with raw, elemental mana. When they enter Overload, their internal energy vents as pure environmental turbulence—fire, lightning, or freezing cold radiating from their very pores. They are volatile assets, often deployed by elite containment units as a 'scorched earth' deterrent against massive gate-swarms where collateral damage is a secondary concern to survival.",
		job_id: "berserker",
	},
	{
		kind: "path",
		id: "contractor--cursed-blade",
		name: "Path of the Cursed Blade",
		description:
			"The Cursed Blade bargain is forged with the sentient, shadow-forged armaments found deep within the Absolute's highest-rank Rifts. They do not just wield a weapon; they are bonded to a physical manifestation of their patron's hunger. In the modern world, the Cursed Blade is a lethal martial specialist, their every strike fueled by an ancient aetheric curse that consumes the resonance of their victims.",
		job_id: "contractor",
	},
	{
		kind: "path",
		id: "contractor--deep-dweller",
		name: "Path of the Deep Dweller",
		description:
			"The Deep Dweller bargain is forged with the colossal, kraken-like entities that rule the Absolute's submerged Rift dimensions. They are masters of the crushing pressure and freezing cold found at the boundaries of the aetheric abyss, manifesting spectral tentacles and dimensional rifts at will. In the modern world, they are the undisputed masters of coastal and underwater Rift containment.",
		job_id: "contractor",
	},
	{
		kind: "path",
		id: "contractor--glamour-weaver",
		name: "Path of the Glamour Weaver",
		description:
			"The Glamour Weaver bargain is forged with the ethereal reflections that rule the Absolute's most vibrant Rift ecosystems. They do not just deceive; they rewrite the sensory reality of those around them, weaving illusions of absolute beauty or terrifying despair. In the modern world, the Glamour Weaver is a master of social and physical manipulation, their presence alone enough to ensnare the unwary.",
		job_id: "contractor",
	},
	{
		kind: "path",
		id: "contractor--infernal-conduit",
		name: "Path of the Infernal Conduit",
		description:
			"The Infernal Conduit bargain is forged with the destructive entities that dwell within the deepest entropic layers of the Rifts. Their physical vessel burns with a literal internal heat, every kill feeding the insatiable hunger of their patron. In the modern world, the Infernal is a walking force of destruction, their aetheric bargain granting them the power to hurl foes through the void itself.",
		job_id: "contractor",
	},
	{
		kind: "path",
		id: "contractor--radiant-vessel",
		name: "Path of the Radiant Vessel",
		description:
			"The Radiant Vessel bargain is forged with the luminous entities of the Zenith lineage — beings of pure restorative and destructive light. They are the rarest of all Contractors, their physical vessel a conduit for aetheric energy that heals and incinerates with equal intensity. In the modern world, they are often seen as modern saints or supreme gate-raid anchors.",
		job_id: "contractor",
	},
	{
		kind: "path",
		id: "contractor--void-whisperer",
		name: "Path of the Void Whisperer",
		description:
			"The Void Whisperer bargain is forged with the vast, ancient intelligences that drift beyond the Absolute's primary resonance-layers. They do not just see the Rifts; they perceive the alien geometry of the multiverse, granting them psionic capabilities that shatter the fragile minds of their enemies. In the modern world, the Void Whisperer is a master of mental dominance and informational warfare.",
		job_id: "contractor",
	},
	{
		kind: "path",
		id: "destroyer--apex-predator",
		name: "Path of the Apex Predator",
		description:
			"The Apex Predator is the ultimate physical mandate of the Destroyer lineage — a recursive refinement of the Awakened's biological vessel into a tool of absolute lethality. In the modern era of Absolute containment, they are the supreme front-line anchors of high-rank guilds, their every movement a masterclass in optimized destructive intent. To walk this path is to accept that your muscles are no longer purely biological, but a perfected conductor for the Absolute's force.",
		job_id: "destroyer",
	},
	{
		kind: "path",
		id: "destroyer--bulwark",
		name: "Path of the Bulwark",
		description:
			"The Bulwark is a living bastion of the Destroyer lineage, an Ascendant whose very presence generates a localized threat field anchored by Absolute-reinforced frames. In modern containment zones, they serve as the physical barriers that allow civilians to escape unstable Rift boundaries. To face a Bulwark is to engage with an immovable force of nature that punishes any attempt to bypass its defensive perimeter.",
		job_id: "destroyer",
	},
	{
		kind: "path",
		id: "destroyer--last-stand",
		name: "Path of the Last Stand",
		description:
			"The Last Stand mandate is granted to survivors of catastrophic Rift incidents who have learned to override their body's inherent mortal limiters. They fight with a transcendent, near-supernatural focus that fuels impossible last-second victories. These Destroyers do not recognize the concept of defeat; they simply channel the Absolute's emergency reserves to maintain lethality long after their physical forms should have failed.",
		job_id: "destroyer",
	},
	{
		kind: "path",
		id: "destroyer--phantom-blade",
		name: "Path of the Aftershock",
		description:
			"The Path of the Aftershock is held by those whose strikes resonate with such intensity that the Absolute generates residual force iterations — temporal echoes of their movements from adjacent reflections. In the field, it manifests as multiple strikes resolving simultaneously from ghostly iterations. Footage of Aftershock Destroyers highlights the sheer visual overload of doubled impacts tearing through Rift entities with absolute recursive power.",
		job_id: "destroyer",
	},
	{
		kind: "path",
		id: "destroyer--spell-breaker",
		name: "Path of the Spell Breaker",
		description:
			"The Spell Breaker mandate designates an Ascendant as the ultimate deterrent against hostile mana-manifestations. They have integrated the primordial threads of the Absolute directly into their weapon bonds, allowing them to channel anti-resonance frequencies through physical strikes. Often recruited by high-stakes containment units, they are the ones who traverse resonant storms to deliver the final, crushing blow to reality-warping entities.",
		job_id: "destroyer",
	},
	{
		kind: "path",
		id: "destroyer--tactician",
		name: "Path of the Tactician",
		description:
			"The Tactician mandate is granted to those whose cognitive resonances can process battlefield echoes at speeds that defy conventional analysis. These are the Mandate architects of top-tier guilds and the strategic specialists of the Ascendant Bureau, treating every gate-boundary as a structural zone of calculated dominance. They do not just fight; they harmonize the local weave into a blueprint for victory, ensuring that no variable remains unaccounted for.",
		job_id: "destroyer",
	},
	{
		kind: "path",
		id: "esper--aberrant-mind",
		name: "Path of the Psionic Breach",
		description:
			"Espers touched by entities from beyond the known Rift network — alien intelligences whose psionic imprint rewired their resonance during awakening. These Ascendants often perceive the Absolute not as a network of laws, but as a collective of interconnected consciousnesses that exist outside of traditional time. They cast with thought alone, their minds becoming an impenetrably alien echo of the Absolute's deepest layers.",
		job_id: "esper",
	},
	{
		kind: "path",
		id: "esper--absolute-spark",
		name: "Path of the Absolute Spark",
		description:
			"Espers who carry a fragment of the Absolute's core energy — not mere Rift mana, but the fundamental force itself. Often individuals whose innate empathy resonated with the restorative layers of the Absolute during their awakening, they access both destructive Esper resonance-flux and Herald restorative transmissions. They are the rarest anomaly type, serving as the ultimate stabilizers for high-tier containment missions.",
		job_id: "esper",
	},
	{
		kind: "path",
		id: "esper--aetheric-cascade",
		name: "Path of the Aetheric Cascade",
		description:
			"The Aetheric Cascade mandate is granted to those whose connection to the Absolute was shattered and reformed into a volatile reactive core. They do not just cast; they trigger cascading aetheric events that baffle traditional understanding. Each manifestation is a harmonic anomaly, a reality-warping discharge that can heal an ally or incinerate a foe with the same unpredictable fervor.",
		job_id: "esper",
	},
	{
		kind: "path",
		id: "esper--draconic-lineage",
		name: "Path of the Aetheric Dragon",
		description:
			"The Aetheric Dragon mandate awakens in those whose anomalous resonance carries the signature of the primordial Rift dragons—ancient masters of the Absolute who predated even the current cycle of Rifts. Their spirit manifests as elemental fury, their very cells crystallizing into regent-tier mana-scales that hum with the power of a dying star. They are not merely casters; they are living manifestations of the Absolute's primal rage.",
		job_id: "esper",
	},
	{
		kind: "path",
		id: "esper--shadow-magic",
		name: "Path of the Void Resonance",
		description:
			"Espers who draw power from the empty space between Rift dimensions — the void that separates realities. They tend to be quiet, withdrawn individuals whose internal resonance focuses on the silence behind the Absolute's weave. Environmental fluctuations are common when they pass, and the shadows around them often seem to detach from their physical anchors. They command absolute darkness, summon void-born entities, and can dissolve their physical form into pure shadow-resonance.",
		job_id: "esper",
	},
	{
		kind: "path",
		id: "esper--storm-sorcery",
		name: "Path of the Tempest Core",
		description:
			"The Path of the Tempest Core is for those whose anomalous resonance is synchronized with absolute atmospheric pressure. Lightning arcs from their skin during moments of high resonance-flux, wind shifts when they move, and environmental sensors fluctuate wildly in their presence. They are the living conduits of the Absolute's storms, their internal resonance-field powered by the very energy that structures a Rift's atmosphere.",
		job_id: "esper",
	},
	{
		kind: "path",
		id: "herald--combat-mandate",
		name: "Path of the Combat Mandate",
		description:
			"The Combat Mandate is given to those who serve as the physical conduit for the Absolute's offensive transmissions. Armored, lethal, and broadcasting the martial directives of the Zenith lineage, they fight at the forefront of every Rift eruption. They do not just support; they lead the charge, their weapon strikes resonating with the pure destructive intent of the Absolute.",
		job_id: "herald",
	},
	{
		kind: "path",
		id: "herald--knowledge-mandate",
		name: "Path of the Knowledge Mandate",
		description:
			"The Knowledge Mandate provides an Ascendant with a direct uplink to the Absolute's primordial records. They do not just learn; they download encrypted knowledge that bypasses all mortal limitations, allowing them to read the aetheric signatures of enemies and objects with near-perfect accuracy. In the modern world, they are the supreme archivists and analysts, their transmissions revealing everything the Rifts seek to hide.",
		job_id: "herald",
	},
	{
		kind: "path",
		id: "herald--radiance-mandate",
		name: "Path of the Radiance Mandate",
		description:
			"The Radiance Mandate grants an Ascendant the ability to broadcast the Absolute's most destructive light resonance. Their presence is a beacon of pure aetheric energy, incinerating the void-remnants of the Rifts and shielding their allies in a protective luminance. In the modern world, a Radiance Herald is often the vanguard of any high-rank Rift suppression, their radiant overloads visible from miles around.",
		job_id: "herald",
	},
	{
		kind: "path",
		id: "herald--restoration-mandate",
		name: "Path of the Restoration Mandate",
		description:
			"The Restoration Mandate designates those who channel the Absolute's most potent restorative resonance. They do not just heal; they stabilize the local reality-variable, ensuring that the physical vessel of their allies remains anchored in its most optimal state. In the modern world, the Restoration Herald is the supreme asset of any raid, their mere presence raising the survival probability of the entire collective.",
		job_id: "herald",
	},
	{
		kind: "path",
		id: "herald--storm-mandate",
		name: "Path of the Storm Mandate",
		description:
			"The Storm Mandate empowers an Ascendant to broadcast the Absolute's most violent atmospheric resonance. They are walking thunderheads, their every gesture capable of summoning lightning and shattering the resolve of their foes. In the modern world, a Storm Herald is the ultimate deterrent, their radiant and electrical overloads enough to power entire city blocks or level them with equal ease.",
		job_id: "herald",
	},
	{
		kind: "path",
		id: "herald--triage-mandate",
		name: "Path of the Triage Mandate",
		description:
			"The Triage Mandate is for those who specialize in the Absolute's emergency field calibrations. They operate on a unique restorative resonance that maximizes output on critical vessels, marking targets for absolute elimination while canceling lethal blows through aetheric realignment. In the modern world, a Triage Herald's presence is the difference between a total wipe and an absolute victory.",
		job_id: "herald",
	},
	{
		kind: "path",
		id: "holy-knight--absolute-devotion",
		name: "Path of the Absolute Devotion",
		description:
			"The Absolute Devotion mandate designates those who are the physical paragons of the Absolute's primary resonance. They do not just follow a code; they become a walking anchor for the restorative and protective frequencies of the Zenith lineage, their presence alone stabilizing the local reality of their allies. In the modern world, the Devotion Knight is the ultimate frontline leader, their absolute faith manifesting as physical aetheric armaments.",
		job_id: "holy-knight",
	},
	{
		kind: "path",
		id: "holy-knight--atonement-mandate",
		name: "Path of the Atonement Mandate",
		description:
			"The Atonement Mandate is held by those who prioritize the absolute preservation of life. They do not just defend; they absorb the suffering of their allies, manifesting as a living shield for the Absolute's most fragile resonance-layers. In the modern world, the Atonement Knight is the supreme guardian of peace, their covenant punishing those who choose violence with a radiant backlash.",
		job_id: "holy-knight",
	},
	{
		kind: "path",
		id: "holy-knight--dominance-mandate",
		name: "Path of the Dominance Mandate",
		description:
			"The Dominance Mandate designates those who wield the Absolute's authority with uncompromising force. They do not just lead; they dominate, their aetheric presence frozen with a chill authority that renders enemies immobile. In the modern world, the Dominance Knight is the supreme arbiter of the Absolute's order, their very will enough to shatter the resolve of those who oppose them.",
		job_id: "holy-knight",
	},
	{
		kind: "path",
		id: "holy-knight--exaltation-mandate",
		name: "Path of the Exaltation Mandate",
		description:
			"The Exaltation Mandate is for those who strive for absolute physical and aetheric perfection. They do not just fight; they perform, their every strike a legendary feat that inspires those around them to reach their own absolute potential. In the modern world, the Exaltation Knight is the supreme hero, their covenant fueling superhuman manifestations that turn every struggle into an epic victory.",
		job_id: "holy-knight",
	},
	{
		kind: "path",
		id: "holy-knight--retribution-mandate",
		name: "Path of the Retribution Mandate",
		description:
			"The Retribution Mandate is held by those who have sacrificed their defensive stability for the absolute destruction of their foes. They do not just strike; they exact a toll for every transgression against the Absolute, pursuing their targets with a relentless aetheric fury that cannot be outrun. In the modern world, the Retribution Knight is a lethal specialist, their covenant burning with the righteous hunger for absolute realignment.",
		job_id: "holy-knight",
	},
	{
		kind: "path",
		id: "holy-knight--verdant-mandate",
		name: "Path of the Verdant Mandate",
		description:
			"Those who walk the Path of the Verdant Mandate swear to protect the Absolute's original intent against the encroaching resonance corruption of the Rifts. Their covenant is a primal pact with the world's original life-resonance, anchoring themselves to threatened Rift biomes to serve as the ultimate custodians of aetheric diversity. In the modern world, they are the bulwark against total ecological collapse, their presence stabilizing the very fabric of reality.",
		job_id: "holy-knight",
	},
	{
		kind: "path",
		id: "idol--blade-resonance",
		name: "Path of the Blade Resonance",
		description:
			"Those who walk the Path of the Blade Resonance channel their harmonic frequencies through physical armaments. They treat the battlefield as a lethal performance, their every strike a precision-weighted aetheric flourish that maximizes destruction while ensuring their own physical integrity. In the elite academies, they are the supreme martial specialists, their combat style a perfect bridge between physical perfection and aetheric art.",
		job_id: "idol",
	},
	{
		kind: "path",
		id: "idol--dance-resonance",
		name: "Path of the Dance Resonance",
		description:
			"Those who walk the Path of the Dance Resonance channel the Absolute's combat-frequency through movement itself — their fighting styles derived from modern dance forms weaponized by the Ascendant Bureau's martial arts division. K-pop precision choreography becomes blade-work timing, contemporary flow becomes evasion doctrine, ballet extension becomes strike reach, and hip-hop impact becomes devastating kinetic force. In the modern world, the Dance Idol is the supreme mobile combatant, their battlefield presence a lethal performance that inspires allies and annihilates anomalies with equal grace.",
		job_id: "idol",
	},
	{
		kind: "path",
		id: "idol--genesis-resonance",
		name: "Path of the Genesis Resonance",
		description:
			"The Path of the Genesis Resonance designates an Idol who taps into the Absolute's foundational harmonic—the vibration that structures matter itself. They do not just imagine; they manifest, fabricating physical items and animating objects from raw mana as a physical manifestation of their art. In the modern world, they are the supreme architects of the material weave, their presence turning any location into a factory of absolute creation.",
		job_id: "idol",
	},
	{
		kind: "path",
		id: "idol--hypnotic-resonance",
		name: "Path of the Hypnotic Resonance",
		description:
			"The Path of the Hypnotic Resonance designates an Idol who broadcasts on the fey-resonance bands of the Absolute. They do not just perform; they project irresistible harmonic patterns that override the common consensus of those who witness them. In the high-stakes world of social and political containment, they are the supreme influencers, their absolute charm capable of turning an entire city-block into a unified collective of their choosing.",
		job_id: "idol",
	},
	{
		kind: "path",
		id: "idol--lore-resonance",
		name: "Path of the Lore Resonance",
		description:
			"Those who walk the Path of the Lore Resonance are collectors of the Absolute's recursive data-manifolds. They do not just record; they weaponize information itself, disrupting enemy manifestations by echoing their own psychological vulnerabilities back at them in a tidal wave of dissonant data. In the modern world, the Lore Idol is the supreme analytical strategist, their mastery of the Absolute's secrets making them feared by any entity with a hidden variable.",
		job_id: "idol",
	},
	{
		kind: "path",
		id: "idol--shadow-resonance",
		name: "Path of the Shadow Resonance",
		description:
			"The Shadow Resonance mandate is walked by those who broadcast on the hidden, subsonic layers of the Absolute's dark architecture. They are the supreme ghosts of the Idol lineage, gathered intel from the very static of the world around them. They do not just hide; they weave fear into the aetheric signatures of their enemies, planting suggestions and extracting secrets with a surgical, undetectable precision.",
		job_id: "idol",
	},
	{
		kind: "path",
		id: "mage--detonation-specialist",
		name: "Path of the Detonation Specialist",
		description:
			"The Detonation Specialist mandate is walked by those who treat aetheric energy as a raw, explosive substrate. They are the architects of controlled destruction, capable of weaving destructive mantras that bypass friendly resonances with surgical precision. In the high-stakes world of Rift clearance, they serve as the heavy artillery, turning the local weave into a localized supernova of calculated fury.",
		job_id: "mage",
	},
	{
		kind: "path",
		id: "mage--matter-weaver",
		name: "Path of the Matter Weaver",
		description:
			"The Matter Weaver mandate allows an Ascendant to rewrite the fundamental physical properties of the local substrate. They treat the world as a programmable weave, capable of turning steel to glass or concrete to water with a single aetheric command. In the modern world of advanced alchemy and essence-cultivation, the Weaver is a priceless asset for both guild construction and tactical environmental manipulation.",
		job_id: "mage",
	},
	{
		kind: "path",
		id: "mage--phantasmist",
		name: "Path of the Phantasmist",
		description:
			"The Phantasmist mandate is walked by those who have mastered the art of weaving aetheric fakes so sophisticated that the Absolute itself accepts them as genuine resonance. They do not just create illusions; they inject false realities into the world, bypassing all senses to fool both sentient and anomalous threats. At their peak, their phantasms can manifest physical presence, proving that in the Absolute's eye, perception IS reality.",
		job_id: "mage",
	},
	{
		kind: "path",
		id: "mage--probability-mandate",
		name: "Path of the Probability Mandate",
		description:
			"The Probability Mandate designates an Ascendant who has learned to perceive the underlying variables of the Absolute. They do not see the future as a vision, but as a series of calculated outcomes that can be anchored into reality. In the modern world, they are the indispensable strategists of any high-tier guild, capable of overriding unfavorable resonance-branches and ensuring the 'unlucky' moment never comes to pass.",
		job_id: "mage",
	},
	{
		kind: "path",
		id: "mage--rift-caller",
		name: "Path of the Rift Caller",
		description:
			"The Rift Caller mandate is for those who treat physical space as a mere suggestion. They specialize in tearing open micro-gates to pull matter from distant reaches or summon reinforcements from the Absolute's many reflections. In the modern world of gate-containment, they are the masters of logistics and tactical displacement, moving through reality via dimensional shortcuts that bypass all conventional defenses.",
		job_id: "mage",
	},
	{
		kind: "path",
		id: "mage--shield-compiler",
		name: "Path of the Shield Architect",
		description:
			"The Shield Architect mandate is for those who view the weave of the Absolute as a protective barrier to be reinforced. They generate persistent aetheric shields that absorb damage and reject hostile manifestations. In a world where a single error can mean total annihilation, the Architect is the foundation of any successful suppression mission—the one whose continuous protection harmonics ensure the survival of the party.",
		job_id: "mage",
	},
	{
		kind: "path",
		id: "revenant--entropy-blade",
		name: "Path of the Grave Shepherd",
		description:
			"The Grave Shepherd does on a battlefield what Marthos does on a cosmic scale: it reaps the fallen and sets them to work. Rather than scatter its harvest, the Shepherd binds a single great Remnant into an elite thrall - a risen champion stitched from the strongest dead - and commands it as an extension of its own will. Few in number but terrible in strength, the Shepherd's risen turn every casualty into a reinforcement.",
		job_id: "revenant",
	},
	{
		kind: "path",
		id: "revenant--entropy-drinker",
		name: "Path of the Black Blood",
		description:
			"The Black Blood walks the oldest bargain of the End-Cycle: pay in your own life and entropy repays it tenfold. Their veins run with congealed Remnant-essence that they spend freely, wounding themselves to deepen the harvest and turning every blow they suffer into slow, crawling recovery. They are the Revenants who simply refuse to fall, buoyed by a tide of blood - their own and their enemies' - that never quite runs dry.",
		job_id: "revenant",
	},
	{
		kind: "path",
		id: "revenant--plague-weaver",
		name: "Path of the Dread Veil",
		description:
			"The Dread Veil wears Marthos's terror like a shroud. Where they walk, the Void-Breath thickens until the bravest find their hands shaking and their courage rotting from within. They need not strike a foe that has already surrendered to despair - and those who flee only die tired. Bureau handlers deploy the Veil to break a Rift's defenders before a single real blow is struck.",
		job_id: "revenant",
	},
	{
		kind: "path",
		id: "revenant--threshold-walker",
		name: "Path of the Threshold Walker",
		description:
			"The Threshold Walker stands where Marthos and Solara contend - on the exact line between the End-Cycle and the next dawn. Alone among Revenants, they can run the harvest backward, pouring reclaimed Remnants into failing allies and dragging the newly dead back across the threshold. To friends they are a cold mercy; to enemies, the hand that decides the moment has come.",
		job_id: "revenant",
	},
	{
		kind: "path",
		id: "revenant--void-lord",
		name: "Path of the Void Eater",
		description:
			"The Void Eater answers Marthos's hunger without restraint: entropy is not a tool but an appetite. Where other Revenants harvest the dying, the Void Eater hastens the dying, treating a wounded foe as a feast half-served. Their necrosis pours through the flimsy wards of the living, and every kill only sharpens the next. The Ascendant Bureau fields them when a Rift must be emptied rather than held - the longer the fight lasts, the less of the enemy remains.",
		job_id: "revenant",
	},
	{
		kind: "path",
		id: "revenant--wither-guard",
		name: "Path of the Hollow King",
		description:
			"The Hollow King rules the front line from a throne of decay. They draw every eye and every blade, daring the enemy to spend itself against an entropy that cannot be outlasted. What strikes their allies, they take instead; what strikes them, they turn to dust. Marthos's mandate names them wardens of the threshold - the immovable dead who hold the breach while the living do their work behind.",
		job_id: "revenant",
	},
	{
		kind: "path",
		id: "stalker--apex-hunter",
		name: "Path of the Apex Ascendant",
		description:
			"The Apex Ascendant mandate is held by those who have mastered the art of exploiting the physical vulnerabilities of the Absolute's most dangerous entities. They do not just hunt; they analyze the aetheric structure of their prey, adapting their strikes to counteract specific threat profiles. In the modern world, the Apex Ascendant is the supreme field operative, capable of neutralizing entities that ignore conventional force.",
		job_id: "stalker",
	},
	{
		kind: "path",
		id: "stalker--apex-slayer",
		name: "Path of the Apex Slayer",
		description:
			"The Apex Slayer mandate is given to those who obsessively study the absolute weaknesses of their prey. They do not just hunt; they deconstruct, learning to counter every aetheric ability and exploit every biological flaw of high-rank Rift entities. In the modern world, the Apex Slayer is the ultimate boss-killer, their analytical focus turning a nightmare encounter into a systematic elimination.",
		job_id: "stalker",
	},
	{
		kind: "path",
		id: "stalker--hive-synchronist",
		name: "Path of the Hive Synchronist",
		description:
			"The Hive Synchronist mandate designates those who have bonded with a living swarm of gate-microorganisms. They do not just carry a hive; they are a walking ecosystem, their swarm enhancing every offensive manifestation and providing absolute mobility via aethertic levitation. In the modern world, the Synchronist is a terrifyingly efficient field operative, their presence denoted by a permanent cloud of aetheric static.",
		job_id: "stalker",
	},
	{
		kind: "path",
		id: "stalker--pack-leader",
		name: "Path of the Pack Leader",
		description:
			"The Pack Leader mandate is for those who forge deep aetheric bonds with the Absolute's apex predators. They do not just hunt alongside their companion; they fuse their hunting instincts into a single, coordinated absolute strikes that dominate the battlefield. In the modern world, the Pack Leader is a one-person tactical unit, their bonded entity often as famous and lethal as the Stalker themselves.",
		job_id: "stalker",
	},
	{
		kind: "path",
		id: "stalker--rift-strider",
		name: "Path of the Rift Strider",
		description:
			"The Rift Strider mandate empowers a Stalker to navigate the precarious boundaries between Rift dimensions. They do not just track prey; they step through micro-rifts in reality, manifesting across the battlefield with a frightening fluidity. In the modern world, the Rift Strider is the supreme interceptor, their ability to seal dimensional crossings and strike through space making them an indispensable asset.",
		job_id: "stalker",
	},
	{
		kind: "path",
		id: "stalker--umbral-hunter",
		name: "Path of the Umbral Ascendant",
		description:
			"The Umbral Ascendant mandate is for those who have mastered the zero-light resonance of the highest-rank Rifts. They do not just hide in shadow; they become one with the void, manifesting as an invisible predator that strikes with absolute lethality from the darkness. In the modern world, the Umbral Ascendant is the supreme assassin of the Stalker lineage, their very existence a ghost story in the halls of the Absolute.",
		job_id: "stalker",
	},
	{
		kind: "path",
		id: "striker--aetheric-channeler",
		name: "Path of the Aetheric Channeler",
		description:
			"The Aetheric Channeler mandate transforms an Ascendant into a living environmental conductor. They do not just strike; they convert ambient aetheric energy into fundamental elemental forces—concussive gravity, thermal discharges, or high-intensity lightning. In the containment of a high-tier Rift, they are the ultimate multi-role assets, capable of adapting their physical strikes to the specific weaknesses of any anomaly.",
		job_id: "striker",
	},
	{
		kind: "path",
		id: "striker--blade-conductor",
		name: "Path of the Blade Conductor",
		description:
			"The Blade Conductor mandate allows an Ascendant to extend their internal aetheric Rifts into physical steel. They do not just carry weapons; they bond with them, turning a simple blade into a high-frequency conductor for the Absolute's destructive frequency. In the elite academies of the modern world, Conductors are praised for their lethal precision and the harmonic 'hum' of their steel as it carves through reality.",
		job_id: "striker",
	},
	{
		kind: "path",
		id: "striker--entropic-flow",
		name: "Path of the Entropic Flow",
		description:
			"The Entropic Flow is walked by those whose internal aetheric Rifts fire in seemingly chaotic, unpredictable patterns. They do not fight with discipline, but with a fluidity that disregards the Absolute's logic. To an observer, they appear to be stumbling, tripping, and swaying through combat—yet every movement somehow lands a devastating blow or evades an impossible strike. They are the living embodiment of the 'unlucky' hit that always finds its mark.",
		job_id: "striker",
	},
	{
		kind: "path",
		id: "striker--harmonic-surgeon",
		name: "Path of the Harmonic Surgeon",
		description:
			"The Harmonic Surgeon mandate is granted to those whose understanding of aetheric pathways allows them to repair the physical vessel with a touch. In the modern world, they are the most critical members of any high-tier raid team, capable of shutting down enemy motor functions with clinical precision or realigning the broken essences of their allies mid-combat. They move with a cold, calculated efficiency that treats the battlefield as a triage unit.",
		job_id: "striker",
	},
	{
		kind: "path",
		id: "striker--kinetic-core",
		name: "Path of the Kinetic Core",
		description:
			"The Path of the Kinetic Core is for those who treat their own body as a high-velocity conductor for the Absolute's power. They do not just strike; they release focused bursts of kinetic resonance that can shatter reinforced Rifts and liquefy the internals of the most durable entities. In the high-stakes world of Rift suppression, they are the undisputed masters of frontline engagement, moving with a speed that leaves afterimages of aetheric fire in their wake.",
		job_id: "striker",
	},
	{
		kind: "path",
		id: "striker--phantom-step",
		name: "Path of the Phantom Step",
		description:
			"The Phantom Step mandate allows an Ascendant to route their physical existence through the low-frequency shadows of the local aether. They are the spectral legends of the gate-wars—flickers in a dark alley followed by the absolute collapse of a high-tier entity. They move not with speed, but with a displacement of reality, stepping through the darkness as if it were a physical gateway.",
		job_id: "striker",
	},
	{
		kind: "path",
		id: "summoner--apex-shifter",
		name: "Path of the Apex Shifter",
		description:
			"The Apex Shifter mandate is for those who seek to dominate their environment by assuming the physical vessels of the Absolute's apex predators. They do not merely shift; they undergo a total biological restructuring into powerful Rift creatures that exceed all earthly limits. In the modern world, they are the front-line tanks who lead every raid, their very existence a bridge between human consciousness and absolute fury.",
		job_id: "summoner",
	},
	{
		kind: "path",
		id: "summoner--biome-architect",
		name: "Path of the Biome Architect",
		description:
			"The Biome Architect mandate is held by those who have attained a perfect resonance with a specific Rift ecosystem. They do not just survive; they recover their internal essence by absorbing ambient Rift energy with an efficiency that borders on the miraculous. In the containment protocols of the modern world, the Architect is indispensable for identifying and stabilizing the volatile environments that bleed into our reality.",
		job_id: "summoner",
	},
	{
		kind: "path",
		id: "summoner--cosmic-conduit",
		name: "Path of the Cosmic Conduit",
		description:
			"The Cosmic Conduit mandate is for those who draw power from the massive, distant aetheric vibrations that resonate through high-rank Rifts. They do not just see stars; they channel the fundamental cosmic energy of the Absolute into manifestations of healing, destruction, and prophetic anchoring. In the modern world, they are the supreme mystics of the gate-age, their every action informed by a variable cosmic map only they can perceive.",
		job_id: "summoner",
	},
	{
		kind: "path",
		id: "summoner--dream-weaver",
		name: "Path of the Dream Weaver",
		description:
			"The Dream Weaver mandate designates those who have forged a connection with the Lush-resonance—the restorative, semi-material reflections that drift along the boundaries of certain Rifts. They do not just heal; they manifest localized patches of aetheric stability that promote rapid biological repair. In the modern world, the Weaver is the emotional and physical anchor of any raid team, transforming a nightmare Rift Break into a temporary sanctuary.",
		job_id: "summoner",
	},
	{
		kind: "path",
		id: "summoner--pack-commander",
		name: "Path of the Pack Commander",
		description:
			"The Pack Commander mandate elevates a Summoner to the status of an absolute leader within the Rift's predatory hierarchy. They do not just summon entities; they command them like a unified tactical unit, reinforcing their creatures with their own internal aetheric essence. In the modern world, one Commander with a full menagerie is a one-person tactical squad, turning a solo raid into a coordinated absolute assault.",
		job_id: "summoner",
	},
	{
		kind: "path",
		id: "summoner--symbiotic-host",
		name: "Path of the Symbiotic Host",
		description:
			"The Symbiotic Host mandate is given to those who have allowed their physical vessel to become a living ecosystem for mutualistic gate-organisms. They do not just host these symbiotes; they fuse with them to gain terrifying biological efficiencies and project a defensive field of aetheric spores. In the Absolute's cycle of life and death, the Host is the bridge where both processes occur simultaneously within the same body.",
		job_id: "summoner",
	},
	{
		kind: "path",
		id: "technomancer--aether-breacher-design",
		name: "Design: Aether Breacher",
		description:
			"The Aetheric Breacher designs are for those who interface directly with the Absolute's core resonance. They treat reality like a malleable sequence — finding vulnerabilities, suppressing enemy manifestations, and realigning the laws of local aetheric flow. In the modern world, the Breacher is the supreme infiltration specialist, their ability to bypass any defensive mandate making them the ultimate asset for high-rank Rift raids.",
		job_id: "technomancer",
	},
	{
		kind: "path",
		id: "technomancer--aether-chemist-design",
		name: "Design: The Aether Chemist",
		description:
			"The Aether Chemist designs are for those who synthesize aetheric reagents harvested directly from the Rifts. They do not just brew potions; they architecture complex somatic sequences that heal, transform, and incinerate with absolute precision. In the modern world, the Aether Chemist is the supreme specialist in restorative and entropic resonance dynamics, their presence stabilizing the party's biological integrity.",
		job_id: "technomancer",
	},
	{
		kind: "path",
		id: "technomancer--aether-vessel-design",
		name: "Design: The Aether Vessel",
		description:
			"The Aether Vessel designs are for those who infuse physical armaments with the Absolute's blueprints. They do not just wear armor; they manifest localized power-frames that grant superhuman strength and impenetrable defensive auras, turning the Technomancer into a walking force of aetheric might. In the modern world, the Aether Vessel is the supreme martial-architect, their designs representing the peak of ascendant warfare.",
		job_id: "technomancer",
	},
	{
		kind: "path",
		id: "technomancer--resonance-siege-design",
		name: "Design: Resonance Siege",
		description:
			"The Resonance Siege designs represent the peak of offensive aetheric manifestations. They do not just build platforms; they architecture localized resonators that project destructive harmonics or protective fields across the battlefield. In the modern world, the Resonance Siege architect is the supreme heavy resonance specialist, their constructs capable of breaking any gate-defense with absolute power.",
		job_id: "technomancer",
	},
	{
		kind: "path",
		id: "technomancer--swarm-conduit-design",
		name: "Design: Swarm Conduit",
		description:
			"The Swarm Conduit designs are for those who deploy aetheric micro-conspicuous to blanket the battlefield. They do not just control drones; they weave a living surveillance and offensive weave that provides absolute oversight and precision strikes. In the modern world, the Swarm Conduit is the supreme tactical specialist, their micro-conduits capable of relaying information and force across any distance.",
		job_id: "technomancer",
	},
	{
		kind: "path",
		id: "technomancer--synchronist-binary-design",
		name: "Design: Synchronist Binary",
		description:
			"The Synchronist Binary designs are for those who bond with a primary aetheric defender. They do not just build a companion; they fuse their own neural resonance with a physical construct, creating a perfect binary fighting unit. In the modern world, the Synchronist is a formidable frontline combatant, their attacks fueled by aetheric compilations that outpace physical reflex.",
		job_id: "technomancer",
	},
	{
		kind: "regent",
		id: "beast_regent",
		name: "Beast Regent",
		title: "Beast Regent (Regent of Beasts)",
		theme: "Primal Evolution & Apex Regentty",
		description:
			"Avatar of primordial evolution and regent of the wild, wielding the power of the Regent of Beasts. All creatures recognize you as the ultimate alpha, and your roar can shatter the instincts of any living being. You embody the perfect predatory form, adaptive and unstoppable. The Ascendant Bureau classifies you as an Alpha-class biodiversity threat.",
	},
	{
		kind: "regent",
		id: "blood_regent",
		name: "Blood Regent",
		title: "Blood Regent (Regent of Blood)",
		theme: "Hemomancy & Sanguine Regentty",
		description:
			"The ultimate authority of biological evolution and living mana-ichor, sharing the adaptive power of Lyra, the Queen of the Swarm. You control the fluid of life, turning it into a regent weapon that ignores the limitations of mortal biology. As a node of the Swarm-Heart, your presence accelerates the evolution of reality and cleanses the bloodlines of the world.",
	},
	{
		kind: "regent",
		id: "destruction_regent",
		name: "Destruction Regent",
		title: "Destruction Regent (Regent of Destruction)",
		theme: "Primordial Destruction and Draconic Apocalypse",
		description:
			"Incarnation of primordial destruction, sharing the catastrophic power of Marthos, the Dragon-King of Void. You are the Ascendant's necessary delete-command, capable of transforming into the dragon of apocalypse whose breath erases corrupted reality. As the mortal anchor for the Void Weaver, you represent the inevitable end and the Next Beginning.",
	},
	{
		kind: "regent",
		id: "frost_regent",
		name: "Frost Regent",
		title: "Frost Regent (Regent of Frost)",
		theme: "Eternal Winter & absolute Zero",
		description:
			"Herald of eternal winter and absolute zero, wielding the power of the Regent of Frost. You command the biting winds, glacial shards, and the crystalline silence of the void. Your presence freezes the very soul of the world, turning landscapes into frozen wastes of pure order. The Ascendant Bureau classifies you as a Climate Catastrophe event, capable of bringing a global ice age.",
	},
	{
		kind: "regent",
		id: "gravity_regent",
		name: "Gravity Regent",
		title: "Gravity Regent (Regent of Weight)",
		theme: "Gravitational Mastery & Fundamental Force",
		description:
			"Vessel of fundamental attraction and universal authority, wielding the incalculable force of Kronos, the Fragment of the Absolute. You command the weight that binds the worlds and collapses the Void into stable geometry. Your will is the anchor of the Ascendant's physics, a universal singularity that dictates the path of all existence in the name of the Absolute Origin.",
	},
	{
		kind: "regent",
		id: "mimic_regent",
		name: "Mimic Regent",
		title: "Mimic Regent Ascendant Class",
		theme: "Infinite Forms",
		description:
			"Embodiment of infinite forms. Copy anything — creatures, objects, concepts. No detection possible. The Ascendant Bureau has contradictory records on you because you appear as a different person in every database. DNA tests return different results each time. Your awakening unlocked the ability to become ANYTHING you observe, perfectly and undetectably, making you the ultimate infiltrator, spy, and adaptive combatant.",
	},
	{
		kind: "regent",
		id: "plague_regent",
		name: "Plague Regent",
		title: "Plague Regent Ascendant Class",
		theme: "Pandemic Incarnate",
		description:
			"Incarnation of plague and pestilence. Walking miasma apocalypse. the Ascendant Bureau tracks 47 unknown pathogens in your wake. The Ascendant Bureau classifies you as a Cataclysm-class entity. Insects obey your will, diseases are your art form, and quarantine zones form wherever you walk. Healing sanctuaries refuse your admittance, biohazard teams follow your movements, and the Grand Healer Guilds have a dedicated task force assigned to you.",
	},
	{
		kind: "regent",
		id: "radiant_regent",
		name: "Radiant Regent",
		title: "Radiant Regent (Regent of White Flames)",
		theme: "White Flames and Purification",
		description:
			"The ultimate manifestation of purification fire, sharing a fragment of Solara, the Brightest Fragment. You command the sacred 'Exarch's Authority' that incinerates corruption and illuminates the darkest depths of the realms. As a vessel of the Radiant Warden, you are tasked with stabilizing the Rifts and purging the void-noise from reality.",
	},
	{
		kind: "regent",
		id: "spatial_regent",
		name: "Spatial Regent",
		title: "Spatial Regent (Regent of Space)",
		theme: "Cosmic Weaving & Dimensional Void",
		description:
			"Regent of the void and master of the dimensional weave. You reshape space, time, and distance with absolute authority. Your Cosmic Senses allow you to perceive the very fabric of the multiverse. The Ascendant Bureau classifies you as a Dimensional Regentty Threat. You collapse distances, create pocket dimensions, and place anchors that bypass the laws of physics.",
	},
	{
		kind: "regent",
		id: "steel_regent",
		name: "Steel Regent",
		title: "Steel Regent (Regent of Iron Body)",
		theme: "Conceptual Invulnerability & Absolutist Defense",
		description:
			"Embodiment of absolute structural integrity, wielding the shared power of Golem, the Eternal of Giants. You are a foundational pillar of the Ascendant, a conceptually invulnerable entity that anchors the realms against the pull of the Void. Your iron will mirrors the Unyielding Wall, making containment of your presence fundamentally impossible.",
	},
	{
		kind: "regent",
		id: "umbral_regent",
		name: "Umbral Regent",
		title: "Umbral (Regent of Shadows)",
		theme: "Umbral and Death",
		description:
			"The ultimate umbral manifestation Ascendant class overlay, sharing the ascendant power of Kael Voss, the Weaver of the Absolute. You embody mastery over the veil and the ability to 'Resurge' an infinite legion of Umbral Echoes. This is the highest tier veil-based Ascendant class, granting true Eternal-tier authority over the shadow realm to protect the timeline in the name of the Prime Eternal.",
	},
	{
		kind: "regent",
		id: "war_regent",
		name: "War Regent",
		title: "War Regent (Regent of Command)",
		theme: "Tactical Battlefield Supremacy & Absolute Command",
		description:
			"Embodiment of tactical genius and absolute battlefield authority, wielding the power of the Regent of Command. You command the vanguard legions with unmatched supremacy, turning every conflict into a masterpiece of war. Your presence governs the flow of battle across dimensions, as you lead the charge of the eternal vanguard.",
	},
];
